namespace EcomAE.Platform.Migration;

/// <summary>
/// Full inventory of PHP bos/ajax_epc_bos.php actions for Wave B zero-PHP coverage.
/// Never invents cutoverAllowed=true; PHP remains authoritative.
/// </summary>
public interface IBosAjaxWriteCatalog
{
    BosAjaxWriteCatalogReport BuildReport();
    bool TryGet(string action, out BosAjaxWriteCatalogEntry entry);
    IReadOnlyList<BosAjaxWriteCatalogEntry> All { get; }
}

public sealed class BosAjaxWriteCatalog : IBosAjaxWriteCatalog
{
    private static readonly BosAjaxWriteCatalogEntry[] Entries =
    [
        new("login", "registry", "/bos/ajax-writes/dry-run/login"),
        new("switch_tenant", "registry", "/bos/ajax-writes/dry-run/switch_tenant"),
        new("tenant_list", "registry", "/bos/ajax-writes/dry-run/tenant_list"),
        new("tenant_info", "registry", "/bos/ajax-writes/dry-run/tenant_info"),
        new("fleet_health", "registry", "/bos/ajax-writes/dry-run/fleet_health"),
        new("tenant_compliance", "registry", "/bos/ajax-writes/dry-run/tenant_compliance"),
        new("system_health", "registry", "/bos/ajax-writes/dry-run/system_health"),
        new("isolation_audit", "registry", "/bos/ajax-writes/dry-run/isolation_audit"),
        new("mfa_policy", "dedicated", "/bos/ajax/mfa-policy"),
        new("mfa_stats", "registry", "/bos/ajax-writes/dry-run/mfa_stats"),
        new("webhooks", "registry", "/bos/ajax-writes/dry-run/webhooks"),
        new("events", "registry", "/bos/ajax-writes/dry-run/events"),
        new("design_tokens", "dedicated", "/bos/ajax/design-tokens"),
        new("readiness_score", "registry", "/bos/ajax-writes/dry-run/readiness_score"),
        new("notifications", "registry", "/bos/ajax-writes/dry-run/notifications"),
        new("db_migrations", "registry", "/bos/ajax-writes/dry-run/db_migrations"),
        new("cp_role_home", "registry", "/bos/ajax-writes/dry-run/cp_role_home"),
        new("credit_limit", "dedicated", "/bos/ajax/credit-limit"),
        new("order_erp_pipeline", "registry", "/bos/ajax-writes/dry-run/order_erp_pipeline"),
        new("po_approval", "registry", "/bos/ajax-writes/dry-run/po_approval"),
        new("rest_api_v2", "registry", "/bos/ajax-writes/dry-run/rest_api_v2"),
        new("fulfillment_queue", "registry", "/bos/ajax-writes/dry-run/fulfillment_queue"),
        new("bi_metrics", "registry", "/bos/ajax-writes/dry-run/bi_metrics"),
        new("ai_classification", "registry", "/bos/ajax-writes/dry-run/ai_classification"),
        new("tenant_config", "registry", "/bos/ajax-writes/dry-run/tenant_config"),
        new("workflow_builder", "registry", "/bos/ajax-writes/dry-run/workflow_builder"),
        new("inventory_forecast", "registry", "/bos/ajax-writes/dry-run/inventory_forecast"),
        new("multi_currency_gl", "registry", "/bos/ajax-writes/dry-run/multi_currency_gl"),
        new("sso_saml", "registry", "/bos/ajax-writes/dry-run/sso_saml"),
        new("wps_payroll", "registry", "/bos/ajax-writes/dry-run/wps_payroll"),
        new("collections_dunning", "registry", "/bos/ajax-writes/dry-run/collections_dunning"),
        new("warranty_rma", "registry", "/bos/ajax-writes/dry-run/warranty_rma"),
        new("dealer_portal", "registry", "/bos/ajax-writes/dry-run/dealer_portal"),
        new("ai_copilot", "registry", "/bos/ajax-writes/dry-run/ai_copilot"),
        new("nl_reporting", "registry", "/bos/ajax-writes/dry-run/nl_reporting"),
        new("industry_packs", "registry", "/bos/ajax-writes/dry-run/industry_packs"),
        new("multi_entity", "registry", "/bos/ajax-writes/dry-run/multi_entity"),
        new("promotions_engine", "registry", "/bos/ajax-writes/dry-run/promotions_engine"),
        new("config_sandbox", "registry", "/bos/ajax-writes/dry-run/config_sandbox"),
        new("import_orchestrator", "registry", "/bos/ajax-writes/dry-run/import_orchestrator"),
        new("document_vault", "registry", "/bos/ajax-writes/dry-run/document_vault"),
        new("subscription_billing", "registry", "/bos/ajax-writes/dry-run/subscription_billing"),
        new("soc2_compliance", "registry", "/bos/ajax-writes/dry-run/soc2_compliance"),
        new("marketplace", "registry", "/bos/ajax-writes/dry-run/marketplace"),
        new("ai_service", "registry", "/bos/ajax-writes/dry-run/ai_service"),
        new("metabase_embed", "registry", "/bos/ajax-writes/dry-run/metabase_embed"),
        new("isolation_anomaly", "registry", "/bos/ajax-writes/dry-run/isolation_anomaly"),
        new("run_audit", "dedicated", "/bos/ajax/run-audit"),
        new("recent_violations", "registry", "/bos/ajax-writes/dry-run/recent_violations"),
        new("latest_run", "registry", "/bos/ajax-writes/dry-run/latest_run"),
        new("get", "registry", "/bos/ajax-writes/dry-run/get"),
        new("save", "dedicated", "/bos/ajax/save"),
        new("list", "registry", "/bos/ajax-writes/dry-run/list"),
        new("register", "registry", "/bos/ajax-writes/dry-run/register"),
        new("update", "dedicated", "/bos/ajax/update"),
        new("delete", "dedicated", "/bos/ajax/delete"),
        new("stats", "registry", "/bos/ajax-writes/dry-run/stats"),
        new("dlq", "registry", "/bos/ajax-writes/dry-run/dlq"),
        new("dlq_retry", "registry", "/bos/ajax-writes/dry-run/dlq_retry"),
        new("dlq_resolve", "registry", "/bos/ajax-writes/dry-run/dlq_resolve"),
        new("summary", "registry", "/bos/ajax-writes/dry-run/summary"),
        new("list_tenants", "registry", "/bos/ajax-writes/dry-run/list_tenants"),
        new("get_tokens", "dedicated", "/bos/ajax/get-tokens"),
        new("save_token", "dedicated", "/bos/ajax/save-token"),
        new("preview_css", "registry", "/bos/ajax-writes/dry-run/preview_css"),
        new("tenant", "registry", "/bos/ajax-writes/dry-run/tenant"),
        new("fleet", "registry", "/bos/ajax-writes/dry-run/fleet"),
        new("unread_count", "registry", "/bos/ajax-writes/dry-run/unread_count"),
        new("mark_read", "registry", "/bos/ajax-writes/dry-run/mark_read"),
        new("mark_all_read", "registry", "/bos/ajax-writes/dry-run/mark_all_read"),
        new("dismiss", "registry", "/bos/ajax-writes/dry-run/dismiss"),
        new("send", "registry", "/bos/ajax-writes/dry-run/send"),
        new("broadcast", "registry", "/bos/ajax-writes/dry-run/broadcast"),
        new("fleet_stats", "registry", "/bos/ajax-writes/dry-run/fleet_stats"),
        new("categories", "registry", "/bos/ajax-writes/dry-run/categories"),
        new("prefs_get", "dedicated", "/bos/ajax/prefs-get"),
        new("prefs_save", "dedicated", "/bos/ajax/prefs-save"),
        new("cleanup", "registry", "/bos/ajax-writes/dry-run/cleanup"),
        new("status", "dedicated", "/bos/ajax/status"),
        new("pending", "registry", "/bos/ajax-writes/dry-run/pending"),
        new("run_all", "dedicated", "/bos/ajax/run-all"),
        new("apply", "registry", "/bos/ajax-writes/dry-run/apply"),
        new("rollback", "registry", "/bos/ajax-writes/dry-run/rollback"),
        new("verify", "registry", "/bos/ajax-writes/dry-run/verify"),
        new("dry_run", "registry", "/bos/ajax-writes/dry-run/dry_run"),
        new("list_roles", "registry", "/bos/ajax-writes/dry-run/list_roles"),
        new("role_tiles", "registry", "/bos/ajax-writes/dry-run/role_tiles"),
        new("role_actions", "registry", "/bos/ajax-writes/dry-run/role_actions"),
        new("role_modules", "registry", "/bos/ajax-writes/dry-run/role_modules"),
        new("check_permission", "registry", "/bos/ajax-writes/dry-run/check_permission"),
        new("fleet_summary", "registry", "/bos/ajax-writes/dry-run/fleet_summary"),
        new("set_limit", "dedicated", "/bos/ajax/set-limit"),
        new("check_order", "registry", "/bos/ajax-writes/dry-run/check_order"),
        new("hold", "registry", "/bos/ajax-writes/dry-run/hold"),
        new("release", "registry", "/bos/ajax-writes/dry-run/release"),
        new("history", "registry", "/bos/ajax-writes/dry-run/history"),
        new("due_for_review", "registry", "/bos/ajax-writes/dry-run/due_for_review"),
        new("order_status", "dedicated", "/bos/ajax/order-status"),
        new("run", "registry", "/bos/ajax-writes/dry-run/run"),
        new("steps", "registry", "/bos/ajax-writes/dry-run/steps"),
        new("retry", "registry", "/bos/ajax-writes/dry-run/retry"),
        new("create", "dedicated", "/bos/ajax/create"),
        new("approve", "dedicated", "/bos/ajax/approve"),
        new("reject", "registry", "/bos/ajax-writes/dry-run/reject"),
        new("cancel", "registry", "/bos/ajax-writes/dry-run/cancel"),
        new("tiers", "registry", "/bos/ajax-writes/dry-run/tiers"),
        new("endpoints", "registry", "/bos/ajax-writes/dry-run/endpoints"),
        new("openapi", "registry", "/bos/ajax-writes/dry-run/openapi"),
        new("keys_list", "registry", "/bos/ajax-writes/dry-run/keys_list"),
        new("key_generate", "dedicated", "/bos/ajax/key-generate"),
        new("key_revoke", "dedicated", "/bos/ajax/key-revoke"),
        new("usage", "registry", "/bos/ajax-writes/dry-run/usage"),
        new("queue", "registry", "/bos/ajax-writes/dry-run/queue"),
        new("transition", "registry", "/bos/ajax-writes/dry-run/transition"),
        new("pick_item", "registry", "/bos/ajax-writes/dry-run/pick_item"),
        new("packing_slip", "registry", "/bos/ajax-writes/dry-run/packing_slip"),
        new("create_wave", "dedicated", "/bos/ajax/create-wave"),
        new("sla_breaches", "registry", "/bos/ajax-writes/dry-run/sla_breaches"),
        new("fleet_overview", "registry", "/bos/ajax-writes/dry-run/fleet_overview"),
        new("dashboard", "registry", "/bos/ajax-writes/dry-run/dashboard"),
        new("trend", "registry", "/bos/ajax-writes/dry-run/trend"),
        new("compute", "registry", "/bos/ajax-writes/dry-run/compute"),
        new("compare", "registry", "/bos/ajax-writes/dry-run/compare"),
        new("definitions", "registry", "/bos/ajax-writes/dry-run/definitions"),
        new("classify", "registry", "/bos/ajax-writes/dry-run/classify"),
        new("classify_product", "registry", "/bos/ajax-writes/dry-run/classify_product"),
        new("batch", "registry", "/bos/ajax-writes/dry-run/batch"),
        new("hs_lookup", "registry", "/bos/ajax-writes/dry-run/hs_lookup"),
        new("seed_hs", "dedicated", "/bos/ajax/seed-hs"),
        new("rules", "registry", "/bos/ajax-writes/dry-run/rules"),
        new("review", "registry", "/bos/ajax-writes/dry-run/review"),
        new("groups", "dedicated", "/bos/ajax/groups"),
        new("all", "registry", "/bos/ajax-writes/dry-run/all"),
        new("group", "dedicated", "/bos/ajax/group"),
        new("set", "registry", "/bos/ajax-writes/dry-run/set"),
        new("bulk_set", "registry", "/bos/ajax-writes/dry-run/bulk_set"),
        new("export", "registry", "/bos/ajax-writes/dry-run/export"),
        new("import", "registry", "/bos/ajax-writes/dry-run/import"),
        new("toggle", "registry", "/bos/ajax-writes/dry-run/toggle"),
        new("execute", "registry", "/bos/ajax-writes/dry-run/execute"),
        new("triggers", "registry", "/bos/ajax-writes/dry-run/triggers"),
        new("actions", "registry", "/bos/ajax-writes/dry-run/actions"),
        new("templates", "registry", "/bos/ajax-writes/dry-run/templates"),
        new("suggestions", "registry", "/bos/ajax-writes/dry-run/suggestions"),
        new("stockouts", "registry", "/bos/ajax-writes/dry-run/stockouts"),
        new("abc", "registry", "/bos/ajax-writes/dry-run/abc"),
        new("currencies", "registry", "/bos/ajax-writes/dry-run/currencies"),
        new("set_rate", "dedicated", "/bos/ajax/set-rate"),
        new("get_rate", "registry", "/bos/ajax-writes/dry-run/get_rate"),
        new("rate_history", "registry", "/bos/ajax-writes/dry-run/rate_history"),
        new("convert", "registry", "/bos/ajax-writes/dry-run/convert"),
        new("journal_entry", "registry", "/bos/ajax-writes/dry-run/journal_entry"),
        new("revalue", "registry", "/bos/ajax-writes/dry-run/revalue"),
        new("exposure", "registry", "/bos/ajax-writes/dry-run/exposure"),
        new("trial_balance", "registry", "/bos/ajax-writes/dry-run/trial_balance"),
        new("seed_rates", "dedicated", "/bos/ajax/seed-rates"),
        new("sp_metadata", "registry", "/bos/ajax-writes/dry-run/sp_metadata"),
        new("sp_metadata_xml", "registry", "/bos/ajax-writes/dry-run/sp_metadata_xml"),
        new("providers", "registry", "/bos/ajax-writes/dry-run/providers"),
        new("provider_get", "dedicated", "/bos/ajax/provider-get"),
        new("provider_create", "dedicated", "/bos/ajax/provider-create"),
        new("provider_toggle", "dedicated", "/bos/ajax/provider-toggle"),
        new("provider_delete", "dedicated", "/bos/ajax/provider-delete"),
        new("initiate", "registry", "/bos/ajax-writes/dry-run/initiate"),
        new("sessions", "registry", "/bos/ajax-writes/dry-run/sessions"),
        new("logout", "registry", "/bos/ajax-writes/dry-run/logout"),
        new("employees", "registry", "/bos/ajax-writes/dry-run/employees"),
        new("employee_add", "registry", "/bos/ajax-writes/dry-run/employee_add"),
        new("create_run", "dedicated", "/bos/ajax/create-run"),
        new("approve_run", "dedicated", "/bos/ajax/approve-run"),
        new("run_details", "dedicated", "/bos/ajax/run-details"),
        new("runs", "registry", "/bos/ajax-writes/dry-run/runs"),
        new("generate_sif", "registry", "/bos/ajax-writes/dry-run/generate_sif"),
        new("profiles", "registry", "/bos/ajax-writes/dry-run/profiles"),
        new("profile_create", "dedicated", "/bos/ajax/profile-create"),
        new("add_invoice", "dedicated", "/bos/ajax/add-invoice"),
        new("update_status", "dedicated", "/bos/ajax/update-status"),
        new("record_payment", "registry", "/bos/ajax-writes/dry-run/record_payment"),
        new("process", "registry", "/bos/ajax-writes/dry-run/process"),
        new("aging", "registry", "/bos/ajax-writes/dry-run/aging"),
        new("check", "registry", "/bos/ajax-writes/dry-run/check"),
        new("warranties", "registry", "/bos/ajax-writes/dry-run/warranties"),
        new("rma_create", "dedicated", "/bos/ajax/rma-create"),
        new("rma_transition", "dedicated", "/bos/ajax/rma-transition"),
        new("rma_list", "dedicated", "/bos/ajax/rma-list"),
        new("rma_detail", "dedicated", "/bos/ajax/rma-detail"),
        new("place_order", "registry", "/bos/ajax-writes/dry-run/place_order"),
        new("auto_tier", "registry", "/bos/ajax-writes/dry-run/auto_tier"),
        new("ask", "registry", "/bos/ajax-writes/dry-run/ask"),
        new("intents", "registry", "/bos/ajax-writes/dry-run/intents"),
        new("builtins", "registry", "/bos/ajax-writes/dry-run/builtins"),
        new("seed", "dedicated", "/bos/ajax/seed"),
        new("assign", "registry", "/bos/ajax-writes/dry-run/assign"),
        new("tenant_packs", "registry", "/bos/ajax-writes/dry-run/tenant_packs"),
        new("create_group", "dedicated", "/bos/ajax/create-group"),
        new("members", "dedicated", "/bos/ajax/members"),
        new("add_member", "dedicated", "/bos/ajax/add-member"),
        new("intercompany", "registry", "/bos/ajax-writes/dry-run/intercompany"),
        new("eliminate", "registry", "/bos/ajax-writes/dry-run/eliminate"),
        new("consolidated_tb", "registry", "/bos/ajax-writes/dry-run/consolidated_tb"),
        new("record_usage", "registry", "/bos/ajax-writes/dry-run/record_usage"),
        new("apply_change", "registry", "/bos/ajax-writes/dry-run/apply_change"),
        new("diff", "registry", "/bos/ajax-writes/dry-run/diff"),
        new("promote", "registry", "/bos/ajax-writes/dry-run/promote"),
        new("discard", "registry", "/bos/ajax-writes/dry-run/discard"),
        new("schemas", "registry", "/bos/ajax-writes/dry-run/schemas"),
        new("errors", "registry", "/bos/ajax-writes/dry-run/errors"),
        new("jobs", "registry", "/bos/ajax-writes/dry-run/jobs"),
        new("folders", "dedicated", "/bos/ajax/folders"),
        new("create_folder", "dedicated", "/bos/ajax/create-folder"),
        new("upload", "registry", "/bos/ajax-writes/dry-run/upload"),
        new("new_version", "registry", "/bos/ajax-writes/dry-run/new_version"),
        new("documents", "registry", "/bos/ajax-writes/dry-run/documents"),
        new("versions", "registry", "/bos/ajax-writes/dry-run/versions"),
        new("plans", "dedicated", "/bos/ajax/plans"),
        new("create_plan", "dedicated", "/bos/ajax/create-plan"),
        new("subscribe", "registry", "/bos/ajax-writes/dry-run/subscribe"),
        new("subscription", "registry", "/bos/ajax-writes/dry-run/subscription"),
        new("invoices", "dedicated", "/bos/ajax/invoices"),
        new("pay", "registry", "/bos/ajax-writes/dry-run/pay"),
        new("controls", "dedicated", "/bos/ajax/controls"),
        new("update_control", "dedicated", "/bos/ajax/update-control"),
        new("add_evidence", "dedicated", "/bos/ajax/add-evidence"),
        new("evidence", "dedicated", "/bos/ajax/evidence"),
        new("gap_analysis", "registry", "/bos/ajax-writes/dry-run/gap_analysis"),
        new("policies", "registry", "/bos/ajax-writes/dry-run/policies"),
        new("create_policy", "dedicated", "/bos/ajax/create-policy"),
        new("browse", "registry", "/bos/ajax-writes/dry-run/browse"),
        new("install", "registry", "/bos/ajax-writes/dry-run/install"),
        new("uninstall", "registry", "/bos/ajax-writes/dry-run/uninstall"),
        new("tenant_apps", "registry", "/bos/ajax-writes/dry-run/tenant_apps"),
    ];

    private static readonly Dictionary<string, BosAjaxWriteCatalogEntry> ByAction =
        Entries.ToDictionary(e => e.Action, StringComparer.OrdinalIgnoreCase);

    public IReadOnlyList<BosAjaxWriteCatalogEntry> All => Entries;

    public bool TryGet(string action, out BosAjaxWriteCatalogEntry entry) =>
        ByAction.TryGetValue(action ?? "", out entry!);

    public BosAjaxWriteCatalogReport BuildReport()
    {
        var dedicated = Entries.Count(e => e.Coverage == "dedicated");
        var registry = Entries.Count(e => e.Coverage == "registry");
        return new(
            Role: "bos-ajax-write-catalog",
            Status: "building-toward-zero-php",
            CutoverAllowed: false,
            ReadyForPhpRemoval: false,
            PhpAuthoritative: true,
            PhpAjax: "/BOS/ajax_epc_bos.php",
            TotalActions: Entries.Length,
            DedicatedDryRuns: dedicated,
            RegistryDryRuns: registry,
            CoveragePct: Entries.Length == 0 ? 0 : (int)Math.Round(100.0 * (dedicated + registry) / Entries.Length),
            Actions: Entries,
            Notes:
            [
                "Coverage means ASP.NET dry-run gate exists (writes=0); live BOS writes remain PHP.",
                "Distinct from ERP ajax_erp.php Bos* dry-runs — this is the BOS host ajax endpoint.",
                "cutoverAllowed stays false until dual-sample + human RELEASE_OWNER_APPROVAL.md.",
            ]);
    }
}

public sealed record BosAjaxWriteCatalogEntry(string Action, string Coverage, string AspNetRouteHint);

public sealed record BosAjaxWriteCatalogReport(
    string Role, string Status, bool CutoverAllowed, bool ReadyForPhpRemoval, bool PhpAuthoritative,
    string PhpAjax, int TotalActions, int DedicatedDryRuns, int RegistryDryRuns, int CoveragePct,
    IReadOnlyList<BosAjaxWriteCatalogEntry> Actions, IReadOnlyList<string> Notes);
