namespace EcomAE.Platform.Migration;

/// <summary>
/// Full inventory of PHP ajax_erp.php actions for Wave B zero-PHP coverage.
/// Every action is either a dedicated dry-run route or the registry dry-run.
/// Never invents cutoverAllowed=true; PHP ajax_erp.php remains authoritative.
/// </summary>
public interface IErpAjaxWriteCatalog
{
    ErpAjaxWriteCatalogReport BuildReport();
    bool TryGet(string action, out ErpAjaxWriteCatalogEntry entry);
    IReadOnlyList<ErpAjaxWriteCatalogEntry> All { get; }
}

public sealed class ErpAjaxWriteCatalog : IErpAjaxWriteCatalog
{
    private static readonly ErpAjaxWriteCatalogEntry[] Entries =
    [
        new("edit_lock_acquire", "dedicated", "/erp/ajax/edit-lock-acquire"),
        new("edit_lock_heartbeat", "dedicated", "/erp/ajax/edit-lock-heartbeat"),
        new("edit_lock_release", "dedicated", "/erp/ajax/edit-lock-release"),
        new("presence_heartbeat", "dedicated", "/erp/ajax/presence-heartbeat"),
        new("concurrency_status", "dedicated", "/erp/ajax/concurrency-status"),
        new("create_supplier", "dedicated", "/erp/ajax/create-supplier"),
        new("sync_suppliers", "dedicated", "/erp/ajax/sync-suppliers"),
        new("create_purchase", "dedicated", "/erp/ajax/create-purchase"),
        new("as_rma_create", "dedicated", "/erp/ajax/as-rma-create"),
        new("supplier_payment", "dedicated", "/erp/ajax/supplier-payment"),
        new("payment_voucher", "dedicated", "/erp/ajax/payment-voucher"),
        new("settlement_open_docs", "dedicated", "/erp/ajax/settlement-open-docs"),
        new("cash_entry", "dedicated", "/erp/ajax/cash-entry"),
        new("create_account", "dedicated", "/erp/ajax/create-account"),
        new("purchase_from_order", "dedicated", "/erp/ajax/purchase-from-order"),
        new("dashboard", "dedicated", "/erp/ajax/dashboard"),
        new("command_center", "dedicated", "/erp/ajax/command-center"),
        new("cc_kpi_tiles", "dedicated", "/erp/ajax/cc-kpi-tiles"),
        new("cc_approval_queue", "dedicated", "/erp/ajax/cc-approval-queue"),
        new("create_coa", "dedicated", "/erp/ajax/create-coa"),
        new("gl_manual_entry", "dedicated", "/erp/ajax/gl-manual-entry"),
        new("gl_reverse_journal", "dedicated", "/erp/ajax/gl-reverse-journal"),
        new("fiscal_set_lock", "dedicated", "/erp/ajax/fiscal-set-lock"),
        new("period_list", "dedicated", "/erp/ajax/period-list"),
        new("period_checklist", "dedicated", "/erp/ajax/period-checklist"),
        new("period_soft_close", "dedicated", "/erp/ajax/period-soft-close"),
        new("period_lock", "dedicated", "/erp/ajax/period-lock"),
        new("period_reopen", "dedicated", "/erp/ajax/period-reopen"),
        new("period_summary", "dedicated", "/erp/ajax/period-summary"),
        new("period_log", "dedicated", "/erp/ajax/period-log"),
        new("ccy_set_rate", "dedicated", "/erp/ajax/ccy-set-rate"),
        new("fx_revaluation_preview", "dedicated", "/erp/ajax/fx-revaluation-preview"),
        new("fx_post_revaluation", "dedicated", "/erp/ajax/fx-post-revaluation"),
        new("gl_post_sales", "dedicated", "/erp/ajax/gl-post-sales"),
        new("gl_sync_unposted", "dedicated", "/erp/ajax/gl-sync-unposted"),
        new("customer_settlement", "dedicated", "/erp/ajax/customer-settlement"),
        new("supplier_settlement", "dedicated", "/erp/ajax/supplier-settlement"),
        new("purchase_adjustment", "dedicated", "/erp/ajax/purchase-adjustment"),
        new("order_settlement", "dedicated", "/erp/ajax/order-settlement"),
        new("workflow_status", "dedicated", "/erp/ajax/workflow-status"),
        new("workflow_create", "dedicated", "/erp/ajax/workflow-create"),
        new("marketing_create", "dedicated", "/erp/ajax/marketing-create"),
        new("bos_compliance_file", "dedicated", "/erp/ajax/bos-compliance-file"),
        new("bos_compliance_add_obligation", "dedicated", "/erp/ajax/bos-compliance-add-obligation"),
        new("bos_compliance_disable_obligation", "dedicated", "/erp/ajax/bos-compliance-disable-obligation"),
        new("bos_compliance_save_retention", "dedicated", "/erp/ajax/bos-compliance-save-retention"),
        new("bos_compliance_fetch", "dedicated", "/erp/ajax/bos-compliance-fetch"),
        new("bos_wf_save_rule", "dedicated", "/erp/ajax/bos-wf-save-rule"),
        new("bos_wf_disable_rule", "dedicated", "/erp/ajax/bos-wf-disable-rule"),
        new("bos_wf_decide", "dedicated", "/erp/ajax/bos-wf-decide"),
        new("bos_wf_raise_test", "dedicated", "/erp/ajax/bos-wf-raise-test"),
        new("bos_intel_toggle_control", "dedicated", "/erp/ajax/bos-intel-toggle-control"),
        new("bos_vat_refund_save", "dedicated", "/erp/ajax/bos-vat-refund-save"),
        new("bos_vat_refund_status", "dedicated", "/erp/ajax/bos-vat-refund-status"),
        new("opl_params_save", "dedicated", "/erp/ajax/opl-params-save"),
        new("opl_set_status", "dedicated", "/erp/ajax/opl-set-status"),
        new("opl_confirm_all", "dedicated", "/erp/ajax/opl-confirm-all"),
        new("opl_create_pos", "dedicated", "/erp/ajax/opl-create-pos"),
        new("opl_autoplan", "dedicated", "/erp/ajax/opl-autoplan"),
        new("opl_seed_demo", "dedicated", "/erp/ajax/opl-seed-demo"),
        new("opl_clear_demo", "dedicated", "/erp/ajax/opl-clear-demo"),
        new("pf_process_save", "dedicated", "/erp/ajax/pf-process-save"),
        new("pf_step_save", "dedicated", "/erp/ajax/pf-step-save"),
        new("pf_step_delete", "dedicated", "/erp/ajax/pf-step-delete"),
        new("pf_set_dept_head", "dedicated", "/erp/ajax/pf-set-dept-head"),
        new("pf_case_start", "dedicated", "/erp/ajax/pf-case-start"),
        new("pf_case_act", "dedicated", "/erp/ajax/pf-case-act"),
        new("pf_case_reassign", "dedicated", "/erp/ajax/pf-case-reassign"),
        new("pf_case_cancel", "dedicated", "/erp/ajax/pf-case-cancel"),
        new("pf_seed_demo", "dedicated", "/erp/ajax/pf-seed-demo"),
        new("pf_clear_demo", "dedicated", "/erp/ajax/pf-clear-demo"),
        new("pf_sync_orders", "dedicated", "/erp/ajax/pf-sync-orders"),
        new("demo_seed_sales", "dedicated", "/erp/ajax/demo-seed-sales"),
        new("demo_clear_sales", "dedicated", "/erp/ajax/demo-clear-sales"),
        new("sub_save", "dedicated", "/erp/ajax/sub-save"),
        new("sub_status", "dedicated", "/erp/ajax/sub-status"),
        new("sub_generate", "dedicated", "/erp/ajax/sub-generate"),
        new("sub_invoice_paid", "dedicated", "/erp/ajax/sub-invoice-paid"),
        new("ctr_save", "dedicated", "/erp/ajax/ctr-save"),
        new("ctr_status", "dedicated", "/erp/ajax/ctr-status"),
        new("ctr_sign", "dedicated", "/erp/ajax/ctr-sign"),
        new("ctr_ocr", "dedicated", "/erp/ajax/ctr-ocr"),
        new("docx_save", "dedicated", "/erp/ajax/docx-save"),
        new("docx_delete", "dedicated", "/erp/ajax/docx-delete"),
        new("docx_run_reminders", "dedicated", "/erp/ajax/docx-run-reminders"),
        new("ins_save", "dedicated", "/erp/ajax/ins-save"),
        new("ins_delete", "dedicated", "/erp/ajax/ins-delete"),
        new("ins_doc_add", "dedicated", "/erp/ajax/ins-doc-add"),
        new("ins_doc_delete", "dedicated", "/erp/ajax/ins-doc-delete"),
        new("ins_claim_add", "dedicated", "/erp/ajax/ins-claim-add"),
        new("wms_location_save", "dedicated", "/erp/ajax/wms-location-save"),
        new("wms_location_delete", "dedicated", "/erp/ajax/wms-location-delete"),
        new("wms_receive", "dedicated", "/erp/ajax/wms-receive"),
        new("wms_wave_create", "dedicated", "/erp/ajax/wms-wave-create"),
        new("wms_wave_release", "dedicated", "/erp/ajax/wms-wave-release"),
        new("wms_work_complete", "dedicated", "/erp/ajax/wms-work-complete"),
        new("mfgr_wc_save", "dedicated", "/erp/ajax/mfgr-wc-save"),
        new("mfgr_route_save", "dedicated", "/erp/ajax/mfgr-route-save"),
        new("mfgr_mrp_run", "dedicated", "/erp/ajax/mfgr-mrp-run"),
        new("mfgr_planned_firm", "dedicated", "/erp/ajax/mfgr-planned-firm"),
        new("fin_periods_generate", "dedicated", "/erp/ajax/fin-periods-generate"),
        new("fin_period_status", "dedicated", "/erp/ajax/fin-period-status"),
        new("fin_fx_revalue", "dedicated", "/erp/ajax/fin-fx-revalue"),
        new("fin_alloc_save", "dedicated", "/erp/ajax/fin-alloc-save"),
        new("fin_alloc_run", "dedicated", "/erp/ajax/fin-alloc-run"),
        new("fin_accrual_save", "dedicated", "/erp/ajax/fin-accrual-save"),
        new("coll_case_save", "dedicated", "/erp/ajax/coll-case-save"),
        new("coll_case_status", "dedicated", "/erp/ajax/coll-case-status"),
        new("coll_case_promise", "dedicated", "/erp/ajax/coll-case-promise"),
        new("coll_activity_log", "dedicated", "/erp/ajax/coll-activity-log"),
        new("coll_dunning_run", "dedicated", "/erp/ajax/coll-dunning-run"),
        new("coll_hold_set", "dedicated", "/erp/ajax/coll-hold-set"),
        new("proc_category_save", "dedicated", "/erp/ajax/proc-category-save"),
        new("proc_policy_save", "dedicated", "/erp/ajax/proc-policy-save"),
        new("proc_req_save", "dedicated", "/erp/ajax/proc-req-save"),
        new("proc_req_add_line", "dedicated", "/erp/ajax/proc-req-add-line"),
        new("proc_req_submit", "dedicated", "/erp/ajax/proc-req-submit"),
        new("proc_req_decision", "dedicated", "/erp/ajax/proc-req-decision"),
        new("proc_req_convert", "dedicated", "/erp/ajax/proc-req-convert"),
        new("bplan_save", "dedicated", "/erp/ajax/bplan-save"),
        new("bplan_line_add", "dedicated", "/erp/ajax/bplan-line-add"),
        new("bplan_position_add", "dedicated", "/erp/ajax/bplan-position-add"),
        new("bplan_advance", "dedicated", "/erp/ajax/bplan-advance"),
        new("hrt_job_save", "dedicated", "/erp/ajax/hrt-job-save"),
        new("hrt_applicant_add", "dedicated", "/erp/ajax/hrt-applicant-add"),
        new("hrt_applicant_stage", "dedicated", "/erp/ajax/hrt-applicant-stage"),
        new("hrt_review_save", "dedicated", "/erp/ajax/hrt-review-save"),
        new("hrt_goal_add", "dedicated", "/erp/ajax/hrt-goal-add"),
        new("hrt_review_finalize", "dedicated", "/erp/ajax/hrt-review-finalize"),
        new("cft_forecast_save", "dedicated", "/erp/ajax/cft-forecast-save"),
        new("cft_line_add", "dedicated", "/erp/ajax/cft-line-add"),
        new("cft_instrument_save", "dedicated", "/erp/ajax/cft-instrument-save"),
        new("cft_instrument_status", "dedicated", "/erp/ajax/cft-instrument-status"),
        new("wht_code_save", "dedicated", "/erp/ajax/wht-code-save"),
        new("wht_record", "dedicated", "/erp/ajax/wht-record"),
        new("wht_certificate", "dedicated", "/erp/ajax/wht-certificate"),
        new("wht_settle", "dedicated", "/erp/ajax/wht-settle"),
        new("er_format_save", "dedicated", "/erp/ajax/er-format-save"),
        new("er_field_add", "dedicated", "/erp/ajax/er-field-add"),
        new("customer_master_save", "dedicated", "/erp/ajax/customer-master-save"),
        new("prja_budget_save", "dedicated", "/erp/ajax/prja-budget-save"),
        new("prja_txn_add", "dedicated", "/erp/ajax/prja-txn-add"),
        new("prja_recognize", "dedicated", "/erp/ajax/prja-recognize"),
        new("costm_item_set", "dedicated", "/erp/ajax/costm-item-set"),
        new("costm_txn_add", "dedicated", "/erp/ajax/costm-txn-add"),
        new("costm_close_run", "dedicated", "/erp/ajax/costm-close-run"),
        new("intg_entity_save", "dedicated", "/erp/ajax/intg-entity-save"),
        new("intg_sub_save", "dedicated", "/erp/ajax/intg-sub-save"),
        new("intg_event_raise", "dedicated", "/erp/ajax/intg-event-raise"),
        new("fy_create", "dedicated", "/erp/ajax/fy-create"),
        new("fy_close", "dedicated", "/erp/ajax/fy-close"),
        new("fy_reopen", "dedicated", "/erp/ajax/fy-reopen"),
        new("fy_period_status", "dedicated", "/erp/ajax/fy-period-status"),
        new("plt_job_save", "dedicated", "/erp/ajax/plt-job-save"),
        new("plt_job_run", "dedicated", "/erp/ajax/plt-job-run"),
        new("plt_feature_save", "dedicated", "/erp/ajax/plt-feature-save"),
        new("oa_party_save", "dedicated", "/erp/ajax/oa-party-save"),
        new("oa_address_save", "dedicated", "/erp/ajax/oa-address-save"),
        new("oa_contact_save", "dedicated", "/erp/ajax/oa-contact-save"),
        new("oa_calendar_save", "dedicated", "/erp/ajax/oa-calendar-save"),
        new("oa_holiday_add", "dedicated", "/erp/ajax/oa-holiday-add"),
        new("rbac_priv_save", "dedicated", "/erp/ajax/rbac-priv-save"),
        new("rbac_duty_save", "dedicated", "/erp/ajax/rbac-duty-save"),
        new("rbac_duty_priv", "dedicated", "/erp/ajax/rbac-duty-priv"),
        new("rbac_role_save", "dedicated", "/erp/ajax/rbac-role-save"),
        new("rbac_role_duty", "dedicated", "/erp/ajax/rbac-role-duty"),
        new("rbac_user_role", "dedicated", "/erp/ajax/rbac-user-role"),
        new("rtl_channel_save", "dedicated", "/erp/ajax/rtl-channel-save"),
        new("rtl_assortment_set", "dedicated", "/erp/ajax/rtl-assortment-set"),
        new("rtl_discount_save", "dedicated", "/erp/ajax/rtl-discount-save"),
        new("rtl_pos_sale", "dedicated", "/erp/ajax/rtl-pos-sale"),
        new("qm_plan_save", "dedicated", "/erp/ajax/qm-plan-save"),
        new("qm_test_add", "dedicated", "/erp/ajax/qm-test-add"),
        new("qm_order_create", "dedicated", "/erp/ajax/qm-order-create"),
        new("qm_order_record", "dedicated", "/erp/ajax/qm-order-record"),
        new("qm_ncr_create", "dedicated", "/erp/ajax/qm-ncr-create"),
        new("qm_ncr_update", "dedicated", "/erp/ajax/qm-ncr-update"),
        new("ins_claim_status", "dedicated", "/erp/ajax/ins-claim-status"),
        new("hr_emp_save", "dedicated", "/erp/ajax/hr-emp-save"),
        new("hr_attendance", "dedicated", "/erp/ajax/hr-attendance"),
        new("hr_leave_request", "dedicated", "/erp/ajax/hr-leave-request"),
        new("hr_leave_status", "dedicated", "/erp/ajax/hr-leave-status"),
        new("hr_expense_save", "dedicated", "/erp/ajax/hr-expense-save"),
        new("hr_expense_status", "dedicated", "/erp/ajax/hr-expense-status"),
        new("prj_save", "dedicated", "/erp/ajax/prj-save"),
        new("prj_task_save", "dedicated", "/erp/ajax/prj-task-save"),
        new("prj_log_time", "dedicated", "/erp/ajax/prj-log-time"),
        new("cons_entity_save", "dedicated", "/erp/ajax/cons-entity-save"),
        new("cons_entity_delete", "dedicated", "/erp/ajax/cons-entity-delete"),
        new("cons_figures_save", "dedicated", "/erp/ajax/cons-figures-save"),
        new("cons_ic_save", "dedicated", "/erp/ajax/cons-ic-save"),
        new("cons_ic_delete", "dedicated", "/erp/ajax/cons-ic-delete"),
        new("mfg_bom_save", "dedicated", "/erp/ajax/mfg-bom-save"),
        new("mfg_wo_create", "dedicated", "/erp/ajax/mfg-wo-create"),
        new("mfg_wo_issue", "dedicated", "/erp/ajax/mfg-wo-issue"),
        new("mfg_wo_complete", "dedicated", "/erp/ajax/mfg-wo-complete"),
        new("payroll_generate", "dedicated", "/erp/ajax/payroll-generate"),
        new("payroll_approve", "dedicated", "/erp/ajax/payroll-approve"),
        new("payroll_pay", "dedicated", "/erp/ajax/payroll-pay"),
        new("payroll_update_days", "dedicated", "/erp/ajax/payroll-update-days"),
        new("hr_update_days", "dedicated", "/erp/ajax/hr-update-days"),
        new("uae_tax_fta_fetch", "dedicated", "/erp/ajax/uae-tax-fta-fetch"),
        new("aml_check", "dedicated", "/erp/ajax/aml-check"),
        new("aml_kyc_save", "dedicated", "/erp/ajax/aml-kyc-save"),
        new("aml_alert_status", "dedicated", "/erp/ajax/aml-alert-status"),
        new("aml_report_generate", "dedicated", "/erp/ajax/aml-report-generate"),
        new("aml_settings_save", "dedicated", "/erp/ajax/aml-settings-save"),
        new("aml_seed_rules", "dedicated", "/erp/ajax/aml-seed-rules"),
        new("uae_tax_legislation_regen_summaries", "dedicated", "/erp/ajax/uae-tax-legislation-regen-summaries"),
        new("uae_tax_legislation_ask", "dedicated", "/erp/ajax/uae-tax-legislation-ask"),
        new("uae_tax_save_ct_adjustments", "dedicated", "/erp/ajax/uae-tax-save-ct-adjustments"),
        new("uae_tax_legislation_checklist_set", "dedicated", "/erp/ajax/uae-tax-legislation-checklist-set"),
        new("einvoice_create", "dedicated", "/erp/ajax/einvoice-create"),
        new("einvoice_save_seller", "dedicated", "/erp/ajax/einvoice-save-seller"),
        new("einvoice_save_buyer", "dedicated", "/erp/ajax/einvoice-save-buyer"),
        new("einvoice_save_asp", "dedicated", "/erp/ajax/einvoice-save-asp"),
        new("einvoice_submit", "dedicated", "/erp/ajax/einvoice-submit"),
        new("einvoice_credit_note", "dedicated", "/erp/ajax/einvoice-credit-note"),
        new("einvoice_poll_asp", "dedicated", "/erp/ajax/einvoice-poll-asp"),
        new("invoice_save", "dedicated", "/erp/ajax/invoice-save"),
        new("invoice_list", "dedicated", "/erp/ajax/invoice-list"),
        new("invoice_from_order", "dedicated", "/erp/ajax/invoice-from-order"),
        new("inv_sync_warehouses", "dedicated", "/erp/ajax/inv-sync-warehouses"),
        new("inv_create_warehouse", "dedicated", "/erp/ajax/inv-create-warehouse"),
        new("inv_create_item", "dedicated", "/erp/ajax/inv-create-item"),
        new("inv_set_reorder_level", "dedicated", "/erp/ajax/inv-set-reorder-level"),
        new("inv_record_movement", "dedicated", "/erp/ajax/inv-record-movement"),
        new("ai_query", "dedicated", "/erp/ajax/ai-query"),
        new("integrity_scan", "dedicated", "/erp/ajax/integrity-scan"),
        new("integrity_apply_fks", "dedicated", "/erp/ajax/integrity-apply-fks"),
        new("inv_scan_lookup", "dedicated", "/erp/ajax/inv-scan-lookup"),
        new("inv_transfer", "dedicated", "/erp/ajax/inv-transfer"),
        new("inv_import_csv", "dedicated", "/erp/ajax/inv-import-csv"),
        new("inv_run_closing", "dedicated", "/erp/ajax/inv-run-closing"),
        new("fa_create_asset", "dedicated", "/erp/ajax/fa-create-asset"),
        new("fa_run_depreciation", "dedicated", "/erp/ajax/fa-run-depreciation"),
        new("opening_create_batch", "dedicated", "/erp/ajax/opening-create-batch"),
        new("opening_add_coa_line", "dedicated", "/erp/ajax/opening-add-coa-line"),
        new("opening_add_inv_line", "dedicated", "/erp/ajax/opening-add-inv-line"),
        new("opening_post_batch", "dedicated", "/erp/ajax/opening-post-batch"),
        new("save_rfq", "dedicated", "/erp/ajax/save-rfq"),
        new("delivery_note_create", "dedicated", "/erp/ajax/delivery-note-create"),
        new("bank_import", "dedicated", "/erp/ajax/bank-import"),
        new("bank_reconcile", "dedicated", "/erp/ajax/bank-reconcile"),
        new("save_contact", "dedicated", "/erp/ajax/save-contact"),
        new("sync_contacts", "dedicated", "/erp/ajax/sync-contacts"),
        new("document_upload", "dedicated", "/erp/ajax/document-upload"),
        new("document_delete", "dedicated", "/erp/ajax/document-delete"),
        new("save_company", "dedicated", "/erp/ajax/save-company"),
        new("save_template", "dedicated", "/erp/ajax/save-template"),
        new("upload_logo", "dedicated", "/erp/ajax/upload-logo"),
        new("upload_attachment", "dedicated", "/erp/ajax/upload-attachment"),
        new("delete_attachment", "dedicated", "/erp/ajax/delete-attachment"),
        new("sync_einvoice_seller", "dedicated", "/erp/ajax/sync-einvoice-seller"),
        new("expense_report_save", "dedicated", "/erp/ajax/expense-report-save"),
        new("po_save", "dedicated", "/erp/ajax/po-save"),
        new("po_status", "dedicated", "/erp/ajax/po-status"),
        new("po_receive_lines", "dedicated", "/erp/ajax/po-receive-lines"),
        new("po_to_invoice", "dedicated", "/erp/ajax/po-to-invoice"),
        new("customer_create", "dedicated", "/erp/ajax/customer-create"),
        new("so_save", "dedicated", "/erp/ajax/so-save"),
        new("so_status", "dedicated", "/erp/ajax/so-status"),
        new("so_to_invoice", "dedicated", "/erp/ajax/so-to-invoice"),
        new("so_delete", "dedicated", "/erp/ajax/so-delete"),
        new("so_cancel", "dedicated", "/erp/ajax/so-cancel"),
        new("po_delete", "dedicated", "/erp/ajax/po-delete"),
        new("cash_voucher_void", "dedicated", "/erp/ajax/cash-voucher-void"),
        new("cash_voucher_amend", "dedicated", "/erp/ajax/cash-voucher-amend"),
        new("purchase_void", "dedicated", "/erp/ajax/purchase-void"),
        new("purchase_delete", "dedicated", "/erp/ajax/purchase-delete"),
        new("purchase_amend", "dedicated", "/erp/ajax/purchase-amend"),
        new("invoice_delete", "dedicated", "/erp/ajax/invoice-delete"),
        new("invoice_cancel", "dedicated", "/erp/ajax/invoice-cancel"),
        new("receipt_voucher", "dedicated", "/erp/ajax/receipt-voucher"),
        new("transfer_voucher", "dedicated", "/erp/ajax/transfer-voucher"),
        new("payment_batch_save", "dedicated", "/erp/ajax/payment-batch-save"),
        new("petty_cash_save", "dedicated", "/erp/ajax/petty-cash-save"),
        new("agenda_save", "dedicated", "/erp/ajax/agenda-save"),
        new("kb_save", "dedicated", "/erp/ajax/kb-save"),
        new("multi_entity_save", "dedicated", "/erp/ajax/multi-entity-save"),
        new("cs_save_declaration", "dedicated", "/erp/ajax/cs-save-declaration"),
        new("cs_submit_declaration", "dedicated", "/erp/ajax/cs-submit-declaration"),
        new("cs_delete_declaration", "dedicated", "/erp/ajax/cs-delete-declaration"),
        new("cs_list_declarations", "dedicated", "/erp/ajax/cs-list-declarations"),
        new("order_fulfillment_bootstrap", "dedicated", "/erp/ajax/order-fulfillment-bootstrap"),
        new("order_fulfillment_status", "dedicated", "/erp/ajax/order-fulfillment-status"),
        new("order_fulfillment_sync", "dedicated", "/erp/ajax/order-fulfillment-sync"),
        new("order_fulfillment_post_po", "dedicated", "/erp/ajax/order-fulfillment-post-po"),
        new("order_fulfillment_post_sales", "dedicated", "/erp/ajax/order-fulfillment-post-sales"),
        new("order_fulfillment_auto_post", "dedicated", "/erp/ajax/order-fulfillment-auto-post"),
        new("order_fulfillment_swap_supplier", "dedicated", "/erp/ajax/order-fulfillment-swap-supplier"),
        new("cs_import_declaration_pdf", "dedicated", "/erp/ajax/cs-import-declaration-pdf"),
        new("pm_save", "dedicated", "/erp/ajax/pm-save"),
        new("pm_toggle", "dedicated", "/erp/ajax/pm-toggle"),
        new("pm_budget_save", "dedicated", "/erp/ajax/pm-budget-save"),
        new("pm_budget_line_save", "dedicated", "/erp/ajax/pm-budget-line-save"),
        new("pm_listing_save", "dedicated", "/erp/ajax/pm-listing-save"),
        new("pm_listing_attach", "dedicated", "/erp/ajax/pm-listing-attach"),
        new("pm_cheque_save", "dedicated", "/erp/ajax/pm-cheque-save"),
        new("shortcut_list", "dedicated", "/erp/ajax/shortcut-list"),
        new("shortcut_add", "dedicated", "/erp/ajax/shortcut-add"),
        new("shortcut_delete", "dedicated", "/erp/ajax/shortcut-delete"),
        new("shortcut_delete_key", "dedicated", "/erp/ajax/shortcut-delete-key"),
        new("shortcut_reset", "dedicated", "/erp/ajax/shortcut-reset"),
        new("shortcut_reorder", "dedicated", "/erp/ajax/shortcut-reorder"),
        new("erp_fav_add", "dedicated", "/erp/ajax/erp-fav-add"),
        new("erp_fav_remove", "dedicated", "/erp/ajax/erp-fav-remove"),
        new("erp_global_search", "dedicated", "/erp/ajax/erp-global-search"),
        new("jw_repair_create", "dedicated", "/erp/ajax/jw-repair-create"),
        new("jw_repair_update_status", "dedicated", "/erp/ajax/jw-repair-update-status"),
        new("jw_seed_sample_data", "dedicated", "/erp/ajax/jw-seed-sample-data"),
        new("ai_assistant_query", "dedicated", "/erp/ajax/ai-assistant-query"),
        new("print_designer_save", "dedicated", "/erp/ajax/print-designer-save"),
        new("workflow_save", "dedicated", "/erp/ajax/workflow-save"),
        new("workflow_run", "dedicated", "/erp/ajax/workflow-run"),
        new("automation_activate", "dedicated", "/erp/ajax/automation-activate"),
        new("automation_deactivate", "dedicated", "/erp/ajax/automation-deactivate"),
        new("automation_install_template", "dedicated", "/erp/ajax/automation-install-template"),
        new("automation_enable_category", "dedicated", "/erp/ajax/automation-enable-category"),
        new("automation_tick", "dedicated", "/erp/ajax/automation-tick"),
        new("tenant_config_save", "dedicated", "/erp/ajax/tenant-config-save"),
    ];

    private static readonly Dictionary<string, ErpAjaxWriteCatalogEntry> ByAction =
        Entries.ToDictionary(e => e.Action, StringComparer.OrdinalIgnoreCase);

    public IReadOnlyList<ErpAjaxWriteCatalogEntry> All => Entries;

    public bool TryGet(string action, out ErpAjaxWriteCatalogEntry entry) =>
        ByAction.TryGetValue(action ?? "", out entry!);

    public ErpAjaxWriteCatalogReport BuildReport()
    {
        var dedicated = Entries.Count(e => e.Coverage == "dedicated");
        var registry = Entries.Count(e => e.Coverage == "registry");
        return new(
            Role: "erp-ajax-write-catalog",
            Status: "building-toward-zero-php",
            CutoverAllowed: false,
            ReadyForPhpRemoval: false,
            PhpAuthoritative: true,
            PhpAjax: "/CP/content/shop/finance/erp/ajax_erp.php",
            TotalActions: Entries.Length,
            DedicatedDryRuns: dedicated,
            RegistryDryRuns: registry,
            CoveragePct: Entries.Length == 0 ? 0 : (int)Math.Round(100.0 * (dedicated + registry) / Entries.Length),
            Actions: Entries,
            Notes:
            [
                "Coverage means ASP.NET dry-run gate exists (writes=0); live writes remain PHP.",
                "Dedicated routes keep richer validation; registry covers the long tail via POST /erp/ajax-writes/dry-run/{action}.",
                "cutoverAllowed stays false until dual-sample + human RELEASE_OWNER_APPROVAL.md.",
            ]);
    }
}

public sealed record ErpAjaxWriteCatalogEntry(string Action, string Coverage, string AspNetRouteHint);

public sealed record ErpAjaxWriteCatalogReport(
    string Role,
    string Status,
    bool CutoverAllowed,
    bool ReadyForPhpRemoval,
    bool PhpAuthoritative,
    string PhpAjax,
    int TotalActions,
    int DedicatedDryRuns,
    int RegistryDryRuns,
    int CoveragePct,
    IReadOnlyList<ErpAjaxWriteCatalogEntry> Actions,
    IReadOnlyList<string> Notes);
