namespace EcomAE.Platform.Migration;

/// <summary>
/// Full inventory of PHP ajax_erp.php actions for Wave B zero-PHP coverage.
/// Every action is either a dedicated dry-run route or the registry dry-run.
/// Never invents cutoverAllowed=true; PHP ajax_erp.php remains authoritative.
/// </summary>
public interface IErpAjaxWriteCatalog
{
    ErpAjaxWriteCatalogReport BuildReport();
    bool TryGet(string action, out ErpAjaxWriteCatalogEntry entry);
    IReadOnlyList<ErpAjaxWriteCatalogEntry> All { get; }
}

public sealed class ErpAjaxWriteCatalog : IErpAjaxWriteCatalog
{
    private static readonly ErpAjaxWriteCatalogEntry[] Entries =
    [
        new("edit_lock_acquire", "dedicated", "/erp/ajax/edit-lock-acquire"),
        new("edit_lock_heartbeat", "dedicated", "/erp/ajax/edit-lock-heartbeat"),
        new("edit_lock_release", "dedicated", "/erp/ajax/edit-lock-release"),
        new("presence_heartbeat", "dedicated", "/erp/ajax/presence-heartbeat"),
        new("concurrency_status", "registry", "/erp/ajax-writes/dry-run/concurrency_status"),
        new("create_supplier", "dedicated", "/erp/ajax/create-supplier"),
        new("sync_suppliers", "dedicated", "/erp/ajax/sync-suppliers"),
        new("create_purchase", "dedicated", "/erp/ajax/create-purchase"),
        new("as_rma_create", "dedicated", "/erp/ajax/as-rma-create"),
        new("supplier_payment", "dedicated", "/erp/ajax/supplier-payment"),
        new("payment_voucher", "dedicated", "/erp/ajax/payment-voucher"),
        new("settlement_open_docs", "registry", "/erp/ajax-writes/dry-run/settlement_open_docs"),
        new("cash_entry", "dedicated", "/erp/ajax/cash-entry"),
        new("create_account", "dedicated", "/erp/ajax/create-account"),
        new("purchase_from_order", "dedicated", "/erp/ajax/purchase-from-order"),
        new("dashboard", "registry", "/erp/ajax-writes/dry-run/dashboard"),
        new("command_center", "registry", "/erp/ajax-writes/dry-run/command_center"),
        new("cc_kpi_tiles", "registry", "/erp/ajax-writes/dry-run/cc_kpi_tiles"),
        new("cc_approval_queue", "registry", "/erp/ajax-writes/dry-run/cc_approval_queue"),
        new("create_coa", "dedicated", "/erp/ajax/create-coa"),
        new("gl_manual_entry", "dedicated", "/erp/ajax/gl-manual-entry"),
        new("gl_reverse_journal", "dedicated", "/erp/ajax/gl-reverse-journal"),
        new("fiscal_set_lock", "dedicated", "/erp/ajax/fiscal-set-lock"),
        new("period_list", "registry", "/erp/ajax-writes/dry-run/period_list"),
        new("period_checklist", "registry", "/erp/ajax-writes/dry-run/period_checklist"),
        new("period_soft_close", "dedicated", "/erp/ajax/period-soft-close"),
        new("period_lock", "dedicated", "/erp/ajax/period-lock"),
        new("period_reopen", "dedicated", "/erp/ajax/period-reopen"),
        new("period_summary", "registry", "/erp/ajax-writes/dry-run/period_summary"),
        new("period_log", "registry", "/erp/ajax-writes/dry-run/period_log"),
        new("ccy_set_rate", "dedicated", "/erp/ajax/ccy-set-rate"),
        new("fx_revaluation_preview", "registry", "/erp/ajax-writes/dry-run/fx_revaluation_preview"),
        new("fx_post_revaluation", "dedicated", "/erp/ajax/fx-post-revaluation"),
        new("gl_post_sales", "dedicated", "/erp/ajax/gl-post-sales"),
        new("gl_sync_unposted", "dedicated", "/erp/ajax/gl-sync-unposted"),
        new("customer_settlement", "dedicated", "/erp/ajax/customer-settlement"),
        new("supplier_settlement", "dedicated", "/erp/ajax/supplier-settlement"),
        new("purchase_adjustment", "dedicated", "/erp/ajax/purchase-adjustment"),
        new("order_settlement", "dedicated", "/erp/ajax/order-settlement"),
        new("workflow_status", "dedicated", "/erp/ajax/workflow-status"),
        new("workflow_create", "dedicated", "/erp/ajax/workflow-create"),
        new("marketing_create", "dedicated", "/erp/ajax/marketing-create"),
        new("bos_compliance_file", "dedicated", "/erp/ajax/bos-compliance-file"),
        new("bos_compliance_add_obligation", "dedicated", "/erp/ajax/bos-compliance-add-obligation"),
        new("bos_compliance_disable_obligation", "dedicated", "/erp/ajax/bos-compliance-disable-obligation"),
        new("bos_compliance_save_retention", "dedicated", "/erp/ajax/bos-compliance-save-retention"),
        new("bos_compliance_fetch", "registry", "/erp/ajax-writes/dry-run/bos_compliance_fetch"),
        new("bos_wf_save_rule", "dedicated", "/erp/ajax/bos-wf-save-rule"),
        new("bos_wf_disable_rule", "dedicated", "/erp/ajax/bos-wf-disable-rule"),
        new("bos_wf_decide", "dedicated", "/erp/ajax/bos-wf-decide"),
        new("bos_wf_raise_test", "dedicated", "/erp/ajax/bos-wf-raise-test"),
        new("bos_intel_toggle_control", "dedicated", "/erp/ajax/bos-intel-toggle-control"),
        new("bos_vat_refund_save", "dedicated", "/erp/ajax/bos-vat-refund-save"),
        new("bos_vat_refund_status", "dedicated", "/erp/ajax/bos-vat-refund-status"),
        new("opl_params_save", "dedicated", "/erp/ajax/opl-params-save"),
        new("opl_set_status", "dedicated", "/erp/ajax/opl-set-status"),
        new("opl_confirm_all", "dedicated", "/erp/ajax/opl-confirm-all"),
        new("opl_create_pos", "dedicated", "/erp/ajax/opl-create-pos"),
        new("opl_autoplan", "registry", "/erp/ajax-writes/dry-run/opl_autoplan"),
        new("opl_seed_demo", "registry", "/erp/ajax-writes/dry-run/opl_seed_demo"),
        new("opl_clear_demo", "registry", "/erp/ajax-writes/dry-run/opl_clear_demo"),
        new("pf_process_save", "dedicated", "/erp/ajax/pf-process-save"),
        new("pf_step_save", "dedicated", "/erp/ajax/pf-step-save"),
        new("pf_step_delete", "dedicated", "/erp/ajax/pf-step-delete"),
        new("pf_set_dept_head", "registry", "/erp/ajax-writes/dry-run/pf_set_dept_head"),
        new("pf_case_start", "dedicated", "/erp/ajax/pf-case-start"),
        new("pf_case_act", "dedicated", "/erp/ajax/pf-case-act"),
        new("pf_case_reassign", "registry", "/erp/ajax-writes/dry-run/pf_case_reassign"),
        new("pf_case_cancel", "registry", "/erp/ajax-writes/dry-run/pf_case_cancel"),
        new("pf_seed_demo", "registry", "/erp/ajax-writes/dry-run/pf_seed_demo"),
        new("pf_clear_demo", "registry", "/erp/ajax-writes/dry-run/pf_clear_demo"),
        new("pf_sync_orders", "registry", "/erp/ajax-writes/dry-run/pf_sync_orders"),
        new("demo_seed_sales", "registry", "/erp/ajax-writes/dry-run/demo_seed_sales"),
        new("demo_clear_sales", "registry", "/erp/ajax-writes/dry-run/demo_clear_sales"),
        new("sub_save", "dedicated", "/erp/ajax/sub-save"),
        new("sub_status", "dedicated", "/erp/ajax/sub-status"),
        new("sub_generate", "dedicated", "/erp/ajax/sub-generate"),
        new("sub_invoice_paid", "dedicated", "/erp/ajax/sub-invoice-paid"),
        new("ctr_save", "dedicated", "/erp/ajax/ctr-save"),
        new("ctr_status", "dedicated", "/erp/ajax/ctr-status"),
        new("ctr_sign", "dedicated", "/erp/ajax/ctr-sign"),
        new("ctr_ocr", "registry", "/erp/ajax-writes/dry-run/ctr_ocr"),
        new("docx_save", "registry", "/erp/ajax-writes/dry-run/docx_save"),
        new("docx_delete", "registry", "/erp/ajax-writes/dry-run/docx_delete"),
        new("docx_run_reminders", "registry", "/erp/ajax-writes/dry-run/docx_run_reminders"),
        new("ins_save", "registry", "/erp/ajax-writes/dry-run/ins_save"),
        new("ins_delete", "registry", "/erp/ajax-writes/dry-run/ins_delete"),
        new("ins_doc_add", "registry", "/erp/ajax-writes/dry-run/ins_doc_add"),
        new("ins_doc_delete", "registry", "/erp/ajax-writes/dry-run/ins_doc_delete"),
        new("ins_claim_add", "registry", "/erp/ajax-writes/dry-run/ins_claim_add"),
        new("wms_location_save", "dedicated", "/erp/ajax/wms-location-save"),
        new("wms_location_delete", "dedicated", "/erp/ajax/wms-location-delete"),
        new("wms_receive", "dedicated", "/erp/ajax/wms-receive"),
        new("wms_wave_create", "dedicated", "/erp/ajax/wms-wave-create"),
        new("wms_wave_release", "dedicated", "/erp/ajax/wms-wave-release"),
        new("wms_work_complete", "dedicated", "/erp/ajax/wms-work-complete"),
        new("mfgr_wc_save", "dedicated", "/erp/ajax/mfgr-wc-save"),
        new("mfgr_route_save", "dedicated", "/erp/ajax/mfgr-route-save"),
        new("mfgr_mrp_run", "dedicated", "/erp/ajax/mfgr-mrp-run"),
        new("mfgr_planned_firm", "dedicated", "/erp/ajax/mfgr-planned-firm"),
        new("fin_periods_generate", "registry", "/erp/ajax-writes/dry-run/fin_periods_generate"),
        new("fin_period_status", "dedicated", "/erp/ajax/fin-period-status"),
        new("fin_fx_revalue", "registry", "/erp/ajax-writes/dry-run/fin_fx_revalue"),
        new("fin_alloc_save", "registry", "/erp/ajax-writes/dry-run/fin_alloc_save"),
        new("fin_alloc_run", "registry", "/erp/ajax-writes/dry-run/fin_alloc_run"),
        new("fin_accrual_save", "registry", "/erp/ajax-writes/dry-run/fin_accrual_save"),
        new("coll_case_save", "dedicated", "/erp/ajax/coll-case-save"),
        new("coll_case_status", "dedicated", "/erp/ajax/coll-case-status"),
        new("coll_case_promise", "dedicated", "/erp/ajax/coll-case-promise"),
        new("coll_activity_log", "dedicated", "/erp/ajax/coll-activity-log"),
        new("coll_dunning_run", "dedicated", "/erp/ajax/coll-dunning-run"),
        new("coll_hold_set", "registry", "/erp/ajax-writes/dry-run/coll_hold_set"),
        new("proc_category_save", "dedicated", "/erp/ajax/proc-category-save"),
        new("proc_policy_save", "dedicated", "/erp/ajax/proc-policy-save"),
        new("proc_req_save", "dedicated", "/erp/ajax/proc-req-save"),
        new("proc_req_add_line", "dedicated", "/erp/ajax/proc-req-add-line"),
        new("proc_req_submit", "dedicated", "/erp/ajax/proc-req-submit"),
        new("proc_req_decision", "dedicated", "/erp/ajax/proc-req-decision"),
        new("proc_req_convert", "dedicated", "/erp/ajax/proc-req-convert"),
        new("bplan_save", "dedicated", "/erp/ajax/bplan-save"),
        new("bplan_line_add", "registry", "/erp/ajax-writes/dry-run/bplan_line_add"),
        new("bplan_position_add", "registry", "/erp/ajax-writes/dry-run/bplan_position_add"),
        new("bplan_advance", "dedicated", "/erp/ajax/bplan-advance"),
        new("hrt_job_save", "registry", "/erp/ajax-writes/dry-run/hrt_job_save"),
        new("hrt_applicant_add", "registry", "/erp/ajax-writes/dry-run/hrt_applicant_add"),
        new("hrt_applicant_stage", "registry", "/erp/ajax-writes/dry-run/hrt_applicant_stage"),
        new("hrt_review_save", "registry", "/erp/ajax-writes/dry-run/hrt_review_save"),
        new("hrt_goal_add", "registry", "/erp/ajax-writes/dry-run/hrt_goal_add"),
        new("hrt_review_finalize", "registry", "/erp/ajax-writes/dry-run/hrt_review_finalize"),
        new("cft_forecast_save", "registry", "/erp/ajax-writes/dry-run/cft_forecast_save"),
        new("cft_line_add", "registry", "/erp/ajax-writes/dry-run/cft_line_add"),
        new("cft_instrument_save", "registry", "/erp/ajax-writes/dry-run/cft_instrument_save"),
        new("cft_instrument_status", "registry", "/erp/ajax-writes/dry-run/cft_instrument_status"),
        new("wht_code_save", "registry", "/erp/ajax-writes/dry-run/wht_code_save"),
        new("wht_record", "registry", "/erp/ajax-writes/dry-run/wht_record"),
        new("wht_certificate", "registry", "/erp/ajax-writes/dry-run/wht_certificate"),
        new("wht_settle", "registry", "/erp/ajax-writes/dry-run/wht_settle"),
        new("er_format_save", "registry", "/erp/ajax-writes/dry-run/er_format_save"),
        new("er_field_add", "registry", "/erp/ajax-writes/dry-run/er_field_add"),
        new("customer_master_save", "dedicated", "/erp/ajax/customer-master-save"),
        new("prja_budget_save", "registry", "/erp/ajax-writes/dry-run/prja_budget_save"),
        new("prja_txn_add", "registry", "/erp/ajax-writes/dry-run/prja_txn_add"),
        new("prja_recognize", "registry", "/erp/ajax-writes/dry-run/prja_recognize"),
        new("costm_item_set", "registry", "/erp/ajax-writes/dry-run/costm_item_set"),
        new("costm_txn_add", "registry", "/erp/ajax-writes/dry-run/costm_txn_add"),
        new("costm_close_run", "registry", "/erp/ajax-writes/dry-run/costm_close_run"),
        new("intg_entity_save", "registry", "/erp/ajax-writes/dry-run/intg_entity_save"),
        new("intg_sub_save", "registry", "/erp/ajax-writes/dry-run/intg_sub_save"),
        new("intg_event_raise", "registry", "/erp/ajax-writes/dry-run/intg_event_raise"),
        new("fy_create", "registry", "/erp/ajax-writes/dry-run/fy_create"),
        new("fy_close", "registry", "/erp/ajax-writes/dry-run/fy_close"),
        new("fy_reopen", "registry", "/erp/ajax-writes/dry-run/fy_reopen"),
        new("fy_period_status", "registry", "/erp/ajax-writes/dry-run/fy_period_status"),
        new("plt_job_save", "registry", "/erp/ajax-writes/dry-run/plt_job_save"),
        new("plt_job_run", "registry", "/erp/ajax-writes/dry-run/plt_job_run"),
        new("plt_feature_save", "registry", "/erp/ajax-writes/dry-run/plt_feature_save"),
        new("oa_party_save", "registry", "/erp/ajax-writes/dry-run/oa_party_save"),
        new("oa_address_save", "registry", "/erp/ajax-writes/dry-run/oa_address_save"),
        new("oa_contact_save", "registry", "/erp/ajax-writes/dry-run/oa_contact_save"),
        new("oa_calendar_save", "registry", "/erp/ajax-writes/dry-run/oa_calendar_save"),
        new("oa_holiday_add", "registry", "/erp/ajax-writes/dry-run/oa_holiday_add"),
        new("rbac_priv_save", "dedicated", "/erp/ajax/rbac-priv-save"),
        new("rbac_duty_save", "dedicated", "/erp/ajax/rbac-duty-save"),
        new("rbac_duty_priv", "dedicated", "/erp/ajax/rbac-duty-priv"),
        new("rbac_role_save", "registry", "/erp/ajax-writes/dry-run/rbac_role_save"),
        new("rbac_role_duty", "registry", "/erp/ajax-writes/dry-run/rbac_role_duty"),
        new("rbac_user_role", "registry", "/erp/ajax-writes/dry-run/rbac_user_role"),
        new("rtl_channel_save", "registry", "/erp/ajax-writes/dry-run/rtl_channel_save"),
        new("rtl_assortment_set", "registry", "/erp/ajax-writes/dry-run/rtl_assortment_set"),
        new("rtl_discount_save", "registry", "/erp/ajax-writes/dry-run/rtl_discount_save"),
        new("rtl_pos_sale", "registry", "/erp/ajax-writes/dry-run/rtl_pos_sale"),
        new("qm_plan_save", "dedicated", "/erp/ajax/qm-plan-save"),
        new("qm_test_add", "dedicated", "/erp/ajax/qm-test-add"),
        new("qm_order_create", "dedicated", "/erp/ajax/qm-order-create"),
        new("qm_order_record", "dedicated", "/erp/ajax/qm-order-record"),
        new("qm_ncr_create", "dedicated", "/erp/ajax/qm-ncr-create"),
        new("qm_ncr_update", "dedicated", "/erp/ajax/qm-ncr-update"),
        new("ins_claim_status", "registry", "/erp/ajax-writes/dry-run/ins_claim_status"),
        new("hr_emp_save", "dedicated", "/erp/ajax/hr-emp-save"),
        new("hr_attendance", "dedicated", "/erp/ajax/hr-attendance"),
        new("hr_leave_request", "dedicated", "/erp/ajax/hr-leave-request"),
        new("hr_leave_status", "dedicated", "/erp/ajax/hr-leave-status"),
        new("hr_expense_save", "dedicated", "/erp/ajax/hr-expense-save"),
        new("hr_expense_status", "dedicated", "/erp/ajax/hr-expense-status"),
        new("prj_save", "registry", "/erp/ajax-writes/dry-run/prj_save"),
        new("prj_task_save", "registry", "/erp/ajax-writes/dry-run/prj_task_save"),
        new("prj_log_time", "registry", "/erp/ajax-writes/dry-run/prj_log_time"),
        new("cons_entity_save", "registry", "/erp/ajax-writes/dry-run/cons_entity_save"),
        new("cons_entity_delete", "registry", "/erp/ajax-writes/dry-run/cons_entity_delete"),
        new("cons_figures_save", "registry", "/erp/ajax-writes/dry-run/cons_figures_save"),
        new("cons_ic_save", "registry", "/erp/ajax-writes/dry-run/cons_ic_save"),
        new("cons_ic_delete", "registry", "/erp/ajax-writes/dry-run/cons_ic_delete"),
        new("mfg_bom_save", "registry", "/erp/ajax-writes/dry-run/mfg_bom_save"),
        new("mfg_wo_create", "registry", "/erp/ajax-writes/dry-run/mfg_wo_create"),
        new("mfg_wo_issue", "registry", "/erp/ajax-writes/dry-run/mfg_wo_issue"),
        new("mfg_wo_complete", "registry", "/erp/ajax-writes/dry-run/mfg_wo_complete"),
        new("payroll_generate", "registry", "/erp/ajax-writes/dry-run/payroll_generate"),
        new("payroll_approve", "registry", "/erp/ajax-writes/dry-run/payroll_approve"),
        new("payroll_pay", "registry", "/erp/ajax-writes/dry-run/payroll_pay"),
        new("payroll_update_days", "registry", "/erp/ajax-writes/dry-run/payroll_update_days"),
        new("hr_update_days", "dedicated", "/erp/ajax/hr-update-days"),
        new("uae_tax_fta_fetch", "registry", "/erp/ajax-writes/dry-run/uae_tax_fta_fetch"),
        new("aml_check", "registry", "/erp/ajax-writes/dry-run/aml_check"),
        new("aml_kyc_save", "dedicated", "/erp/ajax/aml-kyc-save"),
        new("aml_alert_status", "dedicated", "/erp/ajax/aml-alert-status"),
        new("aml_report_generate", "registry", "/erp/ajax-writes/dry-run/aml_report_generate"),
        new("aml_settings_save", "dedicated", "/erp/ajax/aml-settings-save"),
        new("aml_seed_rules", "registry", "/erp/ajax-writes/dry-run/aml_seed_rules"),
        new("uae_tax_legislation_regen_summaries", "registry", "/erp/ajax-writes/dry-run/uae_tax_legislation_regen_summaries"),
        new("uae_tax_legislation_ask", "registry", "/erp/ajax-writes/dry-run/uae_tax_legislation_ask"),
        new("uae_tax_save_ct_adjustments", "registry", "/erp/ajax-writes/dry-run/uae_tax_save_ct_adjustments"),
        new("uae_tax_legislation_checklist_set", "registry", "/erp/ajax-writes/dry-run/uae_tax_legislation_checklist_set"),
        new("einvoice_create", "dedicated", "/erp/ajax/einvoice-create"),
        new("einvoice_save_seller", "dedicated", "/erp/ajax/einvoice-save-seller"),
        new("einvoice_save_buyer", "dedicated", "/erp/ajax/einvoice-save-buyer"),
        new("einvoice_save_asp", "dedicated", "/erp/ajax/einvoice-save-asp"),
        new("einvoice_submit", "dedicated", "/erp/ajax/einvoice-submit"),
        new("einvoice_credit_note", "dedicated", "/erp/ajax/einvoice-credit-note"),
        new("einvoice_poll_asp", "dedicated", "/erp/ajax/einvoice-poll-asp"),
        new("invoice_save", "registry", "/erp/ajax-writes/dry-run/invoice_save"),
        new("invoice_list", "registry", "/erp/ajax-writes/dry-run/invoice_list"),
        new("invoice_from_order", "registry", "/erp/ajax-writes/dry-run/invoice_from_order"),
        new("inv_sync_warehouses", "dedicated", "/erp/ajax/inv-sync-warehouses"),
        new("inv_create_warehouse", "dedicated", "/erp/ajax/inv-create-warehouse"),
        new("inv_create_item", "dedicated", "/erp/ajax/inv-create-item"),
        new("inv_set_reorder_level", "dedicated", "/erp/ajax/inv-set-reorder-level"),
        new("inv_record_movement", "dedicated", "/erp/ajax/inv-record-movement"),
        new("ai_query", "registry", "/erp/ajax-writes/dry-run/ai_query"),
        new("integrity_scan", "registry", "/erp/ajax-writes/dry-run/integrity_scan"),
        new("integrity_apply_fks", "registry", "/erp/ajax-writes/dry-run/integrity_apply_fks"),
        new("inv_scan_lookup", "dedicated", "/erp/ajax/inv-scan-lookup"),
        new("inv_transfer", "dedicated", "/erp/ajax/inv-transfer"),
        new("inv_import_csv", "dedicated", "/erp/ajax/inv-import-csv"),
        new("inv_run_closing", "dedicated", "/erp/ajax/inv-run-closing"),
        new("fa_create_asset", "registry", "/erp/ajax-writes/dry-run/fa_create_asset"),
        new("fa_run_depreciation", "registry", "/erp/ajax-writes/dry-run/fa_run_depreciation"),
        new("opening_create_batch", "registry", "/erp/ajax-writes/dry-run/opening_create_batch"),
        new("opening_add_coa_line", "registry", "/erp/ajax-writes/dry-run/opening_add_coa_line"),
        new("opening_add_inv_line", "registry", "/erp/ajax-writes/dry-run/opening_add_inv_line"),
        new("opening_post_batch", "registry", "/erp/ajax-writes/dry-run/opening_post_batch"),
        new("save_rfq", "registry", "/erp/ajax-writes/dry-run/save_rfq"),
        new("delivery_note_create", "registry", "/erp/ajax-writes/dry-run/delivery_note_create"),
        new("bank_import", "dedicated", "/erp/ajax/bank-import"),
        new("bank_reconcile", "dedicated", "/erp/ajax/bank-reconcile"),
        new("save_contact", "registry", "/erp/ajax-writes/dry-run/save_contact"),
        new("sync_contacts", "registry", "/erp/ajax-writes/dry-run/sync_contacts"),
        new("document_upload", "registry", "/erp/ajax-writes/dry-run/document_upload"),
        new("document_delete", "registry", "/erp/ajax-writes/dry-run/document_delete"),
        new("save_company", "registry", "/erp/ajax-writes/dry-run/save_company"),
        new("save_template", "registry", "/erp/ajax-writes/dry-run/save_template"),
        new("upload_logo", "registry", "/erp/ajax-writes/dry-run/upload_logo"),
        new("upload_attachment", "registry", "/erp/ajax-writes/dry-run/upload_attachment"),
        new("delete_attachment", "registry", "/erp/ajax-writes/dry-run/delete_attachment"),
        new("sync_einvoice_seller", "registry", "/erp/ajax-writes/dry-run/sync_einvoice_seller"),
        new("expense_report_save", "registry", "/erp/ajax-writes/dry-run/expense_report_save"),
        new("po_save", "registry", "/erp/ajax-writes/dry-run/po_save"),
        new("po_status", "registry", "/erp/ajax-writes/dry-run/po_status"),
        new("po_receive_lines", "registry", "/erp/ajax-writes/dry-run/po_receive_lines"),
        new("po_to_invoice", "registry", "/erp/ajax-writes/dry-run/po_to_invoice"),
        new("customer_create", "registry", "/erp/ajax-writes/dry-run/customer_create"),
        new("so_save", "registry", "/erp/ajax-writes/dry-run/so_save"),
        new("so_status", "registry", "/erp/ajax-writes/dry-run/so_status"),
        new("so_to_invoice", "registry", "/erp/ajax-writes/dry-run/so_to_invoice"),
        new("so_delete", "dedicated", "/erp/ajax/so-delete"),
        new("so_cancel", "dedicated", "/erp/ajax/so-cancel"),
        new("po_delete", "dedicated", "/erp/ajax/po-delete"),
        new("cash_voucher_void", "dedicated", "/erp/ajax/cash-voucher-void"),
        new("cash_voucher_amend", "dedicated", "/erp/ajax/cash-voucher-amend"),
        new("purchase_void", "dedicated", "/erp/ajax/purchase-void"),
        new("purchase_delete", "dedicated", "/erp/ajax/purchase-delete"),
        new("purchase_amend", "dedicated", "/erp/ajax/purchase-amend"),
        new("invoice_delete", "dedicated", "/erp/ajax/invoice-delete"),
        new("invoice_cancel", "dedicated", "/erp/ajax/invoice-cancel"),
        new("receipt_voucher", "dedicated", "/erp/ajax/receipt-voucher"),
        new("transfer_voucher", "registry", "/erp/ajax-writes/dry-run/transfer_voucher"),
        new("payment_batch_save", "registry", "/erp/ajax-writes/dry-run/payment_batch_save"),
        new("petty_cash_save", "registry", "/erp/ajax-writes/dry-run/petty_cash_save"),
        new("agenda_save", "registry", "/erp/ajax-writes/dry-run/agenda_save"),
        new("kb_save", "registry", "/erp/ajax-writes/dry-run/kb_save"),
        new("multi_entity_save", "registry", "/erp/ajax-writes/dry-run/multi_entity_save"),
        new("cs_save_declaration", "registry", "/erp/ajax-writes/dry-run/cs_save_declaration"),
        new("cs_submit_declaration", "registry", "/erp/ajax-writes/dry-run/cs_submit_declaration"),
        new("cs_delete_declaration", "registry", "/erp/ajax-writes/dry-run/cs_delete_declaration"),
        new("cs_list_declarations", "registry", "/erp/ajax-writes/dry-run/cs_list_declarations"),
        new("order_fulfillment_bootstrap", "dedicated", "/erp/ajax/order-fulfillment-bootstrap"),
        new("order_fulfillment_status", "dedicated", "/erp/ajax/order-fulfillment-status"),
        new("order_fulfillment_sync", "dedicated", "/erp/ajax/order-fulfillment-sync"),
        new("order_fulfillment_post_po", "dedicated", "/erp/ajax/order-fulfillment-post-po"),
        new("order_fulfillment_post_sales", "dedicated", "/erp/ajax/order-fulfillment-post-sales"),
        new("order_fulfillment_auto_post", "dedicated", "/erp/ajax/order-fulfillment-auto-post"),
        new("order_fulfillment_swap_supplier", "dedicated", "/erp/ajax/order-fulfillment-swap-supplier"),
        new("cs_import_declaration_pdf", "registry", "/erp/ajax-writes/dry-run/cs_import_declaration_pdf"),
        new("pm_save", "dedicated", "/erp/ajax/pm-save"),
        new("pm_toggle", "dedicated", "/erp/ajax/pm-toggle"),
        new("pm_budget_save", "dedicated", "/erp/ajax/pm-budget-save"),
        new("pm_budget_line_save", "dedicated", "/erp/ajax/pm-budget-line-save"),
        new("pm_listing_save", "dedicated", "/erp/ajax/pm-listing-save"),
        new("pm_listing_attach", "dedicated", "/erp/ajax/pm-listing-attach"),
        new("pm_cheque_save", "dedicated", "/erp/ajax/pm-cheque-save"),
        new("shortcut_list", "registry", "/erp/ajax-writes/dry-run/shortcut_list"),
        new("shortcut_add", "registry", "/erp/ajax-writes/dry-run/shortcut_add"),
        new("shortcut_delete", "registry", "/erp/ajax-writes/dry-run/shortcut_delete"),
        new("shortcut_delete_key", "registry", "/erp/ajax-writes/dry-run/shortcut_delete_key"),
        new("shortcut_reset", "registry", "/erp/ajax-writes/dry-run/shortcut_reset"),
        new("shortcut_reorder", "registry", "/erp/ajax-writes/dry-run/shortcut_reorder"),
        new("erp_fav_add", "registry", "/erp/ajax-writes/dry-run/erp_fav_add"),
        new("erp_fav_remove", "registry", "/erp/ajax-writes/dry-run/erp_fav_remove"),
        new("erp_global_search", "registry", "/erp/ajax-writes/dry-run/erp_global_search"),
        new("jw_repair_create", "registry", "/erp/ajax-writes/dry-run/jw_repair_create"),
        new("jw_repair_update_status", "registry", "/erp/ajax-writes/dry-run/jw_repair_update_status"),
        new("jw_seed_sample_data", "registry", "/erp/ajax-writes/dry-run/jw_seed_sample_data"),
        new("ai_assistant_query", "registry", "/erp/ajax-writes/dry-run/ai_assistant_query"),
        new("print_designer_save", "registry", "/erp/ajax-writes/dry-run/print_designer_save"),
        new("workflow_save", "registry", "/erp/ajax-writes/dry-run/workflow_save"),
        new("workflow_run", "registry", "/erp/ajax-writes/dry-run/workflow_run"),
        new("automation_activate", "registry", "/erp/ajax-writes/dry-run/automation_activate"),
        new("automation_deactivate", "registry", "/erp/ajax-writes/dry-run/automation_deactivate"),
        new("automation_install_template", "registry", "/erp/ajax-writes/dry-run/automation_install_template"),
        new("automation_enable_category", "registry", "/erp/ajax-writes/dry-run/automation_enable_category"),
        new("automation_tick", "registry", "/erp/ajax-writes/dry-run/automation_tick"),
        new("tenant_config_save", "registry", "/erp/ajax-writes/dry-run/tenant_config_save"),
    ];

    private static readonly Dictionary<string, ErpAjaxWriteCatalogEntry> ByAction =
        Entries.ToDictionary(e => e.Action, StringComparer.OrdinalIgnoreCase);

    public IReadOnlyList<ErpAjaxWriteCatalogEntry> All => Entries;

    public bool TryGet(string action, out ErpAjaxWriteCatalogEntry entry) =>
        ByAction.TryGetValue(action ?? "", out entry!);

    public ErpAjaxWriteCatalogReport BuildReport()
    {
        var dedicated = Entries.Count(e => e.Coverage == "dedicated");
        var registry = Entries.Count(e => e.Coverage == "registry");
        return new(
            Role: "erp-ajax-write-catalog",
            Status: "building-toward-zero-php",
            CutoverAllowed: false,
            ReadyForPhpRemoval: false,
            PhpAuthoritative: true,
            PhpAjax: "/CP/content/shop/finance/erp/ajax_erp.php",
            TotalActions: Entries.Length,
            DedicatedDryRuns: dedicated,
            RegistryDryRuns: registry,
            CoveragePct: Entries.Length == 0 ? 0 : (int)Math.Round(100.0 * (dedicated + registry) / Entries.Length),
            Actions: Entries,
            Notes:
            [
                "Coverage means ASP.NET dry-run gate exists (writes=0); live writes remain PHP.",
                "Dedicated routes keep richer validation; registry covers the long tail via POST /erp/ajax-writes/dry-run/{action}.",
                "cutoverAllowed stays false until dual-sample + human RELEASE_OWNER_APPROVAL.md.",
            ]);
    }
}

public sealed record ErpAjaxWriteCatalogEntry(string Action, string Coverage, string AspNetRouteHint);

public sealed record ErpAjaxWriteCatalogReport(
    string Role,
    string Status,
    bool CutoverAllowed,
    bool ReadyForPhpRemoval,
    bool PhpAuthoritative,
    string PhpAjax,
    int TotalActions,
    int DedicatedDryRuns,
    int RegistryDryRuns,
    int CoveragePct,
    IReadOnlyList<ErpAjaxWriteCatalogEntry> Actions,
    IReadOnlyList<string> Notes);
