namespace EcomAE.Platform.Migration;

/// <summary>
/// Operator-facing catalog of live Super CP / tenant / ERP / storefront URLs.
/// StackToday reflects production cutover reality: operator chrome remains PHP until exact-route shadows + approval.
/// </summary>
public sealed class LiveSurfaceLinkReporter : ILiveSurfaceLinkReporter
{
    public LiveSurfaceLinkReport BuildReport()
    {
        LiveSurfaceLink[] links =
        [
            // Super CP / platform operator
            Link("super-cp", "Frontend / marketing", "https://www.ecomae.com/", "php", "/", "Platform marketing home remains PHP."),
            Link("super-cp", "Control Panel", "https://www.ecomae.com/CP/", "php", "/cp", "PHP chrome authoritative; ASP.NET shell available on loopback when AdminAspNetEnabled."),
            Link("super-cp", "Control Panel (alias)", "https://www.ecomae.com/cp/", "php", "/cp", "Case-insensitive alias of Super CP."),
            Link("super-cp", "ERP", "https://www.ecomae.com/ERP/", "php", "/erp", "Platform ERP desktop remains PHP."),
            Link("super-cp", "ERP (alias)", "https://www.ecomae.com/erp/", "php", "/erp", "Case-insensitive alias of Platform ERP."),
            Link("super-cp", "BOS", "https://www.ecomae.com/BOS/", "php", "/bos", "Super BOS command center remains PHP."),
            Link("super-cp", "BOS (alias)", "https://www.ecomae.com/bos/", "php", "/bos", "Case-insensitive alias of Super BOS."),
            Link("super-cp", "Dedicated Super CP host", "https://cp.ecomae.com/CP/", "php", "/cp", "cp.ecomae.com is the dedicated Super CP hostname."),
            Link("super-cp", "Dedicated Super CP BOS", "https://cp.ecomae.com/BOS/", "php", "/bos", "BOS on dedicated Super CP host."),
            Link("super-cp", "Dedicated Super CP ERP", "https://cp.ecomae.com/ERP/", "php", "/erp", "ERP on dedicated Super CP host."),

            // ASP.NET diagnostics already live publicly
            Link("aspnet-diagnostics", "Health", "https://www.ecomae.com/health", "aspnet", "/health", "ASP.NET health check."),
            Link("aspnet-diagnostics", "Zero-PHP completion", "https://www.ecomae.com/migration/zero-php-completion", "aspnet", "/migration/zero-php-completion", "Weighted completion (95%/5%)."),
            Link("aspnet-diagnostics", "PHP decommission readiness", "https://www.ecomae.com/migration/php-decommission-readiness", "aspnet", "/migration/php-decommission-readiness", "Final-gate checklist; ReadyToRemovePhp=false."),
            Link("aspnet-diagnostics", "Zero-PHP Blazor console", "https://www.ecomae.com/migration/console", "aspnet", "/migration/console", "Blazor SSR operator console (interim improvement UI). Not product chrome cutover."),
            Link("aspnet-presentation-preview", "CP Command Centre (Blazor preview)", "https://www.ecomae.com/cp/app", "aspnet", "/cp/app", "Hybrid chrome preview (PHP CSS + PHP-linked nav). Live UI remains https://www.ecomae.com/CP/ (PHP)."),
            Link("aspnet-presentation-preview", "ERP Ecom BOS (Blazor preview)", "https://www.ecomae.com/erp/app", "aspnet", "/erp/app", "Hybrid chrome preview (PHP CSS + PHP ERP areas). Live UI remains https://www.ecomae.com/ERP/ (PHP)."),
            Link("aspnet-presentation-preview", "BOS fleet (Blazor preview)", "https://www.ecomae.com/bos/app", "aspnet", "/bos/app", "Hybrid chrome preview. Live UI remains https://www.ecomae.com/BOS/ (PHP)."),
            Link("aspnet-presentation-preview", "Storefront (Blazor preview)", "https://www.ecomae.com/storefront/app", "aspnet", "/storefront/app", "Hybrid chrome preview. Live storefront remains https://epartscart.com/ (PHP)."),
            Link("aspnet-presentation-preview", "CP Orders/OMS read UI", "https://www.ecomae.com/cp/orders", "aspnet", "/cp/orders", "Batch 4 read-only shop_orders list under PhpCpDesktopChrome. Writes/full console remain PHP /CP/shop/orders/orders."),
            Link("aspnet-presentation-preview", "CP Orders digest", "https://www.ecomae.com/cp/orders-digest", "aspnet", "/cp/orders-digest", "Batch 4 read-only KPI+list digest (admin CP). Not counted in surface digests 30/30 inventory."),
            Link("aspnet-presentation-preview", "CP Users read UI", "https://www.ecomae.com/cp/users-app", "aspnet", "/cp/users-app", "Batch 4 Blazor list over /cp/users digest. JSON digest stays at /cp/users. Writes remain PHP /CP/control/users."),
            Link("aspnet-presentation-preview", "CP Groups read UI", "https://www.ecomae.com/cp/groups-app", "aspnet", "/cp/groups-app", "Batch 4 Blazor list over /cp/groups digest. JSON digest stays at /cp/groups. Writes remain PHP /CP/users/usergroups."),
            Link("aspnet-presentation-preview", "CP Modules read UI", "https://www.ecomae.com/cp/modules-app", "aspnet", "/cp/modules-app", "Blazor list over /cp/modules digest under PhpCpDesktopChrome. Writes remain PHP /CP/modules/modules_manager. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "CP Pages read UI", "https://www.ecomae.com/cp/pages-app", "aspnet", "/cp/pages-app", "Blazor list over /cp/pages digest under PhpCpDesktopChrome. Writes remain PHP /CP/content/content_manager. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "CP Menus read UI", "https://www.ecomae.com/cp/menus-app", "aspnet", "/cp/menus-app", "Blazor list over /cp/menus digest under PhpCpDesktopChrome. Writes remain PHP /CP/menu/menu_manager. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "ERP Sales Orders read UI", "https://www.ecomae.com/erp/sales-orders-app", "aspnet", "/erp/sales-orders-app", "Batch 4 Blazor list over /erp/sales-orders digest. JSON digest stays at /erp/sales-orders. Writes remain PHP erp_tabs_sales_orders."),
            Link("aspnet-presentation-preview", "ERP Purchase Orders read UI", "https://www.ecomae.com/erp/purchase-orders-app", "aspnet", "/erp/purchase-orders-app", "Blazor list over /erp/purchase-orders digest under PhpErpDesktopChrome. Writes remain PHP erp_tabs_purchase_orders. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "ERP Invoices read UI", "https://www.ecomae.com/erp/invoices-app", "aspnet", "/erp/invoices-app", "Blazor list over /erp/invoices digest under PhpErpDesktopChrome. Writes remain PHP erp_tabs_invoices. Tenant chrome stays PHP (same-to-same). ASP.NET Core owns hybrid read surface toward Enterprise BOS."),
            Link("aspnet-presentation-preview", "ERP Cash & Bank read UI", "https://www.ecomae.com/erp/cash-accounts-app", "aspnet", "/erp/cash-accounts-app", "Blazor accounts+entries over /erp/cash-accounts|/erp/cash-entries digests under PhpErpDesktopChrome. Writes remain PHP erp_tabs_cash_bank. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "ERP Chart of Accounts read UI", "https://www.ecomae.com/erp/coa-accounts-app", "aspnet", "/erp/coa-accounts-app", "Blazor list over /erp/coa-accounts digest under PhpErpDesktopChrome. Writes remain PHP erp_tabs_accounting (tab=coa). Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "ERP GL Journals read UI", "https://www.ecomae.com/erp/gl-journals-app", "aspnet", "/erp/gl-journals-app", "Blazor list over /erp/gl-journals digest under PhpErpDesktopChrome. Writes remain PHP erp_tabs_accounting (tab=gl). Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "ERP Warehouses read UI", "https://www.ecomae.com/erp/warehouses-app", "aspnet", "/erp/warehouses-app", "Blazor list over /erp/warehouses digest under PhpErpDesktopChrome. Writes remain PHP erp_tabs_inventory. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "ERP Suppliers read UI", "https://www.ecomae.com/erp/suppliers-app", "aspnet", "/erp/suppliers-app", "Blazor list over /erp/suppliers digest under PhpErpDesktopChrome. Writes remain PHP AP payables / epc_erp_list_suppliers. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "ERP Purchases read UI", "https://www.ecomae.com/erp/purchases-app", "aspnet", "/erp/purchases-app", "Blazor list over /erp/purchases digest under PhpErpDesktopChrome. Writes remain PHP purchasing/purchases / epc_erp_list_purchases. Tenant chrome stays PHP (same-to-same)."),
            Link("aspnet-presentation-preview", "Storefront part search read UI", "https://www.ecomae.com/storefront/search-app", "aspnet", "/storefront/search-app", "Batch 4 Blazor warehouse offers under PhpStorefrontDesktopChrome. Full PHP part_search/cart remain authoritative on epartscart.com."),
            Link("aspnet-presentation-preview", "Storefront cart read UI", "https://www.ecomae.com/storefront/cart-app", "aspnet", "/storefront/cart-app", "Batch 4 authenticated cart summary under PhpStorefrontDesktopChrome. Qty/guest cart/checkout remain PHP on epartscart.com."),
            Link("aspnet-login-bridge", "CP login bridge", "https://www.ecomae.com/cp/login", "aspnet", "/cp/login", "Opt-in PHP-compatible admin session mint when EcomAE__SecretSuccession set. PHP /CP/ login remains authoritative."),
            Link("aspnet-login-bridge", "ERP login bridge", "https://www.ecomae.com/erp/login", "aspnet", "/erp/login", "Opt-in admin session mint for ERP digests/shell. PHP ERP routers remain authoritative."),
            Link("aspnet-login-bridge", "BOS login bridge", "https://www.ecomae.com/bos/login", "aspnet", "/bos/login", "Batch 3 decision: admin-cookie bridge for digests//bos/app only. Native BOS $_SESSION remains PHP-authoritative on /BOS/."),
            Link("aspnet-login-bridge", "Storefront login bridge", "https://www.ecomae.com/storefront/login", "aspnet", "/storefront/login", "Batch 3: customer session/u_id mint (md5 contact+userId+time+secret). Cart/checkout remain PHP."),
            Link("aspnet-diagnostics", "Presentation parity", "https://www.ecomae.com/migration/presentation-parity", "aspnet", "/migration/presentation-parity", "PHP chrome asset contract for ASP.NET shells."),
            Link("aspnet-diagnostics", "PHP module catalog", "https://www.ecomae.com/migration/php-module-catalog", "aspnet", "/migration/php-module-catalog", "Full CP/ERP/BOS/storefront module directory counts (hybrid deeplink inventory)."),
            Link("aspnet-diagnostics", "Live surface links", "https://www.ecomae.com/migration/live-surface-links", "aspnet", "/migration/live-surface-links", "This catalog."),
            Link("aspnet-diagnostics", "Surface parity", "https://www.ecomae.com/migration/surface-parity", "aspnet", "/migration/surface-parity", "Surface-by-surface parity statuses."),
            Link("aspnet-diagnostics", "Surface field parity", "https://www.ecomae.com/migration/surface-field-parity", "aspnet", "/migration/surface-field-parity", "Field/function contracts for all wired digests + catalog routes."),
            Link("aspnet-diagnostics", "CP parity board", "https://www.ecomae.com/cp/parity", "aspnet", "/cp/parity", "Control Panel RemainingGaps / verified capabilities (loopback 127.0.0.1:5100 or allowlisted)."),
            Link("aspnet-diagnostics", "ERP parity board", "https://www.ecomae.com/erp/parity", "aspnet", "/erp/parity", "ERP RemainingGaps / verified capabilities (loopback or allowlisted)."),
            Link("aspnet-diagnostics", "BOS parity board", "https://www.ecomae.com/bos/parity", "aspnet", "/bos/parity", "BOS RemainingGaps / verified capabilities (loopback or allowlisted)."),
            Link("aspnet-diagnostics", "Storefront parity board", "https://www.ecomae.com/storefront/parity", "aspnet", "/storefront/parity", "Storefront RemainingGaps (loopback or allowlisted)."),
            Link("aspnet-diagnostics", "Data parity board", "https://www.ecomae.com/migration/data-parity", "aspnet", "/migration/data-parity", "Production data source contracts; cutover blocked."),
            Link("aspnet-diagnostics", "Session parity board", "https://www.ecomae.com/auth/session/parity", "aspnet", "/auth/session/parity", "Legacy session RemainingGaps (loopback; use /auth/session/probe with cookie)."),
            Link("aspnet-diagnostics", "API client parity board", "https://www.ecomae.com/auth/api-client/parity", "aspnet", "/auth/api-client/parity", "epc_api_clients auth RemainingGaps (loopback)."),
            Link("aspnet-diagnostics", "Catalog parity board", "https://www.ecomae.com/api/v1/catalog/parity", "aspnet", "/api/v1/catalog/parity", "Catalog RemainingGaps (loopback or after catalog shadow)."),
            Link("aspnet-diagnostics", "Price parity board", "https://www.ecomae.com/api/v1/price/parity", "aspnet", "/api/v1/price/parity", "Price lookup RemainingGaps (loopback or after price shadow)."),
            Link("aspnet-api", "Price lookup", "https://www.ecomae.com/api/v1/price/lookup", "aspnet", "/api/v1/price/lookup", "Already on ASP.NET; unauthenticated returns JSON missing_api_key."),

            // Industry showcase frontends (*.ecomae.com) — not dedicated client tenants
            Link("industry-frontend", "Healthcare frontend", "https://healthcare.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Healthcare CP", "https://healthcare.ecomae.com/CP/", "php", "/cp", "Industry CP chrome (PHP)."),
            Link("industry-frontend", "Healthcare ERP", "https://healthcare.ecomae.com/ERP/", "php", "/erp", "Industry ERP chrome (PHP)."),
            Link("industry-frontend", "Home & living frontend", "https://homeliving.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Retail frontend", "https://retail.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Fashion frontend", "https://fashion.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Jewellery frontend", "https://jewellery.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Food frontend", "https://food.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Beauty frontend", "https://beauty.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Sports frontend", "https://sports.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),
            Link("industry-frontend", "Pet frontend", "https://pet.ecomae.com/", "php", "/", "Industry subdomain showcase storefront."),

            // Known dedicated tenant / brand hosts
            Link("tenant", "Electronicae frontend", "https://www.electronicae.com/", "php", "/", "Dedicated tenant storefront."),
            Link("tenant", "Electronicae CP", "https://www.electronicae.com/CP/", "php", "/cp", "Tenant CP."),
            Link("tenant", "Electronicae ERP", "https://www.electronicae.com/ERP/", "php", "/erp", "Tenant ERP."),
            Link("tenant", "Style N Look frontend", "https://www.stylenlook.com/", "php", "/", "Dedicated tenant storefront."),
            Link("tenant", "Style N Look CP", "https://www.stylenlook.com/CP/", "php", "/cp", "Tenant CP."),
            Link("tenant", "Style N Look ERP", "https://www.stylenlook.com/ERP/", "php", "/erp", "Tenant ERP."),
            Link("tenant", "Jewellery Trend frontend", "https://www.thejewellerytrend.com/", "php", "/", "Dedicated tenant storefront."),
            Link("tenant", "Jewellery Trend CP", "https://www.thejewellerytrend.com/CP/", "php", "/cp", "Tenant CP."),
            Link("tenant", "Jewellery Trend ERP", "https://www.thejewellerytrend.com/ERP/", "php", "/erp", "Tenant ERP."),
            Link("tenant", "Taxofin CA frontend", "https://www.taxofinca.com/", "php", "/", "Dedicated tenant storefront."),
            Link("tenant", "Taxofin CA CP", "https://www.taxofinca.com/CP/", "php", "/cp", "Tenant CP."),
            Link("tenant", "Taxofin CA ERP", "https://www.taxofinca.com/ERP/", "php", "/erp", "Tenant ERP."),
            Link("tenant", "ePartsCart frontend", "https://epartscart.com/", "php", "/", "Live auto-parts tenant/storefront host."),
            Link("tenant", "ePartsCart CP", "https://epartscart.com/CP/", "php", "/cp", "Tenant CP."),
            Link("tenant", "ePartsCart ERP", "https://epartscart.com/ERP/", "php", "/erp", "Tenant ERP."),
            Link("tenant", "ePartsCart www frontend", "https://www.epartscart.com/", "php", "/", "www alias for ePartsCart."),

            // Exact-route ASP.NET digests (batch via cloudpanel_install_surface_digest_shadows.sh; Cookie proxy; never broad /cp|/erp|/bos)
            Link("aspnet-exact-route-shadow-live", "CP dashboard digest", "https://www.ecomae.com/cp/dashboard-summary", "aspnet", "/cp/dashboard-summary", "Live exact-route nginx shadow on www (unauth 401 unauthorized; admin cookie for 200)."),
            Link("aspnet-exact-route-shadow-live", "CP tenants digest", "https://www.ecomae.com/cp/tenants", "aspnet", "/cp/tenants", "Live exact-route nginx shadow on www (unauth 401 unauthorized)."),
            Link("aspnet-exact-route-shadow-live", "CP users digest", "https://www.ecomae.com/cp/users", "aspnet", "/cp/users", "Live exact-route nginx shadow on www (unauth 401 unauthorized). CDN may briefly cache prior PHP HTML."),
            Link("aspnet-exact-route-shadow-live", "CP groups digest", "https://www.ecomae.com/cp/groups", "aspnet", "/cp/groups", "Live exact-route nginx shadow on www (unauth 401 unauthorized)."),
            Link("aspnet-exact-route-shadow-live", "CP modules digest", "https://www.ecomae.com/cp/modules", "aspnet", "/cp/modules", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "CP menus digest", "https://www.ecomae.com/cp/menus", "aspnet", "/cp/menus", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "CP pages digest", "https://www.ecomae.com/cp/pages", "aspnet", "/cp/pages", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "CP currencies digest", "https://www.ecomae.com/cp/currencies", "aspnet", "/cp/currencies", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "CP api-clients digest", "https://www.ecomae.com/cp/api-clients", "aspnet", "/cp/api-clients", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "CP config-items digest", "https://www.ecomae.com/cp/config-items", "aspnet", "/cp/config-items", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "CP admin-sessions digest", "https://www.ecomae.com/cp/admin-sessions", "aspnet", "/cp/admin-sessions", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "CP storages digest", "https://www.ecomae.com/cp/storages", "aspnet", "/cp/storages", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP dashboard digest", "https://www.ecomae.com/erp/dashboard-summary", "aspnet", "/erp/dashboard-summary", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP accounts-summary digest", "https://www.ecomae.com/erp/accounts-summary", "aspnet", "/erp/accounts-summary", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP suppliers digest", "https://www.ecomae.com/erp/suppliers", "aspnet", "/erp/suppliers", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP purchases digest", "https://www.ecomae.com/erp/purchases", "aspnet", "/erp/purchases", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP cash-accounts digest", "https://www.ecomae.com/erp/cash-accounts", "aspnet", "/erp/cash-accounts", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP cash-entries digest", "https://www.ecomae.com/erp/cash-entries", "aspnet", "/erp/cash-entries", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP COA accounts digest", "https://www.ecomae.com/erp/coa-accounts", "aspnet", "/erp/coa-accounts", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP warehouses digest", "https://www.ecomae.com/erp/warehouses", "aspnet", "/erp/warehouses", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP sales-orders digest", "https://www.ecomae.com/erp/sales-orders", "aspnet", "/erp/sales-orders", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP purchase-orders digest", "https://www.ecomae.com/erp/purchase-orders", "aspnet", "/erp/purchase-orders", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP inventory-stock digest", "https://www.ecomae.com/erp/inventory-stock", "aspnet", "/erp/inventory-stock", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP invoices digest", "https://www.ecomae.com/erp/invoices", "aspnet", "/erp/invoices", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "ERP GL journals digest", "https://www.ecomae.com/erp/gl-journals", "aspnet", "/erp/gl-journals", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "BOS fleet digest", "https://www.ecomae.com/bos/fleet-summary", "aspnet", "/bos/fleet-summary", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "BOS tenants digest", "https://www.ecomae.com/bos/tenants", "aspnet", "/bos/tenants", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "BOS fleet-health digest", "https://www.ecomae.com/bos/fleet-health", "aspnet", "/bos/fleet-health", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "BOS fleet-readiness digest", "https://www.ecomae.com/bos/fleet-readiness", "aspnet", "/bos/fleet-readiness", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Part of surface digests 30/30 batch."),
            Link("aspnet-exact-route-shadow-live", "BOS audit-log digest", "https://www.ecomae.com/bos/audit-log", "aspnet", "/bos/audit-log", "Live exact-route nginx shadow on www (unauth 401 unauthorized). Completes surface digests 30/30."),
            Link("aspnet-exact-route-shadow-live", "Catalog status", "https://www.ecomae.com/api/v1/catalog/status", "aspnet", "/api/v1/catalog/status", "Live exact-route nginx shadow on www (401/200 ASP.NET JSON). PHP remains for chrome/digests."),
            Link("aspnet-exact-route-shadow-live", "Catalog manufacturers", "https://www.ecomae.com/api/v1/catalog/manufacturers?section=passenger", "aspnet", "/api/v1/catalog/manufacturers", "Live exact-route nginx shadow on www (401/200; section=passenger). Dual-sample compare still recommended before more list routes."),
            Link("aspnet-exact-route-shadow-live", "Catalog models", "https://www.ecomae.com/api/v1/catalog/models?section=passenger&mfa_id=1", "aspnet", "/api/v1/catalog/models", "Live exact-route nginx shadow on www (unauth 401; auth needs section+mfa_id>0 for 200; row keys MFA_ID). Dual-sample compare still recommended."),
            Link("aspnet-exact-route-shadow-live", "Catalog modifications", "https://www.ecomae.com/api/v1/catalog/modifications?section=passenger&ms_id=1", "aspnet", "/api/v1/catalog/modifications", "Live exact-route nginx shadow on www (unauth 401; auth needs section+ms_id>0 for 200; row keys MS_ID). Dual-sample compare still recommended."),
            Link("aspnet-exact-route-shadow-live", "Catalog brands", "https://www.ecomae.com/api/v1/catalog/brands", "aspnet", "/api/v1/catalog/brands", "Live exact-route nginx shadow on www (401/200 ASP.NET JSON; no mfa_id/ms_id required). Dual-sample compare still recommended."),
            Link("aspnet-exact-route-shadow-live", "Catalog suppliers", "https://www.ecomae.com/api/v1/catalog/suppliers", "aspnet", "/api/v1/catalog/suppliers", "Live exact-route nginx shadow on www (401/200; brands-table alias, 1314 rows). Dual-sample compare still recommended."),
            Link("aspnet-exact-route-shadow-live", "Catalog VIN", "https://www.ecomae.com/api/v1/catalog/vin?vin=WBAXG1103CDW29096", "aspnet", "/api/v1/catalog/vin", "Live exact-route nginx shadow on www (unauth 401; auth cache hit 200 / miss 404 vin_cache_miss). PHP/UMAPI remains for live fills."),
            Link("aspnet-exact-route-shadow-live", "Catalog engines", "https://www.ecomae.com/api/v1/catalog/engines?section=passenger&mfa_id=16", "aspnet", "/api/v1/catalog/engines", "Live exact-route nginx shadow on www (unauth 401; auth needs section+mfa_id; cache miss 404 remains PHP/UMAPI)."),
            Link("aspnet-exact-route-shadow-live", "Catalog analogs", "https://www.ecomae.com/api/v1/catalog/analogs?section=passenger&article=0986424590&brand=BOSCH", "aspnet", "/api/v1/catalog/analogs", "Live exact-route nginx shadow on www (unauth 401; auth needs article+brand; cache miss 404 remains PHP/UMAPI)."),
            Link("aspnet-exact-route-shadow-live", "Catalog article-brands", "https://www.ecomae.com/api/v1/catalog/article-brands?section=passenger&article=0986424590", "aspnet", "/api/v1/catalog/article-brands", "Live exact-route nginx shadow on www (unauth 401; auth needs article; UMAPI action=brands cache; miss 404 remains PHP)."),
            Link("aspnet-exact-route-shadow-live", "Catalog categories", "https://www.ecomae.com/api/v1/catalog/categories?section=passenger&id=1", "aspnet", "/api/v1/catalog/categories", "Live exact-route nginx shadow on www (unauth 401; auth optional id; cache miss 404 remains PHP/UMAPI)."),
            Link("aspnet-exact-route-shadow-live", "Catalog products", "https://www.ecomae.com/api/v1/catalog/products?section=passenger&category_id=1&id=1", "aspnet", "/api/v1/catalog/products", "Live exact-route nginx shadow on www (unauth 401; auth needs category/id params for cache hit; miss 404 remains PHP/UMAPI)."),
            Link("aspnet-exact-route-shadow-live", "Catalog engine-search", "https://www.ecomae.com/api/v1/catalog/engine-search?section=passenger&code=3L&mfa_id=0", "aspnet", "/api/v1/catalog/engine-search", "Live exact-route nginx shadow on www (unauth 401; auth needs engine_search in allowed_actions_json — smoke key may 403 until re-issue; miss 404 remains PHP)."),
            Link("aspnet-exact-route-shadow-live", "Catalog article-links", "https://www.ecomae.com/api/v1/catalog/article-links?section=passenger&id=123", "aspnet", "/api/v1/catalog/article-links", "Live exact-route nginx shadow on www (unauth 401; auth uses catalog action=article; offline-cache miss 404 remains PHP/UMAPI). Installer may FAIL on CDN lag while location= is already inserted — re-probe public."),
            Link("aspnet-exact-route-shadow-live", "Catalog article", "https://www.ecomae.com/api/v1/catalog/article?section=passenger&id=123", "aspnet", "/api/v1/catalog/article", "Live exact-route nginx shadow on www (unauth 401; auth needs id + action=article; offline-cache miss 404 remains PHP/UMAPI). Exact-match installer fix required so article is not confused with article-links."),
            Link("aspnet-exact-route-shadow-live", "Catalog articles", "https://www.ecomae.com/api/v1/catalog/articles?section=passenger&CATEGORY_ID=1", "aspnet", "/api/v1/catalog/articles", "Live exact-route nginx shadow on www (unauth 401; auth action=articles; opportunistic cache, miss 404 remains PHP/UMAPI)."),
            Link("aspnet-exact-route-shadow-live", "Catalog engine", "https://www.ecomae.com/api/v1/catalog/engine?section=passenger&id=1", "aspnet", "/api/v1/catalog/engine", "Live exact-route nginx shadow on www (unauth 401; auth uses engines action; offline-cache miss 404 remains PHP/UMAPI). Exact-match installer avoids false hit on engines/engine-search."),
            Link("aspnet-exact-route-shadow-live", "Catalog brand-parts", "https://www.ecomae.com/api/v1/catalog/brand-parts?section=passenger&brand=BOSCH", "aspnet", "/api/v1/catalog/brand-parts", "Live exact-route nginx shadow on www (unauth 401; auth needs brand/params; miss 404 remains PHP). Completes wired catalog API exact-route set (18/18)."),
            Link("aspnet-exact-route-shadow-live", "Storefront account summary", "https://www.ecomae.com/storefront/account-summary", "aspnet", "/storefront/account-summary", "Live exact-route nginx shadow on www (unauth 401 unauthorized; customer cookie for 200). Completes storefront digests 4/4."),
            Link("aspnet-exact-route-shadow-live", "Storefront orders", "https://www.ecomae.com/storefront/orders", "aspnet", "/storefront/orders", "Live exact-route nginx shadow on www (unauth 401 unauthorized; customer cookie for 200)."),
            Link("aspnet-exact-route-shadow-live", "Storefront garage", "https://www.ecomae.com/storefront/garage", "aspnet", "/storefront/garage", "Live exact-route nginx shadow on www (unauth 401 unauthorized; customer cookie for 200)."),
            Link("aspnet-exact-route-shadow-live", "Storefront profile", "https://www.ecomae.com/storefront/profile", "aspnet", "/storefront/profile", "Live exact-route nginx shadow on www (unauth 401 unauthorized; customer cookie for 200). Completes storefront digests 4/4.")
        ];

        return new LiveSurfaceLinkReport(
            "catalogued-php-authoritative-except-allowlisted-aspnet",
            "www.ecomae.com",
            links,
            [
                "Live tenant and industry frontend/CP/ERP must remain PHP — migration shadows default to www.ecomae.com only (see docs/migration/TENANT_MIGRATION_SAFETY.md).",
                "Broad /, /api, /cp, /erp, /bos, storefront nginx cutover remains forbidden.",
                "Only approved location = exact-route shadows may be enabled after staging smoke.",
                "Keep MigrationRouteCutover StorefrontAspNetEnabled=false, AdminAspNetEnabled=false, RequirePhpFallback=true until final gate.",
                "ReadyToRemovePhp stays false without staging-smoke artifacts + RELEASE_OWNER_APPROVAL.md."
            ],
            [
                "Diagnose: bash scripts/cloudpanel_diagnose_smoke_db.sh — then apply DDL (clpctl) or use_php_dp_config_as_tenant_registry.sh if CREATE denied.",
                "On CloudPanel: ECOMAE_CONFIRM_CREATE_API_CLIENTS_TABLE=YES bash scripts/cloudpanel_ensure_epc_api_clients_table.sh",
                "Then: ECOMAE_CONFIRM_ISSUE_SMOKE_CREDS=YES ECOMAE_CONFIRM_SYNC_ADMIN_SESSION=YES bash scripts/cloudpanel_issue_smoke_credentials.sh",
                "Validate (redacted): bash scripts/cloudpanel_validate_final_gate_env.sh (or bash scripts/cloudpanel_prepare_smoke_secrets.sh).",
                "source /etc/ecomae-aspnet/platform.env && bash scripts/cloudpanel_capture_final_gate_artifacts.sh && bash scripts/cloudpanel_commit_final_gate_smoke.sh",
                "Auth chain probe: source /etc/ecomae-aspnet/platform.env && bash scripts/cloudpanel_probe_catalog_vehicle_chain.sh",
                "Warm VIN probe: bash scripts/cloudpanel_list_warm_catalog_vehicle_ids.sh vin",
                "Warm UMAPI cache: bash scripts/cloudpanel_list_warm_catalog_vehicle_ids.sh umapi engine_search",
                "Warm UMAPI cache: bash scripts/cloudpanel_list_warm_catalog_vehicle_ids.sh umapi article_links",
                "Warm UMAPI cache: bash scripts/cloudpanel_list_warm_catalog_vehicle_ids.sh umapi article",
                "Batch 5 catalog miss probe: bash scripts/cloudpanel_probe_catalog_miss_path.sh (expect 401 unauth / 404 cache_miss|vin_cache_miss; cutoverAllowed=false).",
                "Batch 5 miss dual-sample: bash scripts/cloudpanel_capture_catalog_miss_dual_samples.sh && python3 scripts/compare_catalog_miss_dual_samples.py (PHP fill remains authoritative).",
                "Batch 5 miss-fill dry-run: worker job catalog-miss-fill (sample_actions); outbound/writes blocked; see docs/migration/evidence/catalog-miss-umapi/miss-fill-dry-run-report.json.",
                "If engine-search/article auth 403 action_not_allowed: re-issue smoke creds (allowlist now includes engine_search+article) via ECOMAE_CONFIRM_ISSUE_SMOKE_CREDS=YES bash scripts/cloudpanel_issue_smoke_credentials.sh",
                "Wired catalog exact-routes complete (18/18). Surface digests: 30/30. Storefront digests: 4/4 (batch installer; never broad /storefront).",
                "Storefront batch: ECOMAE_CONFIRM_INSTALL_STOREFRONT_DIGEST_SHADOWS=YES bash scripts/cloudpanel_install_storefront_digest_shadows.sh",
                "Storefront probe: bash scripts/cloudpanel_probe_storefront_digest_shadows.sh",
                "Blazor SSR console live: /migration/console. Digest dual-sample contract compare: pairsChecked=19 failed=0 (cutoverAllowed=false).",
                "Presentation + login exact-routes: /cp|/erp|/bos|/storefront/{app,login} + POST /auth/login/admin — ECOMAE_CONFIRM_INSTALL_PRESENTATION_APP_SHADOWS=YES bash scripts/cloudpanel_install_presentation_app_shadows.sh",
                "Login bridge needs EcomAE__SecretSuccession (= PHP secret_succession) in platform.env; verify with scripts/cloudpanel_verify_secret_succession_configured.sh (never prints secret); without it UI falls back to PHP login.",
                "Login cookie dual-sample: scripts/cloudpanel_capture_login_cookie_dual_samples.sh + compare_login_cookie_dual_samples.py (cutoverAllowed=false).",
                "Hybrid chrome: ASP.NET shells link PHP modules (see docs/migration/CHROME_PARITY_GAP_MATRIX.md). Product / /CP/ /ERP/ /BOS/ remain PHP.",
                "Same-to-same tenant verify: bash scripts/cloudpanel_verify_tenant_hosts_still_php.sh (PHP chrome on tenant / /CP/ /ERP/ + BOS spot-check; cutoverAllowed=false).",
                "Tenant safety probe: bash scripts/cloudpanel_probe_live_tenant_php_chrome.sh (expect PHP HTML on tenant / /CP/ /ERP/).",
                "Shadow installers refuse tenant vhosts unless ECOMAE_CONFIRM_TENANT_HOST_SHADOW=YES; presentation shadows refuse tenants by default.",
                "Invisible migration law: docs/migration/TENANT_MIGRATION_SAFETY.md — digests/previews never replace tenant UX.",
                "PHP-level parity plan: docs/migration/PHP_LEVEL_FULL_PARITY_PLAN.md — regenerate catalogs via python3 scripts/generate_php_module_catalog.py.",
                "Hybrid module directories on /cp|/erp|/bos|/storefront/app; counts at GET /migration/php-module-catalog.",
                "Human RELEASE_OWNER_APPROVAL.md is the final ReadyToRemovePhp blocker — do not remove PHP while chrome is PHP-authoritative."
            ]);

    }

    private static LiveSurfaceLink Link(
        string hostClass,
        string surface,
        string url,
        string stackToday,
        string aspNetRouteHint,
        string notes) => new(hostClass, surface, url, stackToday, aspNetRouteHint, notes);
}
