namespace EcomAE.Platform.Migration;

/// <summary>
/// Field-level contracts for ASP.NET digests that must stay aligned with PHP-authoritative data shapes.
/// Cutover remains forbidden until live dual samples match these contracts field-by-field.
/// </summary>
public static class SurfacePayloadContractCatalog
{
    public static IReadOnlyList<SurfacePayloadContract> All { get; } =
    [
        Contract("cp", "/cp/dashboard-summary", "cp/index.php dashboard widgets", "admin",
            ["ok", "surface", "summary", "session", "note"],
            ["users", "adminSessions", "portalTenants", "activePortalTenants", "source", "message"],
            ["CP dashboard KPI read", "tenant/user/session counts"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/tenants", "cp/content/control/portal/", "admin-cp",
            ["ok", "surface", "tenants", "count", "source", "message", "session", "note"],
            ["siteKey", "hostname", "industryCode", "status", "tradeName", "hubName", "hostedOn", "erpOnly", "isActive", "hasDb"],
            ["portal tenant registry list"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/users", "cp/content/users/", "admin-cp",
            ["ok", "surface", "users", "count", "source", "message", "session", "note"],
            ["userId", "email", "phone", "unlocked", "timeRegistered", "timeLastVisit"],
            ["user_manager read digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/groups", "cp/content/users/ groups", "admin-cp",
            ["ok", "surface", "groups", "count", "source", "message", "session", "note"],
            ["id", "value", "forBackend", "forGuests", "forRegistrated", "unblocked", "parent", "level"],
            ["groups ACL digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/modules", "cp modules registry", "admin-cp",
            ["ok", "surface", "modules", "count", "source", "message", "session", "note"],
            ["id", "caption", "activated", "isFrontend", "isPrototype", "controlAvailable"],
            ["modules list digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/menus", "cp menus", "admin-cp",
            ["ok", "surface", "menus", "count", "source", "message", "session", "note"],
            ["id", "caption", "isFrontend", "menuUlClass", "menuUlId"],
            ["menu metadata digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/pages", "cp content pages", "admin-cp",
            ["ok", "surface", "pages", "count", "source", "message", "session", "note"],
            ["id", "caption", "url", "alias", "isFrontend", "published", "level", "sortOrder"],
            ["pages metadata digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/currencies", "shop_currencies manager", "admin-cp",
            ["ok", "surface", "currencies", "count", "source", "message", "session", "note"],
            ["id", "isoCode", "isoName", "captionShort", "rate", "available", "sortOrder"],
            ["currency list digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/api-clients", "epc_api_clients metadata", "admin-cp",
            ["ok", "surface", "clients", "count", "source", "message", "session", "note"],
            ["id", "clientKeyPrefix", "product", "label", "contactEmail", "active", "dailyLimit", "callsToday", "timeCreated"],
            ["API client metadata (no key hashes)"],
            "cp/templates/bootstrap_admin/desktop.php"),

        Contract("erp", "/erp/dashboard-summary", "cp/content/shop/finance/erp/erp_dashboard.php", "admin",
            ["ok", "surface", "summary", "session", "note"],
            ["cashPosition", "supplierCredit", "supplierDebit", "supplierNet", "cashAccounts", "activeSuppliers", "activePurchases", "source", "message"],
            ["ERP finance KPI read"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/suppliers", "ERP suppliers", "admin-erp",
            ["ok", "surface", "suppliers", "count", "source", "message", "session", "note"],
            ["id", "name", "storageId", "balance"],
            ["supplier balances digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/purchases", "ERP purchases", "admin-erp",
            ["ok", "surface", "purchases", "count", "source", "message", "session", "note"],
            ["id", "supplierId", "supplierName", "purchaseDate", "invoiceNumber", "totalAmount", "status", "orderId"],
            ["purchase list digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/coa-accounts", "content/shop/finance/epc_erp_gl.php COA", "admin-erp",
            ["ok", "surface", "accounts", "count", "source", "message", "session", "note"],
            ["id", "code", "name", "accountType", "normalSide", "parentId", "openingBalance", "active"],
            ["chart of accounts digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/warehouses", "ERP warehouses", "admin-erp",
            ["ok", "surface", "warehouses", "count", "source", "message", "session", "note"],
            ["id", "storageId", "code", "name", "active", "timeCreated"],
            ["warehouse digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/sales-orders", "ERP sales orders", "admin-erp",
            ["ok", "surface", "orders", "count", "source", "message", "session", "note"],
            ["id", "soNo", "customerUserId", "totalAmount", "status", "timeCreated"],
            ["sales order digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/purchase-orders", "ERP purchase orders", "admin-erp",
            ["ok", "surface", "orders", "count", "source", "message", "session", "note"],
            ["id", "poNo", "supplierId", "title", "totalAmount", "status", "timeCreated"],
            ["purchase order digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/inventory-stock", "ERP inventory stock KPIs", "admin-erp",
            ["ok", "surface", "summary", "session", "note"],
            ["rowCount", "qtyOnHand", "stockValue", "warehouseCount", "itemCount", "source", "message"],
            ["inventory stock KPI digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/invoices", "ERP e-invoices", "admin-erp",
            ["ok", "surface", "invoices", "count", "source", "message", "session", "note"],
            ["id", "invoiceNumber", "orderId", "userId", "customerEmail", "issueDate", "status", "totalInclVat"],
            ["invoice digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/gl-journals", "ERP GL journals", "admin-erp",
            ["ok", "surface", "journals", "count", "source", "message", "session", "note"],
            ["id", "journalNo", "journalDate", "sourceType", "sourceId", "status", "totalDebit"],
            ["GL journal digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),

        Contract("bos", "/bos/fleet-summary", "bos/index.php command center", "admin",
            ["ok", "surface", "summary", "session", "note"],
            ["portalTenants", "activePortalTenants", "adminSessions", "withDatabase", "erpOnly", "source", "message"],
            ["BOS fleet KPI read"],
            "bos/index.php + bos/epc_bos_shell.css"),
        Contract("bos", "/bos/fleet-health", "BOS fleet health", "admin-bos",
            ["ok", "surface", "summary", "sampleTenants", "source", "message", "session", "note"],
            ["portalTenants", "activePortalTenants", "adminSessions", "withDatabase", "erpOnly", "source", "message"],
            ["fleet health sample tenants"],
            "bos/index.php + bos/epc_bos_shell.css"),
        Contract("bos", "/bos/fleet-readiness", "BOS fleet readiness scoring", "admin-bos",
            ["ok", "surface", "readiness", "session", "note"],
            ["tenants", "pass", "warn", "fail", "active", "withDatabase", "erpOnly", "source", "message"],
            ["platform-DB readiness scoring"],
            "bos/index.php + bos/epc_bos_shell.css"),
        Contract("bos", "/bos/audit-log", "epc_boc_audit", "admin-bos",
            ["ok", "surface", "entries", "count", "source", "message", "session", "note"],
            ["id", "ts", "userId", "actor", "area", "action", "target", "ip"],
            ["audit log digest"],
            "bos/index.php + bos/epc_bos_shell.css"),

        Contract("storefront", "/storefront/account-summary", "content/users/ account", "customer",
            ["ok", "surface", "summary", "session", "note"],
            ["userId", "orders", "sessions", "garageVehicles", "source", "message"],
            ["customer account KPI read"],
            "templates/modex/desktop.php"),
        Contract("storefront", "/storefront/orders", "shop_orders customer", "customer",
            ["ok", "surface", "user_id", "orders", "count", "source", "message", "session", "note"],
            ["id", "timeUnix", "paid", "successfullyCreated", "status"],
            ["customer orders digest"],
            "templates/modex/desktop.php"),
        Contract("storefront", "/storefront/garage", "shop_docpart_garage", "customer",
            ["ok", "surface", "user_id", "vehicles", "count", "source", "message", "session", "note"],
            ["id", "caption", "marka", "model", "year", "vin", "active"],
            ["customer garage digest"],
            "templates/modex/desktop.php"),
        Contract("storefront", "/storefront/profile", "DP_User::getUserProfile", "customer",
            ["ok", "surface", "user_id", "email", "email_confirmed", "phone", "phone_confirmed", "reg_variant", "profile_fields", "source", "message", "session", "note"],
            ["userId", "email", "emailConfirmed", "phone", "phoneConfirmed", "regVariant", "profileFields", "source", "message"],
            ["customer profile digest"],
            "templates/modex/desktop.php"),

        Contract("api", "/api/v1/price/lookup", "api/v1/price/lookup.php", "api-key",
            ["status", "brand", "article", "offers"],
            ["supplier", "brand", "article", "name", "price", "currency", "stockHint", "leadTime"],
            ["price lookup offers"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/status", "api/v1/catalog.php status", "api-key",
            ["connected", "message", "status_code", "counts", "source"],
            ["manufacturers", "models", "modifications", "brands", "vins"],
            ["catalog status"],
            "n/a-json-api")
    ];

    public static IReadOnlyList<SurfaceFunctionParityItem> Functions { get; } =
    [
        new("cp", "cp/templates/bootstrap_admin/desktop.php chrome", "/cp?format=html", "presentation-shell-scaffolded", "Must reuse PHP CSS asset URLs; interactive widgets still PHP."),
        new("cp", "CP dashboard KPI widgets", "/cp/dashboard-summary", "digest-wired-awaiting-dual-sample", "Field contract locked; needs authenticated dual sample vs PHP KPIs."),
        new("cp", "user_manager / groups / menus / pages", "/cp/users|/cp/groups|/cp/menus|/cp/pages", "digest-wired-awaiting-dual-sample", "Read digests only; writes remain PHP."),
        new("erp", "erp_desktop.php + erp_dashboard.php", "/erp?format=html + /erp/dashboard-summary", "presentation-and-digest-scaffolded", "Chrome CSS + KPI fields contracted; full voucher/posting UX still PHP."),
        new("erp", "COA / PO / SO / inventory / invoices / GL", "/erp/coa-accounts|/erp/purchase-orders|/erp/sales-orders|/erp/inventory-stock|/erp/invoices|/erp/gl-journals", "digest-wired-awaiting-dual-sample", "Field contracts present; no write/posting cutover."),
        new("bos", "bos/index.php + epc_bos_shell.css", "/bos?format=html + /bos/fleet-summary", "presentation-and-digest-scaffolded", "BOS shell CSS must match; privileged ops remain PHP."),
        new("bos", "fleet health/readiness/audit", "/bos/fleet-health|/bos/fleet-readiness|/bos/audit-log", "digest-wired-awaiting-dual-sample", "Read-only scoring/audit digests."),
        new("storefront", "templates/modex/desktop.php", "/storefront/account?format=html", "presentation-shell-scaffolded", "Must reuse modex CSS; cart/checkout/SEO still PHP."),
        new("storefront", "account/orders/garage/profile", "/storefront/account-summary|/storefront/orders|/storefront/garage|/storefront/profile", "digest-wired-awaiting-dual-sample", "Customer session digests; PHP account remains authoritative."),
        new("frontend", "tenant/industry storefront HTML", "/", "php-authoritative", "No broad storefront cutover until HTML/SEO/cart parity samples match."),
        new("api", "price lookup", "/api/v1/price/lookup", "aspnet-live-exact-route", "Already on ASP.NET with JSON auth gate; authenticated offer parity still required."),
        new("api", "catalog status", "/api/v1/catalog/status", "awaiting-exact-route-shadow", "Contract ready; public host still PHP until shadow + smoke.")
    ];

    private static SurfacePayloadContract Contract(
        string surface,
        string route,
        string legacy,
        string auth,
        string[] envelope,
        string[] fields,
        string[] functions,
        string chrome) => new(
        surface,
        route,
        legacy,
        auth,
        envelope,
        fields,
        functions,
        chrome,
        "contract-locked-awaiting-live-dual-sample");
}
