namespace EcomAE.Platform.Migration;

/// <summary>
/// Field-level contracts for ASP.NET digests that must stay aligned with PHP-authoritative data shapes.
/// Cutover remains forbidden until live dual samples match these contracts field-by-field.
/// </summary>
public static class SurfacePayloadContractCatalog
{
    public static IReadOnlyList<SurfacePayloadContract> All { get; } =
    [
        Contract("cp", "/cp/dashboard-summary", "cp/index.php dashboard widgets", "admin",
            ["ok", "surface", "summary", "session", "note"],
            ["users", "adminSessions", "portalTenants", "activePortalTenants", "source", "message"],
            ["CP dashboard KPI read", "tenant/user/session counts"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/tenants", "cp/content/control/portal/", "admin-cp",
            ["ok", "surface", "tenants", "count", "source", "message", "session", "note"],
            ["siteKey", "hostname", "industryCode", "status", "tradeName", "hubName", "hostedOn", "erpOnly", "isActive", "hasDb"],
            ["portal tenant registry list"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/orders-digest", "cp/content/shop/order_process/orders.php KPI+list", "admin-cp",
            ["ok", "surface", "summary", "orders", "count", "source", "message", "session", "note"],
            ["open", "today", "pendingShip", "source", "message"],
            ["CP OMS shop_orders read digest", "KPI open/today/pendingShip", "writes remain PHP"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/users", "cp/content/users/", "admin-cp",
            ["ok", "surface", "users", "count", "source", "message", "session", "note"],
            ["userId", "email", "phone", "unlocked", "timeRegistered", "timeLastVisit"],
            ["user_manager read digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/groups", "cp/content/users/ groups", "admin-cp",
            ["ok", "surface", "groups", "count", "source", "message", "session", "note"],
            ["id", "value", "forBackend", "forGuests", "forRegistrated", "unblocked", "parent", "level"],
            ["groups ACL digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/modules", "cp modules registry", "admin-cp",
            ["ok", "surface", "modules", "count", "source", "message", "session", "note"],
            ["id", "caption", "activated", "isFrontend", "isPrototype", "controlAvailable"],
            ["modules list digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/menus", "cp menus", "admin-cp",
            ["ok", "surface", "menus", "count", "source", "message", "session", "note"],
            ["id", "caption", "isFrontend", "menuUlClass", "menuUlId"],
            ["menu metadata digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/pages", "cp content pages", "admin-cp",
            ["ok", "surface", "pages", "count", "source", "message", "session", "note"],
            ["id", "caption", "url", "alias", "isFrontend", "published", "level", "sortOrder"],
            ["pages metadata digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/currencies", "shop_currencies manager", "admin-cp",
            ["ok", "surface", "currencies", "count", "source", "message", "session", "note"],
            ["id", "isoCode", "isoName", "captionShort", "rate", "available", "sortOrder"],
            ["currency list digest"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/api-clients", "epc_api_clients metadata", "admin-cp",
            ["ok", "surface", "clients", "count", "source", "message", "session", "note"],
            ["id", "clientKeyPrefix", "product", "label", "contactEmail", "active", "dailyLimit", "callsToday", "timeCreated"],
            ["API client metadata (no key hashes)"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/config-items", "config_items metadata", "admin-cp",
            ["ok", "surface", "items", "count", "source", "message", "session", "note"],
            ["name", "caption", "type", "configGroup", "visible", "order"],
            ["config_items metadata (no secret values)"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/admin-sessions", "admin sessions by user", "admin-cp",
            ["ok", "surface", "sessions", "count", "source", "message", "session", "note"],
            ["userId", "email", "type", "sessionCount"],
            ["admin session counts (tokens never returned)"],
            "cp/templates/bootstrap_admin/desktop.php"),
        Contract("cp", "/cp/storages", "shop_storages", "admin-cp",
            ["ok", "surface", "storages", "count", "source", "message", "session", "note"],
            ["id", "name", "shortName", "hidden"],
            ["shop storages digest"],
            "cp/templates/bootstrap_admin/desktop.php"),

        Contract("erp", "/erp/dashboard-summary", "cp/content/shop/finance/erp/erp_dashboard.php", "admin",
            ["ok", "surface", "summary", "session", "note"],
            ["cashPosition", "supplierCredit", "supplierDebit", "supplierNet", "cashAccounts", "activeSuppliers", "activePurchases", "source", "message"],
            ["ERP finance KPI read"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/accounts-summary", "ERP cash/supplier KPI digest", "admin-erp",
            ["ok", "surface", "summary", "source", "message", "session", "note"],
            ["cashPosition", "supplierCredit", "supplierDebit", "supplierNet", "cashAccounts", "activeSuppliers", "activePurchases", "source", "message"],
            ["ERP accounts KPI digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/suppliers", "ERP suppliers", "admin-erp",
            ["ok", "surface", "suppliers", "count", "source", "message", "session", "note"],
            ["id", "name", "storageId", "balance"],
            ["supplier balances digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/purchases", "ERP purchases", "admin-erp",
            ["ok", "surface", "purchases", "count", "source", "message", "session", "note"],
            ["id", "supplierId", "supplierName", "purchaseDate", "invoiceNumber", "totalAmount", "status", "orderId"],
            ["purchase list digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/cash-accounts", "ERP cash/bank accounts", "admin-erp",
            ["ok", "surface", "accounts", "count", "source", "message", "session", "note"],
            ["id", "name", "accountType", "currencyCode", "openingBalance", "balance"],
            ["cash/bank accounts digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/cash-entries", "ERP cash ledger entries", "admin-erp",
            ["ok", "surface", "entries", "count", "source", "message", "session", "note"],
            ["id", "accountId", "accountName", "accountType", "timeUnix", "direction", "amount", "reference", "note"],
            ["cash entries digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/coa-accounts", "content/shop/finance/epc_erp_gl.php COA", "admin-erp",
            ["ok", "surface", "accounts", "count", "source", "message", "session", "note"],
            ["id", "code", "name", "accountType", "normalSide", "parentId", "openingBalance", "active"],
            ["chart of accounts digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/warehouses", "ERP warehouses", "admin-erp",
            ["ok", "surface", "warehouses", "count", "source", "message", "session", "note"],
            ["id", "storageId", "code", "name", "active", "timeCreated"],
            ["warehouse digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/sales-orders", "ERP sales orders", "admin-erp",
            ["ok", "surface", "orders", "count", "source", "message", "session", "note"],
            ["id", "soNo", "customerUserId", "totalAmount", "status", "timeCreated"],
            ["sales order digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/purchase-orders", "ERP purchase orders", "admin-erp",
            ["ok", "surface", "orders", "count", "source", "message", "session", "note"],
            ["id", "poNo", "supplierId", "title", "totalAmount", "status", "timeCreated"],
            ["purchase order digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/inventory-stock", "ERP inventory stock KPIs", "admin-erp",
            ["ok", "surface", "summary", "session", "note"],
            ["rowCount", "qtyOnHand", "stockValue", "warehouseCount", "itemCount", "source", "message"],
            ["inventory stock KPI digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/invoices", "ERP e-invoices", "admin-erp",
            ["ok", "surface", "invoices", "count", "source", "message", "session", "note"],
            ["id", "invoiceNumber", "orderId", "userId", "customerEmail", "issueDate", "status", "totalInclVat"],
            ["invoice digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),
        Contract("erp", "/erp/gl-journals", "ERP GL journals", "admin-erp",
            ["ok", "surface", "journals", "count", "source", "message", "session", "note"],
            ["id", "journalNo", "journalDate", "sourceType", "sourceId", "status", "totalDebit"],
            ["GL journal digest"],
            "cp/templates/bootstrap_admin/erp_desktop.php"),

        Contract("bos", "/bos/fleet-summary", "bos/index.php command center", "admin",
            ["ok", "surface", "summary", "session", "note"],
            ["portalTenants", "activePortalTenants", "adminSessions", "withDatabase", "erpOnly", "source", "message"],
            ["BOS fleet KPI read"],
            "bos/index.php + bos/epc_bos_shell.css"),
        Contract("bos", "/bos/tenants", "BOS portal tenant digest", "admin-bos",
            ["ok", "surface", "tenants", "count", "source", "message", "session", "note"],
            ["siteKey", "hostname", "industryCode", "status", "tradeName", "hubName", "hostedOn", "erpOnly", "isActive", "hasDb"],
            ["portal tenant registry list"],
            "bos/index.php + bos/epc_bos_shell.css"),
        Contract("bos", "/bos/fleet-health", "BOS fleet health", "admin-bos",
            ["ok", "surface", "summary", "sampleTenants", "source", "message", "session", "note"],
            ["portalTenants", "activePortalTenants", "adminSessions", "withDatabase", "erpOnly", "source", "message"],
            ["fleet health sample tenants"],
            "bos/index.php + bos/epc_bos_shell.css"),
        Contract("bos", "/bos/fleet-readiness", "BOS fleet readiness scoring", "admin-bos",
            ["ok", "surface", "readiness", "session", "note"],
            ["tenants", "pass", "warn", "fail", "active", "withDatabase", "erpOnly", "source", "message"],
            ["platform-DB readiness scoring"],
            "bos/index.php + bos/epc_bos_shell.css"),
        Contract("bos", "/bos/audit-log", "epc_boc_audit", "admin-bos",
            ["ok", "surface", "entries", "count", "source", "message", "session", "note"],
            ["id", "ts", "userId", "actor", "area", "action", "target", "ip"],
            ["audit log digest"],
            "bos/index.php + bos/epc_bos_shell.css"),

        Contract("storefront", "/storefront/account-summary", "content/users/ account", "customer",
            ["ok", "surface", "summary", "session", "note"],
            ["userId", "orders", "sessions", "garageVehicles", "source", "message"],
            ["customer account KPI read"],
            "templates/modex/desktop.php"),
        Contract("storefront", "/storefront/orders", "shop_orders customer", "customer",
            ["ok", "surface", "user_id", "orders", "count", "source", "message", "session", "note"],
            ["id", "timeUnix", "paid", "successfullyCreated", "status"],
            ["customer orders digest"],
            "templates/modex/desktop.php"),
        Contract("storefront", "/storefront/garage", "shop_docpart_garage", "customer",
            ["ok", "surface", "user_id", "vehicles", "count", "source", "message", "session", "note"],
            ["id", "caption", "marka", "model", "year", "vin", "active"],
            ["customer garage digest"],
            "templates/modex/desktop.php"),
        Contract("storefront", "/storefront/profile", "DP_User::getUserProfile", "customer",
            ["ok", "surface", "user_id", "email", "email_confirmed", "phone", "phone_confirmed", "reg_variant", "profile_fields", "source", "message", "session", "note"],
            ["userId", "email", "emailConfirmed", "phone", "phoneConfirmed", "regVariant", "profileFields", "source", "message"],
            ["customer profile digest"],
            "templates/modex/desktop.php"),

        Contract("api", "/api/v1/price/lookup", "api/v1/price/lookup.php", "api-key",
            ["status", "brand", "article", "offers"],
            ["supplier", "brand", "article", "name", "price", "currency", "stockHint", "leadTime"],
            ["price lookup offers"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/status", "api/v1/catalog.php status", "api-key",
            ["connected", "message", "status_code", "counts", "source"],
            ["manufacturers", "models", "modifications", "brands", "vins"],
            ["catalog status"],
            "n/a-json-api"),
        // Catalog list wave 1 — envelope locked; item shape compared via scripts/compare_catalog_list_parity.py
        // when dual samples are attached (empty data[] still satisfies the contract validator).
        Contract("api", "/api/v1/catalog/manufacturers", "api/v1/catalog.php manufacturers", "api-key",
            ["ok", "section", "rows", "source", "data", "message"],
            [],
            ["cached manufacturers list"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/models", "api/v1/catalog.php models", "api-key",
            ["ok", "action", "section", "rows", "source", "data", "message"],
            [],
            ["cached models list"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/modifications", "api/v1/catalog.php modifications", "api-key",
            ["ok", "action", "section", "rows", "source", "data", "message"],
            [],
            ["cached modifications list"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/brands", "api/v1/catalog.php brands", "api-key",
            ["ok", "action", "section", "rows", "source", "data", "message"],
            [],
            ["cached brands list"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/suppliers", "api/v1/catalog.php suppliers", "api-key",
            ["ok", "action", "section", "rows", "source", "data", "message"],
            [],
            ["cached suppliers list (brand suppliers)"],
            "n/a-json-api"),
        // Offline-cache wave 2 — envelope locked; compare via compare_catalog_offline_cache_parity.py
        Contract("api", "/api/v1/catalog/engines", "api/v1/catalog.php engines", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache engines"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/analogs", "api/v1/catalog.php analogs", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache analogs"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/article-brands", "api/v1/catalog.php article brands", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache article brands"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/categories", "api/v1/catalog.php categories", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache categories"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/products", "api/v1/catalog.php products", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache products"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/engine-search", "api/v1/catalog.php engine-search", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache engine-search"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/article-links", "api/v1/catalog.php article-links", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache article-links"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/article", "api/v1/catalog.php article", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache article"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/articles", "api/v1/catalog.php articles", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache articles"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/engine", "api/v1/catalog.php engine", "api-key",
            ["ok", "action", "section", "rows", "source", "stale", "data"],
            [],
            ["offline-cache engine by id"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/vin", "api/v1/catalog.php vin", "api-key",
            ["ok", "source", "stale", "vin", "language", "region", "vehicle_count", "payload"],
            [],
            ["offline VIN decode envelope"],
            "n/a-json-api"),
        Contract("api", "/api/v1/catalog/brand-parts", "api/v1/catalog.php brand-parts", "api-key",
            ["ok", "brand", "rows", "source", "data", "message"],
            [],
            ["brand parts page"],
            "n/a-json-api")
    ];

    public static IReadOnlyList<SurfaceFunctionParityItem> Functions { get; } =
    [
        new("cp", "cp/templates/bootstrap_admin/desktop.php chrome", "/cp?format=html", "presentation-shell-scaffolded", "Must reuse PHP CSS asset URLs; interactive widgets still PHP."),
        new("cp", "CP dashboard KPI widgets", "/cp/dashboard-summary", "digest-wired-awaiting-dual-sample", "Field contract locked; needs authenticated dual sample vs PHP KPIs."),
        new("cp", "dashboard-summary Blazor KPIs", "/cp/dashboard-summary-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/dashboard-summary digest; PHP desktop.php widgets remain authoritative; tenant chrome stays PHP."),
        new("cp", "Orders/OMS shop_orders read", "/cp/orders + /cp/orders-digest", "digest-wired-awaiting-dual-sample", "Batch 4 read UI + KPI digest; PHP OMS console and writes remain authoritative."),
        new("cp", "user_manager / groups Blazor lists", "/cp/users-app|/cp/groups-app", "digest-wired-awaiting-dual-sample", "Batch 4 read UI over existing /cp/users|/cp/groups digests; writes remain PHP."),
        new("cp", "modules Blazor list", "/cp/modules-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/modules digest; PHP modules_manager writes remain authoritative; tenant chrome stays PHP."),
        new("cp", "pages Blazor list", "/cp/pages-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/pages digest (body omitted); PHP content_manager writes remain authoritative; tenant chrome stays PHP."),
        new("cp", "menus Blazor list", "/cp/menus-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/menus digest (structure JSON omitted); PHP menu_manager writes remain authoritative; tenant chrome stays PHP."),
        new("cp", "tenants Blazor list", "/cp/tenants-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/tenants digest; PHP epc_tenant_control_center / portal remain authoritative; tenant product chrome stays PHP."),
        new("cp", "currencies Blazor list", "/cp/currencies-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/currencies digest; PHP nastrojka-kursov-valyut writes remain authoritative; tenant chrome stays PHP."),
        new("cp", "storages Blazor list", "/cp/storages-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/storages digest; PHP /CP/shop/logistics/storages writes remain authoritative; tenant chrome stays PHP."),
        new("cp", "admin-sessions Blazor list", "/cp/admin-sessions-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/admin-sessions digest (tokens never returned); PHP /CP/control/users remains authoritative; tenant chrome stays PHP."),
        new("cp", "api-clients Blazor list", "/cp/api-clients-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/api-clients digest (key hashes never returned); PHP epc_api_clients_manage remains authoritative; tenant chrome stays PHP."),
        new("cp", "config-items Blazor list", "/cp/config-items-app", "digest-wired-awaiting-dual-sample", "Read UI over /cp/config-items digest (secret values never returned); PHP config_edit remains authoritative; tenant chrome stays PHP."),
        new("cp", "user_manager / groups / menus / pages", "/cp/users|/cp/groups|/cp/menus|/cp/pages", "digest-wired-awaiting-dual-sample", "Read digests only; writes remain PHP."),
        new("cp", "config-items / admin-sessions / storages", "/cp/config-items|/cp/admin-sessions|/cp/storages", "digest-wired-awaiting-dual-sample", "Read digests only; config secrets and session tokens never returned."),
        new("erp", "erp_desktop.php + erp_dashboard.php", "/erp?format=html + /erp/dashboard-summary", "presentation-and-digest-scaffolded", "Chrome CSS + KPI fields contracted; full voucher/posting UX still PHP."),
        new("erp", "sales_orders Blazor list", "/erp/sales-orders-app", "digest-wired-awaiting-dual-sample", "Batch 4 read UI over existing /erp/sales-orders digest; PHP erp_tabs_sales_orders writes remain authoritative."),
        new("erp", "purchase_orders Blazor list", "/erp/purchase-orders-app", "digest-wired-awaiting-dual-sample", "Read UI over existing /erp/purchase-orders digest; PHP erp_tabs_purchase_orders writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "invoices Blazor list", "/erp/invoices-app", "digest-wired-awaiting-dual-sample", "Read UI over existing /erp/invoices digest; PHP erp_tabs_invoices writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "cash_bank Blazor list", "/erp/cash-accounts-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/cash-accounts|/erp/cash-entries digests; PHP erp_tabs_cash_bank writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "coa Blazor list", "/erp/coa-accounts-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/coa-accounts digest; PHP erp_tabs_accounting (tab=coa) writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "gl Blazor list", "/erp/gl-journals-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/gl-journals digest; PHP erp_tabs_accounting (tab=gl) writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "warehouses Blazor list", "/erp/warehouses-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/warehouses digest; PHP erp_tabs_inventory writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "suppliers Blazor list", "/erp/suppliers-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/suppliers digest; PHP AP payables / epc_erp_list_suppliers writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "purchases Blazor list", "/erp/purchases-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/purchases digest; PHP purchasing/purchases / epc_erp_list_purchases writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "inventory-stock Blazor KPIs", "/erp/inventory-stock-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/inventory-stock digest; PHP inventory tab / epc_erp_inv_stock writes remain authoritative; tenant chrome stays PHP."),
        new("erp", "accounts-summary Blazor KPIs", "/erp/accounts-summary-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/accounts-summary digest; PHP cash/bank posting remains authoritative; tenant chrome stays PHP."),
        new("erp", "dashboard-summary Blazor KPIs", "/erp/dashboard-summary-app", "digest-wired-awaiting-dual-sample", "Read UI over /erp/dashboard-summary digest; PHP erp_dashboard.php widgets remain authoritative; tenant chrome stays PHP."),
        new("erp", "COA / PO / SO / inventory / invoices / GL", "/erp/coa-accounts|/erp/purchase-orders|/erp/sales-orders|/erp/inventory-stock|/erp/invoices|/erp/gl-journals", "digest-wired-awaiting-dual-sample", "Field contracts present; no write/posting cutover."),
        new("erp", "accounts-summary / cash accounts+entries", "/erp/accounts-summary|/erp/cash-accounts|/erp/cash-entries", "digest-wired-awaiting-dual-sample", "Cash KPI/ledger digests; posting remains PHP."),
        new("bos", "bos/index.php + epc_bos_shell.css", "/bos?format=html + /bos/fleet-summary", "presentation-and-digest-scaffolded", "BOS shell CSS must match; privileged ops remain PHP."),
        new("bos", "audit-log Blazor list", "/bos/audit-log-app", "digest-wired-awaiting-dual-sample", "Read UI over /bos/audit-log digest (meta omitted); PHP epc_boc_audit_log append-only remains authoritative; /BOS/ session still required for native modules."),
        new("bos", "tenants Blazor list", "/bos/tenants-app", "digest-wired-awaiting-dual-sample", "Read UI over /bos/tenants digest; PHP epc_tenant_control_center / /BOS/?m=fleet_cp remain authoritative; /BOS/ session still required for native modules."),
        new("bos", "fleet-health Blazor KPIs", "/bos/fleet-health-app", "digest-wired-awaiting-dual-sample", "Read UI over /bos/fleet-health digest; PHP epc_bos_health_check / epc_platform_health_checkup remain authoritative; /BOS/ session still required for native modules."),
        new("bos", "fleet-readiness Blazor KPIs", "/bos/fleet-readiness-app", "digest-wired-awaiting-dual-sample", "Read UI over /bos/fleet-readiness digest; PHP epc_bos_health_check remains authoritative; /BOS/ session still required for native modules."),
        new("bos", "fleet health/readiness/audit/tenants", "/bos/fleet-health|/bos/fleet-readiness|/bos/audit-log|/bos/tenants", "digest-wired-awaiting-dual-sample", "Read-only scoring/audit/tenant digests."),
        new("storefront", "templates/modex/desktop.php", "/storefront/account?format=html", "presentation-shell-scaffolded", "Must reuse modex CSS; cart/checkout/SEO still PHP."),
        new("storefront", "account/orders/garage/profile", "/storefront/account-summary|/storefront/orders|/storefront/garage|/storefront/profile", "digest-wired-awaiting-dual-sample", "Customer session digests; PHP account remains authoritative."),
        new("storefront", "part_search Blazor results", "/storefront/search-app", "digest-wired-awaiting-dual-sample", "Batch 4 read-only warehouse offers (pyapi SQL parity); full PHP part_search tabs/cart remain authoritative."),
        new("storefront", "cart Blazor summary", "/storefront/cart-app", "digest-wired-awaiting-dual-sample", "Batch 4 authenticated shop_carts read UI; qty/guest cart/checkout writes remain PHP."),
        new("storefront", "orders Blazor list", "/storefront/orders-app", "digest-wired-awaiting-dual-sample", "Read UI over /storefront/orders digest; PHP /shop/orders remains authoritative for detail/reorder; live storefront stays PHP."),
        new("storefront", "garage Blazor list", "/storefront/garage-app", "digest-wired-awaiting-dual-sample", "Read UI over /storefront/garage digest; PHP part_search garage remains authoritative for add/edit; live storefront stays PHP."),
        new("storefront", "profile Blazor read", "/storefront/profile-app", "digest-wired-awaiting-dual-sample", "Read UI over /storefront/profile digest; PHP /users/profile remains authoritative for edits; live storefront stays PHP."),
        new("storefront", "account-summary Blazor KPIs", "/storefront/account-summary-app", "digest-wired-awaiting-dual-sample", "Read UI over /storefront/account-summary digest; PHP /users/ account tools remain authoritative; live storefront stays PHP."),
        new("frontend", "tenant/industry storefront HTML", "/", "php-authoritative", "No broad storefront cutover until HTML/SEO/cart parity samples match."),
        new("api", "price lookup", "/api/v1/price/lookup", "aspnet-live-exact-route", "Already on ASP.NET with JSON auth gate; authenticated offer parity still required."),
        new("api", "catalog status", "/api/v1/catalog/status", "awaiting-exact-route-shadow", "Contract ready; public host still PHP until shadow + smoke."),
        new("api", "catalog manufacturers/models/modifications/brands/suppliers", "/api/v1/catalog/manufacturers|…|/suppliers", "digest-wired-awaiting-dual-sample", "Envelope contracts + compare_catalog_list_parity.py; one-path nginx-catalog-*-shadow after smoke."),
        new("api", "catalog offline-cache + vin + brand-parts", "/api/v1/catalog/engines|analogs|…|vin|brand-parts", "digest-wired-awaiting-dual-sample", "Offline-cache envelopes + compare_catalog_offline_cache_parity.py / compare_catalog_vin_parity.py."),
        new("api", "catalog miss / UMAPI fill", "/api/v1/catalog/* miss → 404", "digest-wired-awaiting-dual-sample", "Batch 5: ASP.NET returns cache_miss/vin_cache_miss; catalog-miss-fill dry-run outbound/writes blocked; live UMAPI fill remains PHP (cutoverAllowed=false).")
    ];

    private static SurfacePayloadContract Contract(
        string surface,
        string route,
        string legacy,
        string auth,
        string[] envelope,
        string[] fields,
        string[] functions,
        string chrome) => new(
        surface,
        route,
        legacy,
        auth,
        envelope,
        fields,
        functions,
        chrome,
        "contract-locked-awaiting-live-dual-sample");
}
