<?php
declare(strict_types=1);
require_once __DIR__ . '/epc_deploy_auth.php';
epc_deploy_require_token();
header('Content-Type: text/plain; charset=utf-8');
echo 'HTTP_HOST=' . ($_SERVER['HTTP_HOST'] ?? '') . "\n";
echo 'SERVER_NAME=' . ($_SERVER['SERVER_NAME'] ?? '') . "\n";
echo 'REQUEST_URI=' . ($_SERVER['REQUEST_URI'] ?? '') . "\n";
define('_ASTEXE_', 1);
require_once __DIR__ . '/config.php';
$DP_Config = new DP_Config();
require_once __DIR__ . '/content/general_pages/epc_portal.php';
epc_portal_apply_config($DP_Config);
$domain_to_check = parse_url($DP_Config->domain_path, PHP_URL_HOST);
echo "domain_path={$DP_Config->domain_path}\n";
echo "domain_host={$domain_to_check}\n";
echo 'check_server_name=' . ($domain_to_check === ($_SERVER['SERVER_NAME'] ?? '') ? 'ok' : 'FAIL') . "\n";
echo 'check_http_host=' . ($domain_to_check === ($_SERVER['HTTP_HOST'] ?? '') ? 'ok' : 'FAIL') . "\n";
$headers_array = array_change_key_case(function_exists('getallheaders') ? getallheaders() : array(), CASE_LOWER);
echo 'header_host=' . ($headers_array['host'] ?? '') . "\n";
echo 'check_header_host=' . ($domain_to_check === ($headers_array['host'] ?? '') ? 'ok' : 'FAIL') . "\n";
