INSERT IGNORE INTO `sms_api` VALUES (1,'СМС Дисконт (iqsms.ru)','[{\"name\":\"login\",\"type\":\"text\",\"caption\":\"4759\"},{\"name\":\"password\",\"type\":\"text\",\"caption\":\"1311\"}]','','',0,'iqsms',0),(2,'SMS Aero (smsaero.ru)','[{\"name\":\"login\",\"type\":\"text\",\"caption\":\"4759\"},{\"name\":\"password\",\"type\":\"text\",\"caption\":\"1311\"},{\"name\":\"from\",\"type\":\"text\",\"caption\":\"4943\"},{\"name\":\"testsend\",\"type\":\"checkbox\",\"caption\":\"4944\"}]','','',0,'smsaero',0),(3,'SMS.RU','[{\"name\":\"api_id\",\"type\":\"text\",\"caption\":\"4945\"},{\"name\":\"translit\",\"type\":\"checkbox\",\"caption\":\"4946\"}]','','',0,'sms_ru',0),(4,'smsvizitka.com','[{\"name\":\"api_key\",\"type\":\"text\",\"caption\":\"4947\"}]','','',0,'smsvizitka_com',0),(5,'SMSimple.ru','[{\"name\":\"login\",\"type\":\"text\",\"caption\":\"4759\"},{\"name\":\"password\",\"type\":\"text\",\"caption\":\"1311\"},{\"name\":\"signature_id\",\"type\":\"text\",\"caption\":\"4948\"}]','','SMSimple.ru',0,'smsimple',0),(6,'rocketsms.by','[{\"name\":\"login\",\"type\":\"text\",\"caption\":\"4759\"},{\"name\":\"pass\",\"type\":\"text\",\"caption\":\"1311\"}]','','',0,'rocketsms_by',0),(7,'smstraffic.ru','[{\"name\":\"login\",\"type\":\"text\",\"caption\":\"4759\"},{\"name\":\"password\",\"type\":\"text\",\"caption\":\"1311\"}]','','',0,'smstraffic',0),(8,'smsgorod.ru','[{\"name\":\"api-key\",\"type\":\"text\",\"caption\":\"4949\"},{\"name\":\"channel\",\"type\":\"text\",\"caption\":\"4950\"},{\"name\":\"sender\",\"type\":\"text\",\"caption\":\"4951\"},{\"name\":\"domain\",\"type\":\"checkbox\",\"caption\":\"4952\"}]','','',0,'smsgorod_ru',0),(9,'semysms.net','[{\"name\":\"token\",\"type\":\"text\",\"caption\":\"4953\"},{\"name\":\"device\",\"type\":\"text\",\"caption\":\"4954\"}]','','',0,'semysms',0);

-- UAE / GCC / Pakistan operators (default From: +971567607011 — changeable in CP)
-- Prefer running epc-sms-mena-setup.php for idempotent insert/update.
INSERT IGNORE INTO `sms_api` (`id`, `name`, `parameters`, `parameters_values`, `description`, `active`, `handler`, `control_available`) VALUES
(10,'Unifonic (GCC / MENA)','[{"name":"appsid","type":"text","caption":"Unifonic AppSid (API key)"},{"name":"sender_number","type":"text","caption":"Sender number / Sender ID (changeable)"},{"name":"api_url","type":"text","caption":"API URL (optional override)"}]','{"appsid":"","sender_number":"+971567607011","api_url":"https://el.cloud.unifonic.com/rest/SMS/messages"}','GCC and Middle East SMS via Unifonic REST. Sender number defaults to +971567607011 — change anytime under parameters.',0,'epc_unifonic',1),
(11,'Etisalat (e&) UAE','[{"name":"api_url","type":"text","caption":"Etisalat partner API URL"},{"name":"api_key","type":"text","caption":"API key / username"},{"name":"api_secret","type":"password","caption":"API secret / password (optional)"},{"name":"auth_header","type":"text","caption":"Auth header (optional Bearer/Basic)"},{"name":"sender_number","type":"text","caption":"Sender number / Sender ID (changeable)"}]','{"api_url":"","api_key":"","api_secret":"","auth_header":"","sender_number":"+971567607011"}','UAE Etisalat / e& partner SMS gateway. From-number defaults to +971567607011.',0,'epc_etisalat',1),
(12,'du UAE','[{"name":"api_url","type":"text","caption":"du partner API URL"},{"name":"api_key","type":"text","caption":"API key / username"},{"name":"api_secret","type":"password","caption":"API secret / password (optional)"},{"name":"auth_header","type":"text","caption":"Auth header (optional Bearer/Basic)"},{"name":"sender_number","type":"text","caption":"Sender number / Sender ID (changeable)"}]','{"api_url":"","api_key":"","api_secret":"","auth_header":"","sender_number":"+971567607011"}','UAE du Messaging / Business SMS gateway. Sender number defaults to +971567607011.',0,'epc_du',1),
(13,'Pakistan / Jazz SMS','[{"name":"api_url","type":"text","caption":"Provider API URL"},{"name":"api_key","type":"text","caption":"API key (optional if username/password)"},{"name":"username","type":"text","caption":"Username (optional)"},{"name":"password","type":"password","caption":"Password (optional)"},{"name":"sender_number","type":"text","caption":"Sender number / mask (changeable)"}]','{"api_url":"","api_key":"","username":"","password":"","sender_number":"+971567607011"}','Pakistan SMS via Jazz or compatible HTTP gateway (+92).',0,'epc_pakistan',1);
