namespace EcomAE.Workers;

public sealed record ZeroPhpBatchOneWorkerReplacement(
    string LegacyPhpEntry,
    string Surface,
    string TargetOwner,
    string TargetSlice,
    string Risk,
    string Status,
    string RequiredEvidence);

public sealed class ZeroPhpBatchOneWorkerReplacementCatalog
{
    public const int BatchNumber = 1;
    public const string CutoverMode = "exact-route-only";
    public const bool PhpFallbackRequired = true;

    public IReadOnlyCollection<ZeroPhpBatchOneWorkerReplacement> Replacements { get; } =
    [
        new("cp/content/content/ajax_create_sitemap.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/content/sitemap.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/catalogue/tree_list_show_async.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/data_transfer/catalogue_csv_import/catalogue_csv_import.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/data_transfer/pages/catalogue_xml_json_import.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/finance/erp/erp_tabs_data_import.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/prices_upload/ajax_5_import_csv_to_db.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/prices_upload/for_pyprices/for_cron/create_edit_cron_task.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/prices_upload/for_pyprices/for_cron/cron_crutch.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/prices_upload/for_pyprices/for_cron/cron_task_executor.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/prices_upload/for_pyprices/for_cron/cron_tasks_actions.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("cp/content/shop/prices_upload/for_pyprices/for_cron/crontab_writer.php", "cp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("content/shop/finance/epc_custom_declaration_pdf_import.php", "erp", "aspnet-with-python-ai-helper", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("content/shop/finance/epc_fulfillment_queue.php", "erp", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("ajax_5_import_csv_to_db.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("deploy/on-premises/backup.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("ecomae-sync-cp-config.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("ecomae-sync-cp-site.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("ecomae-sync-www-to-cp.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-apai-background-jobs-cron.php", "platform", "aspnet-with-python-ai-helper", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-apai-sync-categories-all.php", "platform", "aspnet-with-python-ai-helper", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-apai-weekly-platform-sync.php", "platform", "aspnet-with-python-ai-helper", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-cp-system-menu-cleanup-all.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-currency-live-rates-cron.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-demo-expire-cron.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-ecomae-cp-exec-sync.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-ecomae-cp-import-tar.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-ecomae-cp-pull-sync.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-ecomae-cp-sync-local.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-ecomae-full-sync.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-ecomae-schema-sync.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-epartscart-vps-backup.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-import-r-uae.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-integrations-cleanup.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-platform-full-backup.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-platform-jobs-cron.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-production-backup.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-seo-sitemap-ping.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-seo-sitemap-warm.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-sync-epartscart-docroot.php", "platform", "aspnet-with-python-ai-helper", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-sync-smtp-from-imap.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-taxofinca-discover-sync.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-tenant-code-sync.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc-uae-tax-legislation-cron.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("epc_sitemap_lib.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("import-db.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("production-backup.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("sitemap-index.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("sitemap-industries.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal."),
        new("sitemap-marketing.php", "platform", "aspnet-core", "worker-replacement", "high", "aspnet-worker-dry-run-required", "ASP.NET Core worker implementation, PHP-vs-ASP.NET parity sample, rollback command, exact-route proxy rule, live smoke before PHP fallback removal.")
    ];
}
