using EcomAE.Platform.Api.Catalog;
using EcomAE.Platform.Auth;
using EcomAE.Platform.Components;
using EcomAE.Platform.Configuration;
using EcomAE.Platform.Data;
using EcomAE.Platform.LifeOs;
using EcomAE.Platform.Middleware;
using EcomAE.Platform.Migration;
using EcomAE.Platform.Modules;
using EcomAE.Platform.Presentation;
using EcomAE.Platform.Routing;
using EcomAE.Platform.Security;
using EcomAE.Platform.Services;
using EcomAE.Platform.Surfaces;
using Microsoft.AspNetCore.ResponseCompression;
using System.IO.Compression;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorComponents();

builder.Services.Configure<EcomAeOptions>(builder.Configuration.GetSection(EcomAeOptions.SectionName));
builder.Services.Configure<MigrationRouteCutoverOptions>(builder.Configuration.GetSection(MigrationRouteCutoverOptions.SectionName));
builder.Services.Configure<PhpReferenceOptions>(builder.Configuration.GetSection(PhpReferenceOptions.SectionName));
builder.Services.Configure<PriceLookupOptions>(builder.Configuration.GetSection(PriceLookupOptions.SectionName));
builder.Services.Configure<SessionCacheOptions>(builder.Configuration.GetSection(SessionCacheOptions.SectionName));
builder.Services.Configure<TenantDbPoolOptions>(builder.Configuration.GetSection(TenantDbPoolOptions.SectionName));
builder.Services.AddHttpContextAccessor();
builder.Services.AddMemoryCache();
builder.Services.AddSingleton<ConfigurationTenantRegistry>();
builder.Services.AddSingleton<ITenantDbConnectionFactory, MySqlTenantDbConnectionFactory>();
builder.Services.AddSingleton<IEpartFrontOwnBrandService, EpartFrontOwnBrandService>();
builder.Services.AddSingleton<ITenantRegistry>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    var seed = sp.GetRequiredService<ConfigurationTenantRegistry>();
    if (!connections.IsConfigured)
    {
        return seed;
    }

    return ActivatorUtilities.CreateInstance<DbBackedTenantRegistry>(sp);
});
builder.Services.AddSingleton<TimeProvider>(TimeProvider.System);
builder.Services.AddSingleton<ILegacySessionStore>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    if (!connections.IsConfigured)
    {
        return new MigrationLegacySessionStore();
    }

    var inner = ActivatorUtilities.CreateInstance<DbLegacySessionStore>(sp);
    var cacheOpts = sp.GetRequiredService<Microsoft.Extensions.Options.IOptions<SessionCacheOptions>>().Value;
    return cacheOpts.Enabled
        ? ActivatorUtilities.CreateInstance<CachingLegacySessionStore>(sp, inner)
        : inner;
});
builder.Services.AddSingleton<ILegacySessionValidator, DbBackedLegacySessionValidator>();
builder.Services.AddSingleton<EcomAE.Platform.Storefront.IStorefrontPriceAccess, EcomAE.Platform.Storefront.StorefrontPriceAccess>();
builder.Services.AddSingleton<ILegacySessionParityReporter, LegacySessionParityReporter>();
builder.Services.AddSingleton<LegacyLogoutService>();
builder.Services.AddSingleton<ILegacyAdminLoginService>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    var options = sp.GetRequiredService<Microsoft.Extensions.Options.IOptions<EcomAeOptions>>();
    return connections.IsConfigured && !string.IsNullOrWhiteSpace(options.Value.SecretSuccession)
        ? ActivatorUtilities.CreateInstance<DbLegacyAdminLoginService>(sp)
        : new UnconfiguredLegacyAdminLoginService();
});

builder.Services.AddSingleton<ILegacyApiClientStore, DbLegacyApiClientStore>();
builder.Services.AddSingleton<ILegacyApiUsageLogger, DbLegacyApiUsageLogger>();
builder.Services.AddSingleton<ILegacyApiClientAuthenticator, LegacyApiClientAuthenticator>();
builder.Services.AddSingleton<ILegacyApiClientParityReporter, LegacyApiClientParityReporter>();
builder.Services.AddSingleton<ITenantResolver, RouteTenantResolver>();
builder.Services.AddEcomAeAuthorization();
builder.Services.AddEcomAeSurfaceModules();
builder.Services.AddLifeOsPart2Scaffold();
builder.Services.AddSingleton<ISurfaceShellCatalog, MigrationSurfaceShellCatalog>();
builder.Services.AddSingleton<ILegacyHtmlShellRenderer, LegacyHtmlShellRenderer>();
builder.Services.AddSingleton<IPresentationParityReporter, PresentationParityReporter>();
builder.Services.AddSingleton<IPriceOfferRepository>(sp =>
{
    var configuration = sp.GetRequiredService<IConfiguration>();
    var csvPath = configuration["PriceLookup:FixtureCsvPath"];
    if (!string.IsNullOrWhiteSpace(csvPath))
    {
        return new CsvPriceOfferRepository(csvPath);
    }

    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    if (connections.IsConfigured)
    {
        return ActivatorUtilities.CreateInstance<DbPriceOfferRepository>(sp);
    }

    return new MigrationPriceOfferRepository();
});
builder.Services.AddSingleton<IPriceLookupService, RepositoryPriceLookupService>();
builder.Services.AddSingleton<IPriceLookupParityReporter, PriceLookupParityReporter>();
builder.Services.AddSingleton<ICatalogStatusRepository>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    return connections.IsConfigured
        ? ActivatorUtilities.CreateInstance<DbCatalogStatusRepository>(sp)
        : new MigrationCatalogStatusRepository();
});
builder.Services.AddSingleton<ICatalogStatusService, CatalogStatusService>();
builder.Services.AddSingleton<ICatalogManufacturerRepository>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    return connections.IsConfigured
        ? ActivatorUtilities.CreateInstance<DbCatalogManufacturerRepository>(sp)
        : new MigrationCatalogManufacturerRepository();
});
builder.Services.AddSingleton<ICatalogManufacturerService, CatalogManufacturerService>();
builder.Services.AddSingleton<ICatalogVehicleCacheRepository>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    return connections.IsConfigured
        ? ActivatorUtilities.CreateInstance<DbCatalogVehicleCacheRepository>(sp)
        : new MigrationCatalogVehicleCacheRepository();
});
builder.Services.AddSingleton<ICatalogVehicleCacheService, CatalogVehicleCacheService>();
builder.Services.AddSingleton<ICatalogOfflineCacheRepository>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    return connections.IsConfigured
        ? ActivatorUtilities.CreateInstance<DbCatalogOfflineCacheRepository>(sp)
        : new MigrationCatalogOfflineCacheRepository();
});
builder.Services.AddSingleton<ICatalogOfflineCacheService, CatalogOfflineCacheService>();
builder.Services.AddSingleton<EcomAE.Platform.Storefront.IStorefrontFitmentService, EcomAE.Platform.Storefront.StorefrontFitmentService>();
builder.Services.AddHttpClient(nameof(EcomAE.Platform.Storefront.StorefrontFitmentService))
    .ConfigureHttpClient(c => c.Timeout = TimeSpan.FromSeconds(20));
builder.Services.AddSingleton<EcomAE.Platform.Storefront.IStorefrontSkuMediaService, EcomAE.Platform.Storefront.StorefrontSkuMediaService>();
builder.Services.AddSingleton<ICatalogBrandPartsRepository>(sp =>
{
    var connections = sp.GetRequiredService<ITenantDbConnectionFactory>();
    return connections.IsConfigured
        ? ActivatorUtilities.CreateInstance<DbCatalogBrandPartsRepository>(sp)
        : new MigrationCatalogBrandPartsRepository();
});
builder.Services.AddSingleton<ICatalogBrandPartsService, CatalogBrandPartsService>();
builder.Services.AddSingleton<ICatalogParityReporter, CatalogParityReporter>();
builder.Services.AddSingleton<IMigrationParityReporter, MigrationParityReporter>();
builder.Services.AddSingleton<IControlPanelParityReporter, ControlPanelParityReporter>();
builder.Services.AddSingleton<IErpParityReporter, ErpParityReporter>();
builder.Services.AddSingleton<IBosParityReporter, BosParityReporter>();
builder.Services.AddSingleton<IStorefrontParityReporter, StorefrontParityReporter>();
builder.Services.AddSingleton<ITenantWorkspaceParityReporter, TenantWorkspaceParityReporter>();
builder.Services.AddSingleton<IMigrationReadinessReporter, MigrationReadinessReporter>();
builder.Services.AddSingleton<IMigrationCutoverPlanner, MigrationCutoverPlanner>();
builder.Services.AddSingleton<IMigrationRouteCutoverPolicy, MigrationRouteCutoverPolicy>();
builder.Services.AddSingleton<IDataParityReporter, DataParityReporter>();
builder.Services.AddSingleton<ICutoverValidationReporter, CutoverValidationReporter>();
builder.Services.AddSingleton<IPhpReferenceModeReporter, PhpReferenceModeReporter>();
builder.Services.AddSingleton<IMigrationProgressReporter, MigrationProgressReporter>();
builder.Services.AddSingleton<ISurfaceParityReporter, SurfaceParityReporter>();
builder.Services.AddSingleton<IZeroPhpCompletionReporter, ZeroPhpCompletionReporter>();
builder.Services.AddSingleton<IPhpDecommissionReadinessReporter, PhpDecommissionReadinessReporter>();
builder.Services.AddSingleton<ILiveSurfaceLinkReporter, LiveSurfaceLinkReporter>();
builder.Services.AddSingleton<IMarketingPresentationLockReporter, MarketingPresentationLockReporter>();
builder.Services.AddSingleton<IAspNetZeroPhpPathReporter, AspNetZeroPhpPathReporter>();
builder.Services.AddSingleton<IOnPremisesParityReporter, OnPremisesParityReporter>();
builder.Services.AddSingleton<IBosAjaxWriteCatalog, BosAjaxWriteCatalog>();
builder.Services.AddSingleton<IBosAjaxWriteRegistryDryRun, BosAjaxWriteRegistryDryRun>();
builder.Services.AddSingleton<IBosAjaxMfaPolicyDryRun, BosAjaxMfaPolicyDryRun>();
builder.Services.AddSingleton<IBosAjaxDesignTokensDryRun, BosAjaxDesignTokensDryRun>();
builder.Services.AddSingleton<IBosAjaxCreditLimitDryRun, BosAjaxCreditLimitDryRun>();
builder.Services.AddSingleton<IBosAjaxRunAuditDryRun, BosAjaxRunAuditDryRun>();
builder.Services.AddSingleton<IBosAjaxSaveDryRun, BosAjaxSaveDryRun>();
builder.Services.AddSingleton<IBosAjaxUpdateDryRun, BosAjaxUpdateDryRun>();
builder.Services.AddSingleton<IBosAjaxDeleteDryRun, BosAjaxDeleteDryRun>();
builder.Services.AddSingleton<IBosAjaxGetTokensDryRun, BosAjaxGetTokensDryRun>();
builder.Services.AddSingleton<IBosAjaxSaveTokenDryRun, BosAjaxSaveTokenDryRun>();
builder.Services.AddSingleton<IBosAjaxPrefsGetDryRun, BosAjaxPrefsGetDryRun>();
builder.Services.AddSingleton<IBosAjaxPrefsSaveDryRun, BosAjaxPrefsSaveDryRun>();
builder.Services.AddSingleton<IBosAjaxStatusDryRun, BosAjaxStatusDryRun>();
builder.Services.AddSingleton<IBosAjaxRunAllDryRun, BosAjaxRunAllDryRun>();
builder.Services.AddSingleton<IBosAjaxSetLimitDryRun, BosAjaxSetLimitDryRun>();
builder.Services.AddSingleton<IBosAjaxOrderStatusDryRun, BosAjaxOrderStatusDryRun>();
builder.Services.AddSingleton<IBosAjaxCreateDryRun, BosAjaxCreateDryRun>();
builder.Services.AddSingleton<IBosAjaxApproveDryRun, BosAjaxApproveDryRun>();
builder.Services.AddSingleton<IBosAjaxKeyGenerateDryRun, BosAjaxKeyGenerateDryRun>();
builder.Services.AddSingleton<IBosAjaxKeyRevokeDryRun, BosAjaxKeyRevokeDryRun>();
builder.Services.AddSingleton<IBosAjaxCreateWaveDryRun, BosAjaxCreateWaveDryRun>();
builder.Services.AddSingleton<IBosAjaxSeedHsDryRun, BosAjaxSeedHsDryRun>();
builder.Services.AddSingleton<IBosAjaxGroupsDryRun, BosAjaxGroupsDryRun>();
builder.Services.AddSingleton<IBosAjaxGroupDryRun, BosAjaxGroupDryRun>();
builder.Services.AddSingleton<IBosAjaxSetRateDryRun, BosAjaxSetRateDryRun>();
builder.Services.AddSingleton<IBosAjaxSeedRatesDryRun, BosAjaxSeedRatesDryRun>();
builder.Services.AddSingleton<IBosAjaxProviderGetDryRun, BosAjaxProviderGetDryRun>();
builder.Services.AddSingleton<IBosAjaxProviderCreateDryRun, BosAjaxProviderCreateDryRun>();
builder.Services.AddSingleton<IBosAjaxProviderToggleDryRun, BosAjaxProviderToggleDryRun>();
builder.Services.AddSingleton<IBosAjaxProviderDeleteDryRun, BosAjaxProviderDeleteDryRun>();
builder.Services.AddSingleton<IBosAjaxCreateRunDryRun, BosAjaxCreateRunDryRun>();
builder.Services.AddSingleton<IBosAjaxApproveRunDryRun, BosAjaxApproveRunDryRun>();
builder.Services.AddSingleton<IBosAjaxRunDetailsDryRun, BosAjaxRunDetailsDryRun>();
builder.Services.AddSingleton<IBosAjaxProfileCreateDryRun, BosAjaxProfileCreateDryRun>();
builder.Services.AddSingleton<IBosAjaxAddInvoiceDryRun, BosAjaxAddInvoiceDryRun>();
builder.Services.AddSingleton<IBosAjaxUpdateStatusDryRun, BosAjaxUpdateStatusDryRun>();
builder.Services.AddSingleton<IBosAjaxRmaCreateDryRun, BosAjaxRmaCreateDryRun>();
builder.Services.AddSingleton<IBosAjaxRmaTransitionDryRun, BosAjaxRmaTransitionDryRun>();
builder.Services.AddSingleton<IBosAjaxRmaListDryRun, BosAjaxRmaListDryRun>();
builder.Services.AddSingleton<IBosAjaxRmaDetailDryRun, BosAjaxRmaDetailDryRun>();
builder.Services.AddSingleton<IBosAjaxSeedDryRun, BosAjaxSeedDryRun>();
builder.Services.AddSingleton<IBosAjaxCreateGroupDryRun, BosAjaxCreateGroupDryRun>();
builder.Services.AddSingleton<IBosAjaxMembersDryRun, BosAjaxMembersDryRun>();
builder.Services.AddSingleton<IBosAjaxAddMemberDryRun, BosAjaxAddMemberDryRun>();
builder.Services.AddSingleton<IBosAjaxFoldersDryRun, BosAjaxFoldersDryRun>();
builder.Services.AddSingleton<IBosAjaxCreateFolderDryRun, BosAjaxCreateFolderDryRun>();
builder.Services.AddSingleton<IBosAjaxPlansDryRun, BosAjaxPlansDryRun>();
builder.Services.AddSingleton<IBosAjaxCreatePlanDryRun, BosAjaxCreatePlanDryRun>();
builder.Services.AddSingleton<IBosAjaxInvoicesDryRun, BosAjaxInvoicesDryRun>();
builder.Services.AddSingleton<IBosAjaxControlsDryRun, BosAjaxControlsDryRun>();
builder.Services.AddSingleton<IBosAjaxUpdateControlDryRun, BosAjaxUpdateControlDryRun>();
builder.Services.AddSingleton<IBosAjaxAddEvidenceDryRun, BosAjaxAddEvidenceDryRun>();
builder.Services.AddSingleton<IBosAjaxEvidenceDryRun, BosAjaxEvidenceDryRun>();
builder.Services.AddSingleton<IBosAjaxCreatePolicyDryRun, BosAjaxCreatePolicyDryRun>();
builder.Services.AddSingleton<ICpPosOpenSessionDryRun, CpPosOpenSessionDryRun>();
builder.Services.AddSingleton<ICpPosCloseSessionDryRun, CpPosCloseSessionDryRun>();
builder.Services.AddSingleton<ICpPosCompleteSaleDryRun, CpPosCompleteSaleDryRun>();
builder.Services.AddSingleton<ICpPosSaveSettingsDryRun, CpPosSaveSettingsDryRun>();
builder.Services.AddSingleton<ICpPortalSaveSettingsDryRun, CpPortalSaveSettingsDryRun>();
builder.Services.AddSingleton<ICpPortalDeploySiteDryRun, CpPortalDeploySiteDryRun>();
builder.Services.AddSingleton<ICpCrmActionDryRun, CpCrmActionDryRun>();
builder.Services.AddSingleton<ICpModuleAjaxWriteCatalog, CpModuleAjaxWriteCatalog>();
builder.Services.AddSingleton<ICpModuleAjaxWriteRegistryDryRun, CpModuleAjaxWriteRegistryDryRun>();
builder.Services.AddSingleton<ICpModuleAjaxWriteDedicatedDryRun, CpModuleAjaxWriteDedicatedDryRun>();
builder.Services.AddSingleton<IOnPremisesActivateLicenseCliDryRun, OnPremisesActivateLicenseCliDryRun>();
builder.Services.AddSingleton<IOnPremisesHealthCheckPackDryRun, OnPremisesHealthCheckPackDryRun>();
builder.Services.AddSingleton<IOnPremisesHealthDryRun, OnPremisesHealthDryRun>();
builder.Services.AddSingleton<IOnPremisesLicenseActivateDryRun, OnPremisesLicenseActivateDryRun>();
builder.Services.AddSingleton<IErpAjaxWriteCatalog, ErpAjaxWriteCatalog>();
builder.Services.AddSingleton<IErpAjaxWriteRegistryDryRun, ErpAjaxWriteRegistryDryRun>();
builder.Services.AddSingleton<IOnPremisesSetupWizardDryRun, OnPremisesSetupWizardDryRun>();
builder.Services.AddSingleton<IOnPremisesBackupDryRun, OnPremisesBackupDryRun>();
builder.Services.AddSingleton<IErpEditLockAcquireDryRun, ErpEditLockAcquireDryRun>();
builder.Services.AddSingleton<IErpEditLockHeartbeatDryRun, ErpEditLockHeartbeatDryRun>();
builder.Services.AddSingleton<IErpEditLockReleaseDryRun, ErpEditLockReleaseDryRun>();
builder.Services.AddSingleton<IErpPresenceHeartbeatDryRun, ErpPresenceHeartbeatDryRun>();
builder.Services.AddSingleton<IErpBosComplianceAddObligationDryRun, ErpBosComplianceAddObligationDryRun>();
builder.Services.AddSingleton<IErpBosComplianceDisableObligationDryRun, ErpBosComplianceDisableObligationDryRun>();
builder.Services.AddSingleton<IErpBosComplianceFileDryRun, ErpBosComplianceFileDryRun>();
builder.Services.AddSingleton<IErpBosComplianceSaveRetentionDryRun, ErpBosComplianceSaveRetentionDryRun>();
builder.Services.AddSingleton<IErpBosWfSaveRuleDryRun, ErpBosWfSaveRuleDryRun>();
builder.Services.AddSingleton<IErpBosWfDisableRuleDryRun, ErpBosWfDisableRuleDryRun>();
builder.Services.AddSingleton<IErpBosWfDecideDryRun, ErpBosWfDecideDryRun>();
builder.Services.AddSingleton<IErpBosWfRaiseTestDryRun, ErpBosWfRaiseTestDryRun>();
builder.Services.AddSingleton<IErpBosIntelToggleControlDryRun, ErpBosIntelToggleControlDryRun>();
builder.Services.AddSingleton<IErpBosVatRefundSaveDryRun, ErpBosVatRefundSaveDryRun>();
builder.Services.AddSingleton<IErpBosVatRefundStatusDryRun, ErpBosVatRefundStatusDryRun>();
builder.Services.AddSingleton<IErpOplParamsSaveDryRun, ErpOplParamsSaveDryRun>();
builder.Services.AddSingleton<IErpOplSetStatusDryRun, ErpOplSetStatusDryRun>();
builder.Services.AddSingleton<IErpOplConfirmAllDryRun, ErpOplConfirmAllDryRun>();
builder.Services.AddSingleton<IErpOplCreatePosDryRun, ErpOplCreatePosDryRun>();
builder.Services.AddSingleton<IErpPfProcessSaveDryRun, ErpPfProcessSaveDryRun>();
builder.Services.AddSingleton<IErpPfStepSaveDryRun, ErpPfStepSaveDryRun>();
builder.Services.AddSingleton<IErpPfStepDeleteDryRun, ErpPfStepDeleteDryRun>();
builder.Services.AddSingleton<IErpPfCaseStartDryRun, ErpPfCaseStartDryRun>();
builder.Services.AddSingleton<IErpPfCaseActDryRun, ErpPfCaseActDryRun>();
builder.Services.AddSingleton<IErpSubGenerateDryRun, ErpSubGenerateDryRun>();
builder.Services.AddSingleton<IErpSubInvoicePaidDryRun, ErpSubInvoicePaidDryRun>();
builder.Services.AddSingleton<IErpCtrStatusDryRun, ErpCtrStatusDryRun>();
builder.Services.AddSingleton<IErpCtrSignDryRun, ErpCtrSignDryRun>();
builder.Services.AddSingleton<IErpCollCasePromiseDryRun, ErpCollCasePromiseDryRun>();
builder.Services.AddSingleton<IErpCollActivityLogDryRun, ErpCollActivityLogDryRun>();
builder.Services.AddSingleton<IErpCollDunningRunDryRun, ErpCollDunningRunDryRun>();
builder.Services.AddSingleton<IErpProcCategorySaveDryRun, ErpProcCategorySaveDryRun>();
builder.Services.AddSingleton<IErpProcPolicySaveDryRun, ErpProcPolicySaveDryRun>();
builder.Services.AddSingleton<IErpProcReqAddLineDryRun, ErpProcReqAddLineDryRun>();
builder.Services.AddSingleton<IErpProcReqConvertDryRun, ErpProcReqConvertDryRun>();
builder.Services.AddSingleton<IErpBplanSaveDryRun, ErpBplanSaveDryRun>();
builder.Services.AddSingleton<IErpBplanAdvanceDryRun, ErpBplanAdvanceDryRun>();
builder.Services.AddSingleton<IErpAmlKycSaveDryRun, ErpAmlKycSaveDryRun>();
builder.Services.AddSingleton<IErpAmlAlertStatusDryRun, ErpAmlAlertStatusDryRun>();
builder.Services.AddSingleton<IErpAmlSettingsSaveDryRun, ErpAmlSettingsSaveDryRun>();
builder.Services.AddSingleton<IErpBankImportDryRun, ErpBankImportDryRun>();
builder.Services.AddSingleton<IErpBankReconcileDryRun, ErpBankReconcileDryRun>();
builder.Services.AddSingleton<IErpFxPostRevaluationDryRun, ErpFxPostRevaluationDryRun>();
builder.Services.AddSingleton<IErpSupplierPaymentDryRun, ErpSupplierPaymentDryRun>();
builder.Services.AddSingleton<IErpInvSyncWarehousesDryRun, ErpInvSyncWarehousesDryRun>();
builder.Services.AddSingleton<IErpInvCreateWarehouseDryRun, ErpInvCreateWarehouseDryRun>();
builder.Services.AddSingleton<IErpInvCreateItemDryRun, ErpInvCreateItemDryRun>();
builder.Services.AddSingleton<IErpInvSetReorderLevelDryRun, ErpInvSetReorderLevelDryRun>();
builder.Services.AddSingleton<IErpInvRecordMovementDryRun, ErpInvRecordMovementDryRun>();
builder.Services.AddSingleton<IErpInvScanLookupDryRun, ErpInvScanLookupDryRun>();
builder.Services.AddSingleton<IErpInvTransferDryRun, ErpInvTransferDryRun>();
builder.Services.AddSingleton<IErpInvImportCsvDryRun, ErpInvImportCsvDryRun>();
builder.Services.AddSingleton<IErpInvRunClosingDryRun, ErpInvRunClosingDryRun>();
builder.Services.AddSingleton<IErpHrEmpSaveDryRun, ErpHrEmpSaveDryRun>();
builder.Services.AddSingleton<IErpHrAttendanceDryRun, ErpHrAttendanceDryRun>();
builder.Services.AddSingleton<IErpHrLeaveRequestDryRun, ErpHrLeaveRequestDryRun>();
builder.Services.AddSingleton<IErpHrLeaveStatusDryRun, ErpHrLeaveStatusDryRun>();
builder.Services.AddSingleton<IErpHrExpenseSaveDryRun, ErpHrExpenseSaveDryRun>();
builder.Services.AddSingleton<IErpHrExpenseStatusDryRun, ErpHrExpenseStatusDryRun>();
builder.Services.AddSingleton<IErpHrUpdateDaysDryRun, ErpHrUpdateDaysDryRun>();
builder.Services.AddSingleton<IErpHrPayrollRunDryRun, ErpHrPayrollRunDryRun>();
builder.Services.AddSingleton<IErpEinvoiceCreateDryRun, ErpEinvoiceCreateDryRun>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpEinvoiceProfileWriteService, EcomAE.Platform.Erp.ErpEinvoiceProfileWriteService>();
builder.Services.AddSingleton<IErpEinvoiceSaveSellerDryRun, ErpEinvoiceSaveSellerDryRun>();
builder.Services.AddSingleton<IErpEinvoiceSaveBuyerDryRun, ErpEinvoiceSaveBuyerDryRun>();
builder.Services.AddSingleton<IErpEinvoiceSaveAspDryRun, ErpEinvoiceSaveAspDryRun>();
builder.Services.AddSingleton<IErpEinvoiceSubmitDryRun, ErpEinvoiceSubmitDryRun>();
builder.Services.AddSingleton<IErpEinvoiceCreditNoteDryRun, ErpEinvoiceCreditNoteDryRun>();
builder.Services.AddSingleton<IErpEinvoicePollAspDryRun, ErpEinvoicePollAspDryRun>();
builder.Services.AddSingleton<IErpExternalReportingFetchDryRun, ErpExternalReportingFetchDryRun>();
builder.Services.AddSingleton<IErpExternalReportingPackCache, ErpExternalReportingPackCache>();
builder.Services.AddSingleton<ErpExternalReportingFormService>();
builder.Services.AddSingleton<IErpOrderFulfillmentBootstrapDryRun, ErpOrderFulfillmentBootstrapDryRun>();
builder.Services.AddSingleton<IErpOrderFulfillmentStatusDryRun, ErpOrderFulfillmentStatusDryRun>();
builder.Services.AddSingleton<IErpOrderFulfillmentSyncDryRun, ErpOrderFulfillmentSyncDryRun>();
builder.Services.AddSingleton<IErpOrderFulfillmentPostPoDryRun, ErpOrderFulfillmentPostPoDryRun>();
builder.Services.AddSingleton<IErpOrderFulfillmentPostSalesDryRun, ErpOrderFulfillmentPostSalesDryRun>();
builder.Services.AddSingleton<IErpOrderFulfillmentAutoPostDryRun, ErpOrderFulfillmentAutoPostDryRun>();
builder.Services.AddSingleton<IErpOrderFulfillmentSwapSupplierDryRun, ErpOrderFulfillmentSwapSupplierDryRun>();
builder.Services.AddSingleton<IErpPmSaveDryRun, ErpPmSaveDryRun>();
builder.Services.AddSingleton<IErpPmToggleDryRun, ErpPmToggleDryRun>();
builder.Services.AddSingleton<IErpPmBudgetSaveDryRun, ErpPmBudgetSaveDryRun>();
builder.Services.AddSingleton<IErpPmBudgetLineSaveDryRun, ErpPmBudgetLineSaveDryRun>();
builder.Services.AddSingleton<IErpPmListingSaveDryRun, ErpPmListingSaveDryRun>();
builder.Services.AddSingleton<IErpPmListingAttachDryRun, ErpPmListingAttachDryRun>();
builder.Services.AddSingleton<IErpPmChequeSaveDryRun, ErpPmChequeSaveDryRun>();
builder.Services.AddSingleton<IErpMfgrWcSaveDryRun, ErpMfgrWcSaveDryRun>();
builder.Services.AddSingleton<IErpMfgrRouteSaveDryRun, ErpMfgrRouteSaveDryRun>();
builder.Services.AddSingleton<IErpMfgrMrpRunDryRun, ErpMfgrMrpRunDryRun>();
builder.Services.AddSingleton<IErpMfgrPlannedFirmDryRun, ErpMfgrPlannedFirmDryRun>();
builder.Services.AddSingleton<IErpQmPlanSaveDryRun, ErpQmPlanSaveDryRun>();
builder.Services.AddSingleton<IErpQmTestAddDryRun, ErpQmTestAddDryRun>();
builder.Services.AddSingleton<IErpQmOrderCreateDryRun, ErpQmOrderCreateDryRun>();
builder.Services.AddSingleton<IErpQmOrderRecordDryRun, ErpQmOrderRecordDryRun>();
builder.Services.AddSingleton<IErpQmNcrCreateDryRun, ErpQmNcrCreateDryRun>();
builder.Services.AddSingleton<IErpQmNcrUpdateDryRun, ErpQmNcrUpdateDryRun>();
builder.Services.AddSingleton<IErpRbacPrivSaveDryRun, ErpRbacPrivSaveDryRun>();
builder.Services.AddSingleton<IErpRbacDutySaveDryRun, ErpRbacDutySaveDryRun>();
builder.Services.AddSingleton<IErpRbacDutyPrivDryRun, ErpRbacDutyPrivDryRun>();
builder.Services.AddSingleton<IStorefrontNewsletterSubscribeDryRun, StorefrontNewsletterSubscribeDryRun>();
builder.Services.AddSingleton<IStorefrontAddEvaluationDryRun, StorefrontAddEvaluationDryRun>();
builder.Services.AddSingleton<IStorefrontCreateOperationDryRun, StorefrontCreateOperationDryRun>();
builder.Services.AddSingleton<IStorefrontCheckOrderNotAuthorizedDryRun, StorefrontCheckOrderNotAuthorizedDryRun>();
builder.Services.AddSingleton<IStorefrontSetUserOptionDryRun, StorefrontSetUserOptionDryRun>();
builder.Services.AddSingleton<IErpPeriodLogDryRun, ErpPeriodLogDryRun>();
builder.Services.AddSingleton<IErpOplAutoplanDryRun, ErpOplAutoplanDryRun>();
builder.Services.AddSingleton<IErpOplSeedDemoDryRun, ErpOplSeedDemoDryRun>();
builder.Services.AddSingleton<IErpOplClearDemoDryRun, ErpOplClearDemoDryRun>();
builder.Services.AddSingleton<IErpPfSetDeptHeadDryRun, ErpPfSetDeptHeadDryRun>();
builder.Services.AddSingleton<IErpPfCaseReassignDryRun, ErpPfCaseReassignDryRun>();
builder.Services.AddSingleton<IErpPfCaseCancelDryRun, ErpPfCaseCancelDryRun>();
builder.Services.AddSingleton<IErpPfSeedDemoDryRun, ErpPfSeedDemoDryRun>();
builder.Services.AddSingleton<IErpPfClearDemoDryRun, ErpPfClearDemoDryRun>();
builder.Services.AddSingleton<IErpPfSyncOrdersDryRun, ErpPfSyncOrdersDryRun>();
builder.Services.AddSingleton<IErpDemoSeedSalesDryRun, ErpDemoSeedSalesDryRun>();
builder.Services.AddSingleton<IErpDemoClearSalesDryRun, ErpDemoClearSalesDryRun>();
builder.Services.AddSingleton<IErpCtrOcrDryRun, ErpCtrOcrDryRun>();
builder.Services.AddSingleton<IErpDocxSaveDryRun, ErpDocxSaveDryRun>();
builder.Services.AddSingleton<IErpDocxDeleteDryRun, ErpDocxDeleteDryRun>();
builder.Services.AddSingleton<IErpDocxRunRemindersDryRun, ErpDocxRunRemindersDryRun>();
builder.Services.AddSingleton<IErpInsSaveDryRun, ErpInsSaveDryRun>();
builder.Services.AddSingleton<IErpInsDeleteDryRun, ErpInsDeleteDryRun>();
builder.Services.AddSingleton<IErpInsDocAddDryRun, ErpInsDocAddDryRun>();
builder.Services.AddSingleton<IErpInsDocDeleteDryRun, ErpInsDocDeleteDryRun>();
builder.Services.AddSingleton<IErpInsClaimAddDryRun, ErpInsClaimAddDryRun>();
builder.Services.AddSingleton<IErpFinPeriodsGenerateDryRun, ErpFinPeriodsGenerateDryRun>();
builder.Services.AddSingleton<IErpFinFxRevalueDryRun, ErpFinFxRevalueDryRun>();
builder.Services.AddSingleton<IErpFinAllocSaveDryRun, ErpFinAllocSaveDryRun>();
builder.Services.AddSingleton<IErpFinAllocRunDryRun, ErpFinAllocRunDryRun>();
builder.Services.AddSingleton<IErpFinAccrualSaveDryRun, ErpFinAccrualSaveDryRun>();
builder.Services.AddSingleton<IErpCollHoldSetDryRun, ErpCollHoldSetDryRun>();
builder.Services.AddSingleton<IErpBplanLineAddDryRun, ErpBplanLineAddDryRun>();
builder.Services.AddSingleton<IErpBplanPositionAddDryRun, ErpBplanPositionAddDryRun>();
builder.Services.AddSingleton<IErpHrtJobSaveDryRun, ErpHrtJobSaveDryRun>();
builder.Services.AddSingleton<IErpHrtApplicantAddDryRun, ErpHrtApplicantAddDryRun>();
builder.Services.AddSingleton<IErpHrtApplicantStageDryRun, ErpHrtApplicantStageDryRun>();
builder.Services.AddSingleton<IErpHrtReviewSaveDryRun, ErpHrtReviewSaveDryRun>();
builder.Services.AddSingleton<IErpHrtGoalAddDryRun, ErpHrtGoalAddDryRun>();
builder.Services.AddSingleton<IErpHrtReviewFinalizeDryRun, ErpHrtReviewFinalizeDryRun>();
builder.Services.AddSingleton<IErpCftForecastSaveDryRun, ErpCftForecastSaveDryRun>();
builder.Services.AddSingleton<IErpCftLineAddDryRun, ErpCftLineAddDryRun>();
builder.Services.AddSingleton<IErpCftInstrumentSaveDryRun, ErpCftInstrumentSaveDryRun>();
builder.Services.AddSingleton<IErpCftInstrumentStatusDryRun, ErpCftInstrumentStatusDryRun>();
builder.Services.AddSingleton<IErpWhtCodeSaveDryRun, ErpWhtCodeSaveDryRun>();
builder.Services.AddSingleton<IErpWhtRecordDryRun, ErpWhtRecordDryRun>();
builder.Services.AddSingleton<IErpWhtCertificateDryRun, ErpWhtCertificateDryRun>();
builder.Services.AddSingleton<IErpWhtSettleDryRun, ErpWhtSettleDryRun>();
builder.Services.AddSingleton<IErpMultiEntityWriteDryRun, ErpMultiEntityWriteDryRun>();
builder.Services.AddSingleton<IErpMultiCurrencyGlWriteDryRun, ErpMultiCurrencyGlWriteDryRun>();
builder.Services.AddSingleton<IErpConcurrencyStatusDryRun, ErpConcurrencyStatusDryRun>();
builder.Services.AddSingleton<IErpSettlementOpenDocsDryRun, ErpSettlementOpenDocsDryRun>();
builder.Services.AddSingleton<IErpDashboardDryRun, ErpDashboardDryRun>();
builder.Services.AddSingleton<IErpCommandCenterDryRun, ErpCommandCenterDryRun>();
builder.Services.AddSingleton<IErpCcKpiTilesDryRun, ErpCcKpiTilesDryRun>();
builder.Services.AddSingleton<IErpCcApprovalQueueDryRun, ErpCcApprovalQueueDryRun>();
builder.Services.AddSingleton<IErpPeriodListDryRun, ErpPeriodListDryRun>();
builder.Services.AddSingleton<IErpPeriodChecklistDryRun, ErpPeriodChecklistDryRun>();
builder.Services.AddSingleton<IErpPeriodSummaryDryRun, ErpPeriodSummaryDryRun>();
builder.Services.AddSingleton<IErpFxRevaluationPreviewDryRun, ErpFxRevaluationPreviewDryRun>();
builder.Services.AddSingleton<IErpBosComplianceFetchDryRun, ErpBosComplianceFetchDryRun>();
builder.Services.AddSingleton<IErpRtlAssortmentSetDryRun, ErpRtlAssortmentSetDryRun>();
builder.Services.AddSingleton<IErpRtlDiscountSaveDryRun, ErpRtlDiscountSaveDryRun>();
builder.Services.AddSingleton<IErpRtlPosSaleDryRun, ErpRtlPosSaleDryRun>();
builder.Services.AddSingleton<IErpInsClaimStatusDryRun, ErpInsClaimStatusDryRun>();
builder.Services.AddSingleton<IErpPrjSaveDryRun, ErpPrjSaveDryRun>();
builder.Services.AddSingleton<IErpPrjTaskSaveDryRun, ErpPrjTaskSaveDryRun>();
builder.Services.AddSingleton<IErpPrjLogTimeDryRun, ErpPrjLogTimeDryRun>();
builder.Services.AddSingleton<IErpConsEntitySaveDryRun, ErpConsEntitySaveDryRun>();
builder.Services.AddSingleton<IErpConsEntityDeleteDryRun, ErpConsEntityDeleteDryRun>();
builder.Services.AddSingleton<IErpConsFiguresSaveDryRun, ErpConsFiguresSaveDryRun>();
builder.Services.AddSingleton<IErpConsIcSaveDryRun, ErpConsIcSaveDryRun>();
builder.Services.AddSingleton<IErpConsIcDeleteDryRun, ErpConsIcDeleteDryRun>();
builder.Services.AddSingleton<IErpMfgBomSaveDryRun, ErpMfgBomSaveDryRun>();
builder.Services.AddSingleton<IErpMfgWoCreateDryRun, ErpMfgWoCreateDryRun>();
builder.Services.AddSingleton<IErpMfgWoIssueDryRun, ErpMfgWoIssueDryRun>();
builder.Services.AddSingleton<IErpMfgWoCompleteDryRun, ErpMfgWoCompleteDryRun>();
builder.Services.AddSingleton<IErpPayrollGenerateDryRun, ErpPayrollGenerateDryRun>();
builder.Services.AddSingleton<IErpPayrollApproveDryRun, ErpPayrollApproveDryRun>();
builder.Services.AddSingleton<IErpPayrollPayDryRun, ErpPayrollPayDryRun>();
builder.Services.AddSingleton<IErpPayrollUpdateDaysDryRun, ErpPayrollUpdateDaysDryRun>();
builder.Services.AddSingleton<IErpUaeTaxFtaFetchDryRun, ErpUaeTaxFtaFetchDryRun>();
builder.Services.AddSingleton<IErpAmlCheckDryRun, ErpAmlCheckDryRun>();
builder.Services.AddSingleton<IErpAmlReportGenerateDryRun, ErpAmlReportGenerateDryRun>();
builder.Services.AddSingleton<IErpAmlSeedRulesDryRun, ErpAmlSeedRulesDryRun>();
builder.Services.AddSingleton<IErpUaeTaxLegislationRegenSummariesDryRun, ErpUaeTaxLegislationRegenSummariesDryRun>();
builder.Services.AddSingleton<IErpUaeTaxLegislationAskDryRun, ErpUaeTaxLegislationAskDryRun>();
builder.Services.AddSingleton<IErpUaeTaxSaveCtAdjustmentsDryRun, ErpUaeTaxSaveCtAdjustmentsDryRun>();
builder.Services.AddSingleton<IErpUaeTaxLegislationChecklistSetDryRun, ErpUaeTaxLegislationChecklistSetDryRun>();
builder.Services.AddSingleton<IErpInvoiceSaveDryRun, ErpInvoiceSaveDryRun>();
builder.Services.AddSingleton<IErpInvoiceListDryRun, ErpInvoiceListDryRun>();
builder.Services.AddSingleton<IErpInvoiceFromOrderDryRun, ErpInvoiceFromOrderDryRun>();
builder.Services.AddSingleton<IErpAiQueryDryRun, ErpAiQueryDryRun>();
builder.Services.AddSingleton<IErpIntegrityScanDryRun, ErpIntegrityScanDryRun>();
builder.Services.AddSingleton<IErpIntegrityApplyFksDryRun, ErpIntegrityApplyFksDryRun>();
builder.Services.AddSingleton<IErpFaCreateAssetDryRun, ErpFaCreateAssetDryRun>();
builder.Services.AddSingleton<IErpFaRunDepreciationDryRun, ErpFaRunDepreciationDryRun>();
builder.Services.AddSingleton<IErpOpeningCreateBatchDryRun, ErpOpeningCreateBatchDryRun>();
builder.Services.AddSingleton<IErpOpeningAddCoaLineDryRun, ErpOpeningAddCoaLineDryRun>();
builder.Services.AddSingleton<IErpOpeningAddInvLineDryRun, ErpOpeningAddInvLineDryRun>();
builder.Services.AddSingleton<IErpOpeningPostBatchDryRun, ErpOpeningPostBatchDryRun>();
builder.Services.AddSingleton<IErpSaveRfqDryRun, ErpSaveRfqDryRun>();
builder.Services.AddSingleton<IErpDeliveryNoteCreateDryRun, ErpDeliveryNoteCreateDryRun>();
builder.Services.AddSingleton<IErpSaveContactDryRun, ErpSaveContactDryRun>();
builder.Services.AddSingleton<IErpSyncContactsDryRun, ErpSyncContactsDryRun>();
builder.Services.AddSingleton<IErpDocumentUploadDryRun, ErpDocumentUploadDryRun>();
builder.Services.AddSingleton<IErpDocumentDeleteDryRun, ErpDocumentDeleteDryRun>();
builder.Services.AddSingleton<IErpSaveCompanyDryRun, ErpSaveCompanyDryRun>();
builder.Services.AddSingleton<IErpSaveTemplateDryRun, ErpSaveTemplateDryRun>();
builder.Services.AddSingleton<IErpUploadLogoDryRun, ErpUploadLogoDryRun>();
builder.Services.AddSingleton<IErpUploadAttachmentDryRun, ErpUploadAttachmentDryRun>();
builder.Services.AddSingleton<IErpDeleteAttachmentDryRun, ErpDeleteAttachmentDryRun>();
builder.Services.AddSingleton<IErpSyncEinvoiceSellerDryRun, ErpSyncEinvoiceSellerDryRun>();
builder.Services.AddSingleton<IErpExpenseReportSaveDryRun, ErpExpenseReportSaveDryRun>();
builder.Services.AddSingleton<IErpPoSaveDryRun, ErpPoSaveDryRun>();
builder.Services.AddSingleton<IErpPoStatusDryRun, ErpPoStatusDryRun>();
builder.Services.AddSingleton<IErpPoReceiveLinesDryRun, ErpPoReceiveLinesDryRun>();
builder.Services.AddSingleton<IErpPoToInvoiceDryRun, ErpPoToInvoiceDryRun>();
builder.Services.AddSingleton<IErpCustomerCreateDryRun, ErpCustomerCreateDryRun>();
builder.Services.AddSingleton<IErpSoSaveDryRun, ErpSoSaveDryRun>();
// Live ERP writes (PHP epc_erp_vouchers.php parity) — used when confirmWrites=true.
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWriteConnectionFactory, EcomAE.Platform.Erp.ErpWriteConnectionFactory>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpVoucherNumberService, EcomAE.Platform.Erp.ErpVoucherNumberService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpTaxAmountCalculator, EcomAE.Platform.Erp.ErpTaxAmountCalculator>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAuditLogWriter, EcomAE.Platform.Erp.ErpAuditLogWriter>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSalesOrderWriteService, EcomAE.Platform.Erp.ErpSalesOrderWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpGlPostingService, EcomAE.Platform.Erp.ErpGlPostingService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSettlementAllocationService, EcomAE.Platform.Erp.ErpSettlementAllocationService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAdvanceVatService, EcomAE.Platform.Erp.ErpAdvanceVatService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCashWriteService, EcomAE.Platform.Erp.ErpCashWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpGlLedgerWriteService, EcomAE.Platform.Erp.ErpGlLedgerWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpDocLifecycleWriteService, EcomAE.Platform.Erp.ErpDocLifecycleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSalesInvoiceWriteService, EcomAE.Platform.Erp.ErpSalesInvoiceWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPurchaseOrderWriteService, EcomAE.Platform.Erp.ErpPurchaseOrderWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPurchaseInvoiceWriteService, EcomAE.Platform.Erp.ErpPurchaseInvoiceWriteService>();
builder.Services.AddSingleton<IErpSoStatusDryRun, ErpSoStatusDryRun>();
builder.Services.AddSingleton<IErpSoToInvoiceDryRun, ErpSoToInvoiceDryRun>();
builder.Services.AddSingleton<IErpTransferVoucherDryRun, ErpTransferVoucherDryRun>();
builder.Services.AddSingleton<IErpPaymentBatchSaveDryRun, ErpPaymentBatchSaveDryRun>();
builder.Services.AddSingleton<IErpPettyCashSaveDryRun, ErpPettyCashSaveDryRun>();
builder.Services.AddSingleton<IErpAgendaSaveDryRun, ErpAgendaSaveDryRun>();
builder.Services.AddSingleton<IErpKbSaveDryRun, ErpKbSaveDryRun>();
builder.Services.AddSingleton<IErpMultiEntitySaveDryRun, ErpMultiEntitySaveDryRun>();
builder.Services.AddSingleton<IErpCsSaveDeclarationDryRun, ErpCsSaveDeclarationDryRun>();
builder.Services.AddSingleton<IErpCsSubmitDeclarationDryRun, ErpCsSubmitDeclarationDryRun>();
builder.Services.AddSingleton<IErpCsDeleteDeclarationDryRun, ErpCsDeleteDeclarationDryRun>();
builder.Services.AddSingleton<IErpCsListDeclarationsDryRun, ErpCsListDeclarationsDryRun>();
builder.Services.AddSingleton<IErpCsImportDeclarationPdfDryRun, ErpCsImportDeclarationPdfDryRun>();
builder.Services.AddSingleton<IErpShortcutListDryRun, ErpShortcutListDryRun>();
builder.Services.AddSingleton<IErpShortcutAddDryRun, ErpShortcutAddDryRun>();
builder.Services.AddSingleton<IErpShortcutDeleteDryRun, ErpShortcutDeleteDryRun>();
builder.Services.AddSingleton<IErpShortcutDeleteKeyDryRun, ErpShortcutDeleteKeyDryRun>();
builder.Services.AddSingleton<IErpShortcutResetDryRun, ErpShortcutResetDryRun>();
builder.Services.AddSingleton<IErpShortcutReorderDryRun, ErpShortcutReorderDryRun>();
builder.Services.AddSingleton<IErpErpFavAddDryRun, ErpErpFavAddDryRun>();
builder.Services.AddSingleton<IErpErpFavRemoveDryRun, ErpErpFavRemoveDryRun>();
builder.Services.AddSingleton<IErpErpGlobalSearchDryRun, ErpErpGlobalSearchDryRun>();
builder.Services.AddSingleton<IErpJwRepairCreateDryRun, ErpJwRepairCreateDryRun>();
        builder.Services.AddSingleton<IErpJwRepairUpdateStatusDryRun, ErpJwRepairUpdateStatusDryRun>();
        builder.Services.AddSingleton<IErpJwSeedSampleDataDryRun, ErpJwSeedSampleDataDryRun>();
        builder.Services.AddSingleton<IErpJwModuleSaveDryRun, ErpJwModuleSaveDryRun>();
builder.Services.AddSingleton<IErpAiAssistantQueryDryRun, ErpAiAssistantQueryDryRun>();
builder.Services.AddSingleton<IErpPrintDesignerSaveDryRun, ErpPrintDesignerSaveDryRun>();
builder.Services.AddSingleton<IErpWorkflowSaveDryRun, ErpWorkflowSaveDryRun>();
builder.Services.AddSingleton<IErpWorkflowRunDryRun, ErpWorkflowRunDryRun>();
builder.Services.AddSingleton<IErpAutomationActivateDryRun, ErpAutomationActivateDryRun>();
builder.Services.AddSingleton<IErpAutomationDeactivateDryRun, ErpAutomationDeactivateDryRun>();
builder.Services.AddSingleton<IErpAutomationInstallTemplateDryRun, ErpAutomationInstallTemplateDryRun>();
builder.Services.AddSingleton<IErpAutomationEnableCategoryDryRun, ErpAutomationEnableCategoryDryRun>();
builder.Services.AddSingleton<IErpAutomationTickDryRun, ErpAutomationTickDryRun>();
builder.Services.AddSingleton<IErpTenantConfigSaveDryRun, ErpTenantConfigSaveDryRun>();
builder.Services.AddSingleton<ICpLangSetIsCustomDryRun, CpLangSetIsCustomDryRun>();
builder.Services.AddSingleton<ICpLangSetIsErrorDryRun, CpLangSetIsErrorDryRun>();
builder.Services.AddSingleton<ICpLangSetSameDryRun, CpLangSetSameDryRun>();
builder.Services.AddSingleton<ICpLangSetUsedFoundDryRun, CpLangSetUsedFoundDryRun>();
builder.Services.AddSingleton<ICpLangSearchUsedFoundDryRun, CpLangSearchUsedFoundDryRun>();
builder.Services.AddSingleton<ICpVersionGetUpdatePackDryRun, CpVersionGetUpdatePackDryRun>();
builder.Services.AddSingleton<IStorefrontGetArticleListDryRun, StorefrontGetArticleListDryRun>();
builder.Services.AddSingleton<IStorefrontLoadReturnsDataDryRun, StorefrontLoadReturnsDataDryRun>();
builder.Services.AddSingleton<IErpErFormatSaveDryRun, ErpErFormatSaveDryRun>();
builder.Services.AddSingleton<IErpErFieldAddDryRun, ErpErFieldAddDryRun>();
builder.Services.AddSingleton<IErpPrjaBudgetSaveDryRun, ErpPrjaBudgetSaveDryRun>();
builder.Services.AddSingleton<IErpPrjaTxnAddDryRun, ErpPrjaTxnAddDryRun>();
builder.Services.AddSingleton<IErpPrjaRecognizeDryRun, ErpPrjaRecognizeDryRun>();
builder.Services.AddSingleton<IErpCostmItemSetDryRun, ErpCostmItemSetDryRun>();
builder.Services.AddSingleton<IErpCostmTxnAddDryRun, ErpCostmTxnAddDryRun>();
builder.Services.AddSingleton<IErpCostmCloseRunDryRun, ErpCostmCloseRunDryRun>();
builder.Services.AddSingleton<IErpIntgEntitySaveDryRun, ErpIntgEntitySaveDryRun>();
builder.Services.AddSingleton<IErpIntgSubSaveDryRun, ErpIntgSubSaveDryRun>();
builder.Services.AddSingleton<IErpIntgEventRaiseDryRun, ErpIntgEventRaiseDryRun>();
builder.Services.AddSingleton<IErpFyCreateDryRun, ErpFyCreateDryRun>();
builder.Services.AddSingleton<IErpFyCloseDryRun, ErpFyCloseDryRun>();
builder.Services.AddSingleton<IErpFyReopenDryRun, ErpFyReopenDryRun>();
builder.Services.AddSingleton<IErpFyPeriodStatusDryRun, ErpFyPeriodStatusDryRun>();
builder.Services.AddSingleton<IErpPltJobSaveDryRun, ErpPltJobSaveDryRun>();
builder.Services.AddSingleton<IErpPltJobRunDryRun, ErpPltJobRunDryRun>();
builder.Services.AddSingleton<IErpPltFeatureSaveDryRun, ErpPltFeatureSaveDryRun>();
builder.Services.AddSingleton<IErpOaPartySaveDryRun, ErpOaPartySaveDryRun>();
builder.Services.AddSingleton<IErpOaAddressSaveDryRun, ErpOaAddressSaveDryRun>();
builder.Services.AddSingleton<IErpOaContactSaveDryRun, ErpOaContactSaveDryRun>();
builder.Services.AddSingleton<IErpOaCalendarSaveDryRun, ErpOaCalendarSaveDryRun>();
builder.Services.AddSingleton<IErpOaHolidayAddDryRun, ErpOaHolidayAddDryRun>();
builder.Services.AddSingleton<IErpRbacRoleSaveDryRun, ErpRbacRoleSaveDryRun>();
builder.Services.AddSingleton<IErpRbacRoleDutyDryRun, ErpRbacRoleDutyDryRun>();
builder.Services.AddSingleton<IErpRbacUserRoleDryRun, ErpRbacUserRoleDryRun>();
builder.Services.AddSingleton<IErpRtlChannelSaveDryRun, ErpRtlChannelSaveDryRun>();
builder.Services.AddSingleton<ICpCreateSitemapDryRun, CpCreateSitemapDryRun>();
builder.Services.AddSingleton<ICpLangSaveTranslationDryRun, CpLangSaveTranslationDryRun>();
builder.Services.AddSingleton<ICpLangSaveDescriptionDryRun, CpLangSaveDescriptionDryRun>();
builder.Services.AddSingleton<ICpLangCreateStringDryRun, CpLangCreateStringDryRun>();
builder.Services.AddSingleton<ICpLangDeleteNotUsedDryRun, CpLangDeleteNotUsedDryRun>();
builder.Services.AddSingleton<ICpPacksDeleteDryRun, CpPacksDeleteDryRun>();
builder.Services.AddSingleton<ICpChannelsWriteDryRun, CpChannelsWriteDryRun>();
builder.Services.AddSingleton<ICpLogisticsWriteDryRun, CpLogisticsWriteDryRun>();
builder.Services.AddSingleton<ICpPaymentsWriteDryRun, CpPaymentsWriteDryRun>();
builder.Services.AddSingleton<ICpWorkshopWriteDryRun, CpWorkshopWriteDryRun>();
builder.Services.AddSingleton<ICpFulfillmentQueueWriteDryRun, CpFulfillmentQueueWriteDryRun>();
builder.Services.AddSingleton<ICpCollectionsDunningWriteDryRun, CpCollectionsDunningWriteDryRun>();
builder.Services.AddSingleton<ICpTemplatesActionsDryRun, CpTemplatesActionsDryRun>();
builder.Services.AddSingleton<ICpPriceReviewWriteDryRun, CpPriceReviewWriteDryRun>();
builder.Services.AddSingleton<ICpPriceReviewCreateCsvDryRun, CpPriceReviewCreateCsvDryRun>();
builder.Services.AddSingleton<ICpAccessoriesPhotosDryRun, CpAccessoriesPhotosDryRun>();
builder.Services.AddSingleton<ICpVersionClearUpdatesDryRun, CpVersionClearUpdatesDryRun>();
builder.Services.AddSingleton<IStorefrontBulkUploadProcessDryRun, StorefrontBulkUploadProcessDryRun>();
builder.Services.AddSingleton<EcomAE.Platform.Storefront.IStorefrontBulkUploadCheckService, EcomAE.Platform.Storefront.StorefrontBulkUploadCheckService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontBulkUploadHistoryWriteService, EcomAE.Platform.Storefront.StorefrontBulkUploadHistoryWriteService>();
builder.Services.AddSingleton<IStorefrontSetMyCityDryRun, StorefrontSetMyCityDryRun>();
builder.Services.AddSingleton<IStorefrontLoginSendCodeDryRun, StorefrontLoginSendCodeDryRun>();
builder.Services.AddSingleton<IStorefrontLoginCheckCodeDryRun, StorefrontLoginCheckCodeDryRun>();
builder.Services.AddSingleton<ICpReturnActionDryRun, CpReturnActionDryRun>();
builder.Services.AddSingleton<ICpSetUsersVinViewedDryRun, CpSetUsersVinViewedDryRun>();
builder.Services.AddSingleton<ICpSetUserCommentDryRun, CpSetUserCommentDryRun>();
builder.Services.AddSingleton<ICpPricesImportCsvDryRun, CpPricesImportCsvDryRun>();
builder.Services.AddSingleton<ICpPricesCompleteSessionDryRun, CpPricesCompleteSessionDryRun>();
builder.Services.AddSingleton<ISurfaceFieldParityReporter, SurfaceFieldParityReporter>();
builder.Services.AddSingleton<IUmapiUsageSummaryReporter, UmapiUsageSummaryReporter>();
builder.Services.AddSingleton<IPlatformJobsSummaryReporter, PlatformJobsSummaryReporter>();
builder.Services.AddHttpClient();
builder.Services.AddHttpClient(nameof(PhpWarehouseSearchBridge))
    .ConfigureHttpClient(client =>
    {
        // Progressive ajax_getProductsOfBunch can exceed 8s (supplier handlers).
        // Brands/offers GETs usually finish faster; one client covers both.
        client.Timeout = TimeSpan.FromSeconds(45);
        client.DefaultRequestHeaders.UserAgent.ParseAdd("EcomAE-PhpWarehouseBridge/1.0");
    })
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
    {
        // Loopback 127.0.0.1 + Host header must not follow off-box redirects to splash HTML.
        AllowAutoRedirect = false,
        UseCookies = false
    });
builder.Services.AddSingleton<PhpWarehouseSearchBridge>();
builder.Services.AddSingleton<ISurfaceDashboardSummaryReporter, SurfaceDashboardSummaryReporter>();builder.Services.AddSingleton<IStorefrontCartChangeCountNeedDryRun, StorefrontCartChangeCountNeedDryRun>();
builder.Services.AddSingleton<IStorefrontCartCheckForOrderDryRun, StorefrontCartCheckForOrderDryRun>();
builder.Services.AddSingleton<IStorefrontCartDeleteDryRun, StorefrontCartDeleteDryRun>();
builder.Services.AddSingleton<ICpOmsSetItemStatusDryRun, CpOmsSetItemStatusDryRun>();
builder.Services.AddSingleton<ICpOmsSetItemsStatusDryRun, CpOmsSetItemsStatusDryRun>();
builder.Services.AddSingleton<ICpOmsSendMessageDryRun, CpOmsSendMessageDryRun>();
builder.Services.AddSingleton<ICpOmsAddCommentDryRun, CpOmsAddCommentDryRun>();
builder.Services.AddSingleton<ICpOmsSetViewedDryRun, CpOmsSetViewedDryRun>();
builder.Services.AddSingleton<ICpOmsUpdateItemDryRun, CpOmsUpdateItemDryRun>();
builder.Services.AddSingleton<ICpOmsPayRefundDryRun, CpOmsPayRefundDryRun>();
builder.Services.AddSingleton<ICpOmsUpdateItemsDryRun, CpOmsUpdateItemsDryRun>();
builder.Services.AddSingleton<ICpOmsFulfillmentSetStageDryRun, CpOmsFulfillmentSetStageDryRun>();
builder.Services.AddSingleton<ICpOmsFulfillmentAdvanceDryRun, CpOmsFulfillmentAdvanceDryRun>();
builder.Services.AddSingleton<ICpOmsRefreshItemCostDryRun, CpOmsRefreshItemCostDryRun>();
builder.Services.AddSingleton<ICpFulfillmentQueueWriteDryRun, CpFulfillmentQueueWriteDryRun>();
builder.Services.AddSingleton<ICpCollectionsDunningWriteDryRun, CpCollectionsDunningWriteDryRun>();
builder.Services.AddSingleton<ICpCustomShippingWriteDryRun, CpCustomShippingWriteDryRun>();
builder.Services.AddSingleton<IErpPurchaseFromOrderDryRun, ErpPurchaseFromOrderDryRun>();
builder.Services.AddSingleton<IErpCcySetRateDryRun, ErpCcySetRateDryRun>();
builder.Services.AddSingleton<IErpPeriodSoftCloseDryRun, ErpPeriodSoftCloseDryRun>();
builder.Services.AddSingleton<IErpPeriodLockDryRun, ErpPeriodLockDryRun>();
builder.Services.AddSingleton<IErpCustomerSettlementDryRun, ErpCustomerSettlementDryRun>();
builder.Services.AddSingleton<IErpSupplierSettlementDryRun, ErpSupplierSettlementDryRun>();
builder.Services.AddSingleton<IErpFiscalSetLockDryRun, ErpFiscalSetLockDryRun>();
builder.Services.AddSingleton<IErpPeriodReopenDryRun, ErpPeriodReopenDryRun>();
builder.Services.AddSingleton<IErpPurchaseAdjustmentDryRun, ErpPurchaseAdjustmentDryRun>();
builder.Services.AddSingleton<IErpOrderSettlementDryRun, ErpOrderSettlementDryRun>();
builder.Services.AddSingleton<IErpSyncSuppliersDryRun, ErpSyncSuppliersDryRun>();
builder.Services.AddSingleton<IErpGlPostSalesDryRun, ErpGlPostSalesDryRun>();
builder.Services.AddSingleton<IErpGlSyncUnpostedDryRun, ErpGlSyncUnpostedDryRun>();
builder.Services.AddSingleton<IErpWorkflowStatusDryRun, ErpWorkflowStatusDryRun>();
builder.Services.AddSingleton<IErpWorkflowCreateDryRun, ErpWorkflowCreateDryRun>();
builder.Services.AddSingleton<IErpMarketingCreateDryRun, ErpMarketingCreateDryRun>();
builder.Services.AddSingleton<IErpSubscriptionSaveDryRun, ErpSubscriptionSaveDryRun>();
builder.Services.AddSingleton<IErpContractSaveDryRun, ErpContractSaveDryRun>();
builder.Services.AddSingleton<IErpWmsReceiveDryRun, ErpWmsReceiveDryRun>();
builder.Services.AddSingleton<IErpWmsLocationSaveDryRun, ErpWmsLocationSaveDryRun>();
builder.Services.AddSingleton<IErpCollectionsCaseSaveDryRun, ErpCollectionsCaseSaveDryRun>();
builder.Services.AddSingleton<IErpProcReqSaveDryRun, ErpProcReqSaveDryRun>();
builder.Services.AddSingleton<IErpFinPeriodStatusDryRun, ErpFinPeriodStatusDryRun>();
builder.Services.AddSingleton<IErpWmsWaveCreateDryRun, ErpWmsWaveCreateDryRun>();
builder.Services.AddSingleton<IErpWmsWaveReleaseDryRun, ErpWmsWaveReleaseDryRun>();
builder.Services.AddSingleton<IErpWmsWorkCompleteDryRun, ErpWmsWorkCompleteDryRun>();
builder.Services.AddSingleton<IErpSubscriptionStatusDryRun, ErpSubscriptionStatusDryRun>();
builder.Services.AddSingleton<IErpCollectionsCaseStatusDryRun, ErpCollectionsCaseStatusDryRun>();
builder.Services.AddSingleton<IErpProcReqSubmitDryRun, ErpProcReqSubmitDryRun>();
builder.Services.AddSingleton<IErpProcReqDecisionDryRun, ErpProcReqDecisionDryRun>();
builder.Services.AddSingleton<IErpWmsLocationDeleteDryRun, ErpWmsLocationDeleteDryRun>();
builder.Services.AddSingleton<ICpOmsSetCourierDryRun, CpOmsSetCourierDryRun>();
builder.Services.AddSingleton<ICpOmsDeleteOrdersDryRun, CpOmsDeleteOrdersDryRun>();
builder.Services.AddSingleton<IErpCashVoucherAmendDryRun, ErpCashVoucherAmendDryRun>();
builder.Services.AddSingleton<IErpCashVoucherVoidDryRun, ErpCashVoucherVoidDryRun>();
builder.Services.AddSingleton<IErpCashEntryCreateDryRun, ErpCashEntryCreateDryRun>();
builder.Services.AddSingleton<IErpReceiptVoucherDryRun, ErpReceiptVoucherDryRun>();
builder.Services.AddSingleton<IErpPaymentVoucherDryRun, ErpPaymentVoucherDryRun>();
builder.Services.AddSingleton<IErpSupplierCreateDryRun, ErpSupplierCreateDryRun>();
builder.Services.AddSingleton<IErpPurchaseCreateDryRun, ErpPurchaseCreateDryRun>();
builder.Services.AddSingleton<IErpPurchaseDeleteDryRun, ErpPurchaseDeleteDryRun>();
builder.Services.AddSingleton<IErpPurchaseAmendDryRun, ErpPurchaseAmendDryRun>();
builder.Services.AddSingleton<IErpInvoiceDeleteDryRun, ErpInvoiceDeleteDryRun>();
builder.Services.AddSingleton<IErpCashAccountCreateDryRun, ErpCashAccountCreateDryRun>();
builder.Services.AddSingleton<IErpCoaCreateDryRun, ErpCoaCreateDryRun>();
builder.Services.AddSingleton<IErpCustomerMasterSaveDryRun, ErpCustomerMasterSaveDryRun>();
builder.Services.AddSingleton<IErpAsRmaCreateDryRun, ErpAsRmaCreateDryRun>();

builder.Services.AddSingleton<IErpGlManualEntryDryRun, ErpGlManualEntryDryRun>();
builder.Services.AddSingleton<IErpGlReverseJournalDryRun, ErpGlReverseJournalDryRun>();
builder.Services.AddSingleton<IErpPurchaseVoidDryRun, ErpPurchaseVoidDryRun>();
builder.Services.AddSingleton<IErpInvoiceCancelDryRun, ErpInvoiceCancelDryRun>();
builder.Services.AddSingleton<IErpSalesOrderCancelDryRun, ErpSalesOrderCancelDryRun>();
builder.Services.AddSingleton<IErpSalesOrderDeleteDryRun, ErpSalesOrderDeleteDryRun>();
builder.Services.AddSingleton<IErpPoDeleteDryRun, ErpPoDeleteDryRun>();
builder.Services.AddSingleton<IStorefrontCartAddDryRun, StorefrontCartAddDryRun>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontCartAddService, EcomAE.Platform.Storefront.StorefrontCartAddService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontCartWriteService, EcomAE.Platform.Storefront.StorefrontCartWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontCheckoutWriteService, EcomAE.Platform.Storefront.StorefrontCheckoutWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontVendorPortalReader, EcomAE.Platform.Storefront.StorefrontVendorPortalReader>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontGuestSessionService, EcomAE.Platform.Storefront.StorefrontGuestSessionService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontPaymentWriteService, EcomAE.Platform.Storefront.StorefrontPaymentWriteService>();
builder.Services.AddHttpClient(nameof(EcomAE.Platform.Storefront.LaximoVinDecodeService));
builder.Services.AddScoped<EcomAE.Platform.Storefront.ILaximoVinDecodeService, EcomAE.Platform.Storefront.LaximoVinDecodeService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontVinRequestWriteService, EcomAE.Platform.Storefront.StorefrontVinRequestWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontQuoteWriteService, EcomAE.Platform.Storefront.StorefrontQuoteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontGarageWriteService, EcomAE.Platform.Storefront.StorefrontGarageWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontCustomerWriteService, EcomAE.Platform.Storefront.StorefrontCustomerWriteService>();
builder.Services.AddSingleton<EcomAE.Platform.Migration.CpWebTrackerCollectRateLimiter>();
builder.Services.AddScoped<EcomAE.Platform.Migration.ICpWebTrackerCollectService, EcomAE.Platform.Migration.CpWebTrackerCollectService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontRegisterWriteService, EcomAE.Platform.Storefront.StorefrontRegisterWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPayrollWriteService, EcomAE.Platform.Erp.ErpPayrollWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPayrollPayWriteService, EcomAE.Platform.Erp.ErpPayrollPayWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPayrollUpdateDaysWriteService, EcomAE.Platform.Erp.ErpPayrollUpdateDaysWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPayrollGenerateWriteService, EcomAE.Platform.Erp.ErpPayrollGenerateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInventoryForecastWriteService, EcomAE.Platform.Erp.ErpInventoryForecastWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMultiEntityWriteService, EcomAE.Platform.Erp.ErpMultiEntityWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMultiCurrencyGlWriteService, EcomAE.Platform.Erp.ErpMultiCurrencyGlWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWorkspaceFavoritesWriteService, EcomAE.Platform.Erp.ErpWorkspaceFavoritesWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInventoryReorderWriteService, EcomAE.Platform.Erp.ErpInventoryReorderWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInventoryMovementWriteService, EcomAE.Platform.Erp.ErpInventoryMovementWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpDimensionWriteService, EcomAE.Platform.Erp.ErpDimensionWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCustomerMasterWriteService, EcomAE.Platform.Erp.ErpCustomerMasterWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAftersalesRmaWriteService, EcomAE.Platform.Erp.ErpAftersalesRmaWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAftersalesWarrantyWriteService, EcomAE.Platform.Erp.ErpAftersalesWarrantyWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAftersalesJobWriteService, EcomAE.Platform.Erp.ErpAftersalesJobWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwRepairWriteService, EcomAE.Platform.Erp.ErpJwRepairWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwKaratWriteService, EcomAE.Platform.Erp.ErpJwKaratWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwRateTypeWriteService, EcomAE.Platform.Erp.ErpJwRateTypeWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwCurrencyWriteService, EcomAE.Platform.Erp.ErpJwCurrencyWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwDiamondWriteService, EcomAE.Platform.Erp.ErpJwDiamondWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwDesignWriteService, EcomAE.Platform.Erp.ErpJwDesignWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwPearlWriteService, EcomAE.Platform.Erp.ErpJwPearlWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwColorStoneWriteService, EcomAE.Platform.Erp.ErpJwColorStoneWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwBarcodeWriteService, EcomAE.Platform.Erp.ErpJwBarcodeWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwTagWriteService, EcomAE.Platform.Erp.ErpJwTagWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwGoldSchemeWriteService, EcomAE.Platform.Erp.ErpJwGoldSchemeWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwFixUnfixWriteService, EcomAE.Platform.Erp.ErpJwFixUnfixWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwBarcodePurchaseWriteService, EcomAE.Platform.Erp.ErpJwBarcodePurchaseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpTouristRefundWriteService, EcomAE.Platform.Erp.ErpTouristRefundWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRfidRegisterWriteService, EcomAE.Platform.Erp.ErpRfidRegisterWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRfidScanWriteService, EcomAE.Platform.Erp.ErpRfidScanWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpGoldRateSetWriteService, EcomAE.Platform.Erp.ErpGoldRateSetWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAmlKycSaveWriteService, EcomAE.Platform.Erp.ErpAmlKycSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAmlAlertStatusWriteService, EcomAE.Platform.Erp.ErpAmlAlertStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSlaWriteService, EcomAE.Platform.Erp.ErpSlaWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpTicketsWriteService, EcomAE.Platform.Erp.ErpTicketsWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCustomerGroupsWriteService, EcomAE.Platform.Erp.ErpCustomerGroupsWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpReportSchedulerWriteService, EcomAE.Platform.Erp.ErpReportSchedulerWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpVirtualWarehouseWriteService, EcomAE.Platform.Erp.ErpVirtualWarehouseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwMetalStockWriteService, EcomAE.Platform.Erp.ErpJwMetalStockWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwFixingWriteService, EcomAE.Platform.Erp.ErpJwFixingWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwVoucherWriteService, EcomAE.Platform.Erp.ErpJwVoucherWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwPettyCashWriteService, EcomAE.Platform.Erp.ErpJwPettyCashWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwTouristVatWriteService, EcomAE.Platform.Erp.ErpJwTouristVatWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwRepairReceiptWriteService, EcomAE.Platform.Erp.ErpJwRepairReceiptWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwRepairTransferWriteService, EcomAE.Platform.Erp.ErpJwRepairTransferWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwWorkshopReceiveWriteService, EcomAE.Platform.Erp.ErpJwWorkshopReceiveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwRepairDeliveryWriteService, EcomAE.Platform.Erp.ErpJwRepairDeliveryWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpJwStockVerifyWriteService, EcomAE.Platform.Erp.ErpJwStockVerifyWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrDaysWriteService, EcomAE.Platform.Erp.ErpHrDaysWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpStorageGroupWriteService, EcomAE.Platform.Cp.CpStorageGroupWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpStorageWriteService, EcomAE.Platform.Cp.CpStorageWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpOfficeWriteService, EcomAE.Platform.Cp.CpOfficeWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpTenantEmailWriteService, EcomAE.Platform.Cp.CpTenantEmailWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpSmsWhatsappWriteService, EcomAE.Platform.Cp.CpSmsWhatsappWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpPluginsWriteService, EcomAE.Platform.Cp.CpPluginsWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpTemplatesWriteService, EcomAE.Platform.Cp.CpTemplatesWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpNotificationSettingsWriteService, EcomAE.Platform.Cp.CpNotificationSettingsWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpObtainingModeWriteService, EcomAE.Platform.Cp.CpObtainingModeWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpGeoTreeWriteService, EcomAE.Platform.Cp.CpGeoTreeWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpSearchTabWriteService, EcomAE.Platform.Cp.CpSearchTabWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpAdditionalTextWriteService, EcomAE.Platform.Cp.CpAdditionalTextWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpSliderWriteService, EcomAE.Platform.Cp.CpSliderWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpProductFilterWriteService, EcomAE.Platform.Cp.CpProductFilterWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpOrderStatusWriteService, EcomAE.Platform.Cp.CpOrderStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpPricesUploadWriteService, EcomAE.Platform.Cp.CpPricesUploadWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpQuoteWriteService, EcomAE.Platform.Cp.CpQuoteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpVendorApprovalWriteService, EcomAE.Platform.Cp.CpVendorApprovalWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontVendorRegisterWriteService, EcomAE.Platform.Storefront.StorefrontVendorRegisterWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Storefront.IStorefrontConfirmContactWriteService, EcomAE.Platform.Storefront.StorefrontConfirmContactWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpApiClientWriteService, EcomAE.Platform.Cp.CpApiClientWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpPriceStorageRuleWriteService, EcomAE.Platform.Cp.CpPriceStorageRuleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpContentManagerWriteService, EcomAE.Platform.Cp.CpContentManagerWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpMenuWriteService, EcomAE.Platform.Cp.CpMenuWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpModuleWriteService, EcomAE.Platform.Cp.CpModuleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOfficesCashWriteService, EcomAE.Platform.Erp.ErpOfficesCashWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWmsLocationWriteService, EcomAE.Platform.Erp.ErpWmsLocationWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSubscriptionStatusWriteService, EcomAE.Platform.Erp.ErpSubscriptionStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSubscriptionSaveWriteService, EcomAE.Platform.Erp.ErpSubscriptionSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpContractStatusWriteService, EcomAE.Platform.Erp.ErpContractStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpContractSaveWriteService, EcomAE.Platform.Erp.ErpContractSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWorkflowStatusWriteService, EcomAE.Platform.Erp.ErpWorkflowStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWorkflowCreateWriteService, EcomAE.Platform.Erp.ErpWorkflowCreateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCollectionsCaseStatusWriteService, EcomAE.Platform.Erp.ErpCollectionsCaseStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCollectionsCaseSaveWriteService, EcomAE.Platform.Erp.ErpCollectionsCaseSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCollectionsCasePromiseWriteService, EcomAE.Platform.Erp.ErpCollectionsCasePromiseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCollectionsActivityLogWriteService, EcomAE.Platform.Erp.ErpCollectionsActivityLogWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCollectionsHoldSetWriteService, EcomAE.Platform.Erp.ErpCollectionsHoldSetWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCollectionsDunningRunWriteService, EcomAE.Platform.Erp.ErpCollectionsDunningRunWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpProcurementReqWriteService, EcomAE.Platform.Erp.ErpProcurementReqWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpProcurementReqSaveWriteService, EcomAE.Platform.Erp.ErpProcurementReqSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpProcurementReqAddLineWriteService, EcomAE.Platform.Erp.ErpProcurementReqAddLineWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWmsWaveReleaseWriteService, EcomAE.Platform.Erp.ErpWmsWaveReleaseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWmsReceiveWriteService, EcomAE.Platform.Erp.ErpWmsReceiveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWmsWorkCompleteWriteService, EcomAE.Platform.Erp.ErpWmsWorkCompleteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWmsWaveCreateWriteService, EcomAE.Platform.Erp.ErpWmsWaveCreateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMarketingWriteService, EcomAE.Platform.Erp.ErpMarketingWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInsClaimStatusWriteService, EcomAE.Platform.Erp.ErpInsClaimStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInsClaimAddWriteService, EcomAE.Platform.Erp.ErpInsClaimAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosVatRefundStatusWriteService, EcomAE.Platform.Erp.ErpBosVatRefundStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosVatRefundSaveWriteService, EcomAE.Platform.Erp.ErpBosVatRefundSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSubInvoicePaidWriteService, EcomAE.Platform.Erp.ErpSubInvoicePaidWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpSubGenerateWriteService, EcomAE.Platform.Erp.ErpSubGenerateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfCaseCancelWriteService, EcomAE.Platform.Erp.ErpPfCaseCancelWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfStepDeleteWriteService, EcomAE.Platform.Erp.ErpPfStepDeleteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosWfDisableRuleWriteService, EcomAE.Platform.Erp.ErpBosWfDisableRuleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosComplianceDisableObligationWriteService, EcomAE.Platform.Erp.ErpBosComplianceDisableObligationWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrStatusWriteService, EcomAE.Platform.Erp.ErpHrStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrExpenseSaveWriteService, EcomAE.Platform.Erp.ErpHrExpenseSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrLeaveRequestWriteService, EcomAE.Platform.Erp.ErpHrLeaveRequestWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrEmpSaveWriteService, EcomAE.Platform.Erp.ErpHrEmpSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrAttendanceWriteService, EcomAE.Platform.Erp.ErpHrAttendanceWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPrjLogTimeWriteService, EcomAE.Platform.Erp.ErpPrjLogTimeWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPrjTaskSaveWriteService, EcomAE.Platform.Erp.ErpPrjTaskSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrPayrollRunWriteService, EcomAE.Platform.Erp.ErpHrPayrollRunWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpConsDeleteWriteService, EcomAE.Platform.Erp.ErpConsDeleteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpConsEntitySaveWriteService, EcomAE.Platform.Erp.ErpConsEntitySaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpConsFiguresSaveWriteService, EcomAE.Platform.Erp.ErpConsFiguresSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpConsIcSaveWriteService, EcomAE.Platform.Erp.ErpConsIcSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInsSaveWriteService, EcomAE.Platform.Erp.ErpInsSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInsDocAddWriteService, EcomAE.Platform.Erp.ErpInsDocAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInsDeleteWriteService, EcomAE.Platform.Erp.ErpInsDeleteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMfgBomSaveWriteService, EcomAE.Platform.Erp.ErpMfgBomSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMfgWoCreateWriteService, EcomAE.Platform.Erp.ErpMfgWoCreateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosComplianceAddObligationWriteService, EcomAE.Platform.Erp.ErpBosComplianceAddObligationWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfCaseReassignWriteService, EcomAE.Platform.Erp.ErpPfCaseReassignWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfCaseStartWriteService, EcomAE.Platform.Erp.ErpPfCaseStartWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfCaseActWriteService, EcomAE.Platform.Erp.ErpPfCaseActWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosWfSaveRuleWriteService, EcomAE.Platform.Erp.ErpBosWfSaveRuleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosRetentionSaveWriteService, EcomAE.Platform.Erp.ErpBosRetentionSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfSetDeptHeadWriteService, EcomAE.Platform.Erp.ErpPfSetDeptHeadWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosComplianceFileWriteService, EcomAE.Platform.Erp.ErpBosComplianceFileWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpFyCreateWriteService, EcomAE.Platform.Erp.ErpFyCreateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosWfDecideWriteService, EcomAE.Platform.Erp.ErpBosWfDecideWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosWfRaiseWriteService, EcomAE.Platform.Erp.ErpBosWfRaiseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOaPartySaveWriteService, EcomAE.Platform.Erp.ErpOaPartySaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpErFormatSaveWriteService, EcomAE.Platform.Erp.ErpErFormatSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOaAddressSaveWriteService, EcomAE.Platform.Erp.ErpOaAddressSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpErFieldAddWriteService, EcomAE.Platform.Erp.ErpErFieldAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRtlChannelSaveWriteService, EcomAE.Platform.Erp.ErpRtlChannelSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOaContactSaveWriteService, EcomAE.Platform.Erp.ErpOaContactSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOaHolidayAddWriteService, EcomAE.Platform.Erp.ErpOaHolidayAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOaCalendarSaveWriteService, EcomAE.Platform.Erp.ErpOaCalendarSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPrjaBudgetSaveWriteService, EcomAE.Platform.Erp.ErpPrjaBudgetSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPltJobSaveWriteService, EcomAE.Platform.Erp.ErpPltJobSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPltFeatureSaveWriteService, EcomAE.Platform.Erp.ErpPltFeatureSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpIntgEntitySaveWriteService, EcomAE.Platform.Erp.ErpIntgEntitySaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfStepSaveWriteService, EcomAE.Platform.Erp.ErpPfStepSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPfProcessSaveWriteService, EcomAE.Platform.Erp.ErpPfProcessSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpKbSaveWriteService, EcomAE.Platform.Erp.ErpKbSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAgendaSaveWriteService, EcomAE.Platform.Erp.ErpAgendaSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpIntgSubSaveWriteService, EcomAE.Platform.Erp.ErpIntgSubSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMultiEntitySaveWriteService, EcomAE.Platform.Erp.ErpMultiEntitySaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCostmItemSetWriteService, EcomAE.Platform.Erp.ErpCostmItemSetWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpIntgEventRaiseWriteService, EcomAE.Platform.Erp.ErpIntgEventRaiseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCostmTxnAddWriteService, EcomAE.Platform.Erp.ErpCostmTxnAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPrjaTxnAddWriteService, EcomAE.Platform.Erp.ErpPrjaTxnAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRtlAssortmentSetWriteService, EcomAE.Platform.Erp.ErpRtlAssortmentSetWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPltJobRunWriteService, EcomAE.Platform.Erp.ErpPltJobRunWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRtlDiscountSaveWriteService, EcomAE.Platform.Erp.ErpRtlDiscountSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRbacPrivSaveWriteService, EcomAE.Platform.Erp.ErpRbacPrivSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRbacDutySaveWriteService, EcomAE.Platform.Erp.ErpRbacDutySaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRbacRoleSaveWriteService, EcomAE.Platform.Erp.ErpRbacRoleSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRbacDutyPrivWriteService, EcomAE.Platform.Erp.ErpRbacDutyPrivWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRbacRoleDutyWriteService, EcomAE.Platform.Erp.ErpRbacRoleDutyWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpRbacUserRoleWriteService, EcomAE.Platform.Erp.ErpRbacUserRoleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpQmPlanSaveWriteService, EcomAE.Platform.Erp.ErpQmPlanSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpQmTestAddWriteService, EcomAE.Platform.Erp.ErpQmTestAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpProcCategorySaveWriteService, EcomAE.Platform.Erp.ErpProcCategorySaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpProcPolicySaveWriteService, EcomAE.Platform.Erp.ErpProcPolicySaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrtJobSaveWriteService, EcomAE.Platform.Erp.ErpHrtJobSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrtApplicantAddWriteService, EcomAE.Platform.Erp.ErpHrtApplicantAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBplanSaveWriteService, EcomAE.Platform.Erp.ErpBplanSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBplanLineAddWriteService, EcomAE.Platform.Erp.ErpBplanLineAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBplanPositionAddWriteService, EcomAE.Platform.Erp.ErpBplanPositionAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrtReviewSaveWriteService, EcomAE.Platform.Erp.ErpHrtReviewSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrtGoalAddWriteService, EcomAE.Platform.Erp.ErpHrtGoalAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOplParamsSaveWriteService, EcomAE.Platform.Erp.ErpOplParamsSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCftForecastSaveWriteService, EcomAE.Platform.Erp.ErpCftForecastSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCftLineAddWriteService, EcomAE.Platform.Erp.ErpCftLineAddWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCftInstrumentSaveWriteService, EcomAE.Platform.Erp.ErpCftInstrumentSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCftInstrumentStatusWriteService, EcomAE.Platform.Erp.ErpCftInstrumentStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpDocxSaveWriteService, EcomAE.Platform.Erp.ErpDocxSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpFinAllocSaveWriteService, EcomAE.Platform.Erp.ErpFinAllocSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpDocxDeleteWriteService, EcomAE.Platform.Erp.ErpDocxDeleteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpTenantConfigSaveWriteService, EcomAE.Platform.Erp.ErpTenantConfigSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPrintDesignerSaveWriteService, EcomAE.Platform.Erp.ErpPrintDesignerSaveWriteService>();
builder.Services.AddHttpClient<EcomAE.Platform.Erp.IErpUaeFtaHttpClient, EcomAE.Platform.Erp.ErpUaeFtaHttpClient>(client =>
{
    client.Timeout = TimeSpan.FromSeconds(45);
    client.DefaultRequestHeaders.UserAgent.ParseAdd(EcomAE.Platform.Erp.ErpUaeTaxFtaLegislation.UserAgent);
});
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpUaeTaxFtaFetchWriteService, EcomAE.Platform.Erp.ErpUaeTaxFtaFetchWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpUaeTaxLegislationAskWriteService, EcomAE.Platform.Erp.ErpUaeTaxLegislationAskWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpUaeTaxLegislationRegenWriteService, EcomAE.Platform.Erp.ErpUaeTaxLegislationRegenWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpUaeTaxLegislationChecklistSetWriteService, EcomAE.Platform.Erp.ErpUaeTaxLegislationChecklistSetWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPmSaveWriteService, EcomAE.Platform.Erp.ErpPmSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPmBudgetSaveWriteService, EcomAE.Platform.Erp.ErpPmBudgetSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPmBudgetLineSaveWriteService, EcomAE.Platform.Erp.ErpPmBudgetLineSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPmToggleWriteService, EcomAE.Platform.Erp.ErpPmToggleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPmChequeSaveWriteService, EcomAE.Platform.Erp.ErpPmChequeSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPmListingAttachWriteService, EcomAE.Platform.Erp.ErpPmListingAttachWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMfgrWcSaveWriteService, EcomAE.Platform.Erp.ErpMfgrWcSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMfgrRouteSaveWriteService, EcomAE.Platform.Erp.ErpMfgrRouteSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpMfgrPlannedFirmWriteService, EcomAE.Platform.Erp.ErpMfgrPlannedFirmWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOplSetStatusWriteService, EcomAE.Platform.Erp.ErpOplSetStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpQmNcrUpdateWriteService, EcomAE.Platform.Erp.ErpQmNcrUpdateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBosIntelToggleWriteService, EcomAE.Platform.Erp.ErpBosIntelToggleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCtrOcrWriteService, EcomAE.Platform.Erp.ErpCtrOcrWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCtrSignWriteService, EcomAE.Platform.Erp.ErpCtrSignWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpUaeTaxSaveCtAdjustmentsWriteService, EcomAE.Platform.Erp.ErpUaeTaxSaveCtAdjustmentsWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpFiscalSetLockWriteService, EcomAE.Platform.Erp.ErpFiscalSetLockWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCcySetRateWriteService, EcomAE.Platform.Erp.ErpCcySetRateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOpeningCreateBatchWriteService, EcomAE.Platform.Erp.ErpOpeningCreateBatchWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOpeningAddCoaLineWriteService, EcomAE.Platform.Erp.ErpOpeningAddCoaLineWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpOpeningAddInvLineWriteService, EcomAE.Platform.Erp.ErpOpeningAddInvLineWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpHrtApplicantStageWriteService, EcomAE.Platform.Erp.ErpHrtApplicantStageWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpFinPeriodsGenerateWriteService, EcomAE.Platform.Erp.ErpFinPeriodsGenerateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBankReconcileWriteService, EcomAE.Platform.Erp.ErpBankReconcileWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpAutomationDeactivateWriteService, EcomAE.Platform.Erp.ErpAutomationDeactivateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPeriodSoftCloseWriteService, EcomAE.Platform.Erp.ErpPeriodSoftCloseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpBplanAdvanceWriteService, EcomAE.Platform.Erp.ErpBplanAdvanceWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpEditLockReleaseWriteService, EcomAE.Platform.Erp.ErpEditLockReleaseWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpEditLockHeartbeatWriteService, EcomAE.Platform.Erp.ErpEditLockHeartbeatWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpCsDeleteDeclarationWriteService, EcomAE.Platform.Erp.ErpCsDeleteDeclarationWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpPrjSaveWriteService, EcomAE.Platform.Erp.ErpPrjSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpInsDocDeleteWriteService, EcomAE.Platform.Erp.ErpInsDocDeleteWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpFyWriteService, EcomAE.Platform.Erp.ErpFyWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpFinPeriodStatusWriteService, EcomAE.Platform.Erp.ErpFinPeriodStatusWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWhtSettleWriteService, EcomAE.Platform.Erp.ErpWhtSettleWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWhtCodeSaveWriteService, EcomAE.Platform.Erp.ErpWhtCodeSaveWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWhtRecordWriteService, EcomAE.Platform.Erp.ErpWhtRecordWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Erp.IErpWhtCertificateWriteService, EcomAE.Platform.Erp.ErpWhtCertificateWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpOmsWriteService, EcomAE.Platform.Cp.CpOmsWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpFulfillmentQueueWriteService, EcomAE.Platform.Cp.CpFulfillmentQueueWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpPosWriteService, EcomAE.Platform.Cp.CpPosWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCollectionsDunningWriteService, EcomAE.Platform.Cp.CpCollectionsDunningWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCustomShippingWriteService, EcomAE.Platform.Cp.CpCustomShippingWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpUserWriteService, EcomAE.Platform.Cp.CpUserWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpLangWriteService, EcomAE.Platform.Cp.CpLangWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpChannelWriteService, EcomAE.Platform.Cp.CpChannelWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpLogisticsWriteService, EcomAE.Platform.Cp.CpLogisticsWriteService>();

builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCrmActivityWriteService, EcomAE.Platform.Cp.CpCrmActivityWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpWorkshopWriteService, EcomAE.Platform.Cp.CpWorkshopWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpFulfillmentQueueWriteService, EcomAE.Platform.Cp.CpFulfillmentQueueWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCollectionsDunningWriteService, EcomAE.Platform.Cp.CpCollectionsDunningWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCatalogueWriteService, EcomAE.Platform.Cp.CpCatalogueWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpLineListWriteService, EcomAE.Platform.Cp.CpLineListWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpTreeListWriteService, EcomAE.Platform.Cp.CpTreeListWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpSkuMediaWriteService, EcomAE.Platform.Cp.CpSkuMediaWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpMainPageProductsWriteService, EcomAE.Platform.Cp.CpMainPageProductsWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpSpecialSearchWriteService, EcomAE.Platform.Cp.CpSpecialSearchWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCatalogueEditorWriteService, EcomAE.Platform.Cp.CpCatalogueEditorWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCatalogueProductWriteService, EcomAE.Platform.Cp.CpCatalogueProductWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCatalogueReviewWriteService, EcomAE.Platform.Cp.CpCatalogueReviewWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCatalogueProductsDeleteService, EcomAE.Platform.Cp.CpCatalogueProductsDeleteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpAccessoriesPhotoWriteService, EcomAE.Platform.Cp.CpAccessoriesPhotoWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpAccessoriesListingWriteService, EcomAE.Platform.Cp.CpAccessoriesListingWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpAccessoriesTaxonomyWriteService, EcomAE.Platform.Cp.CpAccessoriesTaxonomyWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpManufacturerSynonymWriteService, EcomAE.Platform.Cp.CpManufacturerSynonymWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCrossWriteService, EcomAE.Platform.Cp.CpCrossWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpPricesEditWriteService, EcomAE.Platform.Cp.CpPricesEditWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCurrencyWriteService, EcomAE.Platform.Cp.CpCurrencyWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpReturnWriteService, EcomAE.Platform.Cp.CpReturnWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpCreditLimitWriteService, EcomAE.Platform.Cp.CpCreditLimitWriteService>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpTaxToolkitWriteService, EcomAE.Platform.Cp.CpTaxToolkitWriteService>();
builder.Services.AddSingleton<ICpTaxToolkitInstallDryRun, CpTaxToolkitInstallDryRun>();
builder.Services.AddSingleton<ICpTaxToolkitAssignDryRun, CpTaxToolkitAssignDryRun>();
builder.Services.AddScoped<EcomAE.Platform.Cp.ICpPoApprovalWriteService, EcomAE.Platform.Cp.CpPoApprovalWriteService>();
builder.Services.AddSingleton<IStorefrontGarageNotepadAddDryRun, StorefrontGarageNotepadAddDryRun>();
builder.Services.AddSingleton<IStorefrontQuoteSubmitDryRun, StorefrontQuoteSubmitDryRun>();
builder.Services.AddSingleton<IStorefrontQuoteAcceptDryRun, StorefrontQuoteAcceptDryRun>();
builder.Services.AddSingleton<IStorefrontQuoteAddItemDryRun, StorefrontQuoteAddItemDryRun>();
builder.Services.AddSingleton<IStorefrontQuoteAddManualDryRun, StorefrontQuoteAddManualDryRun>();
builder.Services.AddSingleton<IStorefrontGarageSetActiveDryRun, StorefrontGarageSetActiveDryRun>();
builder.Services.AddSingleton<IStorefrontGarageDeleteDryRun, StorefrontGarageDeleteDryRun>();
builder.Services.AddSingleton<IStorefrontGarageCheckCarDryRun, StorefrontGarageCheckCarDryRun>();
builder.Services.AddSingleton<IStorefrontCheckoutCreateDryRun, StorefrontCheckoutCreateDryRun>();
builder.Services.AddSingleton<IStorefrontOrderSendMessageDryRun, StorefrontOrderSendMessageDryRun>();
builder.Services.AddSingleton<IPythonSidecarCatalogReporter, PythonSidecarCatalogReporter>();
builder.Services.AddRouting(options => options.LowercaseUrls = true);
builder.Services.AddResponseCompression(options =>
{
    options.EnableForHttps = true;
    options.Providers.Add<BrotliCompressionProvider>();
    options.Providers.Add<GzipCompressionProvider>();
    options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
    [
        "application/json",
        "application/javascript",
        "text/css",
        "text/html",
        "text/plain",
        "text/json",
        "image/svg+xml"
    ]);
});
builder.Services.Configure<BrotliCompressionProviderOptions>(options => options.Level = CompressionLevel.Fastest);
builder.Services.Configure<GzipCompressionProviderOptions>(options => options.Level = CompressionLevel.Fastest);
builder.Services.AddHealthChecks();
