<?php
/**
 * Super CP capabilities catalog — 113 customer-facing items (included from data.php).
 */
defined('_ASTEXE_') or die('No access');

return array(
	// Platform & Super CP (9)
	array('id' => 'super-cp-console', 'category' => 'Platform & Super CP', 'title' => 'Super CP operator console', 'summary' => 'Run every tenant from one hosted console at ecomae.com/cp — same ECOM AE control panel shell with platform packs. Onboard clients, push templates, and monitor health without exposing operator tools on client domains.', 'icon' => 'fa-cloud'),
	array('id' => 'platform-health-monitoring', 'category' => 'Platform & Super CP', 'title' => 'Platform health monitoring', 'summary' => 'Super CP health checkup probes all tenant storefronts and CP paths, SSL expiry, ERP DB isolation, nginx duplicate server_name warnings, backup age, and sitemap readiness — export CSV for ops records.', 'icon' => 'fa-heartbeat'),
	array('id' => 'tenant-hub', 'category' => 'Platform & Super CP', 'title' => 'Tenant hub & registry', 'summary' => 'Central registry of all clients: trade name, hostname, industry, database, and status from draft through live. One screen to see who is pending DNS, who is live, and who needs attention.', 'icon' => 'fa-sitemap'),
	array('id' => 'tenant-onboarding', 'category' => 'Platform & Super CP', 'title' => 'Client onboard intro form', 'summary' => 'Single intro form captures brand, domain, industry, admin email, and tenant MySQL details — seeds portal settings and industry template on save. Most operators go from form to working stack within 24 hours once DNS is pointed.', 'icon' => 'fa-rocket'),
	array('id' => 'dns-launch-checklist', 'category' => 'Platform & Super CP', 'title' => 'DNS & launch checklist', 'summary' => 'Step-by-step GoDaddy-friendly A-record guide, domain alias on the platform stack, SSL issuance, and status flip to Live when probes pass. Clients keep their registrar — no separate hosting package.', 'icon' => 'fa-globe'),
	array('id' => 'industry-settings-deploy', 'category' => 'Platform & Super CP', 'title' => 'Industry settings & deploy', 'summary' => 'Pick vertical, visual style, enabled module packs, and sidebar visibility — then push to a client site when ready. Deploy portal packages to registered targets from Super CP without rebuilding per tenant.', 'icon' => 'fa-cogs'),
	array('id' => 'tenant-health-probes', 'category' => 'Platform & Super CP', 'title' => 'Health probes & go-live', 'summary' => 'HTTP checks on live tenants confirm storefront and CP endpoints respond before handoff. Track draft → DNS pending → live with confidence that the client site is reachable.', 'icon' => 'fa-heartbeat'),
	array('id' => 'business-continuity-failover', 'category' => 'Platform & Super CP', 'title' => 'Business continuity & failover', 'summary' => 'Cloud-first operations with a professional backup path when the primary stack hiccups. Shoppers see guided splash screens instead of generic errors while traffic can route to your backup origin.', 'icon' => 'fa-shield'),
	array('id' => 'multi-tenant-routing', 'category' => 'Platform & Super CP', 'title' => 'Multi-tenant hostname routing', 'summary' => 'One nginx stack serves many client domains — hostname selects isolated MySQL tenant database and branding. Model C hosting saves disk, ops time, and per-client hosting bills.', 'icon' => 'fa-random'),
	array('id' => 'erp-only-deployment', 'category' => 'Platform & Super CP', 'title' => 'ERP-only deployment', 'summary' => 'Finance-led tenants with no public storefront — homepage redirects to /erp, commerce packs stay off, and staff sign in at the ERP shell (/cp/shop/finance/erp?epc_erp_shell=1) or the standalone finance portal with username/password access.', 'icon' => 'fa-line-chart'),
	array('id' => 'modular-erp-access', 'category' => 'Platform & Super CP', 'title' => 'Modular ERP access', 'summary' => 'Enable only the ERP areas each client needs — full suite, Custom & Shipping only, People (HR/payroll), or Finance + e-invoice. Super CP toggles modules at onboard or Industry settings; the ERP shell and staff permissions respect the same flags.', 'icon' => 'fa-puzzle-piece'),
	array('id' => 'api-integrations', 'category' => 'Platform & Super CP', 'title' => 'API integrations (Phase 1)', 'summary' => 'Read-only JSON REST at /epc-api/v1/ — tenant-scoped API keys for orders, product search, and ERP KPIs. OpenAPI spec and marketing docs for enterprise middleware, BI, and partner systems.', 'icon' => 'fa-code'),

	// Commerce — Pricing & catalog (10)
	array('id' => 'product-catalogue', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Product catalogue', 'summary' => 'Full SKU management with rich product pages, media, and category trees for fashion, electronics, medical, and general retail. Storefront and CP share the same catalogue data — no duplicate entry.', 'icon' => 'fa-th-large'),
	array('id' => 'bulk-csv-import', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Bulk CSV import & export', 'summary' => 'Upload seasonal collections or thousands of SKUs via CSV — map columns, preview, and commit in minutes. Export for backup, supplier handoff, or marketplace feeds.', 'icon' => 'fa-upload'),
	array('id' => 'categories-attributes', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Categories & attributes', 'summary' => 'Merchandise with nested categories, spec filters, and custom attribute fields. Electronics get datasheet filters; fashion gets size and colour — all configurable per industry.', 'icon' => 'fa-tags'),
	array('id' => 'variant-skus', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Variant SKUs (size, colour, spec)', 'summary' => 'Sell products with multiple variants — each with its own SKU, stock, and price. Storefront variant selectors and CP stock-by-variant keep fulfilment accurate.', 'icon' => 'fa-clone'),
	array('id' => 'supplier-price-upload', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Supplier price upload', 'summary' => 'Import supplier price files and keep trade pricing current without manual re-keying. Built for auto-parts distributors and B2B wholesalers with frequent price updates.', 'icon' => 'fa-file-excel-o'),
	array('id' => 'live-price-search', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Live supplier price search', 'summary' => 'Search pulls prices from connected suppliers at order time — customers see current trade rates on the storefront. Ideal for parts traders who compete on availability and price.', 'icon' => 'fa-search'),
	array('id' => 'cross-references', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Cross-reference lookup', 'summary' => 'OEM and aftermarket cross tables help customers find interchangeable parts. Cross matches against in-stock SKUs display price and quantity on the search results page.', 'icon' => 'fa-exchange'),
	array('id' => 'vin-oem-search', 'category' => 'Commerce — Pricing & catalog', 'title' => 'VIN & OEM number search', 'summary' => 'Vehicle-aware search widgets decode VIN or accept OEM numbers for precise fitment. Reduces wrong-part orders and builds trust with workshop and fleet buyers.', 'icon' => 'fa-car'),
	array('id' => 'vehicle-catalogue', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Vehicle-fitment catalogue', 'summary' => 'Browse by make, model, and modification — Epart catalog integration for passenger, commercial, and motorbike segments. Product groups and articles flow into cart and ERP.', 'icon' => 'fa-road'),
	array('id' => 'price-lists-margins', 'category' => 'Commerce — Pricing & catalog', 'title' => 'Price lists & customer margins', 'summary' => 'Customer groups and profiles drive margin rules, fixed currency, and visibility show/hide by brand. B2B clients see contract pricing; retail sees standard shelf prices.', 'icon' => 'fa-percent'),

	// Commerce — Orders & fulfilment (8)
	array('id' => 'shopping-cart-checkout', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'Shopping cart & checkout', 'summary' => 'Guest and logged-in checkout with delivery choice, promo codes, and payment at checkout. Orders flow straight into CP order desk and ERP finance — one data path end to end.', 'icon' => 'fa-shopping-cart'),
	array('id' => 'order-management', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'Order desk & statuses', 'summary' => 'Staff manage order lifecycle from new through packed, shipped, and completed. Status updates trigger customer emails and feed fulfilment and finance modules.', 'icon' => 'fa-list-alt'),
	array('id' => 'order-fulfilment', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'Order fulfilment workflows', 'summary' => 'Pick, pack, and ship with warehouse-aware fulfilment hooks tied to stock. Returns and partial shipments stay traceable in CP and ERP fulfilment tabs.', 'icon' => 'fa-random'),
	array('id' => 'delivery-notes', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'Delivery notes & pick lists', 'summary' => 'Generate delivery notes and pick lists from confirmed orders — print-ready documents with line items, weights, and customer delivery details.', 'icon' => 'fa-truck'),
	array('id' => 'returns-rma', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'Returns & RMA handling', 'summary' => 'Process returns and warranty claims with status tracking and stock put-back. Electronics and medical verticals get serial and batch fields for audit-friendly RMA.', 'icon' => 'fa-undo'),
	array('id' => 'whatsapp-order-share', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'WhatsApp order sharing', 'summary' => 'Share cart or order summaries via WhatsApp for quick B2B confirmation. Popular with UAE and GCC traders who close deals on mobile messaging.', 'icon' => 'fa-whatsapp'),
	array('id' => 'promo-discount-rules', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'Promos & discount rules', 'summary' => 'Campaign promo codes, cart rules, and tiered discounts drive conversion on the storefront. Link promotions to marketing campaigns for measurable uplift.', 'icon' => 'fa-gift'),
	array('id' => 'b2b-trade-accounts', 'category' => 'Commerce — Orders & fulfilment', 'title' => 'B2B trade accounts', 'summary' => 'Logged-in trade buyers get fixed currency, credit limits, balance view, and re-order from history. Auto-parts and wholesale tenants rely on this for repeat B2B cycles.', 'icon' => 'fa-briefcase'),

	// Payments (5)
	array('id' => 'payment-gateways', 'category' => 'Payments', 'title' => 'Payment gateway setup', 'summary' => 'Configure card and local payment gateways for UAE and GCC checkout. Gateway settings live in CP — test mode and live credentials per tenant.', 'icon' => 'fa-credit-card'),
	array('id' => 'multi-currency', 'category' => 'Payments', 'title' => 'Multi-currency display & checkout', 'summary' => 'Show prices and accept payment in multiple currencies for cross-border and tourist retail. Exchange display rules configurable per storefront theme.', 'icon' => 'fa-money'),
	array('id' => 'payment-reconciliation', 'category' => 'Payments', 'title' => 'Payment reconciliation', 'summary' => 'Match gateway settlements to orders and ERP receipts — reduce manual spreadsheet work for finance teams. Discrepancies surface in CP for quick resolution.', 'icon' => 'fa-check-circle'),
	array('id' => 'customer-balance-credit', 'category' => 'Payments', 'title' => 'Customer balance & credit limits', 'summary' => 'Track trade account balances and enforce credit limits at checkout. B2B clients see running balance in client CP; staff approve overrides in order desk.', 'icon' => 'fa-balance-scale'),
	array('id' => 'payment-batches', 'category' => 'Payments', 'title' => 'Payment batches (ERP treasury)', 'summary' => 'Batch outgoing supplier and expense payments from ERP treasury — approve, schedule, and audit payment runs from finance roles.', 'icon' => 'fa-send'),

	// Logistics & shipping (6)
	array('id' => 'warehouses-storages', 'category' => 'Logistics & shipping', 'title' => 'Warehouses & storages', 'summary' => 'Master warehouse and storage locations with stock allocation per site. Multi-warehouse inventory feeds catalogue availability and checkout delivery options.', 'icon' => 'fa-building-o'),
	array('id' => 'carriers-shipments', 'category' => 'Logistics & shipping', 'title' => 'Carriers & shipments', 'summary' => 'Manage carrier accounts, shipment creation, and tracking references. Logistics hub ties customer orders to outbound shipments and delivery documentation.', 'icon' => 'fa-shipping-fast'),
	array('id' => 'delivery-methods', 'category' => 'Logistics & shipping', 'title' => 'Delivery methods & pickup', 'summary' => 'Configure courier, branch pickup, and service-area rules on the storefront. Customers choose delivery at checkout; lead times display on SKU where configured.', 'icon' => 'fa-map-marker'),
	array('id' => 'branch-offices', 'category' => 'Logistics & shipping', 'title' => 'Branch & office list', 'summary' => 'Maintain branch offices and pickup points shown on storefront and delivery notes. Useful for multi-location retailers and parts distributors with counter collection.', 'icon' => 'fa-map-o'),
	array('id' => 'logistics-reports', 'category' => 'Logistics & shipping', 'title' => 'Logistics reports', 'summary' => 'Operational reports on fulfilment throughput, carrier performance, and stock by location. Export-friendly views for warehouse managers and operators.', 'icon' => 'fa-bar-chart'),
	array('id' => 'custom-shipping-declarations', 'category' => 'Logistics & shipping', 'title' => 'Custom & shipping declarations', 'summary' => 'UAE customs declaration registry — import, export, transit, temporary admission, transfer, and LGP entries with dashboard counts and core field capture from the C&L workbook format.', 'icon' => 'fa-ship'),

	// Marketplace channels (5)
	array('id' => 'omnichannel-hub', 'category' => 'Marketplace channels', 'title' => 'Omnichannel hub', 'summary' => 'Central hub for selling beyond your own storefront — connect marketplaces and sales channels from one CP screen. Orders from all channels land in the same order desk.', 'icon' => 'fa-plug'),
	array('id' => 'channel-integrations', 'category' => 'Marketplace channels', 'title' => 'Channel integrations pack', 'summary' => 'Enable marketplace and aggregator integrations per industry pack. Fashion, electronics, and auto-parts tenants extend reach without separate middleware hosting.', 'icon' => 'fa-share-alt'),
	array('id' => 'marketplace-listings', 'category' => 'Marketplace channels', 'title' => 'Marketplace listing sync', 'summary' => 'Push catalogue and stock updates to connected channels — reduce overselling with shared inventory truth. Listing errors surface in channels guide for operator fix.', 'icon' => 'fa-cloud-upload'),
	array('id' => 'channel-order-routing', 'category' => 'Marketplace channels', 'title' => 'Channel order routing', 'summary' => 'External channel orders route into the same fulfilment and ERP pipeline as web orders. One pick/pack workflow regardless of where the sale originated.', 'icon' => 'fa-random'),
	// Procurement & suppliers (6)
	array('id' => 'supplier-directory', 'category' => 'Procurement & suppliers', 'title' => 'Supplier directory', 'summary' => 'Maintain supplier master data — contacts, terms, and linked price files. Auto-parts and wholesale tenants manage dozens of suppliers from one procurement hub.', 'icon' => 'fa-truck'),
	array('id' => 'purchase-orders', 'category' => 'Procurement & suppliers', 'title' => 'Purchase orders', 'summary' => 'Create and track POs from requisition through receipt. PO lines link to ERP payables and three-way match when finance pack is active.', 'icon' => 'fa-clipboard'),
	array('id' => 'rfq-quotes', 'category' => 'Procurement & suppliers', 'title' => 'RFQ & supplier quotes', 'summary' => 'Request quotes from multiple suppliers and compare responses before committing to a PO. Built for project-based and MRO procurement workflows.', 'icon' => 'fa-envelope-o'),
	array('id' => 'three-way-match', 'category' => 'Procurement & suppliers', 'title' => '3-way match (PO / GRN / invoice)', 'summary' => 'Match purchase order, goods receipt, and supplier invoice before payment approval. Reduces duplicate payments and catches quantity or price variances early.', 'icon' => 'fa-check-square-o'),
	array('id' => 'supplier-payments', 'category' => 'Procurement & suppliers', 'title' => 'Supplier payables', 'summary' => 'Track amounts owed to suppliers and schedule settlement from ERP payables tab. Aging reports help finance prioritise cash outflows.', 'icon' => 'fa-credit-card'),
	array('id' => 'procurement-workflows', 'category' => 'Procurement & suppliers', 'title' => 'Procurement workflows', 'summary' => 'End-to-end buy-side process from demand signal through PO, receipt, and invoice. Integrated with auto-parts SAO and ERP purchasing areas.', 'icon' => 'fa-sitemap'),

	// Finance & ERP (17)
	array('id' => 'worldwide-tax-toolkit', 'category' => 'Finance & ERP', 'title' => 'Worldwide Tax Toolkit', 'summary' => 'Complete business taxation for 195+ countries — VAT/GST, corporate income tax (CIT), import/export customs duty, withholding, double taxation & foreign tax credits, plus ERP hooks for purchase inventory, sales output tax, and profit CIT estimates. One-click Update refreshes seed rates and UAE FTA legislation. Tenant jurisdiction drives all tax defaults.', 'icon' => 'fa-globe'),
	array('id' => 'erp-dashboard', 'category' => 'Finance & ERP', 'title' => 'ERP dashboard & KPIs', 'summary' => 'Live KPIs across sales, stock, and finance on one dashboard — plus cross-department workflow view. Standalone /erp portal option for client finance teams.', 'icon' => 'fa-dashboard'),
	array('id' => 'general-ledger', 'category' => 'Finance & ERP', 'title' => 'General ledger', 'summary' => 'Double-entry GL with journal entries, period close, and audit-friendly posting history. Commerce and ERP share customer and SKU master data — no re-keying invoices.', 'icon' => 'fa-book'),
	array('id' => 'chart-of-accounts', 'category' => 'Finance & ERP', 'title' => 'Chart of accounts', 'summary' => 'Configure COA structure for UAE trading, services, and multi-department businesses. Opening balances migration supported for tenants moving from spreadsheets.', 'icon' => 'fa-list'),
	array('id' => 'cash-bank-treasury', 'category' => 'Finance & ERP', 'title' => 'Cash & bank treasury', 'summary' => 'Manage bank accounts, petty cash, and treasury movements in one finance area. Payment batches and reconciliation tie back to GL automatically.', 'icon' => 'fa-university'),
	array('id' => 'bank-reconciliation', 'category' => 'Finance & ERP', 'title' => 'Bank reconciliation', 'summary' => 'Match bank statement lines to ERP receipts and payments — flag unmatched items for review. Monthly recon workflow keeps books aligned with actual cash.', 'icon' => 'fa-check-square'),
	array('id' => 'receivables', 'category' => 'Finance & ERP', 'title' => 'Accounts receivable', 'summary' => 'Track customer invoices, receipts, and aging from sales orders through collection. B2B trade balances sync with storefront client login where configured.', 'icon' => 'fa-users'),
	array('id' => 'inventory-valuation', 'category' => 'Finance & ERP', 'title' => 'Inventory & weighted average cost', 'summary' => 'Multi-warehouse stock with purchase receipts, sales issues, and weighted average costing. Perishable expiry and batch fields for FMCG and medical supplies.', 'icon' => 'fa-cubes'),
	array('id' => 'fixed-assets', 'category' => 'Finance & ERP', 'title' => 'Fixed assets & depreciation', 'summary' => 'Asset register with straight-line and declining depreciation, monthly runs, and net book value reports. Tracking IDs and locations support audit and fleet operators.', 'icon' => 'fa-building'),
	array('id' => 'pl-balance-sheet', 'category' => 'Finance & ERP', 'title' => 'P&L & balance sheet', 'summary' => 'Standard financial statements from posted GL — filter by period and export for advisors. Tax firms use this alongside VAT return data for client reporting.', 'icon' => 'fa-bar-chart'),
	array('id' => 'erp-workflow', 'category' => 'Finance & ERP', 'title' => 'Cross-department workflow', 'summary' => 'Visual workflow across sales, purchasing, finance, and operations — see bottlenecks before month-end. Native ERP tabs replace disconnected spreadsheets for growing tenants.', 'icon' => 'fa-tasks'),
	array('id' => 'multi-company-erp-access', 'category' => 'Finance & ERP', 'title' => 'Multi-company ERP access', 'summary' => 'Username/password sign-in per department user with company-scoped customs declarations, cost summaries, and entity fields — one hosted tenant serves multiple legal entities without a storefront account.', 'icon' => 'fa-sitemap'),
	array('id' => 'business-unit-dimensions', 'category' => 'Finance & ERP', 'title' => 'Business unit & financial dimensions', 'summary' => 'D365-style financial dimensions — business unit, cost centre, department, project and custom tenant dimensions — selectable on every entry (sales orders, purchase orders, customers, vendors, invoices, receipt & payment vouchers, journals, inventory, listings and more). Each transaction is tagged and reportable so clients segregate results by any dimension combination.', 'icon' => 'fa-tags'),
	array('id' => 'enterprise-modules-d365', 'category' => 'Finance & ERP', 'title' => 'Enterprise modules (D365-style)', 'summary' => 'Fourteen config-driven enterprise modules with sub-modules — Business unit, Listing, Product information, Inventory, AP, AR, Budgeting, Bank, Consolidation, Reporting, Landed cost, Master planning, Retail barcode and Documents — each writing to the tenant\'s own database, no storefront required.', 'icon' => 'fa-th-large'),
	array('id' => 'netsuite-d365-ux', 'category' => 'Finance & ERP', 'title' => 'NetSuite dashboard + D365 forms', 'summary' => 'NetSuite-style role dashboard (tiles, KPI gauge, aging chart, quick actions) with Dynamics 365 Finance & Operations inner experience — sliding navigation pane, action-pane command bars, FastTab entry forms and grid list pages across every module.', 'icon' => 'fa-window-maximize'),
	array('id' => 'period-asof-reporting', 'category' => 'Finance & ERP', 'title' => 'Period & as-of-date reporting', 'summary' => 'True point-in-time ERP reporting — inventory on hand, stock value and balances reconstructed as at any date or fiscal period from dated movement ledgers, with From/To period flows on P&L, ledgers and transaction reports. Per-tenant fiscal calendar drives every year.', 'icon' => 'fa-calendar-check-o'),
	array('id' => 'aging-statements', 'category' => 'Finance & ERP', 'title' => 'Aging & statements of account', 'summary' => 'Config-driven AR / AP / inventory aging with per-bucket totals and distribution bars, plus customer and vendor statements of account rendered with tenant letterhead and TRN for collections and audit.', 'icon' => 'fa-clock-o'),

	// UAE e-invoicing & VAT (5)
	array('id' => 'uae-vat-returns', 'category' => 'UAE e-invoicing & VAT', 'title' => 'UAE VAT 201 return (full format)', 'summary' => 'The complete FTA VAT 201 built from posted sales & purchases — Boxes 1a–1g standard-rated per Emirate, tourist refunds, reverse charge, zero-rated, exempt, imports, and net payable/refundable. TRN-aware, reconciles end-to-end, drills down to invoice and transaction level, and prints a professional summary PDF. See External Reporting for the full statutory suite.', 'icon' => 'fa-percent'),
	array('id' => 'peppol-einvoice', 'category' => 'UAE e-invoicing & VAT', 'title' => 'Peppol / PINT-AE e-invoice', 'summary' => 'Generate Peppol-ready e-invoices aligned with UAE PINT-AE requirements — validate, print, and export XML/JSON for FTA readiness. Built into ERP Finance, not a bolt-on.', 'icon' => 'fa-file-code-o'),
	array('id' => 'tax-invoices-trn', 'category' => 'UAE e-invoicing & VAT', 'title' => 'Tax invoices with TRN', 'summary' => 'Tax-inclusive pricing on storefront with seller TRN on invoices visible to clients. Create invoices from orders with legal footer blocks per UAE practice.', 'icon' => 'fa-file-text-o'),
	array('id' => 'credit-notes', 'category' => 'UAE e-invoicing & VAT', 'title' => 'Credit notes & adjustments', 'summary' => 'Issue credit notes linked to original tax invoices for returns and billing corrections. Maintains audit trail required for VAT reporting and client disputes.', 'icon' => 'fa-minus-circle'),
	array('id' => 'fta-xml-export', 'category' => 'UAE e-invoicing & VAT', 'title' => 'FTA XML / JSON export', 'summary' => 'Export e-invoice payloads in formats suitable for Peppol endpoints and FTA compliance workflows. Operators configure seller profile once per tenant in ERP.', 'icon' => 'fa-download'),

	// External Reporting & statutory returns (11)
	array('id' => 'ext-reporting-centre', 'category' => 'External Reporting & statutory returns', 'title' => 'Statutory reporting centre', 'summary' => 'A country-driven report centre that auto-builds filing-ready statutory returns from your ERP data, localized to your registration country (UAE by default: FTA, MOHRE, goAML, MoEC). One catalogue covers tax, financial, audit, HR/WPS, AML and corporate filings — each in the official format with full sample data so nothing is ever blank.', 'icon' => 'fa-landmark'),
	array('id' => 'ext-ct-return', 'category' => 'External Reporting & statutory returns', 'title' => 'Corporate Tax return (full computation)', 'summary' => 'The complete UAE Corporate Tax return under Federal Decree-Law 47/2022 — taxpayer & period, elections/reliefs (Small Business Relief, QFZP 0%/9%, group transfers), accounting profit reconciled to taxable income through add-backs, interest limitation and loss relief, then 0% up to AED 375,000 and 9% above, with six supporting schedules and tax-group/intercompany handling.', 'icon' => 'fa-building'),
	array('id' => 'ext-drill-txn', 'category' => 'External Reporting & statutory returns', 'title' => 'Drill-down to transaction level', 'summary' => 'Every figure on a return is clickable in place: a box or computation line expands to its breakdown, a line expands to its invoices or entries, and a single invoice expands to its individual supply / GL lines — recursively, until you reach the individual transaction behind the number.', 'icon' => 'fa-sitemap'),
	array('id' => 'ext-compliance-engine', 'category' => 'External Reporting & statutory returns', 'title' => 'Built-in compliance engine', 'summary' => 'Each return is validated against the law with PASS / REVIEW / FAIL flags — VAT special schemes (24kt investment gold 0%, B2B gold/diamond reverse charge, residential lease exempt) and CT conditions (non-deductibles, 30% EBITDA interest cap, exempt income, 75% loss relief, transfer pricing) — so nothing is left to check before filing.', 'icon' => 'fa-shield'),
	array('id' => 'ext-period-control', 'category' => 'External Reporting & statutory returns', 'title' => 'Flexible reporting periods', 'summary' => 'Each report carries its own statutory period model — VAT monthly or quarterly, Corporate Tax by financial year (including non-calendar / transitional first periods via a custom range), WPS monthly, financials annual. A Run / Recalculate control rebuilds the return for the exact period selected.', 'icon' => 'fa-calendar'),
	array('id' => 'ext-audit-schedules', 'category' => 'External Reporting & statutory returns', 'title' => 'FTA-style audit-file schedules', 'summary' => 'One-click Excel/CSV supporting schedules in the FTA layout — VAT invoice-wise, customer TRN-wise, supplier-wise and adjustments; CT adjustments, fixed-asset depreciation, exempt income, related-party / transfer pricing, tax losses and foreign tax credit.', 'icon' => 'fa-file-excel-o'),
	array('id' => 'ext-pro-pdf', 'category' => 'External Reporting & statutory returns', 'title' => 'Professional PDF + commentary', 'summary' => 'A colour, MIS-style filing pack with cover page, section numbering, the summary schedules and a plain-language "report explained" commentary on both VAT and CT so a learner understands every figure. Invoice-level detail is excluded so a 10k-invoice tenant still gets a clean summary.', 'icon' => 'fa-file-pdf-o'),
	array('id' => 'ext-offsystem-import', 'category' => 'External Reporting & statutory returns', 'title' => 'Off-system Excel import → return', 'summary' => 'Check or file other clients without touching the ERP: download a multi-sheet Excel template (company & TRN, boxes/lines, invoice detail, compliance, instructions), fill it, upload, and the tool builds the full VAT, Corporate Tax or IFRS financial-statements report and PDF entirely from the uploaded data.', 'icon' => 'fa-upload'),
	array('id' => 'ext-audit-report', 'category' => 'External Reporting & statutory returns', 'title' => 'External Audit Report (ISA 700 / IFRS)', 'summary' => 'A complete IFRS assurance pack with a professional cover page and table of contents: the Independent Auditor\'s Report (opinion, basis for opinion, going concern, key audit matters, responsibilities — ISA 700/701/705/570/720) and all four primary statements with prior-year comparatives — financial position, profit or loss & OCI, changes in equity and cash flows — plus detailed notes referencing each IAS/IFRS standard, drill-down to transaction level and a Fetch button to refresh the standards.', 'icon' => 'fa-certificate'),
	array('id' => 'ext-fin-model', 'category' => 'External Reporting & statutory returns', 'title' => 'Financial model & 5-year forecast', 'summary' => 'A five-year financial model built from the live GL actuals — an explicit assumptions block (growth, margins, capex, working capital, tax, WACC), a projected profit & loss, an EBITDA and free-cash-flow build and key ratios. The free-cash-flow line drives the business valuation so the two stay consistent.', 'icon' => 'fa-line-chart'),
	array('id' => 'ext-valuation', 'category' => 'External Reporting & statutory returns', 'title' => 'Business valuation report', 'summary' => 'Values the business by three methods on the same model — discounted cash flow (WACC + Gordon terminal value), market multiples (EV/EBITDA and P/E) and net assets / book value — with an enterprise-value → equity-value bridge, an indicative range and a central estimate, field guide and commentary.', 'icon' => 'fa-balance-scale'),

	// Document control (4)
	array('id' => 'document-templates', 'category' => 'Document control', 'title' => 'Document templates', 'summary' => 'Branded invoice, delivery note, quote, and contract templates with merge fields from orders and customers. Tax advisory tenants use approval-ready document layouts.', 'icon' => 'fa-file-text'),
	array('id' => 'print-documents', 'category' => 'Document control', 'title' => 'Print documents & PDFs', 'summary' => 'Print or PDF from CP for any operational document — orders, deliveries, statements. Consistent branding across storefront downloads and staff-printed copies.', 'icon' => 'fa-print'),
	array('id' => 'document-library', 'category' => 'Document control', 'title' => 'Document library & archive', 'summary' => 'Store signed contracts, compliance files, and client deliverables per customer or order. Tax and consultancy verticals give clients secure download access from storefront hub.', 'icon' => 'fa-folder-open-o'),
	array('id' => 'legal-footers-trn', 'category' => 'Document control', 'title' => 'Legal footers & TRN blocks', 'summary' => 'Configurable legal text, bank details, and TRN footer on all customer-facing documents. Reduces manual edits when onboarding new UAE entities.', 'icon' => 'fa-gavel'),

	// CRM & customer management (6)
	array('id' => 'crm-pipeline', 'category' => 'CRM & customer management', 'title' => 'CRM pipeline & kanban', 'summary' => 'Native CRM kanban pipeline inside ERP — leads, opportunities, and won deals without a separate CRM subscription. Consultancies and B2B services run sales and billing on one stack.', 'icon' => 'fa-handshake-o'),
	array('id' => 'leads-opportunities', 'category' => 'CRM & customer management', 'title' => 'Leads & opportunities', 'summary' => 'Capture website enquiries as leads and convert to opportunities with value and stage tracking. Won opportunities hint order creation — smooth handoff to commerce.', 'icon' => 'fa-filter'),
	array('id' => 'customer-hub', 'category' => 'CRM & customer management', 'title' => 'Customer management hub', 'summary' => '360° customer view: contacts, orders, balance, documents, and notes in one CP screen. Staff answer client calls without jumping between modules.', 'icon' => 'fa-address-book'),
	array('id' => 'customer-approvals', 'category' => 'CRM & customer management', 'title' => 'Customer approval workflows', 'summary' => 'Approve new B2B accounts, medical institutions, or advisory clients before they can order. Tax and regulated catalogue verticals gate access by design.', 'icon' => 'fa-check-circle'),
	array('id' => 'customer-groups-profiles', 'category' => 'CRM & customer management', 'title' => 'Customer groups & profiles', 'summary' => 'Segment customers for pricing, catalog visibility, and marketing. Profiles drive margin rules and which brands or categories appear on login.', 'icon' => 'fa-users'),
	array('id' => 'activities-followups', 'category' => 'CRM & customer management', 'title' => 'Activities & follow-ups', 'summary' => 'Log calls, meetings, and tasks against leads and customers — nothing falls through after a showroom visit or advisory intake form.', 'icon' => 'fa-calendar-check-o'),

	// AI & automation (5)
	array('id' => 'ai-parts-agent', 'category' => 'AI & automation', 'title' => 'AI parts agent chat', 'summary' => 'Conversational parts expert on the storefront — search by part number, decode VIN, and get guided recommendations. Reduces counter load for auto-parts distributors.', 'icon' => 'fa-robot'),
	array('id' => 'vin-decode-ai', 'category' => 'AI & automation', 'title' => 'AI VIN decode assistance', 'summary' => 'AI-assisted VIN decode narrows vehicle context before catalogue browse — fewer wrong-fit orders and faster workshop self-service.', 'icon' => 'fa-magic'),
	array('id' => 'demand-intelligence', 'category' => 'AI & automation', 'title' => 'Demand intelligence', 'summary' => 'Signals from search, crosses, and order history highlight what to stock and promote. Professional services pack includes demand views for advisory upsell.', 'icon' => 'fa-line-chart'),
	array('id' => 'auto-price-ai', 'category' => 'AI & automation', 'title' => 'Auto Price AI', 'summary' => 'Discover, compare, and import products across market sources — buy from retailers or wholesalers, sell on Noon, Amazon, and eBay. Country-aware sources, margin rules, and one-click catalogue import for every industry.', 'icon' => 'fa-magic'),
	array('id' => 'automation-hooks', 'category' => 'AI & automation', 'title' => 'Automation & integration hooks', 'summary' => 'Event hooks for order placed, stock low, and lead captured — wire email, WhatsApp, or external systems. Foundation for operator-built automations per tenant.', 'icon' => 'fa-bolt'),

	// Marketing & growth (5)
	array('id' => 'marketing-campaigns', 'category' => 'Marketing & growth', 'title' => 'Marketing campaigns hub', 'summary' => 'Plan and track campaigns linked to storefront landing pages and promo codes. Merchandising teams launch seasonal pushes without developer tickets.', 'icon' => 'fa-bullhorn'),
	array('id' => 'growth-strategies', 'category' => 'Marketing & growth', 'title' => 'Ten growth strategies', 'summary' => 'Built-in playbook of ten proven growth tactics — from basket recovery to B2B outreach — with CP guidance per strategy. Agencies show clients a structured marketing layer.', 'icon' => 'fa-lightbulb-o'),
	array('id' => 'promo-merchandising', 'category' => 'Marketing & growth', 'title' => 'Promo & merchandising', 'summary' => 'Hero banners, featured collections, and campaign-driven catalogue highlights on the storefront. UTM-ready URLs for measuring ad spend effectiveness.', 'icon' => 'fa-star'),
	array('id' => 'featured-collections', 'category' => 'Marketing & growth', 'title' => 'Featured collections & banners', 'summary' => 'Curate lookbooks and collection grids — Namshi-style fashion and jewellery gallery layouts ship with industry themes. Mobile-ready grids for Instagram traffic.', 'icon' => 'fa-picture-o'),

	// System & admin (5)
	array('id' => 'users-roles', 'category' => 'System & admin', 'title' => 'Users, groups & roles', 'summary' => 'Role-based CP access for admin, warehouse, finance, and counter staff. Super CP operators stay on platform DB; client staff authenticate on their own domain only.', 'icon' => 'fa-user-secret'),
	array('id' => 'cp-module-packs', 'category' => 'System & admin', 'title' => 'CP module packs per industry', 'summary' => 'Enable or hide entire module packs — commerce, ERP, auto parts, logistics — per tenant. Sidebar groups stay clean; clients only see what their rental includes.', 'icon' => 'fa-cubes'),
	array('id' => 'ssl-dns-assist', 'category' => 'System & admin', 'title' => 'SSL & DNS onboarding assist', 'summary' => 'Let\'s Encrypt certificates and DNS checklists handled on platform infrastructure. Tenants get HTTPS on www.client.com without managing certificates themselves.', 'icon' => 'fa-lock'),
	array('id' => 'storefront-themes', 'category' => 'System & admin', 'title' => 'Storefront theme packages', 'summary' => 'Five production retail and services layouts — automotive, electronics, fashion, jewellery, advisory — with industry-tuned CP chrome. Switch visual style without losing catalogue data.', 'icon' => 'fa-paint-brush'),
	array('id' => 'operator-audit', 'category' => 'System & admin', 'title' => 'Operator audit & platform settings', 'summary' => 'Platform branding, contact JSON presets, and deploy audit for operators. Super CP settings never leak to client hostnames — enforced by hostname routing rules.', 'icon' => 'fa-eye'),

	// Industry templates (9)
	array('id' => 'industry-auto-parts', 'category' => 'Industry templates', 'title' => 'Auto spare parts template', 'summary' => 'VIN-aware catalogue, supplier prices, crosses, procurement, and B2B balances — the full eParts-style stack pre-loaded for parts distributors in UAE & GCC.', 'icon' => 'fa-car'),
	array('id' => 'industry-tax-advisory', 'category' => 'Industry templates', 'title' => 'Tax & advisory template', 'summary' => 'Client portal, VAT workflows, document control, and advisory CRM on one hosted domain — Prime Invest-style layout for tax firms and corporate advisors.', 'icon' => 'fa-balance-scale'),
	array('id' => 'industry-fashion', 'category' => 'Industry templates', 'title' => 'Fashion & beauty template', 'summary' => 'Lookbook collections, variant catalogue, and campaign-ready Namshi-style storefront. Order fulfilment and returns modules aligned to apparel retail.', 'icon' => 'fa-female'),
	array('id' => 'industry-electronics', 'category' => 'Industry templates', 'title' => 'Electronics retail template', 'summary' => 'Virgin-style mega navigation, spec-heavy homepage, and SKU pagination for IT and consumer electronics. RMA and warranty hooks included in pack.', 'icon' => 'fa-plug'),
	array('id' => 'industry-medical', 'category' => 'Industry templates', 'title' => 'Medical supplies template', 'summary' => 'Regulated catalogue, institutional login, batch and expiry fields, and audit-friendly delivery documentation for clinic procurement teams.', 'icon' => 'fa-medkit'),
	array('id' => 'industry-consultancy', 'category' => 'Industry templates', 'title' => 'Consultancy & services template', 'summary' => 'Proposal-to-delivery: CRM, projects, billing, and client-facing hub for management consultancies and professional service firms.', 'icon' => 'fa-briefcase'),
	array('id' => 'industry-rental', 'category' => 'Industry templates', 'title' => 'Rental operations template', 'summary' => 'Rental SKU with daily/monthly periods, deposits, contracts, and monthly billing hooks for fleet, equipment, and commercial leasing businesses.', 'icon' => 'fa-calendar'),
	array('id' => 'industry-jewellery', 'category' => 'Industry templates', 'title' => 'Jewellery & luxury template', 'summary' => 'Kiyasha-style gold and diamond aesthetic, gallery product cards, certificate metadata, and premium enquiry flows for fine jewellers.', 'icon' => 'fa-diamond'),
);
