<?php
/**
 * Customer-facing guide steps for capability detail modals (maps Super CP operator guides).
 * Keys = capability id from epc_ecomae_platform_capabilities_catalog.php
 * Generated by tools/generate_capability_guides.py — edit RICH/STEPS there and regenerate.
 */
defined('_ASTEXE_') or die('No access');

return array(
	'super-cp-console' => array(
		'intro' => 'Run every tenant from one hosted console at ecomae.com/cp — same ECOM AE control panel shell with platform packs. Onboard clients, push templates, and monitor health without exposing operator tools on client domains.', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Sign in at Super CP', 'body' => 'Platform operators open the hosted console — same control panel shell as client sites with tenant orchestration packs in the sidebar.'),
			array('title' => 'Tenant registry overview', 'body' => 'See every client: trade name, hostname, industry, database, and status from draft through live on one screen.'),
			array('title' => 'Deploy industry packs', 'body' => 'Pick vertical, visual style, and enabled module packs — push templates to registered client targets without rebuilding per tenant.'),
			array('title' => 'Monitor health probes', 'body' => 'HTTP checks confirm storefront and CP endpoints respond before flipping a tenant to Live status.'),
		),
	),
	'tenant-hub' => array(
		'intro' => 'Central registry of all clients: trade name, hostname, industry, database, and status from draft through live. One screen to see who is pending DNS, who is live, and who needs attention.', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Open tenant hub', 'body' => 'Super CP → Tenants lists all registered clients with trade name, hostname, industry code, and MySQL database name.'),
			array('title' => 'Filter by status', 'body' => 'Quickly see who is draft, DNS pending, or live — pending DNS and failed probes surface for operator attention.'),
			array('title' => 'Drill into tenant record', 'body' => 'Open a tenant to edit portal settings, industry template, module packs, and deploy audit history.'),
		),
	),
	'tenant-onboarding' => array(
		'intro' => 'Single intro form captures brand, domain, industry, admin email, and tenant MySQL details — seeds portal settings and industry template on save. Most operators go from form to working stack within 24 hours once DNS is...', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Complete intro form', 'body' => 'Capture brand, domain, industry, admin e-mail, and tenant database credentials — portal settings and industry template apply on save.'),
			array('title' => 'Apply industry template', 'body' => 'Nine verticals pre-load CP module packs, storefront package, and visual style — auto parts, tax, fashion, electronics, medical, jewellery, and more.'),
			array('title' => 'Hand off DNS checklist', 'body' => 'Client adds registrar A records; operator attaches domain alias and issues SSL when probes pass.'),
			array('title' => 'Go live within 24 hours', 'body' => 'Most operators reach a working storefront and CP stack within one business day once DNS is pointed.'),
		),
	),
	'dns-launch-checklist' => array(
		'intro' => 'Step-by-step GoDaddy-friendly A-record guide, domain alias on the platform stack, SSL issuance, and status flip to Live when probes pass. Clients keep their registrar — no separate hosting package.', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Registrar A records', 'body' => 'GoDaddy-friendly checklist: client adds @ and www A records pointing to the ECOM AE platform IP — no separate hosting package.'),
			array('title' => 'Domain alias on stack', 'body' => 'Attach hostname as nginx alias on the live platform vhost — same codebase routes to the isolated tenant database by hostname.'),
			array('title' => 'SSL issuance', 'body' => 'Let\'s Encrypt certificates issue on the platform stack — tenants get HTTPS on www.client.com without managing certificates.'),
			array('title' => 'Status flip to Live', 'body' => 'When HTTP probes pass on storefront and /cp/, set tenant status to Live and hand off credentials to the client.'),
		),
	),
	'industry-settings-deploy' => array(
		'intro' => 'Pick vertical, visual style, enabled module packs, and sidebar visibility — then push to a client site when ready. Deploy portal packages to registered targets from Super CP without rebuilding per tenant.', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Pick vertical & visual style', 'body' => 'Super CP → Industry settings selects vertical, storefront theme, and CP chrome — fashion Namshi-style, Virgin electronics, eParts automotive, and more.'),
			array('title' => 'Enable module packs', 'body' => 'Toggle commerce, ERP, auto parts, logistics, procurement, and e-invoice packs per rental tier.'),
			array('title' => 'Push to client site', 'body' => 'Deploy portal packages to registered targets — sidebar groups and enabled modules update without rebuilding the tenant codebase.'),
		),
	),
	'tenant-health-probes' => array(
		'intro' => 'HTTP checks on live tenants confirm storefront and CP endpoints respond before handoff. Track draft → DNS pending → live with confidence that the client site is reachable.', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Configure probe endpoints', 'body' => 'Health checks hit storefront home, CP login, and optional /erp routes for each live tenant hostname.'),
			array('title' => 'Review probe results', 'body' => 'Failed probes highlight tenants needing DNS, SSL, or database attention before customer handoff.'),
			array('title' => 'Go-live gate', 'body' => 'Operators flip status to Live only when all configured probes return HTTP 200.'),
		),
	),
	'business-continuity-failover' => array(
		'intro' => 'Cloud-first operations with a professional backup path when the primary stack hiccups. Shoppers see guided splash screens instead of generic errors while traffic can route to your backup origin.', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Cloud-first operations', 'body' => 'Tenants run on ECOM AE infrastructure day to day — storefront, /cp/, and /erp on the primary cloud stack.'),
			array('title' => 'Guided splash screens', 'body' => 'If the primary stack is unreachable, shoppers see professional step-by-step splash copy instead of generic error pages.'),
			array('title' => 'Operator failover modes', 'body' => 'Platform operators manage connecting to backup, backup online, and restoring cloud from Super CP failover guide.'),
		),
	),
	'multi-tenant-routing' => array(
		'intro' => 'One nginx stack serves many client domains — hostname selects isolated MySQL tenant database and branding. Model C hosting saves disk, ops time, and per-client hosting bills.', 
		'guide_area' => 'overview', 
		'image' => 'guide-super-cp', 
		'steps' => array(
			array('title' => 'Single nginx stack', 'body' => 'One platform nginx vhost serves many client domains — hostname selects tenant context at request time.'),
			array('title' => 'Isolated MySQL per tenant', 'body' => 'Each client domain maps to its own database — catalogue, orders, and ERP data never cross tenants.'),
			array('title' => 'Model C hosting savings', 'body' => 'Shared codebase and ops reduce disk, deployment time, and per-client hosting bills versus separate VPS per shop.'),
		),
	),
	'modular-erp-access' => array(
		'intro' => 'Turn on only the ERP areas each company needs — from a full suite down to Custom & Shipping or People-only deployments. Shared ERP companies on www.ecomae.com use the same login URL with per-company module packs.',
		'guide_area' => 'overview',
		'image' => 'guide-erp-only',
		'steps' => array(
			array('title' => 'Pick modules at onboard', 'body' => 'Tenant hub → Onboard client — tick ERP only + Hosted on ecomae.com (shared). Use ERP module presets or tick individual areas. No client domain required.'),
			array('title' => 'Adjust in Industry settings', 'body' => 'Super CP → Industry settings → ERP modules grid. Select a tenant by site key and Save to push erp_modules_json to that company database.'),
			array('title' => 'Shell hides disabled areas', 'body' => 'Staff only see enabled sidebar groups at www.ecomae.com/cp/shop/finance/erp?epc_erp_shell=1 after company login.'),
			array('title' => 'Separate DB per company', 'body' => 'Add company 2, 3 with new site keys and MySQL databases — same www.ecomae.com/cp/ login; email maps to the correct tenant.'),
		),
	),
	'erp-only-deployment' => array(
		'intro' => 'Deploy finance-led companies with no public e-commerce and no client domain — all ERP-only tenants log in at www.ecomae.com/cp/ with isolated MySQL per company.',
		'guide_area' => 'overview',
		'image' => 'guide-erp-only',
		'steps' => array(
			array('title' => 'Register shared ERP company', 'body' => 'Super CP → Onboard: ERP only + Hosted on ecomae.com. Enter company name and site key only — hostname is www.ecomae.com. No DNS or domain alias.'),
			array('title' => 'Create company MySQL + CP users', 'body' => 'One database per company (asap, company2, …). Create staff in CP → Users. Login email binds the session to that tenant DB automatically.'),
			array('title' => 'Full ERP module packs', 'body' => 'Enable Full ERP or granular areas at onboard. Commerce, catalogue, and storefront packs stay off — sidebar is finance-first.'),
			array('title' => 'Login at www.ecomae.com/cp/', 'body' => 'Hand off https://www.ecomae.com/cp/ or direct ERP shell URL. After login, users land in the professional ERP layout for their company only.'),
			array('title' => 'Multi-company on one URL', 'body' => 'Repeat onboard for each new company with a unique site key and database. Optional company picker if the same email exists in two tenants.'),
			array('title' => 'Super CP stays separate', 'body' => 'Platform operators use the same /cp/ URL with platform credentials → Tenant hub. Company users never see operator tools.'),
		),
	),
	'product-catalogue' => array(
		'intro' => 'Full SKU management with rich product pages, media, and category trees for fashion, electronics, medical, and general retail. Storefront and CP share the same catalogue data — no duplicate entry.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-catalog', 
		'steps' => array(
			array('title' => 'Open product manager', 'body' => 'Shop → Products lists SKUs with categories, media, and stock links — same data powers storefront product pages.'),
			array('title' => 'Rich product pages', 'body' => 'Add descriptions, images, specs, and related items — electronics get datasheet fields; fashion gets size and colour attributes.'),
			array('title' => 'Publish to storefront', 'body' => 'Saved products appear on category trees and search immediately — no duplicate entry between CP and shop theme.'),
		),
	),
	'bulk-csv-import' => array(
		'intro' => 'Upload seasonal collections or thousands of SKUs via CSV — map columns, preview, and commit in minutes. Export for backup, supplier handoff, or marketplace feeds.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-catalog', 
		'steps' => array(
			array('title' => 'Prepare CSV template', 'body' => 'Export a sample from Shop → Products → Export to match column order for title, SKU, category, price, and stock.'),
			array('title' => 'Upload & map columns', 'body' => 'Import wizard maps CSV headers to product fields — preview first rows before commit.'),
			array('title' => 'Commit seasonal collections', 'body' => 'Upload thousands of SKUs for fashion drops or electronics refreshes in minutes instead of manual entry.'),
			array('title' => 'Export for backup or feeds', 'body' => 'Export catalogue for backup, supplier handoff, or marketplace feed generation.'),
		),
	),
	'categories-attributes' => array(
		'intro' => 'Merchandise with nested categories, spec filters, and custom attribute fields. Electronics get datasheet filters; fashion gets size and colour — all configurable per industry.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-catalog', 
		'steps' => array(
			array('title' => 'Nested category trees', 'body' => 'Shop → Products → Categories build parent/child merchandise trees — drag order controls storefront navigation.'),
			array('title' => 'Custom attribute fields', 'body' => 'Add spec filters for electronics, size/colour for fashion, or batch fields for medical — configurable per industry pack.'),
			array('title' => 'Storefront filters', 'body' => 'Category and attribute filters appear on search and browse pages — shoppers narrow results without leaving the catalog.'),
		),
	),
	'variant-skus' => array(
		'intro' => 'Sell products with multiple variants — each with its own SKU, stock, and price. Storefront variant selectors and CP stock-by-variant keep fulfilment accurate.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-catalog', 
		'steps' => array(
			array('title' => 'Create variant matrix', 'body' => 'On product edit, add size, colour, or spec variants — each variant gets its own SKU, stock row, and optional price override.'),
			array('title' => 'Storefront selectors', 'body' => 'Shoppers pick variant options on the product page — cart and checkout carry the exact SKU for fulfilment.'),
			array('title' => 'Stock by variant', 'body' => 'CP stock view and warehouse allocation track quantity per variant — pick lists show the correct SKU on each line.'),
		),
	),
	'supplier-price-upload' => array(
		'intro' => 'Keep trade pricing current by importing supplier files without manual re-keying — map columns, preview, and commit thousands of SKUs in minutes.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-pricing', 
		'steps' => array(
			array('title' => 'Open price upload guide', 'body' => 'In client CP: Shop → Prices → step-by-step guide (blue button on Price lists). Describes every channel that loads data into the price database.'),
			array('title' => 'Choose upload channel', 'body' => 'Manual CSV upload, e-mail inbox auto-import, FTP drop, or pyprices scheduled cron — each price list has a load mode configured on the list settings page.'),
			array('title' => 'Map columns & preview', 'body' => 'Match article, brand, description, price, and stock columns to warehouse fields. Preview rows before commit to catch formatting errors.'),
			array('title' => 'Warehouse & price list link', 'body' => 'Each price list ties to a warehouse/storage — imported stock feeds catalogue availability and live supplier price search on the storefront.'),
			array('title' => 'Verify on storefront', 'body' => 'Search a known part number after import — trade buyers see current rates and quantity badges on results and product pages.'),
		),
	),
	'live-price-search' => array(
		'intro' => 'Search pulls prices from connected suppliers at order time — customers see current trade rates on the storefront. Ideal for parts traders who compete on availability and price.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-search-parts', 
		'steps' => array(
			array('title' => 'Connect supplier price lists', 'body' => 'Link warehouses to imported price lists — search queries pull current trade rates at order time.'),
			array('title' => 'Storefront search results', 'body' => 'Part number and cross-reference searches show price and quantity badges from connected lists.'),
			array('title' => 'Multi-warehouse display', 'body' => 'When the same article exists on multiple lists, results show best price or all sources per theme configuration.'),
		),
	),
	'cross-references' => array(
		'intro' => 'OEM and aftermarket cross tables help customers find interchangeable parts. Cross matches against in-stock SKUs display price and quantity on the search results page.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-search-parts', 
		'steps' => array(
			array('title' => 'Maintain cross tables', 'body' => 'Shop → Prices → Cross references map OEM numbers to aftermarket equivalents — import via CSV or edit inline.'),
			array('title' => 'Search integration', 'body' => 'When a shopper searches an OEM number, cross matches against in-stock SKUs display price and quantity.'),
			array('title' => 'Reduce wrong-part orders', 'body' => 'Workshop buyers find interchangeable parts faster — builds trust and lowers return rates.'),
		),
	),
	'vin-oem-search' => array(
		'intro' => 'Vehicle-aware search widgets decode VIN or accept OEM numbers for precise fitment. Reduces wrong-part orders and builds trust with workshop and fleet buyers.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-search-parts', 
		'steps' => array(
			array('title' => 'Enable search widgets', 'body' => 'Storefront search bar accepts VIN decode or direct OEM/part number entry — auto-parts themes ship with vehicle-aware widgets.'),
			array('title' => 'VIN decode flow', 'body' => 'Decoded VIN narrows make, model, and engine — catalogue browse filters to compatible articles.'),
			array('title' => 'OEM number lookup', 'body' => 'Enter manufacturer part number for precise fitment — results cross-match to in-stock SKUs with live pricing.'),
		),
	),
	'vehicle-catalogue' => array(
		'intro' => 'Browse by make, model, and modification — Epart catalog integration for passenger, commercial, and motorbike segments. Product groups and articles flow into cart and ERP.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-search-parts', 
		'steps' => array(
			array('title' => 'Open Epart catalog', 'body' => 'Shoppers browse by make, model, and modification — passenger, commercial, and motorbike segments from integrated eparts catalog.'),
			array('title' => 'Product groups & articles', 'body' => 'OEM-style categories, technical measurements, and article pages flow into cart and order desk without duplicate data entry.'),
			array('title' => 'Vehicle catalog route', 'body' => 'Optional vehicle catalog page lets buyers pick year → make → model → engine before viewing compatible articles and in-stock prices.'),
		),
	),
	'price-lists-margins' => array(
		'intro' => 'Segment B2B and retail buyers with customer groups, price profiles, and margin rules — retail shelf prices, wholesale CIS/GCC margins, and brand visibility controls from one CP screen.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-pricing', 
		'steps' => array(
			array('title' => 'Customer groups & profiles', 'body' => 'Shop → Customers → Groups and Profiles assign each buyer a segment. Profiles drive which brands and categories appear after login and which margin rule applies.'),
			array('title' => 'Retail vs wholesale margins', 'body' => 'Configure retail mark-up and wholesale discount tiers per profile — CIS and GCC trade accounts can have separate margin tables and fixed dealing currency.'),
			array('title' => 'Price list assignment', 'body' => 'Link customer profiles to price lists (S-UAE, R-UAE, etc.) so logged-in trade buyers see contract rates while guests see standard shelf pricing.'),
			array('title' => 'Show/hide by brand', 'body' => 'Hide premium or restricted brands from retail profiles while exposing full catalog to approved wholesale accounts — useful for distributor and medical verticals.'),
			array('title' => 'Upload wizard & pyprices', 'body' => 'Refresh underlying price lists via Shop → Prices → upload guide — CSV upload, e-mail inbox, FTP, or pyprices cron. Imported rows feed live search and profile-driven margins instantly.'),
		),
	),
	'shopping-cart-checkout' => array(
		'intro' => 'Guest and logged-in checkout with delivery choice, promo codes, and payment at checkout. Orders flow straight into CP order desk and ERP finance — one data path end to end.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-checkout', 
		'steps' => array(
			array('title' => 'Guest or logged-in cart', 'body' => 'Storefront cart persists for logged-in buyers; guests checkout with e-mail capture — promo codes apply at cart review.'),
			array('title' => 'Delivery & payment choice', 'body' => 'Checkout selects obtaining mode, payment type, and contact details — credit limits enforced for trade accounts.'),
			array('title' => 'Order creation', 'body' => 'Confirmed checkout saves to order desk — manager, customer, and supplier LPO notifications fire automatically.'),
			array('title' => 'ERP handoff', 'body' => 'Completed orders feed ERP Revenue and receivables — one data path from storefront to finance.'),
		),
	),
	'order-management' => array(
		'intro' => 'Staff manage order lifecycle from new through packed, shipped, and completed. Status updates trigger customer emails and feed fulfilment and finance modules.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-fulfilment', 
		'steps' => array(
			array('title' => 'Orders list filters', 'body' => 'Shop → Orders — filter by status, office, payment type, article, or date range to find work in the queue.'),
			array('title' => 'Order card intelligence', 'body' => 'Open order number for customer profile, margin totals, line statuses, messages, and order log history.'),
			array('title' => 'Status-driven e-mails', 'body' => 'Configure order and line statuses in Shop → Orders → Statuses — each status can notify manager and/or customer.'),
			array('title' => 'Payment confirmation', 'body' => 'Record payment on the order card or via Finance — advance order status when fully paid.'),
		),
	),
	'order-fulfilment' => array(
		'intro' => 'Move every web order from checkout to supplier LPO, warehouse pick/pack, and ERP recognition without leaving the control panel. Warehouse-aware fulfilment keeps stock, finance, and customer notifications in sync.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-fulfilment', 
		'steps' => array(
			array('title' => 'Order desk pipeline', 'body' => 'New web orders land in Shop → Orders. Staff advance statuses from confirmed through packed and shipped — customer e-mails fire on each configured status change.'),
			array('title' => 'Trade approval before checkout', 'body' => 'Wholesale buyers register on the storefront; checkout stays blocked until CP approves the account and assigns a fixed dealing currency under Users → Customer approvals.'),
			array('title' => 'Automatic checkout notifications', 'body' => 'On order creation, three channels fire: manager alert with CP link, customer confirmation, and supplier LPO e-mail per warehouse — configure templates in Control panel → Notifications.'),
			array('title' => 'Supplier LPO per warehouse', 'body' => 'Each warehouse with order lines receives a purchase request — LPO number equals the customer order ID. Set Supplier order email on Shop → Logistics → Warehouses before go-live.'),
			array('title' => 'Pick, pack & line statuses', 'body' => 'On the order card, confirm payment, update line item statuses (ordered → in stock → shipped → delivered), and message the customer from the Messages tab.'),
			array('title' => 'Delivery notes & obtaining modes', 'body' => 'Generate delivery notes from confirmed orders and configure pickup or courier modes in Shop → Logistics → Obtaining modes. Print-ready documents include line items and delivery details.'),
			array('title' => 'ERP fulfilment tab', 'body' => 'Shop → ERP Finance → Fulfilment shows the visual pipeline: customer payment → supplier payment → goods in stock → delivery → returns. Revenue and payables post when the order is Completed.'),
			array('title' => 'Returns & partial shipments', 'body' => 'Process returns in CP returns module — goods return to stock then to supplier if needed. Partial shipments stay traceable via line-level statuses and order log entries.'),
		),
	),
	'delivery-notes' => array(
		'intro' => 'Generate delivery notes and pick lists from confirmed orders — print-ready documents with line items, weights, and customer delivery details.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-fulfilment', 
		'steps' => array(
			array('title' => 'Generate from confirmed order', 'body' => 'On order card, print delivery note with line items, weights, and customer delivery address.'),
			array('title' => 'Pick list alignment', 'body' => 'Pick lists group warehouse lines for floor staff — same SKU and quantity as delivery note for audit.'),
			array('title' => 'Branded PDF output', 'body' => 'Document templates merge company logo, TRN footer, and bank details — consistent with invoice layouts.'),
		),
	),
	'returns-rma' => array(
		'intro' => 'Process returns and warranty claims with status tracking and stock put-back. Electronics and medical verticals get serial and batch fields for audit-friendly RMA.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-fulfilment', 
		'steps' => array(
			array('title' => 'Customer initiates return', 'body' => 'Storefront returns form or CP manual RMA captures reason, serial/batch if required, and linked order lines.'),
			array('title' => 'RMA status tracking', 'body' => 'Staff advance return statuses — received, inspected, credited — with optional customer e-mail on each step.'),
			array('title' => 'Stock put-back', 'body' => 'Approved returns increment warehouse stock; credit notes link to original tax invoice for VAT audit trail.'),
		),
	),
	'whatsapp-order-share' => array(
		'intro' => 'Share cart or order summaries via WhatsApp for quick B2B confirmation. Popular with UAE and GCC traders who close deals on mobile messaging.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-checkout', 
		'steps' => array(
			array('title' => 'Share from cart or order', 'body' => 'Storefront share button sends cart summary or order confirmation via WhatsApp deep link — popular with UAE B2B traders.'),
			array('title' => 'Mobile-friendly format', 'body' => 'Shared message includes part numbers, quantities, and totals for quick buyer confirmation on mobile.'),
			array('title' => 'Close on messaging', 'body' => 'Counter staff follow up in WhatsApp then convert to CP order if the buyer confirms — same fulfilment pipeline applies.'),
		),
	),
	'promo-discount-rules' => array(
		'intro' => 'Campaign promo codes, cart rules, and tiered discounts drive conversion on the storefront. Link promotions to marketing campaigns for measurable uplift.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-checkout', 
		'steps' => array(
			array('title' => 'Create promo codes', 'body' => 'Shop → Marketing → Promotions define codes, percentage or fixed discount, date range, and minimum cart value.'),
			array('title' => 'Cart rules & tiers', 'body' => 'Tiered discounts apply automatically when cart crosses thresholds — link campaigns to UTM landing pages for measurement.'),
			array('title' => 'Storefront application', 'body' => 'Shoppers enter code at checkout or see auto-applied tier — discount flows to order totals and ERP revenue.'),
		),
	),
	'b2b-trade-accounts' => array(
		'intro' => 'Logged-in trade buyers get fixed currency, credit limits, balance view, and re-order from history. Auto-parts and wholesale tenants rely on this for repeat B2B cycles.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-checkout', 
		'steps' => array(
			array('title' => 'Wholesale registration', 'body' => 'Buyers choose Wholesale at registration — checkout blocked until CP approves under Users → Customer approvals.'),
			array('title' => 'Fixed currency & credit', 'body' => 'Assign dealing currency and credit limit on approval — balance and limit visible in client CP login.'),
			array('title' => 'Re-order from history', 'body' => 'Logged-in trade buyers re-order from past invoices — contract pricing from their profile applies automatically.'),
		),
	),
	'payment-gateways' => array(
		'intro' => 'Configure card and local payment gateways for UAE and GCC checkout. Gateway settings live in CP — test mode and live credentials per tenant.', 
		'guide_area' => 'payments', 
		'image' => 'guide-payments', 
		'steps' => array(
			array('title' => 'Open payments guide', 'body' => 'Shop → Finance → Payments guide walks gateway setup for UAE and GCC card and local payment methods.'),
			array('title' => 'Test vs live credentials', 'body' => 'Enter merchant ID, API keys, and webhook URLs — toggle test mode before go-live checkout.'),
			array('title' => 'Checkout integration', 'body' => 'Enabled gateways appear at storefront checkout — successful payments mark order paid and trigger notifications.'),
		),
	),
	'multi-currency' => array(
		'intro' => 'Show prices and accept payment in multiple currencies for cross-border and tourist retail. Exchange display rules configurable per storefront theme.', 
		'guide_area' => 'payments', 
		'image' => 'guide-payments', 
		'steps' => array(
			array('title' => 'Configure display currencies', 'body' => 'Shop → Settings → Currencies add AED, USD, SAR, and others — set display rules per storefront theme.'),
			array('title' => 'Checkout currency', 'body' => 'Logged-in trade buyers checkout in assigned dealing currency; tourist retail can show converted display prices.'),
			array('title' => 'ERP reporting', 'body' => 'Finance reports remain in base currency with order-level currency captured for audit.'),
		),
	),
	'payment-reconciliation' => array(
		'intro' => 'Match gateway settlements to orders and ERP receipts — reduce manual spreadsheet work for finance teams. Discrepancies surface in CP for quick resolution.', 
		'guide_area' => 'payments', 
		'image' => 'guide-payments', 
		'steps' => array(
			array('title' => 'Import gateway settlements', 'body' => 'Match gateway batch files to CP orders — unmatched items surface for finance review.'),
			array('title' => 'ERP receipt posting', 'body' => 'Confirmed matches post customer receipts in ERP Cash & bank — reduces manual spreadsheet reconciliation.'),
			array('title' => 'Discrepancy resolution', 'body' => 'Short payments and chargebacks flag on order card for staff follow-up before month-end close.'),
		),
	),
	'customer-balance-credit' => array(
		'intro' => 'Track trade account balances and enforce credit limits at checkout. B2B clients see running balance in client CP; staff approve overrides in order desk.', 
		'guide_area' => 'payments', 
		'image' => 'guide-payments', 
		'steps' => array(
			array('title' => 'Prepaid ledger', 'body' => 'Shop → Finance → Customer accounts track credit top-ups and order debits per trade buyer.'),
			array('title' => 'Credit limit at checkout', 'body' => 'Checkout blocks orders exceeding available balance plus approved credit limit — staff override in order desk if needed.'),
			array('title' => 'Client CP balance view', 'body' => 'Logged-in B2B clients see running balance and recent movements on storefront account page.'),
		),
	),
	'payment-batches' => array(
		'intro' => 'Batch outgoing supplier and expense payments from ERP treasury — approve, schedule, and audit payment runs from finance roles.', 
		'guide_area' => 'payments', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Open ERP treasury', 'body' => 'Shop → ERP Finance → Cash & bank — create payment batch for supplier or expense runs.'),
			array('title' => 'Approve & schedule', 'body' => 'Finance role selects payables lines, approves batch, and schedules settlement date.'),
			array('title' => 'Audit trail', 'body' => 'Batch history logs who approved, which suppliers paid, and GL postings for month-end audit.'),
		),
	),
	'warehouses-storages' => array(
		'intro' => 'Master warehouse and storage locations with stock allocation per site. Multi-warehouse inventory feeds catalogue availability and checkout delivery options.', 
		'guide_area' => 'logistics', 
		'image' => 'guide-logistics', 
		'steps' => array(
			array('title' => 'Master warehouse list', 'body' => 'Shop → Logistics → Warehouses defines storage locations, linked price lists, and LPO supplier e-mail per site.'),
			array('title' => 'Stock allocation', 'body' => 'Each SKU row ties to a warehouse — catalogue availability and checkout delivery options reflect per-site quantity.'),
			array('title' => 'Multi-warehouse orders', 'body' => 'Orders with lines from multiple warehouses trigger separate supplier LPO e-mails — one per warehouse.'),
		),
	),
	'carriers-shipments' => array(
		'intro' => 'Manage carrier accounts, shipment creation, and tracking references. Logistics hub ties customer orders to outbound shipments and delivery documentation.', 
		'guide_area' => 'logistics', 
		'image' => 'guide-logistics', 
		'steps' => array(
			array('title' => 'Carrier accounts', 'body' => 'Logistics hub stores carrier API credentials and service codes — create shipment from confirmed order.'),
			array('title' => 'Tracking references', 'body' => 'Outbound shipments capture AWB or tracking number — customer notification optional on dispatch status.'),
			array('title' => 'Delivery documentation', 'body' => 'Shipment links to delivery note and order card — logistics reports show carrier performance.'),
		),
	),
	'delivery-methods' => array(
		'intro' => 'Configure courier, branch pickup, and service-area rules on the storefront. Customers choose delivery at checkout; lead times display on SKU where configured.', 
		'guide_area' => 'logistics', 
		'image' => 'guide-logistics', 
		'steps' => array(
			array('title' => 'Obtaining modes', 'body' => 'Shop → Logistics → Obtaining modes configure courier, branch pickup, and service-area delivery rules.'),
			array('title' => 'Checkout selection', 'body' => 'Customers choose delivery or pickup at checkout — lead times display on SKU where configured.'),
			array('title' => 'Fee rules', 'body' => 'Flat or weight-based delivery fees apply per mode — free delivery thresholds configurable per campaign.'),
		),
	),
	'branch-offices' => array(
		'intro' => 'Maintain branch offices and pickup points shown on storefront and delivery notes. Useful for multi-location retailers and parts distributors with counter collection.', 
		'guide_area' => 'logistics', 
		'image' => 'guide-logistics', 
		'steps' => array(
			array('title' => 'Branch master data', 'body' => 'Maintain branch name, address, hours, and map coordinates — shown on storefront contact and pickup selector.'),
			array('title' => 'Pickup at branch', 'body' => 'Link branches to obtaining modes — delivery notes and e-mails show collection point details.'),
			array('title' => 'Multi-location retail', 'body' => 'Fashion and parts distributors display nearest counter for click-and-collect orders.'),
		),
	),
	'logistics-reports' => array(
		'intro' => 'Operational reports on fulfilment throughput, carrier performance, and stock by location. Export-friendly views for warehouse managers and operators.', 
		'guide_area' => 'logistics', 
		'image' => 'guide-logistics', 
		'steps' => array(
			array('title' => 'Fulfilment throughput', 'body' => 'Reports show orders packed and shipped by period, warehouse, and carrier — export for warehouse managers.'),
			array('title' => 'Stock by location', 'body' => 'Inventory snapshot per warehouse supports replenishment decisions and cycle counts.'),
			array('title' => 'Carrier performance', 'body' => 'Delivery SLA and exception counts help negotiate carrier contracts.'),
		),
	),
	'custom-shipping-declarations' => array(
		'intro' => 'UAE customs declaration registry mapped from the C&L Excel format — 36 declaration types across import, export, transit, temporary admission, and transfer, plus LGP warehouse intake. Dashboard KPIs, category lists, core field capture, and Phase 2 reports (search, cost summary, duty stub, re-export, document expiry) are live in ERP.', 
		'guide_area' => 'logistics', 
		'image' => 'guide-custom-shipping', 
		'steps' => array(
			array('title' => 'Open Custom & Shipping dashboard', 'body' => 'In client CP go to ERP Suite → Custom & Shipping (sidebar group) or Shop → Finance → ERP with area custom_shipping. The dashboard shows total, draft, submitted, and cleared counts plus six category cards.'),
			array('title' => 'Review declaration categories', 'body' => 'Import (12 types), Export (13), Transit (6), Temporary Admission (3), Transfer (2), and LGP warehouse intake each have their own card with live counts. Click a card to list declarations in that category.'),
			array('title' => 'Start from quick action or type list', 'body' => 'Use quick actions for Import to Local from ROW, Export from Local to ROW, FZ transit in, or New LGP entry — or open a category and pick any of the 36 registered declaration types from the Excel workbook.'),
			array('title' => 'Fill core required fields', 'body' => 'Every customs declaration requires Company, Customs emirate (Dubai, Sharjah, Abu Dhabi, etc.), Declaration type, Date, and Declaration date. Add B/L #, SRV #, supplier detail, currency, and invoice amount from your customs paperwork.'),
			array('title' => 'Import workflow fields', 'body' => 'Import declarations add supplier code (customs), custom inspection flag, and D365 PO reference — matching the Excel import columns for local, FZ, CW, and courier entries.'),
			array('title' => 'Multiple HS code line items', 'body' => 'Use the declaration line items grid to add one row per HS code: country of origin, quantity, unit (PCS, KG, etc.), volume (CBM), amount, and optional weight. Totals sum qty, volume, and amount; lists show item count per declaration.'),
			array('title' => 'Export, transit & transfer fields', 'body' => 'Export, transit, temporary admission, and transfer types capture import (re-export) declaration ref #, document expiry date, D365 SO reference, customer ref, and customer country where applicable on re-export and return flows.'),
			array('title' => 'LGP warehouse intake', 'body' => 'LGP entries use a dedicated form: customer ref, cargo source, goods coming from, warehouse name/number, local company, purpose of entry, packing list, and commercial invoice are required. Use line items for multiple HS codes, weights, volumes, and values.'),
			array('title' => 'Save draft and submit', 'body' => 'Click Save draft while paperwork is in progress. Open the saved record from the category list, review captured fields, then Submit when filed with UAE customs. Status flows draft → submitted → cleared.'),
			array('title' => 'Run declaration reports', 'body' => 'Open Reports from the Custom & Shipping dashboard. Use Declaration search to filter by date, type, category, company, emirate, and status — or search by declaration #, supplier, and SRV/shipment no. Export CSV or print results.'),
			array('title' => 'Cost summary and duty stub', 'body' => 'Cost summary aggregates invoice amount, total cost, and line-item amounts by company and category. Duty report lists HS codes and origins per line with declaration totals — full duty calculation arrives in a later phase.'),
			array('title' => 'Re-export and document expiry', 'body' => 'Re-export tracking shows import-for-re-export and re-export declarations with links to the original import ref #. Document expiry lists overdue and upcoming expiry dates within a configurable day window.'),
		),
	),
	'omnichannel-hub' => array(
		'intro' => 'Central hub for selling beyond your own storefront — connect marketplaces and sales channels from one CP screen. Orders from all channels land in the same order desk.', 
		'guide_area' => 'channels', 
		'image' => 'guide-channels', 
		'steps' => array(
			array('title' => 'Open channels hub', 'body' => 'Shop → Channels centralises marketplace and aggregator connections — one screen for all non-web sales routes.'),
			array('title' => 'Unified order desk', 'body' => 'Orders from every connected channel land in the same Shop → Orders queue — no separate middleware inbox.'),
			array('title' => 'Shared inventory truth', 'body' => 'Catalogue and stock updates push to channels — reduce overselling with single warehouse allocation.'),
		),
	),
	'channel-integrations' => array(
		'intro' => 'Enable marketplace and aggregator integrations per industry pack. Fashion, electronics, and auto-parts tenants extend reach without separate middleware hosting.', 
		'guide_area' => 'channels', 
		'image' => 'guide-channels', 
		'steps' => array(
			array('title' => 'Enable channel pack', 'body' => 'Industry settings enable marketplace integrations per vertical — fashion, electronics, and auto-parts packs differ.'),
			array('title' => 'Connect credentials', 'body' => 'Enter marketplace API keys and seller IDs in Channels guide — test listing before production sync.'),
			array('title' => 'Operator fix queue', 'body' => 'Listing errors surface in Channels guide for operator correction without developer tickets.'),
		),
	),
	'marketplace-listings' => array(
		'intro' => 'Push catalogue and stock updates to connected channels — reduce overselling with shared inventory truth. Listing errors surface in channels guide for operator fix.', 
		'guide_area' => 'channels', 
		'image' => 'guide-channels', 
		'steps' => array(
			array('title' => 'Catalogue sync', 'body' => 'Push active SKUs, titles, images, and stock levels to connected marketplaces on schedule or on demand.'),
			array('title' => 'Price rules per channel', 'body' => 'Optional channel-specific margin or rounding rules — base price from same CP catalogue.'),
			array('title' => 'Error monitoring', 'body' => 'Failed listing updates log in Channels hub — fix category mapping or attribute gaps in CP.'),
		),
	),
	'channel-order-routing' => array(
		'intro' => 'External channel orders route into the same fulfilment and ERP pipeline as web orders. One pick/pack workflow regardless of where the sale originated.', 
		'guide_area' => 'channels', 
		'image' => 'guide-channels', 
		'steps' => array(
			array('title' => 'Inbound order import', 'body' => 'Marketplace orders import with channel reference — line items map to warehouse SKUs automatically.'),
			array('title' => 'Same fulfilment pipeline', 'body' => 'Pick, pack, LPO, and ERP recognition follow identical steps as web orders — staff need one workflow.'),
			array('title' => 'Status sync back', 'body' => 'Shipped and delivered statuses optionally push tracking back to the originating channel.'),
		),
	),
	'supplier-directory' => array(
		'intro' => 'Maintain supplier master data — contacts, terms, and linked price files. Auto-parts and wholesale tenants manage dozens of suppliers from one procurement hub.', 
		'guide_area' => 'procurement', 
		'image' => 'guide-procurement', 
		'steps' => array(
			array('title' => 'Procurement hub', 'body' => 'Shop → Procurement → Suppliers maintains legal name, TRN, contacts, payment terms, and linked warehouses.'),
			array('title' => 'Price list association', 'body' => 'Link supplier to price lists for LPO routing — operational purchasing separate from warehouse stock source.'),
			array('title' => 'Dozens of suppliers', 'body' => 'Auto-parts and wholesale tenants manage full supplier roster without spreadsheet master data.'),
		),
	),
	'purchase-orders' => array(
		'intro' => 'Create and track POs from requisition through receipt. PO lines link to ERP payables and three-way match when finance pack is active.', 
		'guide_area' => 'procurement', 
		'image' => 'guide-procurement', 
		'steps' => array(
			array('title' => 'Create PO', 'body' => 'Procurement → Purchase orders — add lines from requisition or generate from low-stock signals.'),
			array('title' => 'Approval workflow', 'body' => 'Draft → approved → sent → received statuses track buy-side lifecycle with e-mail to supplier optional.'),
			array('title' => 'ERP payables link', 'body' => 'Received PO lines feed ERP payables and three-way match when finance pack is active.'),
		),
	),
	'rfq-quotes' => array(
		'intro' => 'Request quotes from multiple suppliers and compare responses before committing to a PO. Built for project-based and MRO procurement workflows.', 
		'guide_area' => 'procurement', 
		'image' => 'guide-procurement', 
		'steps' => array(
			array('title' => 'Issue RFQ', 'body' => 'Create request for quote with line specs — send to multiple suppliers from procurement hub.'),
			array('title' => 'Compare responses', 'body' => 'Record supplier quotes side by side — select winner and convert to PO in one click.'),
			array('title' => 'Project & MRO buying', 'body' => 'Built for project-based procurement where price and lead time vary by supplier bid.'),
		),
	),
	'three-way-match' => array(
		'intro' => 'Match purchase order, goods receipt, and supplier invoice before payment approval. Reduces duplicate payments and catches quantity or price variances early.', 
		'guide_area' => 'procurement', 
		'image' => 'guide-procurement', 
		'steps' => array(
			array('title' => 'Three documents', 'body' => 'Match purchase order, goods receipt note (GRN), and supplier invoice quantities and prices before payment.'),
			array('title' => 'Variance flags', 'body' => 'Quantity or price mismatches block payment approval — finance resolves with procurement before posting.'),
			array('title' => 'Reduce duplicate pay', 'body' => 'Catches double billing and short shipments early — audit-friendly for UAE trading entities.'),
		),
	),
	'supplier-payments' => array(
		'intro' => 'Track amounts owed to suppliers and schedule settlement from ERP payables tab. Aging reports help finance prioritise cash outflows.', 
		'guide_area' => 'procurement', 
		'image' => 'guide-procurement', 
		'steps' => array(
			array('title' => 'Payables aging', 'body' => 'ERP → Supplier payables shows amounts owed by supplier and due date — aging report prioritises cash outflows.'),
			array('title' => 'Record payment', 'body' => 'Post supplier payment from payables tab — reduces balance and posts cash/bank GL entry automatically.'),
			array('title' => 'Payment batches', 'body' => 'Group multiple supplier payments into treasury batch for single bank transfer and approval run.'),
		),
	),
	'procurement-workflows' => array(
		'intro' => 'End-to-end buy-side process from demand signal through PO, receipt, and invoice. Integrated with auto-parts SAO and ERP purchasing areas.', 
		'guide_area' => 'procurement', 
		'image' => 'guide-procurement', 
		'steps' => array(
			array('title' => 'Demand to PO', 'body' => 'Low stock, SAO signals, or manual requisition start the buy-side process in Procurement panel.'),
			array('title' => 'Receipt & GRN', 'body' => 'Goods receipt updates warehouse stock and feeds three-way match when supplier invoice arrives.'),
			array('title' => 'Auto-parts SAO integration', 'body' => 'API warehouse lines may trigger supplier auto-order workflows alongside LPO e-mail path.'),
		),
	),
	'erp-dashboard' => array(
		'intro' => 'One finance dashboard for revenue, margin, receivables, payables, and cash — plus a cross-department workflow view for growing UAE trading businesses.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Open ERP Finance', 'body' => 'Client CP → Shop → ERP Finance. Set From/To dates and review KPI cards: revenue MTD, margin, receivable due, payable balance, and cash total.'),
			array('title' => 'Sales → revenue → receivable flow', 'body' => 'Completed orders feed Revenue tab; customer payments reduce receivable; prepaid ledger balance shows on Customer receivables with per-customer statements.'),
			array('title' => 'Purchase → payable → cash flow', 'body' => 'Procurement purchase bills increase supplier payable; Record supplier payment posts cash outflow and reduces AP — all visible on Payables and Cash & bank tabs.'),
			array('title' => 'COA, GL, P&L & balance sheet', 'body' => 'Chart of accounts lists assets through expenses; GL journals post from orders and manual entries; P&L and Balance sheet tabs export period reports for advisors.'),
			array('title' => 'Fulfilment & inventory tabs', 'body' => 'Fulfilment pipeline visualises operations stages; Inventory tab tracks multi-warehouse weighted average cost with purchase receipts and sales issues.'),
			array('title' => 'CRM inside ERP', 'body' => 'Pipeline kanban, quotes, and support tickets live in the same ERP module — consultancies run sales and billing without a separate CRM subscription.'),
		),
	),
	'general-ledger' => array(
		'intro' => 'Double-entry GL with journal entries, period close, and audit-friendly posting history. Commerce and ERP share customer and SKU master data — no re-keying invoices.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-gl', 
		'steps' => array(
			array('title' => 'GL journal list', 'body' => 'ERP → GL tab shows posted journals with debit/credit lines — filter by date and source document.'),
			array('title' => 'Auto-post from sub-ledgers', 'body' => 'Sales orders, purchase bills, and cash entries post balanced journals — Sync unposted catches backlog.'),
			array('title' => 'Manual journals', 'body' => 'Finance enters balanced debit/credit lines for adjustments — Post journal writes to GL with audit user stamp.'),
		),
	),
	'chart-of-accounts' => array(
		'intro' => 'Configure COA structure for UAE trading, services, and multi-department businesses. Opening balances migration supported for tenants moving from spreadsheets.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-gl', 
		'steps' => array(
			array('title' => 'COA structure', 'body' => 'ERP → Chart of accounts lists codes: assets 1xxx, liabilities 2xxx, equity 3xxx, revenue 4xxx, expenses 5xxx/6xxx.'),
			array('title' => 'UAE trading defaults', 'body' => 'Industry template seeds COA suited to UAE trading and services — edit or extend per department.'),
			array('title' => 'Opening balances', 'body' => 'Opening balances tab supports migration date cutover from spreadsheets or prior system.'),
		),
	),
	'cash-bank-treasury' => array(
		'intro' => 'Manage bank accounts, petty cash, and treasury movements in one finance area. Payment batches and reconciliation tie back to GL automatically.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Bank accounts', 'body' => 'ERP → Cash & bank — create main cash, current accounts, and petty cash with opening balances.'),
			array('title' => 'Receipts & payments', 'body' => 'Post customer receipts and expense payments — supplier payments auto-post from payables module.'),
			array('title' => 'Account balance', 'body' => 'Running balance = opening + receipts − payments — ties to GL cash accounts on reconciliation.'),
		),
	),
	'bank-reconciliation' => array(
		'intro' => 'Match bank statement lines to ERP receipts and payments — flag unmatched items for review. Monthly recon workflow keeps books aligned with actual cash.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-gl', 
		'steps' => array(
			array('title' => 'Import statement', 'body' => 'Upload or enter bank statement lines for the period — unmatched ERP entries highlight in review queue.'),
			array('title' => 'Match lines', 'body' => 'Link statement lines to ERP receipts and payments — flag items needing investigation.'),
			array('title' => 'Monthly close', 'body' => 'Reconciled accounts confirm books align with actual cash before P&L and VAT reporting.'),
		),
	),
	'receivables' => array(
		'intro' => 'Track customer invoices, receipts, and aging from sales orders through collection. B2B trade balances sync with storefront client login where configured.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Customer receivables tab', 'body' => 'ERP lists customers with ledger balance and open order due — click Statement for full history.'),
			array('title' => 'Order-level due', 'body' => 'Revenue tab shows unpaid completed orders incl. VAT — payments reduce due on order card or finance ops.'),
			array('title' => 'Adjustments & write-offs', 'body' => 'Customer adjustment form handles settlements and write-offs with optional GL post to AR accounts.'),
		),
	),
	'inventory-valuation' => array(
		'intro' => 'Multi-warehouse stock with purchase receipts, sales issues, and weighted average costing. Perishable expiry and batch fields for FMCG and medical supplies.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Multi-warehouse stock', 'body' => 'ERP → Inventory shows quantity and weighted average cost per warehouse and SKU.'),
			array('title' => 'Purchase receipts', 'body' => 'Goods receipt increases stock and updates average cost — sales issues reduce quantity on shipment.'),
			array('title' => 'Batch & expiry', 'body' => 'Medical and FMCG packs add batch and expiry fields — FEFO picking supported in fulfilment workflow.'),
		),
	),
	'fixed-assets' => array(
		'intro' => 'Asset register with straight-line and declining depreciation, monthly runs, and net book value reports. Tracking IDs and locations support audit and fleet operators.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Asset register', 'body' => 'ERP → Fixed assets — add assets with cost, useful life, location, and tracking ID.'),
			array('title' => 'Depreciation run', 'body' => 'Straight-line or declining methods — monthly run posts depreciation to GL and updates net book value.'),
			array('title' => 'NBV reports', 'body' => 'Export asset schedule for auditors and fleet operators — disposal workflow removes from register.'),
		),
	),
	'pl-balance-sheet' => array(
		'intro' => 'Standard financial statements from posted GL — filter by period and export for advisors. Tax firms use this alongside VAT return data for client reporting.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'P&L tab', 'body' => 'Select period — total revenue minus expenses equals net profit; drill to GL account detail.'),
			array('title' => 'Balance sheet', 'body' => 'Assets, liabilities, and equity as of end date — current period earnings included in equity.'),
			array('title' => 'Export for advisors', 'body' => 'Filter by period and export — tax firms combine with VAT return data for client reporting.'),
		),
	),
	'erp-workflow' => array(
		'intro' => 'Visual workflow across sales, purchasing, finance, and operations — see bottlenecks before month-end. Native ERP tabs replace disconnected spreadsheets for growing tenants.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Cross-department view', 'body' => 'ERP workflow tab visualises sales, purchasing, finance, and operations stages — spot bottlenecks before month-end.'),
			array('title' => 'Native ERP tabs', 'body' => 'Replace disconnected spreadsheets — revenue, payables, inventory, and CRM share one database.'),
			array('title' => 'Standalone /erp portal', 'body' => 'Optional client finance portal at /erp for teams who need finance access without full CP.'),
		),
	),
	'multi-company-erp-access' => array(
		'intro' => 'One hosted tenant serves multiple legal entities — each staff user signs in with username and password, company-scoped customs data and reports stay separate, and ERP tabs respect department roles.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-erp-finance', 
		'steps' => array(
			array('title' => 'Create users per company team', 'body' => 'Control panel → Users → add finance, logistics, and customs staff with individual username/password credentials. Assign backend groups for admin, finance, warehouse, or read-only roles.'),
			array('title' => 'Role-based ERP tabs', 'body' => 'After sign-in at /erp or the ERP shell, users see only permitted areas — GL, payables, Custom & Shipping, and reports based on their group membership.'),
			array('title' => 'Company field on declarations', 'body' => 'Custom & Shipping captures Company on every customs entry — import, export, transit, LGP, and transfer forms all require the legal entity name for multi-company tracking.'),
			array('title' => 'Filter reports by company', 'body' => 'Open Custom & Shipping → Reports → Declaration search. Set the company filter (cs_company) to isolate one entity\'s declarations, then export CSV or print.'),
			array('title' => 'Cost summary by company', 'body' => 'Cost summary report aggregates invoice amount, total cost, and line-item amounts grouped by company and category — compare entities without separate databases.'),
			array('title' => 'Multi-entity consolidation', 'body' => 'ERP → Multi-entity tab (when enabled) prepares inter-company eliminations and group reporting — entity switcher and consolidated P&L expand in later platform packs.'),
		),
	),
	'uae-vat-returns' => array(
		'intro' => 'Prepare VAT return data from posted sales and purchases with TRN-aware totals. Export-friendly views for tax advisors and in-house finance on UAE mainland entities.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-einvoice', 
		'steps' => array(
			array('title' => 'Posted sales & purchases', 'body' => 'VAT return data aggregates from posted ERP sales and purchase documents with TRN-aware totals.'),
			array('title' => 'Output vs input VAT', 'body' => 'Standard-rated, zero-rated, and exempt lines separated — 5% UAE VAT on taxable supplies.'),
			array('title' => 'Advisor export', 'body' => 'Export-friendly views for in-house finance or external tax advisors on UAE mainland entities.'),
		),
	),
	'peppol-einvoice' => array(
		'intro' => 'Issue UAE PINT-AE e-invoices from ERP Finance — Peppol-ready XML with TRN validation, document types 380/381, and a readiness checklist before ASP submission. Built into the finance module, not a separate bolt-on.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-einvoice', 
		'steps' => array(
			array('title' => 'Open E-Invoicing tab', 'body' => 'In client CP go to Shop → ERP Finance → E-Invoicing. The dashboard shows validated, submitted, and accepted counts plus a readiness checklist for go-live.'),
			array('title' => 'Configure seller profile', 'body' => 'Enter legal name, TRN, TIN, UAE address, Peppol endpoint (0235 scheme), bank details, and payment terms under Seller profile. TRN drives TIN auto-fill for FTA compliance.'),
			array('title' => 'Buyer Peppol endpoints', 'body' => 'For B2B buyers, capture Peppol endpoint IDs under Buyer Peppol. Use deemed-supply and export endpoint codes where transaction flags require them.'),
			array('title' => 'Document types 380 and 381', 'body' => 'Tax invoices use type code 380; credit notes reference the original invoice with type 381. Commercial invoices follow the same PINT-AE specification ID urn:peppol:pint:billing-1@ae-1.'),
			array('title' => 'Generate from completed orders', 'body' => 'From E-Invoicing → Generate or the Revenue tab, build an e-invoice from a completed order — line items, VAT breakdown, and buyer TRN pull from order and customer master data.'),
			array('title' => '51-field validation before submit', 'body' => 'The system validates all PINT-AE mandatory fields — seller and buyer TRN, addresses, line tax categories, totals, and payment means — before status moves from draft to validated.'),
			array('title' => 'Download PINT-AE XML / JSON', 'body' => 'Validated documents export Peppol XML and JSON payloads suitable for your Accredited Service Provider. Print PDF tax invoices for customer delivery in parallel.'),
			array('title' => 'ASP submission & FTA timeline', 'body' => 'Connect your ASP under ASP & FTA settings. Voluntary e-invoicing from 1 Jul 2026; mandatory phased from 1 Jan 2027 for entities with revenue ≥ AED 50M. FTA reporting runs through your ASP after validation.'),
		),
	),
	'tax-invoices-trn' => array(
		'intro' => 'Tax-inclusive pricing on storefront with seller TRN on invoices visible to clients. Create invoices from orders with legal footer blocks per UAE practice.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-einvoice', 
		'steps' => array(
			array('title' => 'Seller TRN on documents', 'body' => 'Configure TRN in company settings and e-invoice seller profile — appears on all customer tax invoices.'),
			array('title' => 'Tax-inclusive storefront', 'body' => 'Display prices incl. VAT where required — invoice breakdown shows ex-VAT, VAT, and incl-VAT totals.'),
			array('title' => 'Create from order', 'body' => 'Completed orders generate tax invoices with legal footer blocks per UAE practice — print or e-mail to client.'),
		),
	),
	'credit-notes' => array(
		'intro' => 'Issue credit notes linked to original tax invoices for returns and billing corrections. Maintains audit trail required for VAT reporting and client disputes.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-einvoice', 
		'steps' => array(
			array('title' => 'Link to original invoice', 'body' => 'Issue credit note referencing original tax invoice number — document type 381 in PINT-AE.'),
			array('title' => 'Returns & billing fixes', 'body' => 'Partial or full credit for returns, pricing corrections, or goodwill — maintains VAT audit trail.'),
			array('title' => 'ERP & e-invoice sync', 'body' => 'Credit notes post to GL and export Peppol XML alongside original invoice chain for FTA readiness.'),
		),
	),
	'fta-xml-export' => array(
		'intro' => 'Export e-invoice payloads in formats suitable for Peppol endpoints and FTA compliance workflows. Operators configure seller profile once per tenant in ERP.', 
		'guide_area' => 'erp-finance', 
		'image' => 'guide-einvoice', 
		'steps' => array(
			array('title' => 'Validated payload export', 'body' => 'Download PINT-AE XML or JSON from e-invoice document view after 51-field validation passes.'),
			array('title' => 'ASP handoff', 'body' => 'Submit export to Accredited Service Provider — FTA tax data reporting runs through ASP after acceptance.'),
			array('title' => 'Archive & audit', 'body' => 'Document library retains XML, PDF, and submission status for compliance audits.'),
		),
	),
	'document-templates' => array(
		'intro' => 'Branded invoice, delivery note, quote, and contract templates with merge fields from orders and customers. Tax advisory tenants use approval-ready document layouts.', 
		'guide_area' => 'documents', 
		'image' => 'guide-documents', 
		'steps' => array(
			array('title' => 'Template manager', 'body' => 'Shop → Document control → Templates — branded layouts for invoice, delivery note, quote, and contract.'),
			array('title' => 'Merge fields', 'body' => 'Templates pull customer name, order lines, TRN, and bank details from live order and company data.'),
			array('title' => 'Approval-ready layouts', 'body' => 'Tax advisory tenants use consistent document formats for client deliverables and FTA submissions.'),
		),
	),
	'print-documents' => array(
		'intro' => 'Print or PDF from CP for any operational document — orders, deliveries, statements. Consistent branding across storefront downloads and staff-printed copies.', 
		'guide_area' => 'documents', 
		'image' => 'guide-documents', 
		'steps' => array(
			array('title' => 'Print from order card', 'body' => 'Any operational document — order confirmation, delivery note, statement — prints or PDFs from CP.'),
			array('title' => 'Storefront downloads', 'body' => 'Clients download invoices and statements from logged-in hub — same branding as staff-printed copies.'),
			array('title' => 'Batch print', 'body' => 'Select multiple orders for pick list or delivery note batch print during peak fulfilment.'),
		),
	),
	'document-library' => array(
		'intro' => 'Store signed contracts, compliance files, and client deliverables per customer or order. Tax and consultancy verticals give clients secure download access from storefront hub.', 
		'guide_area' => 'documents', 
		'image' => 'guide-documents', 
		'steps' => array(
			array('title' => 'Per-customer archive', 'body' => 'Upload signed contracts, compliance files, and deliverables — link to customer or order record.'),
			array('title' => 'Secure client access', 'body' => 'Tax and consultancy verticals expose selected files on storefront client hub with login gate.'),
			array('title' => 'Version history', 'body' => 'Replace document while retaining audit of prior uploads for regulated industries.'),
		),
	),
	'legal-footers-trn' => array(
		'intro' => 'Configurable legal text, bank details, and TRN footer on all customer-facing documents. Reduces manual edits when onboarding new UAE entities.', 
		'guide_area' => 'documents', 
		'image' => 'guide-documents', 
		'steps' => array(
			array('title' => 'Footer configuration', 'body' => 'Company settings define legal text, bank IBAN, and TRN block applied to all customer-facing PDFs.'),
			array('title' => 'Multi-entity support', 'body' => 'Different footers per branch or legal entity when group operates multiple UAE TRNs.'),
			array('title' => 'Reduce manual edits', 'body' => 'New UAE entity onboarding updates footer once — all templates inherit automatically.'),
		),
	),
	'crm-pipeline' => array(
		'intro' => 'Native CRM kanban pipeline inside ERP — leads, opportunities, and won deals without a separate CRM subscription. Consultancies and B2B services run sales and billing on one stack.', 
		'guide_area' => 'crm', 
		'image' => 'guide-crm', 
		'steps' => array(
			array('title' => 'Kanban pipeline', 'body' => 'ERP → CRM → Pipeline — drag leads and opportunities across stages from enquiry to won.'),
			array('title' => 'No separate CRM bill', 'body' => 'Native kanban inside ERP — consultancies and B2B services run sales and billing on one stack.'),
			array('title' => 'Won → order hint', 'body' => 'Won opportunities link to order creation — smooth handoff from sales to commerce fulfilment.'),
		),
	),
	'leads-opportunities' => array(
		'intro' => 'Capture website enquiries as leads and convert to opportunities with value and stage tracking. Won opportunities hint order creation — smooth handoff to commerce.', 
		'guide_area' => 'crm', 
		'image' => 'guide-crm', 
		'steps' => array(
			array('title' => 'Capture website leads', 'body' => 'Storefront enquiry forms create CRM leads — assign owner and expected value in CP.'),
			array('title' => 'Convert to opportunity', 'body' => 'Qualify lead to opportunity with stage, probability, and close date — track in pipeline kanban.'),
			array('title' => 'Activity logging', 'body' => 'Calls and meetings logged against opportunity — nothing lost after showroom or advisory intake.'),
		),
	),
	'customer-hub' => array(
		'intro' => '360° customer view: contacts, orders, balance, documents, and notes in one CP screen. Staff answer client calls without jumping between modules.', 
		'guide_area' => 'crm', 
		'image' => 'guide-crm', 
		'steps' => array(
			array('title' => '360° customer view', 'body' => 'Shop → Customer management — contacts, orders, balance, documents, and notes on one screen.'),
			array('title' => 'Answer calls faster', 'body' => 'Staff resolve client questions without jumping between orders, finance, and CRM modules.'),
			array('title' => 'CRM assignment', 'body' => 'Link customer to CRM owner — new orders notify assigned manager automatically.'),
		),
	),
	'customer-approvals' => array(
		'intro' => 'Approve new B2B accounts, medical institutions, or advisory clients before they can order. Tax and regulated catalogue verticals gate access by design.', 
		'guide_area' => 'crm', 
		'image' => 'guide-crm', 
		'steps' => array(
			array('title' => 'Pending queue', 'body' => 'Users → Customer approvals lists wholesale and regulated sign-ups awaiting manager decision.'),
			array('title' => 'Approve with currency', 'body' => 'On approve, assign fixed dealing currency and customer group — required for wholesale checkout.'),
			array('title' => 'Gate regulated catalogues', 'body' => 'Medical and tax verticals block ordering until institutional approval completes.'),
		),
	),
	'customer-groups-profiles' => array(
		'intro' => 'Segment customers for pricing, catalog visibility, and marketing. Profiles drive margin rules and which brands or categories appear on login.', 
		'guide_area' => 'crm', 
		'image' => 'guide-crm', 
		'steps' => array(
			array('title' => 'Segment buyers', 'body' => 'Groups and profiles drive pricing, catalog visibility, and marketing — retail vs wholesale vs institutional.'),
			array('title' => 'Margin rules', 'body' => 'Each profile links to price list and margin table — contract pricing applies at login automatically.'),
			array('title' => 'Brand visibility', 'body' => 'Show or hide brands and categories per profile — premium lines visible only to approved B2B accounts.'),
		),
	),
	'activities-followups' => array(
		'intro' => 'Log calls, meetings, and tasks against leads and customers — nothing falls through after a showroom visit or advisory intake form.', 
		'guide_area' => 'crm', 
		'image' => 'guide-crm', 
		'steps' => array(
			array('title' => 'Log activities', 'body' => 'CRM → Activities — record calls, meetings, tasks against leads and customers with due dates.'),
			array('title' => 'Follow-up reminders', 'body' => 'Due tasks surface on dashboard — sales team closes loop after site visit or advisory intake.'),
			array('title' => 'Order context', 'body' => 'Activities visible on customer hub — staff see full relationship history on inbound call.'),
		),
	),
	'ai-parts-agent' => array(
		'intro' => 'Give workshop and fleet buyers a conversational parts expert on the storefront — search by part number, decode VIN, and get guided recommendations that reduce counter load.', 
		'guide_area' => 'commerce', 
		'image' => 'guide-ai', 
		'steps' => array(
			array('title' => 'Enable on auto-parts storefront', 'body' => 'The AI parts agent chat widget appears on industry auto-parts themes — buyers ask in natural language for part numbers, crosses, or VIN-based fitment.'),
			array('title' => 'VIN decode & catalogue context', 'body' => 'AI-assisted VIN decode narrows vehicle make, model, and engine before browsing the Epart catalog — fewer wrong-fit orders and faster self-service.'),
			array('title' => 'Review sessions in CP', 'body' => 'Staff open Shop → AI Parts Expert → Chats to review customer country, full transcript, and quoted articles before follow-up or order conversion.'),
			array('title' => 'Hand off to order desk', 'body' => 'When the buyer adds recommended lines to cart and checks out, the session links to the standard order fulfilment pipeline — same LPO and ERP path as manual orders.'),
		),
	),
	'vin-decode-ai' => array(
		'intro' => 'AI-assisted VIN decode narrows vehicle context before catalogue browse — fewer wrong-fit orders and faster workshop self-service.', 
		'guide_area' => 'automation', 
		'image' => 'guide-ai', 
		'steps' => array(
			array('title' => 'VIN entry on storefront', 'body' => 'Buyer enters 17-character VIN in search or AI chat — decode narrows vehicle context instantly.'),
			array('title' => 'Catalogue filter', 'body' => 'Decoded make/model/engine filters Epart browse and cross-reference results to compatible SKUs.'),
			array('title' => 'Fewer wrong-fit orders', 'body' => 'Workshop self-service reduces counter calls and return rates from incorrect part selection.'),
		),
	),
	'demand-intelligence' => array(
		'intro' => 'Signals from search, crosses, and order history highlight what to stock and promote. Professional services pack includes demand views for advisory upsell.', 
		'guide_area' => 'automation', 
		'image' => 'guide-ai', 
		'steps' => array(
			array('title' => 'Search & order signals', 'body' => 'Dashboard aggregates popular searches, cross lookups, and repeat order patterns by SKU.'),
			array('title' => 'Stocking decisions', 'body' => 'Highlight articles to reorder or promote — professional services pack adds advisory upsell views.'),
			array('title' => 'Campaign targeting', 'body' => 'Feed merchandising and promo decisions — pair with Marketing campaigns hub for seasonal pushes.'),
		),
	),
	'auto-price-ai' => array(
		'intro' => 'Multi-source price intelligence for every tenant — crawl buy sources and sell marketplaces, compare margin, import winners to your catalogue, and list on Noon, Amazon, or eBay. Country packs, industry taxonomy, and scheduled crons keep prices fresh.',
		'guide_area' => 'automation',
		'image' => 'guide-ai',
		'steps' => array(
			array('title' => 'Enable on your tenant', 'body' => 'Super CP enables Auto Price AI under Tenant features. First engine load seeds country sources, product lines, and sell marketplaces for your industry.'),
			array('title' => 'Discover → Quick crawl', 'body' => 'Open Discover and run Quick crawl — cards show buy lowest, marketplace sell target, and margin. Review Marketplace opportunities or Market confirmed views.'),
			array('title' => 'Import to catalogue', 'body' => 'Add to my catalogue sets cost = lowest buy and sell = marketplace target. Photos and specs copy across — you approve every import before publish.'),
			array('title' => 'List on marketplaces', 'body' => 'Configure sell channels on Rules (Noon, Amazon.ae, eBay). Buy sources like Sharaf DG or spare247 are for sourcing only — never sell targets.'),
			array('title' => 'Full guide', 'body' => 'Marketing overview at www.ecomae.com/platform/auto-price-ai — operator handbook in CP Auto Price AI → Guide tab.'),
		),
	),
	'automation-hooks' => array(
		'intro' => 'Event hooks for order placed, stock low, and lead captured — wire email, WhatsApp, or external systems. Foundation for operator-built automations per tenant.', 
		'guide_area' => 'automation', 
		'image' => 'guide-ai', 
		'steps' => array(
			array('title' => 'Event triggers', 'body' => 'Hooks fire on order placed, stock low, lead captured, and status changes — foundation for tenant automations.'),
			array('title' => 'E-mail & WhatsApp', 'body' => 'Wire notifications to external channels — extend with operator-built scripts per tenant policy.'),
			array('title' => 'Integration ready', 'body' => 'Standard events expose order and customer payload for middleware or accounting connectors.'),
		),
	),
	'marketing-campaigns' => array(
		'intro' => 'Plan and track campaigns linked to storefront landing pages and promo codes. Merchandising teams launch seasonal pushes without developer tickets.', 
		'guide_area' => 'marketing', 
		'image' => 'guide-marketing', 
		'steps' => array(
			array('title' => 'Campaign planner', 'body' => 'Shop → Marketing → Campaigns — name, date range, linked promo codes, and landing page URL with UTM tags.'),
			array('title' => 'Measure uplift', 'body' => 'Track orders attributed to campaign codes — compare periods in order desk filters.'),
			array('title' => 'Seasonal launches', 'body' => 'Merchandising teams push fashion and electronics collections without developer tickets.'),
		),
	),
	'growth-strategies' => array(
		'intro' => 'Built-in playbook of ten proven growth tactics — from basket recovery to B2B outreach — with CP guidance per strategy. Agencies show clients a structured marketing layer.', 
		'guide_area' => 'marketing', 
		'image' => 'guide-marketing', 
		'steps' => array(
			array('title' => 'Ten-strategy playbook', 'body' => 'Built-in growth tactics cover basket recovery, B2B outreach, cross-sell, and referral prompts.'),
			array('title' => 'CP guidance per strategy', 'body' => 'Each strategy opens step-by-step checklist in CP — agencies show clients structured marketing layer.'),
			array('title' => 'Link to promos', 'body' => 'Strategies connect to promo codes and featured collections for executable campaigns.'),
		),
	),
	'promo-merchandising' => array(
		'intro' => 'Hero banners, featured collections, and campaign-driven catalogue highlights on the storefront. UTM-ready URLs for measuring ad spend effectiveness.', 
		'guide_area' => 'marketing', 
		'image' => 'guide-marketing', 
		'steps' => array(
			array('title' => 'Hero banners', 'body' => 'Storefront theme editor places campaign banners on home and category pages — mobile-ready grids.'),
			array('title' => 'Featured SKUs', 'body' => 'Pin promotional articles to collection grids — Virgin-style electronics and Namshi-style fashion layouts.'),
			array('title' => 'UTM tracking', 'body' => 'Campaign URLs carry UTM parameters — measure ad spend effectiveness in analytics.'),
		),
	),
	'featured-collections' => array(
		'intro' => 'Curate lookbooks and collection grids — Namshi-style fashion and jewellery gallery layouts ship with industry themes. Mobile-ready grids for Instagram traffic.', 
		'guide_area' => 'marketing', 
		'image' => 'guide-marketing', 
		'steps' => array(
			array('title' => 'Curate lookbooks', 'body' => 'Shop → Marketing → Collections group SKUs for seasonal lookbooks and gallery grids.'),
			array('title' => 'Industry layouts', 'body' => 'Fashion and jewellery themes render collection pages with large imagery and quick-add to cart.'),
			array('title' => 'Instagram traffic', 'body' => 'Mobile-optimised grids convert social traffic — link collections from bio and paid ads.'),
		),
	),
	'users-roles' => array(
		'intro' => 'Role-based CP access for admin, warehouse, finance, and counter staff. Super CP operators stay on platform DB; client staff authenticate on their own domain only.', 
		'guide_area' => 'admin', 
		'image' => 'guide-admin', 
		'steps' => array(
			array('title' => 'Role-based access', 'body' => 'Users → Groups & roles assign admin, warehouse, finance, and counter permissions — sidebar hides unauthorised modules.'),
			array('title' => 'Client staff on own domain', 'body' => 'Client employees authenticate on www.client.com/cp only — Super CP operators stay on platform hostname.'),
			array('title' => 'Audit user actions', 'body' => 'Sensitive finance and approval actions log admin user — supports internal control reviews.'),
		),
	),
	'cp-module-packs' => array(
		'intro' => 'Enable or hide entire module packs — commerce, ERP, auto parts, logistics — per tenant. Sidebar groups stay clean; clients only see what their rental includes.', 
		'guide_area' => 'admin', 
		'image' => 'guide-admin', 
		'steps' => array(
			array('title' => 'Industry pack toggles', 'body' => 'Super CP or tenant admin enables commerce, ERP, auto parts, logistics packs per rental agreement.'),
			array('title' => 'Clean sidebar', 'body' => 'Disabled modules hide from sidebar — clients only see included functionality.'),
			array('title' => 'Upgrade path', 'body' => 'Enable ERP or e-invoice pack when tenant grows — no migration to new platform required.'),
		),
	),
	'ssl-dns-assist' => array(
		'intro' => 'Let\'s Encrypt certificates and DNS checklists handled on platform infrastructure. Tenants get HTTPS on www.client.com without managing certificates themselves.', 
		'guide_area' => 'admin', 
		'image' => 'guide-admin', 
		'steps' => array(
			array('title' => 'Platform-managed SSL', 'body' => 'Let\'s Encrypt certificates issue automatically when domain alias attaches — no client certificate management.'),
			array('title' => 'DNS checklist in onboarding', 'body' => 'Step-by-step registrar guide included in tenant onboarding — operator verifies before go-live.'),
			array('title' => 'HTTPS everywhere', 'body' => 'Storefront, /cp/, and /erp serve over HTTPS on client domain from day one.'),
		),
	),
	'storefront-themes' => array(
		'intro' => 'Five production retail and services layouts — automotive, electronics, fashion, jewellery, advisory — with industry-tuned CP chrome. Switch visual style without losing catalogue data.', 
		'guide_area' => 'admin', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Five production layouts', 'body' => 'Automotive, electronics, fashion, jewellery, and advisory themes ship with industry-tuned CP chrome.'),
			array('title' => 'Switch visual style', 'body' => 'Change theme in industry settings — catalogue and order data persist across theme switches.'),
			array('title' => 'Mobile-first retail', 'body' => 'All themes responsive for UAE mobile commerce and WhatsApp-driven traffic.'),
		),
	),
	'operator-audit' => array(
		'intro' => 'Platform branding, contact JSON presets, and deploy audit for operators. Super CP settings never leak to client hostnames — enforced by hostname routing rules.', 
		'guide_area' => 'admin', 
		'image' => 'guide-admin', 
		'steps' => array(
			array('title' => 'Platform settings', 'body' => 'Super CP → Settings — platform branding, contact JSON presets, and default industry options.'),
			array('title' => 'Deploy audit log', 'body' => 'Each template push records operator, target tenant, timestamp, and package version.'),
			array('title' => 'Hostname isolation', 'body' => 'Operator tools never expose on client hostnames — enforced by multi-tenant routing rules.'),
		),
	),
	'industry-auto-parts' => array(
		'intro' => 'VIN-aware catalogue, supplier prices, crosses, procurement, and B2B balances — the full eParts-style stack pre-loaded for parts distributors in UAE & GCC.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Pre-loaded eParts stack', 'body' => 'VIN search, supplier prices, crosses, procurement, B2B balances, and AI parts agent enabled out of box.'),
			array('title' => 'Warehouse & LPO setup', 'body' => 'Template seeds UAE warehouse price lists and LPO e-mail placeholders — follow price and fulfilment guides.'),
			array('title' => 'Go live for distributors', 'body' => 'Full path from supplier price upload to storefront search to order desk in one hosted domain.'),
		),
	),
	'industry-tax-advisory' => array(
		'intro' => 'Client portal, VAT workflows, document control, and advisory CRM on one hosted domain — Prime Invest-style layout for tax firms and corporate advisors.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Client portal hub', 'body' => 'Prime Invest-style layout — clients log in for documents, VAT status, and advisory deliverables.'),
			array('title' => 'VAT & e-invoice pack', 'body' => 'UAE VAT returns, PINT-AE e-invoicing, and document control pre-enabled for tax firms.'),
			array('title' => 'Advisory CRM', 'body' => 'Pipeline and activities track engagements — bill from ERP without separate CRM subscription.'),
		),
	),
	'industry-fashion' => array(
		'intro' => 'Lookbook collections, variant catalogue, and campaign-ready Namshi-style storefront. Order fulfilment and returns modules aligned to apparel retail.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Namshi-style storefront', 'body' => 'Lookbook collections, variant catalogue, and campaign-ready mobile grids.'),
			array('title' => 'Apparel fulfilment', 'body' => 'Size/colour variants, returns module, and delivery notes aligned to fashion retail operations.'),
			array('title' => 'Seasonal CSV import', 'body' => 'Bulk upload collections via CSV — map size run and colour columns in import wizard.'),
		),
	),
	'industry-electronics' => array(
		'intro' => 'Virgin-style mega navigation, spec-heavy homepage, and SKU pagination for IT and consumer electronics. RMA and warranty hooks included in pack.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Virgin-style navigation', 'body' => 'Mega menu, spec-heavy homepage, and SKU pagination for IT and consumer electronics.'),
			array('title' => 'RMA & warranty', 'body' => 'Serial number fields on order lines — RMA workflow with warranty claim tracking included in pack.'),
			array('title' => 'Spec filters', 'body' => 'Category attributes drive datasheet filters on browse and search pages.'),
		),
	),
	'industry-medical' => array(
		'intro' => 'Regulated catalogue, institutional login, batch and expiry fields, and audit-friendly delivery documentation for clinic procurement teams.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Regulated catalogue', 'body' => 'Institutional login and customer approval gate ordering for clinic procurement teams.'),
			array('title' => 'Batch & expiry', 'body' => 'SKU fields capture batch number and expiry — audit-friendly delivery documentation.'),
			array('title' => 'Compliance documents', 'body' => 'Document library stores certificates and MSDS — institutional buyers download from client hub.'),
		),
	),
	'industry-consultancy' => array(
		'intro' => 'Proposal-to-delivery: CRM, projects, billing, and client-facing hub for management consultancies and professional service firms.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Proposal to delivery', 'body' => 'CRM pipeline, project tracking, time billing, and client-facing hub on one domain.'),
			array('title' => 'Professional services ERP', 'body' => 'Invoice from opportunities, track receivables, and export P&L for management consultancies.'),
			array('title' => 'Client hub access', 'body' => 'Secure document and statement downloads — reduce e-mail attachment friction.'),
		),
	),
	'industry-rental' => array(
		'intro' => 'Rental SKU with daily/monthly periods, deposits, contracts, and monthly billing hooks for fleet, equipment, and commercial leasing businesses.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Rental SKU periods', 'body' => 'Daily, weekly, and monthly rate periods on rental SKUs — deposits and contract terms on order.'),
			array('title' => 'Contract generation', 'body' => 'Document templates produce rental agreements with merge fields from customer and asset data.'),
			array('title' => 'Monthly billing hooks', 'body' => 'Recurring invoice generation from active contracts — ties to ERP receivables.'),
		),
	),
	'industry-jewellery' => array(
		'intro' => 'Kiyasha-style gold and diamond aesthetic, gallery product cards, certificate metadata, and premium enquiry flows for fine jewellers.', 
		'guide_area' => 'industry', 
		'image' => 'guide-industry', 
		'steps' => array(
			array('title' => 'Kiyasha-style aesthetic', 'body' => 'Gold and diamond gallery product cards with certificate metadata fields.'),
			array('title' => 'Premium enquiry flows', 'body' => 'High-value items use enquiry or appointment CTAs alongside cart for fine jewellers.'),
			array('title' => 'Luxury merchandising', 'body' => 'Featured collections and hero imagery optimised for mobile Instagram traffic.'),
		),
	),
	'api-integrations' => array(
		'intro' => 'Read-only JSON REST at /epc-api/v1/ for enterprise middleware, BI dashboards, and partner systems — tenant-scoped API keys with OpenAPI spec and Super CP operator guide.',
		'guide_area' => 'overview',
		'image' => 'guide-super-cp',
		'steps' => array(
			array('title' => 'Review public API docs', 'body' => 'Marketing page at www.ecomae.com/platform/api-documentation lists Phase 1 endpoints, auth, and curl examples with placeholders only.'),
			array('title' => 'Issue tenant API keys', 'body' => 'Super CP → Portal → API documentation guide — run epc-api-keys-setup.php or insert hashed keys in epc_api_keys for each site_key.'),
			array('title' => 'Test read endpoints', 'body' => 'curl tenant/info, orders, products/search, and erp/dashboard-summary with X-API-Key header — expect 401 without key.'),
			array('title' => 'Share OpenAPI with developers', 'body' => 'Download /epc-api/v1/openapi.json for codegen and contract tests — Phase 2 will add webhooks and write APIs.'),
		),
	),
);
