<?php
/**
 * ECOM AE marketing FAQ — 105 tenant questions across 7 modules.
 * Generated by tools/gen_ecomae_faq.py — edit answers there and regenerate.
 */
defined('_ASTEXE_') or die('No access');

function epc_ecomae_faq_modules(): array
{
	return array(
		array(
			'id' => 'automotive',
			'icon' => 'fa-car',
			'title' => 'Automotive Data, TecDoc & Catalog',
			'range' => '1–15',
			'items' => array(
				array(
					'num' => 1,
					'q' => 'Does the platform natively support international catalog standards like TecDoc, ACES, or PIES?',
					'status' => 'Partial',
					'a' => 'ECOM AE does not natively import TecDoc, ACES, or PIES files. Automotive catalog, VIN decode, and fitment run on the eparts catalog with epartscross for cross-references — the same stack live on epartscart.com. See our Catalog API and vehicle catalogue capability pages.',
				),
				array(
					'num' => 2,
					'q' => 'How does the system handle OEM-to-aftermarket cross-referencing matrices?',
					'status' => 'Yes',
					'a' => 'Cross-referencing combines local analog tables, live eparts catalog analogs, and epartscross lookups. Operators maintain crosses via CSV in CP; storefront search expands bidirectional interchange up to six rounds.',
				),
				array(
					'num' => 3,
					'q' => 'What is the maximum number of part supercessions (part A replaced by B, then C) the catalog can chain together?',
					'status' => 'Yes',
					'a' => 'Interchange expansion walks up to six bidirectional rounds with a row cap per lookup — enough to discover multi-hop supersession chains through cross tables and eparts catalog analogs. There is no separate supersession audit UI, but the lookup engine handles chained replacements.',
				),
				array(
					'num' => 4,
					'q' => 'Can the search engine index and deliver results for partial or punctuated part numbers (e.g., searching 06H-103-483-D via 06H103483D)?',
					'status' => 'Yes',
					'a' => 'Punctuated numbers work: dashes, spaces, and dots are stripped so 06H-103-483-D matches 06H103483D. Prefix autocomplete works on price lists; middle-of-number fuzzy matching on the main results page is not implemented today.',
				),
				array(
					'num' => 5,
					'q' => 'What specific third-party APIs or databases do you use to power the VIN (Vehicle Identification Number) decoding?',
					'status' => 'Yes',
					'a' => 'VIN decode uses the Epart autocatalog API, proxied through our tenant-safe catalog API proxy with response caching. External partners can also call our Catalog API action=vin with an API key.',
				),
				array(
					'num' => 6,
					'q' => 'Does the VIN lookup map directly to specific engine codes, chassis restrictions, and production month variations?',
					'status' => 'Partial',
					'a' => 'VIN decode returns matching vehicles with make, model, year, and engine fields; ambiguous VINs show a picker. Production ranges appear as year-from/year-to when browsing modifications, but production month and explicit chassis restriction codes are not first-class storefront fields.',
				),
				array(
					'num' => 7,
					'q' => 'How does the search algorithm prioritize exact OEM matches versus cheaper aftermarket alternatives?',
					'status' => 'Yes',
					'a' => 'Results split into Genuine (OE) and Aftermarket sections — OE first, each sorted by ascending price within the section. Cross-reference matches and warehouse stock can still appear alongside the requested number depending on search mode.',
				),
				array(
					'num' => 8,
					'q' => 'Can we create custom attributes for parts, such as core charges/deposits for remanufactured alternators or engines?',
					'status' => 'Yes',
					'a' => 'Tenants add custom catalogue properties and ERP inventory custom fields (up to five per SKU) to model core charges and deposits — no prebuilt preset, but fully configurable per tenant.',
				),
				array(
					'num' => 9,
					'q' => 'How does the system handle oversized/bulky items in the catalog to prevent incorrect standard shipping calculations?',
					'status' => 'Partial',
					'a' => 'Article weight from the catalog is shown on part pages; logistics uses manual weight input for carrier rates and labels. No dedicated oversized/bulky SKU flag auto-applies volumetric surcharges at checkout today.',
				),
				array(
					'num' => 10,
					'q' => 'Can the system automatically suggest required complementary parts at checkout (e.g., suggesting a new gasket when a water pump is purchased)?',
					'status' => 'Yes',
					'a' => 'Checkout and part pages show a Related parts panel built from cross references and name-cluster rules — customers can add suggested gaskets, seals, or alternates in one click. Mandatory auto-add at checkout is not enforced.',
				),
				array(
					'num' => 11,
					'q' => 'How frequently can the automotive catalog database be updated without causing storefront downtime?',
					'status' => 'Yes',
					'a' => 'Catalog and supplier price lists refresh continuously without taking the shop offline. Eparts catalog data is fetched live with DB caching; CP price uploads and pyprices cron feed search instantly after import.',
				),
				array(
					'num' => 12,
					'q' => 'Does the platform support KType or NType vehicle identification codes common in European and GCC catalogs?',
					'status' => 'No',
					'a' => 'KType and NType codes are not used in the current stack. Vehicle identification uses eparts catalog tree IDs and VIN decode — contact us if KType mapping is a hard requirement.',
				),
				array(
					'num' => 13,
					'q' => 'Can we manually override or append fitment data to a specific SKU if an error is found in the master catalog?',
					'status' => 'Partial',
					'a' => 'Fitment on master-catalog SKUs comes from eparts catalog and epartscross — there is no CP tool to override upstream fitment on a supplier line. Local crosses and custom catalogue products are separate workarounds.',
				),
				array(
					'num' => 14,
					'q' => 'How does the system handle "universal parts" (like zip ties, fluids, or generic clips) that do not map to a specific vehicle?',
					'status' => 'Yes',
					'a' => 'Universal items are searchable by normalized part number without vehicle links. Parts search has a Universal parts mode flag; epartscross fitment fallback uses cartype=UNI. Stocked universal SKUs add to cart without a vehicle picker.',
				),
				array(
					'num' => 15,
					'q' => 'Is there a built-in tool to handle product variants like brake pads that fit both front and rear axles with slight variations?',
					'status' => 'Partial',
					'a' => 'Retail catalogue supports generic variant SKUs. Automotive axle-position variants (front vs rear) are not a built-in matrix — use separate articles/SKUs or custom properties.',
				),
			),
		),
		array(
			'id' => 'b2b',
			'icon' => 'fa-briefcase',
			'title' => 'B2B Portal & Tiered Accounts',
			'range' => '16–30',
			'items' => array(
				array(
					'num' => 16,
					'q' => 'Can we run a fully public B2C storefront and a password-protected B2B garage portal off the exact same inventory pool?',
					'status' => 'Yes',
					'a' => 'Retail and wholesale share the same warehouse and price-list pool (e.g. S-UAE, R-UAE on epartscart). B2C guests browse with prices hidden; B2B buyers log in for contract pricing — one storefront with tiered accounts, not a separate B2B-only site.',
				),
				array(
					'num' => 17,
					'q' => 'Does the CRM allow for custom price sheets mapped to specific wholesale garage accounts?',
					'status' => 'Yes',
					'a' => 'Price profiles map to customer groups with per-profile margins and brand/article rules. CP assigns profiles per customer; imported price lists like S-UAE and R-UAE tie to warehouses.',
				),
				array(
					'num' => 18,
					'q' => 'Can B2B customers input their own internal Purchase Order (PO) numbers during the checkout flow?',
					'status' => 'Yes',
					'a' => 'Logged-in buyers enter a dedicated Purchase Order (PO) number at checkout. It is stored on the order (messages + order log) alongside the optional order comment. Supplier-facing LPO numbers remain system order IDs.',
				),
				array(
					'num' => 19,
					'q' => 'Does the platform support credit limit management and terms (e.g., Net 30, Net 60) for commercial fleet buyers?',
					'status' => 'Yes',
					'a' => 'Trade credit uses overdraft limits enforced at payment time plus customer balance tracking. Supplier payment terms is a configurable text field (e.g. Net 30). Automated aging-driven Net30/Net60 invoicing is not fully automated — confirm scope for your tenant.',
				),
				array(
					'num' => 20,
					'q' => 'Can a single B2B corporate account have multiple user logins with different permission tiers (e.g., Mechanic can search/cart, Workshop Manager must approve/pay)?',
					'status' => 'No',
					'a' => 'Accounts are per user today. Customer groups drive price profiles and margins only — not mechanic vs manager approval tiers under one corporate parent. Contact us for enterprise permission scoping.',
				),
				array(
					'num' => 21,
					'q' => 'Is there a built-in quote generation tool where a garage can request a bulk price, and our team can adjust it via the dashboard?',
					'status' => 'Yes',
					'a' => 'Storefront quote requests let customers build and submit drafts; CP quote-requests lets staff price and mark quoted. CRM quotes exist for staff-side sales — not a full RFQ negotiation portal with counter-offers.',
				),
				array(
					'num' => 22,
					'q' => 'How does the system handle tax-exempt certificates for wholesale buyers?',
					'status' => 'Partial',
					'a' => 'Wholesale accounts can upload a tax-exempt certificate (PDF/image) from My profile for manager review. Exempt checkout logic after approval is tenant-specific — contact us for US or GCC exempt buyer workflows.',
				),
				array(
					'num' => 23,
					'q' => 'Can we restrict certain hazardous or regulated brands/items (e.g., car batteries, air bag modules) from B2C buyers while keeping them visible to B2B?',
					'status' => 'Yes',
					'a' => 'Per price-profile brand and article visibility rules hide SKUs from retail/guest groups while showing them to wholesale profiles. No hazardous/regulated category preset — configure by brand/article rules.',
				),
				array(
					'num' => 24,
					'q' => 'Can B2B clients upload bulk CSV orders of part numbers directly into their shopping cart?',
					'status' => 'Yes',
					'a' => 'Bulk upload accepts CSV part lists, resolves crosses and availability, and adds lines to cart with per-user history — popular with UAE wholesale garages.',
				),
				array(
					'num' => 25,
					'q' => 'Does the platform support targeted marketing banners displayed exclusively to B2B users vs B2C users?',
					'status' => 'No',
					'a' => 'Info blocks scope by tenant, site, and placement (homepage, checkout, CP) — not by retail vs wholesale user type today.',
				),
				array(
					'num' => 26,
					'q' => 'Can we set different minimum order quantities (MOQ) for B2B wholesale buyers compared to retail buyers?',
					'status' => 'Yes',
					'a' => 'Base MOQ comes from supplier price-list rows; epc_price_profiles moq_multiplier adjusts effective MOQ per customer group (retail vs wholesale) at add-to-cart. Configure multipliers in Price management.',
				),
				array(
					'num' => 27,
					'q' => 'Is there a function for garages to save specific customer vehicle profiles (e.g., "Customer A\'s Toyota Camry") for quick re-ordering?',
					'status' => 'Yes',
					'a' => 'Logged-in users maintain vehicles in the garage/notepad and can tie orders to saved vehicles for quick re-ordering. This is user garage history — not a separate named end-customer CRM entity.',
				),
				array(
					'num' => 28,
					'q' => 'How does the system handle past-due invoice alerts and automatic account locking for B2B clients?',
					'status' => 'No',
					'a' => 'Checkout blocks only pending/rejected trade registration. No overdue-invoice detection or automatic account lock on past-due balances is implemented today.',
				),
				array(
					'num' => 29,
					'q' => 'Can B2B buyers request dynamic delivery times based on their workshop operational hours?',
					'status' => 'No',
					'a' => 'Delivery lead time comes from imported price rows and is filterable on search. Workshop-hours scheduling or delivery-window requests are not supported.',
				),
				array(
					'num' => 30,
					'q' => 'Does the dashboard provide B2B clients with their own custom statements, payment histories, and usage analytics?',
					'status' => 'Yes',
					'a' => 'Logged-in buyers see account balance, order history, and trade profile on the storefront My account area. Full GL statements and advanced analytics live in ERP Receivables for staff export.',
				),
			),
		),
		array(
			'id' => 'supply_chain',
			'icon' => 'fa-cubes',
			'title' => 'Supply Chain, Multi-Warehouse & Ghost Stock',
			'range' => '31–45',
			'items' => array(
				array(
					'num' => 31,
					'q' => 'How many unique warehouse locations or fulfillment nodes can the inventory module track simultaneously?',
					'status' => 'Yes',
					'a' => 'No hard cap found in code. Multi-warehouse is core via shop storages; ERP syncs warehouses from shop storages. eParts Cart uses S-UAE, R-UAE, RK-UAE, L-UAE and more.',
				),
				array(
					'num' => 32,
					'q' => 'Does the platform support virtual inventory sync from third-party distributor feeds without holding physical stock?',
					'status' => 'Yes',
					'a' => 'Supplier price lists act as virtual availability; warehouses can be toggled off the storefront via storefront_temp_disabled without deleting data — common for distributor feeds.',
				),
				array(
					'num' => 33,
					'q' => 'What file formats and protocols are supported for automated inventory updates (e.g., REST API, GraphQL, Webhooks, EDI, SFTP/CSV)?',
					'status' => 'Yes',
					'a' => 'Built in: CSV/Excel upload, email inbox import, FTP, URL fetch, pyprices cron, and REST upload_price.php. Native EDI, GraphQL, and webhooks are not built in — contact us for custom integrations.',
				),
				array(
					'num' => 34,
					'q' => 'What is the system\'s maximum frequency for inventory syncs to prevent "ghost stock" sales of fast-moving parts?',
					'status' => 'Yes',
					'a' => 'Pyprices cron can run on short intervals; cart reserves stock at add-to-cart; storefront warehouse toggles (storefront_temp_disabled) hide feeds instantly. No contractual max-frequency SLA — tune cron per supplier.',
				),
				array(
					'num' => 35,
					'q' => 'Does the system feature automated safety stock triggers that draft POs to suppliers when stock falls below a threshold?',
					'status' => 'Partial',
					'a' => 'ERP SKUs have reorder_level fields and capability guides describe low-stock to PO workflows. Fully automated safety-stock PO drafting depends on tenant ERP setup — confirm scope during onboarding.',
				),
				array(
					'num' => 36,
					'q' => 'How does the platform handle split-shipments if an order contains one part from Warehouse A and another from Supplier B?',
					'status' => 'Yes',
					'a' => 'Multi-warehouse orders generate separate supplier LPO emails per warehouse with lines tied to each storage_id — live on epartscart with S-UAE/R-UAE split fulfilment.',
				),
				array(
					'num' => 37,
					'q' => 'Does the Warehouse Management System (WMS) module support barcode scanning (1D/2D) for picking and packing workflows?',
					'status' => 'Planned',
					'a' => 'POS stores barcodes on sale lines and supports SKU lookup; mobile app lists barcode scan as Phase 2. Dedicated WMS pick/pack scan workflows are on the roadmap.',
				),
				array(
					'num' => 38,
					'q' => 'How are parts returns (Reverse Logistics) managed, especially regarding opened boxes, electronic components, or dirty parts?',
					'status' => 'Yes',
					'a' => 'Customer returns module handles RMA reasons, messaging, and staff workflow. Condition-based rules (opened box, electronics QC, dirty parts) are configured per tenant — not a fixed automotive QC preset.',
				),
				array(
					'num' => 39,
					'q' => 'Can the system prioritize fulfillment from the closest geographical warehouse to the customer automatically?',
					'status' => 'No',
					'a' => 'Geo settings drive which offices/storages are queried in search, but automatic fulfillment routing to the nearest warehouse by customer location is not implemented.',
				),
				array(
					'num' => 40,
					'q' => 'How does the platform track inventory changes across physical retail shelves vs online stock locks during an active checkout?',
					'status' => 'Yes',
					'a' => 'Online checkout reserves stock via shop storages reserved counters at add-to-cart. ERP inventory and POS retail shelf counts are separate layers — unified shelf-to-web sync is not fully integrated.',
				),
				array(
					'num' => 41,
					'q' => 'Can we configure lead-time variations per supplier so the storefront updates delivery estimates dynamically?',
					'status' => 'Yes',
					'a' => 'Lead time comes from imported price rows (time_to_exe fields) and is shown/filtered on parts search and stored on cart lines — configured via price file content per supplier/warehouse feed.',
				),
				array(
					'num' => 42,
					'q' => 'Does the system natively handle "drop-shipping" directly from a manufacturer\'s facility to our end customer?',
					'status' => 'Yes',
					'a' => 'Supplier LPO flow emails suppliers to ship against the customer order — a virtual-stock drop-ship model live on auto-parts tenants (S-UAE/R-UAE split fulfilment).',
				),
				array(
					'num' => 43,
					'q' => 'How does the platform manage inventory write-offs for damaged, obsolete, or expired chemical products?',
					'status' => 'Yes',
					'a' => 'ERP supports write_off and adjustment movements on ledgers plus inventory adjustments via CSV. Perishable expiry is tracked for ERP perishable item types.',
				),
				array(
					'num' => 44,
					'q' => 'Is there an integrated cycle-counting workflow within the WMS to audit inventory without shutting down operations?',
					'status' => 'Planned',
					'a' => 'ERP allows adjustment movements and bulk CSV corrections. Dedicated cycle-count task workflows (count sheets, blind counts, variance approval) are planned — contact us for timeline.',
				),
				array(
					'num' => 45,
					'q' => 'Can the platform track lot numbers and expiration dates for items like automotive paints, sealants, or brake fluids?',
					'status' => 'Yes',
					'a' => 'ERP inventory supports batch_no and expiry_date on perishable SKUs with bulk CSV import. Storefront catalog display for chemical expiry is tenant-configured — common on FMCG/medical templates.',
				),
			),
		),
		array(
			'id' => 'erp_gcc',
			'icon' => 'fa-line-chart',
			'title' => 'ERP, Finance & GCC Localization',
			'range' => '46–60',
			'items' => array(
				array(
					'num' => 46,
					'q' => 'Is the Finance module fully compliant with FTA (Federal Tax Authority) regulations for UAE VAT?',
					'status' => 'Yes',
					'a' => 'UAE VAT workflow is built in: Tax Toolkit, Peppol/PINT-AE e-invoicing, TRN invoices, VAT return prep, and FTA XML/JSON export. This is operational compliance tooling — not a published FTA product certification badge.',
				),
				array(
					'num' => 47,
					'q' => 'Does the system natively generate compliant Arabic/English tax invoices?',
					'status' => 'Partial',
					'a' => 'Document Control ships English FTA tax invoice templates with TRN/legal footers. Storefront supports EN, AR, and RU languages, but a native dual-language Arabic/English tax invoice PDF generator is not shipped today.',
				),
				array(
					'num' => 48,
					'q' => 'Can the system manage multi-currency transactions (e.g., buying in USD/EUR from suppliers, selling in AED/SAR to customers)?',
					'status' => 'Yes',
					'a' => 'Multi-currency is implemented across ERP contacts/invoices, payment gateways (AED default), and B2B trade accounts — standard for GCC trading tenants.',
				),
				array(
					'num' => 49,
					'q' => 'Does the General Ledger (GL) support multi-company accounting if we operate separate legal entities across the GCC?',
					'status' => 'Partial',
					'a' => 'Marketing describes multi-company scoped customs and entity fields within one tenant — not separate GL books per GCC legal entity. Multiple entities on one hosted stack are supported at field level; full multi-entity GL is contact us.',
				),
				array(
					'num' => 50,
					'q' => 'Which local payment gateways (e.g., Stripe, Checkout.com, Network International, Tabby/Tamara) are pre-integrated?',
					'status' => 'Partial',
					'a' => 'Pre-integrated UAE gateways include Stripe, Telr, PayTabs, PayPal, and Amazon Payment Services. Tabby/Tamara appear in demo retail copy only — not in the live gateway registry. Network International and Checkout.com are not pre-integrated.',
				),
				array(
					'num' => 51,
					'q' => 'How does the ERP handle the amortization of shipping and customs duties into the final landed cost of the part?',
					'status' => 'Partial',
					'a' => 'Tax Toolkit computes landed cost with import duty; Custom & Shipping tracks duties and HS codes on declarations. Automated amortization of freight/customs into inventory COGS on receipt is not fully automated.',
				),
				array(
					'num' => 52,
					'q' => 'Can the system export financial data natively into external platforms like SAP, Oracle, or Microsoft Dynamics if required?',
					'status' => 'Partial',
					'a' => 'ERP exports CSV (GL trial balance, sales, stock). SAP/Oracle native connectors are not built in. Microsoft Dynamics 365 sync is listed under future scope in our API documentation.',
				),
				array(
					'num' => 53,
					'q' => 'Does the platform automate bank reconciliation processing for credit card and bank transfer payments?',
					'status' => 'Partial',
					'a' => 'Bank reconciliation UI matches statement lines to cash entries manually — not fully automated card/bank feed reconciliation.',
				),
				array(
					'num' => 54,
					'q' => 'How does the platform handle the calculating and collection of dynamic regional customs duties for cross-border GCC shipping?',
					'status' => 'Partial',
					'a' => 'GCC/UAE customs declaration registry with import/export/transit types and duty fields exists. Some duty paid/payable reports are still Phase 3 stubs — confirm scope for your routes.',
				),
				array(
					'num' => 55,
					'q' => 'Can the accounting module generate real-time Profit and Loss (P&L) statements down to the specific part category?',
					'status' => 'Partial',
					'a' => 'Real-time P&L by GL chart-of-accounts is available — not by product category or SKU. Category-level margin analysis uses ERP reports and exports.',
				),
				array(
					'num' => 56,
					'q' => 'How does the platform calculate cost of goods sold (COGS)—does it use FIFO, LIFO, or Weighted Average Costing?',
					'status' => 'Yes',
					'a' => 'Inventory uses weighted average cost only — documented in ERP inventory guide. FIFO and LIFO are not implemented.',
				),
				array(
					'num' => 57,
					'q' => 'Is there built-in support for processing cash-on-delivery (COD) workflows, including courier reconciliation management?',
					'status' => 'No',
					'a' => 'No COD payment handler or courier-reconciliation workflow found among payment systems or order flows today.',
				),
				array(
					'num' => 58,
					'q' => 'Can the system automate corporate tax reporting rules required for operational entities in the Middle East?',
					'status' => 'Partial',
					'a' => 'UAE Corporate Tax provision is calculated on the P&L tab. Worldwide Tax Toolkit mentions CIT for 195+ countries — advisory/estimate level, not full ME corporate tax filing automation.',
				),
				array(
					'num' => 59,
					'q' => 'How are credit notes and customer refunds processed and tracked within the built-in General Ledger?',
					'status' => 'Yes',
					'a' => 'Credit notes are supported in e-invoice schema, capability catalog, and UAE tax compliance rules. Submitted invoices direct users to issue credit notes with audit trail.',
				),
				array(
					'num' => 60,
					'q' => 'Does the platform support instant processing of split-payments if parts of an order are fulfilled by independent contractors?',
					'status' => 'Partial',
					'a' => 'POS supports split payment (cash/card). Split settlement across independent contractor fulfillments on a single web order is not implemented.',
				),
			),
		),
		array(
			'id' => 'ai',
			'icon' => 'fa-magic',
			'title' => 'AI Companion & Automated Engine',
			'range' => '61–75',
			'items' => array(
				array(
					'num' => 61,
					'q' => 'Is the AI Parts Expert a proprietary LLM model built by ECOM AE, or does it leverage a third-party API (e.g., OpenAI, Anthropic)?',
					'status' => 'Partial',
					'a' => 'AI Parts Expert chat is rule-based plus live DB/catalog tools — not a proprietary LLM. OpenAI is used optionally in Auto Price AI product copy enrichment. Anthropic is not integrated.',
				),
				array(
					'num' => 62,
					'q' => 'How do we feed technical parts documentation and fitment notes into the AI to improve its accuracy?',
					'status' => 'Partial',
					'a' => 'Operators can add a custom system prompt in CP. Fitment comes from eparts catalog/epartscross/live stock — not uploaded PDF/RAG ingestion today. Contact us for custom knowledge projects.',
				),
				array(
					'num' => 63,
					'q' => 'Can the AI chat retrieve real-time data to answer questions like: "Do you have a front brake pad for a 2018 Golf GTI in stock right now?"',
					'status' => 'Yes',
					'a' => 'The agent queries live warehouse stock and returns qty/price in real time — try it on epartscart.com or see our Auto Price AI page.',
				),
				array(
					'num' => 64,
					'q' => 'Does the AI support multilingual conversations, specifically switching seamlessly between English and Arabic?',
					'status' => 'Partial',
					'a' => 'Storefront is multilingual (EN/AR/RU). Parts Agent replies are English-oriented; seamless EN/Arabic switching in chat is not implemented today.',
				),
				array(
					'num' => 65,
					'q' => 'Can the AI assist a user in finding an alternative part if their primary choice is out of stock?',
					'status' => 'Yes',
					'a' => 'Part lookup returns cross-references; the Parts Agent suggests other brands and crosses when stock is empty — rule-based, not a ranked ML substitute engine.',
				),
				array(
					'num' => 66,
					'q' => 'Does the platform use AI to dynamically adjust retail pricing based on competitor tracking or supply scarcity?',
					'status' => 'Partial',
					'a' => 'Auto Price AI (APAI) discovers/compares market prices and applies margin rules on import — catalog pricing intelligence, not continuous competitor-driven repricing on live storefront SKUs.',
				),
				array(
					'num' => 67,
					'q' => 'Can the AI auto-detect spelling mistakes in part searches and route users to the correct component family?',
					'status' => 'Yes',
					'a' => 'Part numbers are normalized for search (punctuation/spacing stripped). Parts Agent uses the same normalization — dedicated LLM typo-correction for component names is not implemented.',
				),
				array(
					'num' => 68,
					'q' => 'Is the AI trained to understand regional automotive slang (e.g., local names for specific suspension or engine components)?',
					'status' => 'No',
					'a' => 'No regional automotive slang training or dialect handling in agent code today.',
				),
				array(
					'num' => 69,
					'q' => 'Can the AI analyze vehicle mileage inputs from customers to proactively recommend maintenance kits?',
					'status' => 'No',
					'a' => 'No mileage-based maintenance kit recommendation logic is implemented.',
				),
				array(
					'num' => 70,
					'q' => 'How does the AI flag or escalate a complex compatibility ticket to a human parts specialist?',
					'status' => 'Partial',
					'a' => 'Agent escalates via WhatsApp/phone/contact links and FAQ paths. Super CP mentions support escalations — no formal ticket queue from chat today.',
				),
				array(
					'num' => 71,
					'q' => 'Can the AI parse uploaded images or photos of damaged parts to identify the required replacement component?',
					'status' => 'No',
					'a' => 'No image/photo upload parsing for part identification in Parts Agent or AI Parts Expert API.',
				),
				array(
					'num' => 72,
					'q' => 'Is there an analytics dashboard to audit the conversation accuracy and conversion rates of the AI tool?',
					'status' => 'Partial',
					'a' => 'CP AI agent chats panel lists sessions, transcripts, filters, and stats. Conversion-rate or accuracy scoring dashboard is not built in.',
				),
				array(
					'num' => 73,
					'q' => 'Can the AI automate the generation of SEO-optimized product titles and descriptions for newly imported SKUs?',
					'status' => 'Partial',
					'a' => 'APAI can generate titles/descriptions via rule-based cleanup plus optional OpenAI — not bulk autonomous SEO for every imported SKU without operator approval.',
				),
				array(
					'num' => 74,
					'q' => 'Does the AI engine automatically flag conflicting fitment information coming from different supplier data streams?',
					'status' => 'No',
					'a' => 'Fitment check exists on part pages but automatic conflict flagging across supplier streams is not implemented.',
				),
				array(
					'num' => 75,
					'q' => 'Can the AI chat guide a customer through the standard returns workflow autonomously?',
					'status' => 'Partial',
					'a' => 'Agent links customers to returns pages; CP has returns manager. Does not autonomously process RMAs end-to-end.',
				),
			),
		),
		array(
			'id' => 'infrastructure',
			'icon' => 'fa-server',
			'title' => 'Infrastructure, Scalability & Security',
			'range' => '76–90',
			'items' => array(
				array(
					'num' => 76,
					'q' => 'What is your guaranteed Uptime SLA, and what are the penalties if it is breached?',
					'status' => 'No',
					'a' => 'Platform Health Checkup monitors uptime, SSL, and backups for operators — no contractual uptime SLA or breach penalties are published in product terms.',
				),
				array(
					'num' => 77,
					'q' => 'Can you explain your dual-cloud failover infrastructure? If your primary cloud host goes down, what is the exact RTO (Recovery Time Objective)?',
					'status' => 'Partial',
					'a' => 'Cloud-hosted stack with failover splash, backup mirror, and health monitoring (60s polling). RTO is operator-configured — we do not publish a guaranteed customer-facing RTO or uptime SLA. See our business continuity page.',
				),
				array(
					'num' => 78,
					'q' => 'Is the platform PCI-DSS Level 1 compliant for credit card security?',
					'status' => 'No',
					'a' => 'No PCI-DSS Level 1 certification documentation in product. Card processing is delegated to gateways (Stripe, Telr, etc.).',
				),
				array(
					'num' => 79,
					'q' => 'What measures are in place to mitigate DDoS attacks during peak high-traffic events?',
					'status' => 'Yes',
					'a' => 'Cloudflare protects the edge (DDoS mitigation, WAF, caching). Origin capacity scales per tenant VPS — no guaranteed absorption spec for extreme peak events.',
				),
				array(
					'num' => 80,
					'q' => 'How does the database scale when dealing with millions of active SKUs and complex compatibility matrices?',
					'status' => 'Partial',
					'a' => 'Architecture is isolated MySQL per tenant on Model C hosting. Performance reports note ~1–2.4s TTFB on large storefronts; Redis/CDN recommended for scale — not proven for millions of SKUs out of the box.',
				),
				array(
					'num' => 81,
					'q' => 'Do we get a dedicated staging/sandbox environment for testing catalog changes before pushing them live to production?',
					'status' => 'Yes',
					'a' => '3-day isolated demo sandbox with own DB, storefront, CP, and ERP — request via our demo page. Super CP can extend demos or convert to live.',
				),
				array(
					'num' => 82,
					'q' => 'What is your data backup frequency, and where are recovery backups physically or virtually stored?',
					'status' => 'Yes',
					'a' => 'Platform full backup tooling and health API track backup age on each tenant. Operator-scheduled full backups (target under 24h) with off-server mirror — not a fixed contractual RPO.',
				),
				array(
					'num' => 83,
					'q' => 'Does the platform use a Content Delivery Network (CDN) to ensure fast image load times for mechanics in remote areas?',
					'status' => 'Yes',
					'a' => 'Cloudflare CDN serves edge cache for static assets and tenant storefronts. Additional asset CDN tuning is available per tenant during onboarding.',
				),
				array(
					'num' => 84,
					'q' => 'How are administrative user permissions tracked? Is there a full, unalterable audit log of back-end staff changes?',
					'status' => 'Yes',
					'a' => 'ERP Audit trail tab logs purchases, GL posts, bank matches, and more — available in CP finance.',
				),
				array(
					'num' => 85,
					'q' => 'Does the infrastructure offer native support for Single Sign-On (SSO) for our corporate enterprise staff?',
					'status' => 'Partial',
					'a' => 'OAuth (Google, Microsoft, Facebook, GitHub, Apple) for storefront/CP login. Enterprise SAML/SSO is not built in — contact us for enterprise requirements.',
				),
				array(
					'num' => 86,
					'q' => 'What is the average page load speed (Time to First Byte) under a simulated load of 10,000 concurrent users?',
					'status' => 'Partial',
					'a' => 'Documented origin TTFB: marketing ~126 ms, epartscart storefront ~1.0–2.4 s under normal load. No 10,000 concurrent user benchmark or guarantee — contact us for load testing on your tenant.',
				),
				array(
					'num' => 87,
					'q' => 'How does the system protect against automated scraping bots trying to steal our pricing and inventory database?',
					'status' => 'Yes',
					'a' => 'API rate limits, CSRF tokens, and Cloudflare edge protection reduce scraping. No dedicated anti-scraping SKU for pricing bots — enterprise tenants can add stricter rate limits.',
				),
				array(
					'num' => 88,
					'q' => 'Is the platform compliant with local Middle Eastern data residency regulations requiring user data to remain in-country?',
					'status' => 'No',
					'a' => 'Hosting on VPS (Model C). No in-country UAE data residency compliance claim or sovereign cloud option is documented.',
				),
				array(
					'num' => 89,
					'q' => 'How frequently do you conduct external third-party penetration testing and vulnerability assessments?',
					'status' => 'No',
					'a' => 'No third-party penetration testing schedule or reports are published in product documentation.',
				),
				array(
					'num' => 90,
					'q' => 'Can the platform handle sudden spikes in API calls when ten suppliers push live updates simultaneously?',
					'status' => 'Partial',
					'a' => 'Public API Phase 1 is read-only with key auth. APAI has cron jobs for crawls. No documented load-shedding for simultaneous supplier feed spikes.',
				),
			),
		),
		array(
			'id' => 'logistics',
			'icon' => 'fa-handshake-o',
			'title' => 'Logistics, Operations & Licensing',
			'range' => '91–105',
			'items' => array(
				array(
					'num' => 91,
					'q' => 'What is the exact licensing model (e.g., monthly SaaS subscription, tier-based seats, or percentage fee of GMV)?',
					'status' => 'Yes',
					'a' => 'Monthly SaaS rental in AED: Starter AED 299, Business AED 599, Enterprise custom — see our pricing page. No GMV percentage in standard plans.',
				),
				array(
					'num' => 92,
					'q' => 'Are there any hidden transactional or API call fees as our traffic scales?',
					'status' => 'Yes',
					'a' => 'Platform rental plans list inclusive features on the pricing page. Catalog/Price PRO API documents daily quotas separately — no hidden per-order fees in standard SaaS plans.',
				),
				array(
					'num' => 93,
					'q' => 'What does the typical deployment and implementation timeline look like for a marketplace of our scope?',
					'status' => 'Yes',
					'a' => 'Standard tenant ERP and storefront can go live within 24 hours after DNS. Full multi-supplier marketplace scope is scoped via demo — enterprise timelines are custom.',
				),
				array(
					'num' => 94,
					'q' => 'Do you assign a dedicated Solution Architect and Account Manager to our project during the build phase?',
					'status' => 'No',
					'a' => 'Contact form and demo wizard handle intake — no productized dedicated Solution Architect assignment workflow in self-service onboarding.',
				),
				array(
					'num' => 95,
					'q' => 'What does post-launch support look like? Do you offer 24/7/365 coverage for Tier 1 (critical checkout/system down) issues?',
					'status' => 'No',
					'a' => 'Contact page: response within one business day (GST). Enterprise plan mentions dedicated operator support but no 24/7/365 Tier-1 SLA is documented.',
				),
				array(
					'num' => 96,
					'q' => 'Which local logistics and courier services (e.g., Aramex, DHL, SMSA) have ready-to-use plug-ins available?',
					'status' => 'No',
					'a' => 'Logistics covers generic carriers, delivery methods, and customs declarations. Named Aramex, DHL, or SMSA plug-ins are not pre-integrated — configure carriers manually or contact us.',
				),
				array(
					'num' => 97,
					'q' => 'Can the system calculate dynamic volumetric weight shipping rates directly at checkout for multi-item orders?',
					'status' => 'No',
					'a' => 'No volumetric/dimensional weight checkout calculator in shipping modules today.',
				),
				array(
					'num' => 98,
					'q' => 'How are custom-tailored courier picking labels and manifests generated inside the shipping module?',
					'status' => 'Partial',
					'a' => 'Delivery notes and customs declaration PDFs/manifests exist in Custom & Shipping. Courier API label generation (Aramex/DHL ZPL/PDF) is not built in.',
				),
				array(
					'num' => 99,
					'q' => 'Does the platform support automated SMS or WhatsApp tracking notifications for delivery status changes?',
					'status' => 'Yes',
					'a' => 'On order status change the platform generates bilingual WhatsApp tracking messages (wa.me templates logged on the order) plus email notifications. SMS and WhatsApp Business API auto-send are not built in — operators send the logged template.',
				),
				array(
					'num' => 100,
					'q' => 'What training documentation, video tutorials, or manuals do you provide for our operations and warehouse staff?',
					'status' => 'Yes',
					'a' => 'Operator guides plus POS, Tax, Integrations, Auto Price AI, Deployment docs. CP has module-specific guides for ERP, payments, and custom shipping.',
				),
				array(
					'num' => 101,
					'q' => 'Is there a cap on the total file storage capacity allowed for product images, videos, and technical drawings?',
					'status' => 'Yes',
					'a' => 'No enforced storage cap per tenant plan in product code — practical limits follow VPS disk allocation for your hosting tier.',
				),
				array(
					'num' => 102,
					'q' => 'Can we white-label the entire customer-facing ecosystem, including emails, invoices, and mobile app elements?',
					'status' => 'Yes',
					'a' => 'Each tenant runs on its own domain with branding (logo, colours, CP settings) and mobile app white-label pack. Email/invoice template depth varies by plan — scope per contract on our pricing page.',
				),
				array(
					'num' => 103,
					'q' => 'What is your product roadmap for the next 12–24 months, and do we get automatic access to newly developed features?',
					'status' => 'Partial',
					'a' => '12–24 month ecosystem roadmap is on our platform overview. No automatic feature access guarantee — rental plans say indicative, final terms per contract.',
				),
				array(
					'num' => 104,
					'q' => 'Are there early termination penalties if our business needs change and we decide to migrate off the ECOM AE cloud platform?',
					'status' => 'No',
					'a' => 'Early termination penalties are not documented in codebase or pricing pages — governed by your commercial agreement.',
				),
				array(
					'num' => 105,
					'q' => 'Can we build custom front-end storefronts (Headless Commerce architecture) using your back-end core ERP engine?',
					'status' => 'Partial',
					'a' => 'Phase 1 read-only REST API plus Catalog/Price PRO API for external frontends. Write APIs and full headless commerce checkout against ERP core are future scope — contact us for API roadmap.',
				),
			),
		),
	);
}

function epc_ecomae_faq_status_counts(): array
{
	$counts = array('Yes' => 0, 'Partial' => 0, 'Planned' => 0, 'No' => 0);
	foreach (epc_ecomae_faq_modules() as $mod) {
		foreach ($mod['items'] as $item) {
			$s = (string) ($item['status'] ?? 'Partial');
			if (isset($counts[$s])) { $counts[$s]++; }
		}
	}
	return $counts;
}
