<?php
/**
 * Client CP + Super CP brochure inventory (exhaustive).
 * Sources: capabilities catalog, CP guideline, mainstream menu builders,
 * tenant dashboard, ecomae menu cache, portal/BOC/ERP nav.
 *
 * Item: name (EN), does (one line), url (typical /cp/…), scope ('client'|'super'|'both')
 * Usage: $inv = require __DIR__ . '/epc_cp_brochure_inventory.php';
 */
if (!defined('_ASTEXE_')) { define('_ASTEXE_', 1); }

return array(
	'Super CP / Platform' => array(
		array('name' => 'API clients', 'does' => 'Tenant-scoped API keys, scopes, and quotas for /epc-api/v1/.', 'url' => '/cp/control/portal/epc_api_clients_manage', 'scope' => 'super'),
		array('name' => 'API documentation guide', 'does' => 'OpenAPI and key-management guide.', 'url' => '/cp/control/portal/epc_api_documentation_guide', 'scope' => 'super'),
		array('name' => 'Demo tenants', 'does' => 'Sandbox extend / convert / delete for demo sites.', 'url' => '/cp/control/portal/epc_demo_tenants_manage', 'scope' => 'super'),
		array('name' => 'Epc Api Clients Manage', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_api_clients_manage', 'scope' => 'super'),
		array('name' => 'Epc Demo Tenants Manage', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_demo_tenants_manage', 'scope' => 'super'),
		array('name' => 'Epc Erp Only Onboard Guide', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_erp_only_onboard_guide', 'scope' => 'super'),
		array('name' => 'Epc Platform Failover Guide', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_platform_failover_guide', 'scope' => 'super'),
		array('name' => 'Epc Platform Governance', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_platform_governance', 'scope' => 'super'),
		array('name' => 'Epc Platform Health Checkup', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_platform_health_checkup', 'scope' => 'super'),
		array('name' => 'Epc Pos Tenant Manage', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_pos_tenant_manage', 'scope' => 'super'),
		array('name' => 'Epc Tenant Control Center', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_tenant_control_center', 'scope' => 'super'),
		array('name' => 'ERP-only onboard guide', 'does' => 'Launch finance-only tenants without a storefront.', 'url' => '/cp/control/portal/epc_erp_only_onboard_guide', 'scope' => 'super'),
		array('name' => 'Failover runbook', 'does' => 'Business continuity splash screens and backup origin steps.', 'url' => '/cp/control/portal/epc_platform_failover_guide', 'scope' => 'super'),
		array('name' => 'Free Tools admin', 'does' => 'Activate/deactivate free tools; usage stats.', 'url' => '/cp/control/portal/epc_free_tools_admin', 'scope' => 'super'),
		array('name' => 'Industry settings & deploy', 'does' => 'Vertical packs, branding, sidebar; deploy packages to tenants.', 'url' => '/cp/control/portal/industry_settings', 'scope' => 'super'),
		array('name' => 'Modular ERP access', 'does' => 'Toggle ERP packs per client: full, C&S only, People, Finance+e-invoice.', 'url' => '/cp/control/portal/industry_settings', 'scope' => 'super'),
		array('name' => 'Multi-tenant hostname routing', 'does' => 'One nginx stack; hostname selects isolated tenant DB and branding.', 'url' => '', 'scope' => 'super'),
		array('name' => 'Platform governance', 'does' => 'Cross-tenant policies and platform rules.', 'url' => '/cp/control/portal/epc_platform_governance', 'scope' => 'super'),
		array('name' => 'Platform health checkup', 'does' => 'Probe storefronts, SSL, ERP DB, nginx, backups, sitemaps; CSV export.', 'url' => '/cp/control/portal/epc_platform_health_checkup', 'scope' => 'super'),
		array('name' => 'POS tenant overview', 'does' => 'POS status and settings across all tenants.', 'url' => '/cp/control/portal/epc_pos_tenant_manage', 'scope' => 'super'),
		array('name' => 'Super CP operator console', 'does' => 'Hosted console at ecomae.com/cp to run every tenant.', 'url' => '/cp/', 'scope' => 'super'),
		array('name' => 'Tenant control center', 'does' => 'Credentials, on/off, and per-tenant operator controls.', 'url' => '/cp/control/portal/epc_tenant_control_center', 'scope' => 'super'),
		array('name' => 'Tenant features', 'does' => 'Per-tenant feature flag matrix.', 'url' => '/cp/control/portal/epc_tenant_features', 'scope' => 'super'),
		array('name' => 'Tenant hub', 'does' => 'Client registry, onboard form, DNS checklist, go-live probes.', 'url' => '/cp/shop/tenant_hub/tenant_hub', 'scope' => 'super'),
	),
	'Super CP / Operator' => array(
		array('name' => 'Communication', 'does' => 'Platform e-mail policy and operator tasks.', 'url' => '/cp/control/portal/epc_super_cp_communication', 'scope' => 'super'),
		array('name' => 'Customer board', 'does' => 'Cross-tenant CRM/ERP customer search.', 'url' => '/cp/control/portal/epc_super_cp_customer_board', 'scope' => 'super'),
		array('name' => 'Epc Super Cp Communication', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_super_cp_communication', 'scope' => 'super'),
		array('name' => 'Epc Super Cp Customer Board', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_super_cp_customer_board', 'scope' => 'super'),
		array('name' => 'Epc Super Cp Info Blocks', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_super_cp_info_blocks', 'scope' => 'super'),
		array('name' => 'Epc Super Cp Operator Guide', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_super_cp_operator_guide', 'scope' => 'super'),
		array('name' => 'Epc Super Cp Price Configs', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_super_cp_price_configs', 'scope' => 'super'),
		array('name' => 'Epc Visual Page Editor', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_visual_page_editor', 'scope' => 'super'),
		array('name' => 'Info blocks (CMS)', 'does' => 'Cross-tenant storefront & CP info blocks.', 'url' => '/cp/control/portal/epc_super_cp_info_blocks', 'scope' => 'super'),
		array('name' => 'Operator guide', 'does' => 'Who uses what across Super CP operator tools.', 'url' => '/cp/control/portal/epc_super_cp_operator_guide', 'scope' => 'super'),
		array('name' => 'Price configs', 'does' => 'Platform markup / price generation configs.', 'url' => '/cp/control/portal/epc_super_cp_price_configs', 'scope' => 'super'),
	),
	'Super CP / BOC' => array(
		array('name' => 'Audit log', 'does' => 'Who did what, when — operator audit trail.', 'url' => '/cp/control/portal/epc_boc_audit_log', 'scope' => 'super'),
		array('name' => 'Channels & orders (fleet OMS)', 'does' => 'Web / POS / API / marketplace surfaces fleet-wide.', 'url' => '/cp/control/portal/epc_boc_channel_control', 'scope' => 'super'),
		array('name' => 'Command Center', 'does' => 'Live fleet health, KPIs, and alerts across all tenant types.', 'url' => '/cp/control/portal/epc_boc_command_center', 'scope' => 'super'),
		array('name' => 'Vendor & sourcing (fleet)', 'does' => 'Fleet-wide suppliers, RFQs, and spend.', 'url' => '/cp/control/portal/epc_boc_vendor_control', 'scope' => 'super'),
		array('name' => 'Warehouse & inventory (fleet)', 'does' => 'Stock value, locations, replenishment risk across tenants.', 'url' => '/cp/control/portal/epc_boc_warehouse_control', 'scope' => 'super'),
	),
	'Portal' => array(
		array('name' => 'Epc Api Documentation Guide', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_api_documentation_guide', 'scope' => 'client'),
		array('name' => 'Epc Auto Price Engine', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_auto_price_engine', 'scope' => 'client'),
		array('name' => 'Epc Cp Auth Settings', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_cp_auth_settings', 'scope' => 'client'),
		array('name' => 'Epc Custom Shipping Guide', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_custom_shipping_guide', 'scope' => 'client'),
		array('name' => 'Epc Marketing Broadcast', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_marketing_broadcast', 'scope' => 'client'),
		array('name' => 'Epc Social Media Hub', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_social_media_hub', 'scope' => 'client'),
		array('name' => 'Epc Tax Toolkit Manage', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_tax_toolkit_manage', 'scope' => 'client'),
		array('name' => 'Epc Visual Page Editor', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_visual_page_editor', 'scope' => 'client'),
		array('name' => 'Industry settings', 'does' => 'Branding, industry packs, module visibility (client view; no deploy).', 'url' => '/cp/control/portal/industry_settings', 'scope' => 'client'),
		array('name' => 'POS Terminal', 'does' => 'In-store checkout.', 'url' => '/cp/shop/pos/terminal', 'scope' => 'client'),
		array('name' => 'Auto Price AI', 'does' => 'Discover, compare, and import products across market sources.', 'url' => '/cp/control/portal/epc_auto_price_engine', 'scope' => 'both'),
		array('name' => 'Autoworkshop guide', 'does' => 'Workshop vertical setup guide.', 'url' => '/cp/control/portal/epc_autoworkshop_guide', 'scope' => 'both'),
		array('name' => 'CP auth settings', 'does' => 'Password, e-mail OTP, Google OAuth, operator MFA.', 'url' => '/cp/control/portal/epc_cp_auth_settings', 'scope' => 'both'),
		array('name' => 'Custom & Shipping guide', 'does' => 'How-to for UAE customs declarations module.', 'url' => '/cp/control/portal/epc_custom_shipping_guide', 'scope' => 'both'),
		array('name' => 'Marketing broadcast', 'does' => 'Bulk e-mail / WhatsApp marketing broadcasts.', 'url' => '/cp/control/portal/epc_marketing_broadcast', 'scope' => 'both'),
		array('name' => 'Power BI', 'does' => 'Power BI embed / connector settings.', 'url' => '/cp/control/portal/epc_power_bi', 'scope' => 'both'),
		array('name' => 'Power BI guide', 'does' => 'How to connect Power BI to tenant data.', 'url' => '/cp/control/portal/epc_power_bi_guide', 'scope' => 'both'),
		array('name' => 'Social media hub', 'does' => 'Captions, accounts, and AI social advisor.', 'url' => '/cp/control/portal/epc_social_media_hub', 'scope' => 'both'),
		array('name' => 'Tax Toolkit', 'does' => 'Worldwide VAT/GST/CIT kits; one-click rate refresh.', 'url' => '/cp/control/portal/epc_tax_toolkit_manage', 'scope' => 'both'),
		array('name' => 'Visual page editor', 'does' => 'Block layout editor for storefront pages with live preview.', 'url' => '/cp/control/portal/epc_visual_page_editor', 'scope' => 'both'),
		array('name' => 'Web tracker', 'does' => 'Site analytics / visitor tracking admin.', 'url' => '/cp/control/portal/epc_web_tracker', 'scope' => 'both'),
	),
	'Integrations' => array(
		array('name' => 'Epc Integrations Hub', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_integrations_hub', 'scope' => 'client'),
		array('name' => 'Epc Mobile Apps', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_mobile_apps', 'scope' => 'client'),
		array('name' => 'Epc Tenant Email Settings', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_tenant_email_settings', 'scope' => 'client'),
		array('name' => 'Tenant e-mail / SMTP', 'does' => 'Per-tenant SMTP mailbox settings (client CP only).', 'url' => '/cp/control/portal/epc_tenant_email_settings', 'scope' => 'client'),
		array('name' => 'Integrations hub', 'does' => 'Connection health for e-mail, payments, mobile, and more.', 'url' => '/cp/control/portal/epc_integrations_hub', 'scope' => 'both'),
		array('name' => 'Mobile apps', 'does' => 'Android / iOS / PWA app settings and packaging.', 'url' => '/cp/control/portal/epc_mobile_apps', 'scope' => 'both'),
		array('name' => 'Epc Tenant Features', 'does' => 'Open from left CP menu.', 'url' => '/cp/control/portal/epc_tenant_features', 'scope' => 'super'),
	),
	'Shop / OMS' => array(
		array('name' => 'Abandoned carts', 'does' => 'View customer carts that have not checked out.', 'url' => '/cp/shop/orders/carts', 'scope' => 'client'),
		array('name' => 'Accessories marketplace', 'does' => 'Marketplace-style accessories listings.', 'url' => '/cp/shop/accessories', 'scope' => 'client'),
		array('name' => 'Account operations', 'does' => 'Customer balance top-ups, charges, ledger ops.', 'url' => '/cp/shop/finance/account_operations', 'scope' => 'client'),
		array('name' => 'B2B trade accounts', 'does' => 'Logged-in trade buyers get fixed currency, credit limits, balance view, and re-order from history. Auto-parts and wholesale…', 'url' => '/cp/users/customer_approvals', 'scope' => 'client'),
		array('name' => 'Branch offices', 'does' => 'Pickup points and branch office list.', 'url' => '/cp/shop/logistics/offices', 'scope' => 'client'),
		array('name' => 'Cash book', 'does' => 'Petty cash / cash register book.', 'url' => '/cp/shop/cash', 'scope' => 'client'),
		array('name' => 'Cross-references', 'does' => 'OEM / aftermarket interchange management.', 'url' => '/cp/shop/crosses', 'scope' => 'client'),
		array('name' => 'Currency rates', 'does' => 'Exchange rates for multi-currency display.', 'url' => '/cp/shop/finance/nastrojka-kursov-valyut', 'scope' => 'client'),
		array('name' => 'Delivery notes & pick lists', 'does' => 'Generate delivery notes and pick lists from confirmed orders — print-ready documents with line items, weights, and customer…', 'url' => '/cp/shop/document_control/document_control', 'scope' => 'client'),
		array('name' => 'Demand countries', 'does' => 'Demand intel export.', 'url' => '/cp/shop/demand_countries', 'scope' => 'client'),
		array('name' => 'Downloadable price lists', 'does' => 'Publish price lists customers can download.', 'url' => '/cp/shop/prices/prajs-listy-dlya-skachivaniya', 'scope' => 'client'),
		array('name' => 'Geo / regions', 'does' => 'Geographic nodes for delivery and localization.', 'url' => '/cp/shop/geo/nodes', 'scope' => 'client'),
		array('name' => 'Manufacturer synonyms', 'does' => 'Normalize brand name aliases for search and pricing.', 'url' => '/cp/shop/manufacturers_synonyms', 'scope' => 'client'),
		array('name' => 'OMS daily guide', 'does' => 'Daily OMS workflow for staff.', 'url' => '/cp/shop/orders/oms-guide', 'scope' => 'client'),
		array('name' => 'OMS · Orders', 'does' => 'Order desk console.', 'url' => '/cp/shop/orders/orders', 'scope' => 'client'),
		array('name' => 'Online cash registers', 'does' => 'Fiscal online cash register integration.', 'url' => '/cp/shop/onlajn-kassy', 'scope' => 'client'),
		array('name' => 'Order desk & statuses', 'does' => 'Staff manage order lifecycle from new through packed, shipped, and completed. Status updates trigger customer emails and feed…', 'url' => '/cp/shop/orders/orders', 'scope' => 'client'),
		array('name' => 'Order fulfilment guide', 'does' => 'Checkout → LPO → processing.', 'url' => '/cp/shop/orders/guide', 'scope' => 'client'),
		array('name' => 'Order fulfilment workflows', 'does' => 'Pick, pack, and ship with warehouse-aware fulfilment hooks tied to stock. Returns and partial shipments stay traceable in CP…', 'url' => '/cp/shop/orders/orders', 'scope' => 'client'),
		array('name' => 'Order items', 'does' => 'Browse order line items across all orders.', 'url' => '/cp/shop/orders/items', 'scope' => 'client'),
		array('name' => 'Order statuses', 'does' => 'Configure order lifecycle statuses.', 'url' => '/cp/shop/orders/statuses', 'scope' => 'client'),
		array('name' => 'Price lists', 'does' => 'Upload, schedule, and monitor supplier price files.', 'url' => '/cp/shop/prices', 'scope' => 'client'),
		array('name' => 'Price management', 'does' => 'Profiles, margins, brand/article rules.', 'url' => '/cp/shop/price-management', 'scope' => 'client'),
		array('name' => 'Product filters', 'does' => 'Configure catalogue filter facets.', 'url' => '/cp/shop/filter', 'scope' => 'client'),
		array('name' => 'Promos & discount rules', 'does' => 'Campaign promo codes, cart rules, and tiered discounts drive conversion on the storefront. Link promotions to marketing…', 'url' => '/cp/shop/marketing/marketing', 'scope' => 'client'),
		array('name' => 'Quote requests', 'does' => 'Manage customer RFQ / quote request submissions.', 'url' => '/cp/shop/quote-requests', 'scope' => 'client'),
		array('name' => 'Returns & RMA handling', 'does' => 'Process returns and warranty claims with status tracking and stock put-back. Electronics and medical verticals get serial and…', 'url' => '/cp/shop/returns-manager', 'scope' => 'client'),
		array('name' => 'Returns manager', 'does' => 'Process returns and RMA claims.', 'url' => '/cp/shop/returns-manager', 'scope' => 'client'),
		array('name' => 'SAO status links', 'does' => 'Map supplier API states to local order statuses.', 'url' => '/cp/shop/orders/sao_states_statuses_link', 'scope' => 'client'),
		array('name' => 'Search tabs', 'does' => 'Configure storefront search tab layout.', 'url' => '/cp/shop/taby-poiska', 'scope' => 'client'),
		array('name' => 'Send price lists', 'does' => 'Email price lists to customers or partners.', 'url' => '/cp/shop/prices_send', 'scope' => 'client'),
		array('name' => 'Shop statistics', 'does' => 'Sales and storefront analytics charts.', 'url' => '/cp/shop/statistika', 'scope' => 'client'),
		array('name' => 'Shopping cart & checkout', 'does' => 'Guest and logged-in checkout with delivery choice, promo codes, and payment at checkout. Orders flow straight into CP order…', 'url' => '/cp/shop/orders/orders', 'scope' => 'client'),
		array('name' => 'System requests', 'does' => 'Background/async request queue.', 'url' => '/cp/requests', 'scope' => 'client'),
		array('name' => 'Warehouses', 'does' => 'Warehouse master data and LPO e-mail for suppliers.', 'url' => '/cp/shop/logistics/storages', 'scope' => 'client'),
		array('name' => 'WhatsApp order sharing', 'does' => 'Share cart or order summaries via WhatsApp for quick B2B confirmation. Popular with UAE and GCC traders who close deals on…', 'url' => '/cp/shop/orders/whatsapp-guide', 'scope' => 'client'),
	),
	'Prices & Catalogue' => array(
		array('name' => 'Bulk CSV import & export', 'does' => 'Upload seasonal collections or thousands of SKUs via CSV — map columns, preview, and commit in minutes. Export for backup,…', 'url' => '/cp/shop/prices', 'scope' => 'client'),
		array('name' => 'Catalogue tree', 'does' => 'Edit nested category tree.', 'url' => '/cp/shop/catalogue/catalogue_editor', 'scope' => 'client'),
		array('name' => 'Categories & attributes', 'does' => 'Merchandise with nested categories, spec filters, and custom attribute fields. Electronics get datasheet filters; fashion gets…', 'url' => '/cp/shop/catalogue/catalogue_editor', 'scope' => 'client'),
		array('name' => 'Cross-reference lookup', 'does' => 'OEM and aftermarket cross tables help customers find interchangeable parts. Cross matches against in-stock SKUs display price…', 'url' => '/cp/shop/crosses', 'scope' => 'client'),
		array('name' => 'Customer reviews', 'does' => 'Moderate storefront product reviews.', 'url' => '/cp/shop/catalogue/otzyvy-pokupatelej', 'scope' => 'client'),
		array('name' => 'Data migration', 'does' => 'Import/export catalogue and related data.', 'url' => '/cp/shop/perenos-dannyx', 'scope' => 'client'),
		array('name' => 'Edit price rows', 'does' => 'Browse imported rows; preview per profile.', 'url' => '/cp/shop/prices/prices_edit', 'scope' => 'client'),
		array('name' => 'Homepage products', 'does' => 'Featured products on storefront home.', 'url' => '/cp/shop/catalogue/tovary-na-glavnoj', 'scope' => 'client'),
		array('name' => 'Line lists', 'does' => 'Flat product lists for merchandising.', 'url' => '/cp/shop/catalogue/line_lists', 'scope' => 'client'),
		array('name' => 'Live supplier price search', 'does' => 'Search pulls prices from connected suppliers at order time — customers see current trade rates on the storefront. Ideal for…', 'url' => '/cp/shop/prices', 'scope' => 'client'),
		array('name' => 'Multivendor prices', 'does' => 'Supplier price pipelines.', 'url' => '/cp/shop/prices/multivendor', 'scope' => 'client'),
		array('name' => 'Price lists & customer margins', 'does' => 'Customer groups and profiles drive margin rules, fixed currency, and visibility show/hide by brand. B2B clients see contract…', 'url' => '/cp/shop/price-management', 'scope' => 'client'),
		array('name' => 'Price upload guide', 'does' => 'CSV price list import walkthrough.', 'url' => '/cp/shop/prices/guide', 'scope' => 'client'),
		array('name' => 'Product catalogue', 'does' => 'Full SKU management with rich product pages, media, and category trees for fashion, electronics, medical, and general retail.…', 'url' => '/cp/shop/catalogue/products', 'scope' => 'client'),
		array('name' => 'Products', 'does' => 'SKU management: publish, media, attributes, variants.', 'url' => '/cp/shop/catalogue/products', 'scope' => 'client'),
		array('name' => 'Related products', 'does' => 'Cross-sell / accessory product links.', 'url' => '/cp/shop/catalogue/soputstvuyushhie-tovary', 'scope' => 'client'),
		array('name' => 'Special searches', 'does' => 'Custom search widgets (VIN, OEM, etc.).', 'url' => '/cp/shop/catalogue/specialnye-poiski', 'scope' => 'client'),
		array('name' => 'Stock levels', 'does' => 'Stock quantities by category and product.', 'url' => '/cp/shop/logistics/stock', 'scope' => 'client'),
		array('name' => 'Supplier price upload', 'does' => 'Import supplier price files and keep trade pricing current without manual re-keying. Built for auto-parts distributors and B2B…', 'url' => '/cp/shop/prices', 'scope' => 'client'),
		array('name' => 'Tree lists', 'does' => 'Hierarchical product list structures.', 'url' => '/cp/shop/catalogue/tree_lists', 'scope' => 'client'),
		array('name' => 'Variant SKUs (size, colour, spec)', 'does' => 'Sell products with multiple variants — each with its own SKU, stock, and price. Storefront variant selectors and CP…', 'url' => '/cp/shop/catalogue/products', 'scope' => 'client'),
		array('name' => 'Vehicle-fitment catalogue', 'does' => 'Browse by make, model, and modification — Epart catalog integration for passenger, commercial, and motorbike segments. Product…', 'url' => '/cp/shop/catalogue/specialnye-poiski', 'scope' => 'client'),
		array('name' => 'VIN & OEM number search', 'does' => 'Vehicle-aware search widgets decode VIN or accept OEM numbers for precise fitment. Reduces wrong-part orders and builds trust…', 'url' => '/cp/shop/catalogue/specialnye-poiski', 'scope' => 'client'),
	),
	'Payments' => array(
		array('name' => 'Customer balance & credit limits', 'does' => 'Track trade account balances and enforce credit limits at checkout. B2B clients see running balance in client CP; staff…', 'url' => '/cp/shop/finance/account_operations', 'scope' => 'client'),
		array('name' => 'Multi-currency display & checkout', 'does' => 'Show prices and accept payment in multiple currencies for cross-border and tourist retail. Exchange display rules configurable…', 'url' => '/cp/shop/finance/nastrojka-kursov-valyut', 'scope' => 'client'),
		array('name' => 'Payment batches (ERP treasury)', 'does' => 'Batch outgoing supplier and expense payments from ERP treasury — approve, schedule, and audit payment runs from finance roles.', 'url' => '/cp/shop/finance/erp?area=banking&tab=payment_batches&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Payment gateway setup', 'does' => 'Configure card and local payment gateways for UAE and GCC checkout. Gateway settings live in CP — test mode and live…', 'url' => '/cp/shop/payments/payments', 'scope' => 'client'),
		array('name' => 'Payment gateways', 'does' => 'Card and local gateways.', 'url' => '/cp/shop/payments/payments', 'scope' => 'client'),
		array('name' => 'Payment reconciliation', 'does' => 'Match gateway settlements to orders and ERP receipts — reduce manual spreadsheet work for finance teams. Discrepancies surface…', 'url' => '/cp/shop/payments/payments', 'scope' => 'client'),
		array('name' => 'Payments guide', 'does' => 'Gateway setup walkthrough.', 'url' => '/cp/shop/payments/payments/guide', 'scope' => 'client'),
	),
	'Logistics' => array(
		array('name' => 'Branch & office list', 'does' => 'Maintain branch offices and pickup points shown on storefront and delivery notes. Useful for multi-location retailers and…', 'url' => '/cp/shop/logistics/offices', 'scope' => 'client'),
		array('name' => 'Carriers & shipments', 'does' => 'Manage carrier accounts, shipment creation, and tracking references. Logistics hub ties customer orders to outbound shipments…', 'url' => '/cp/shop/logistics/carriers', 'scope' => 'client'),
		array('name' => 'Custom & shipping declarations', 'does' => 'UAE customs declaration registry — import, export, transit, temporary admission, transfer, and LGP entries with dashboard…', 'url' => '/cp/shop/finance/erp?area=logistics&tab=custom_shipping&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Delivery methods', 'does' => 'Courier, pickup, service-area rules.', 'url' => '/cp/shop/logistics/sposoby-polucheniya', 'scope' => 'client'),
		array('name' => 'Delivery methods & pickup', 'does' => 'Configure courier, branch pickup, and service-area rules on the storefront. Customers choose delivery at checkout; lead times…', 'url' => '/cp/shop/logistics/sposoby-polucheniya', 'scope' => 'client'),
		array('name' => 'Logistics guide', 'does' => 'Logistics how-to.', 'url' => '/cp/shop/logistics/guide', 'scope' => 'client'),
		array('name' => 'Logistics hub', 'does' => 'Warehouses, carriers, delivery.', 'url' => '/cp/shop/logistics', 'scope' => 'client'),
		array('name' => 'Logistics reports', 'does' => 'Operational reports on fulfilment throughput, carrier performance, and stock by location. Export-friendly views for warehouse…', 'url' => '/cp/shop/logistics', 'scope' => 'client'),
		array('name' => 'OMS · Orders', 'does' => 'Customer orders shortcut from Logistics.', 'url' => '/cp/shop/orders/orders', 'scope' => 'client'),
		array('name' => 'Warehouses & storages', 'does' => 'Master warehouse and storage locations with stock allocation per site. Multi-warehouse inventory feeds catalogue availability…', 'url' => '/cp/shop/logistics/storages', 'scope' => 'client'),
		array('name' => 'WhatsApp sharing guide', 'does' => 'WhatsApp order sharing.', 'url' => '/cp/shop/orders/whatsapp-guide', 'scope' => 'client'),
	),
	'Channels / Marketplace' => array(
		array('name' => 'Channel integrations pack', 'does' => 'Enable marketplace and aggregator integrations per industry pack. Fashion, electronics, and auto-parts tenants extend reach…', 'url' => '/cp/shop/channels/channels', 'scope' => 'client'),
		array('name' => 'Channel order routing', 'does' => 'External channel orders route into the same fulfilment and ERP pipeline as web orders. One pick/pack workflow regardless of…', 'url' => '/cp/shop/channels/channels', 'scope' => 'client'),
		array('name' => 'Channels guide', 'does' => 'Marketplace setup help.', 'url' => '/cp/shop/channels/guide', 'scope' => 'client'),
		array('name' => 'Marketplace listing sync', 'does' => 'Push catalogue and stock updates to connected channels — reduce overselling with shared inventory truth. Listing errors…', 'url' => '/cp/shop/channels/channels', 'scope' => 'client'),
		array('name' => 'Omnichannel hub', 'does' => 'Central hub for selling beyond your own storefront — connect marketplaces and sales channels from one CP screen. Orders from…', 'url' => '/cp/shop/channels/channels', 'scope' => 'client'),
	),
	'Procurement' => array(
		array('name' => '3-way match (PO / GRN / invoice)', 'does' => 'Match purchase order, goods receipt, and supplier invoice before payment approval. Reduces duplicate payments and catches…', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=three_way_match&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement & suppliers', 'does' => 'Purchasing hub.', 'url' => '/cp/shop/procurement/procurement', 'scope' => 'client'),
		array('name' => 'Procurement workflows', 'does' => 'End-to-end buy-side process from demand signal through PO, receipt, and invoice. Integrated with auto-parts SAO and ERP…', 'url' => '/cp/shop/procurement/procurement', 'scope' => 'client'),
		array('name' => 'Purchase orders', 'does' => 'Create and track POs from requisition through receipt. PO lines link to ERP payables and three-way match when finance pack is…', 'url' => '/cp/shop/procurement/procurement', 'scope' => 'client'),
		array('name' => 'RFQ & supplier quotes', 'does' => 'Request quotes from multiple suppliers and compare responses before committing to a PO. Built for project-based and MRO…', 'url' => '/cp/shop/procurement/procurement', 'scope' => 'client'),
		array('name' => 'Supplier directory', 'does' => 'Maintain supplier master data — contacts, terms, and linked price files. Auto-parts and wholesale tenants manage dozens of…', 'url' => '/cp/shop/procurement/procurement', 'scope' => 'client'),
		array('name' => 'Supplier payables', 'does' => 'Track amounts owed to suppliers and schedule settlement from ERP payables tab. Aging reports help finance prioritise cash…', 'url' => '/cp/shop/procurement/procurement', 'scope' => 'client'),
	),
	'ERP / Finance' => array(
		array('name' => 'Accounts receivable', 'does' => 'Track customer invoices, receipts, and aging from sales orders through collection. B2B trade balances sync with storefront…', 'url' => '/cp/shop/finance/erp?area=ar&tab=receivables&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Aging & statements of account', 'does' => 'Config-driven AR / AP / inventory aging with per-bucket totals and distribution bars, plus customer and vendor statements of…', 'url' => '/cp/shop/finance/erp?area=finance&tab=aging&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Bank reconciliation', 'does' => 'Match bank statement lines to ERP receipts and payments — flag unmatched items for review. Monthly recon workflow keeps books…', 'url' => '/cp/shop/finance/erp?area=banking&tab=bank_recon&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Business unit & financial dimensions', 'does' => 'D365-style financial dimensions — business unit, cost centre, department, project and custom tenant dimensions — selectable on…', 'url' => '/cp/shop/finance/erp?area=enterprise&tab=business_units&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash & bank treasury', 'does' => 'Manage bank accounts, petty cash, and treasury movements in one finance area. Payment batches and reconciliation tie back to…', 'url' => '/cp/shop/finance/erp?area=banking&tab=cash_bank&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Chart of accounts', 'does' => 'Configure COA structure for UAE trading, services, and multi-department businesses. Opening balances migration supported for…', 'url' => '/cp/shop/finance/erp?area=finance&tab=coa&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cross-department workflow', 'does' => 'Visual workflow across sales, purchasing, finance, and operations — see bottlenecks before month-end. Native ERP tabs replace…', 'url' => '/cp/shop/finance/erp?area=overview&tab=workflow&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Custom & Shipping', 'does' => 'UAE customs declarations in ERP.', 'url' => '/cp/shop/finance/erp?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Custom & Shipping guide', 'does' => 'Customs how-to.', 'url' => '/cp/shop/finance/erp/custom-shipping-guide?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Enterprise modules (D365-style)', 'does' => 'Fourteen config-driven enterprise modules with sub-modules — Business unit, Listing, Product information, Inventory, AP, AR,…', 'url' => '/cp/shop/finance/erp?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'ERP dashboard & KPIs', 'does' => 'Live KPIs across sales, stock, and finance on one dashboard — plus cross-department workflow view. Standalone /erp portal…', 'url' => '/cp/shop/finance/erp?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'ERP guide', 'does' => 'ERP how-to for finance teams.', 'url' => '/cp/shop/finance/erp/guide?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Fixed assets & depreciation', 'does' => 'Asset register with straight-line and declining depreciation, monthly runs, and net book value reports. Tracking IDs and…', 'url' => '/cp/shop/finance/erp?area=fixed_assets&tab=fixed_assets&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger', 'does' => 'Double-entry GL with journal entries, period close, and audit-friendly posting history. Commerce and ERP share customer and…', 'url' => '/cp/shop/finance/erp?area=finance&tab=gl&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory & weighted average cost', 'does' => 'Multi-warehouse stock with purchase receipts, sales issues, and weighted average costing. Perishable expiry and batch fields…', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=inventory&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Multi-company ERP access', 'does' => 'Username/password sign-in per department user with company-scoped customs declarations, cost summaries, and entity fields —…', 'url' => '/cp/shop/finance/erp?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'NetSuite dashboard + D365 forms', 'does' => 'NetSuite-style role dashboard (tiles, KPI gauge, aging chart, quick actions) with Dynamics 365 Finance & Operations inner…', 'url' => '/cp/shop/finance/erp?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'P&L & balance sheet', 'does' => 'Standard financial statements from posted GL — filter by period and export for advisors. Tax firms use this alongside VAT…', 'url' => '/cp/shop/finance/erp?area=finance&tab=pl&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Period & as-of-date reporting', 'does' => 'True point-in-time ERP reporting — inventory on hand, stock value and balances reconstructed as at any date or fiscal period…', 'url' => '/cp/shop/finance/erp?area=finance&tab=reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'UAE tax compliance', 'does' => 'FTA VAT / CT workspace.', 'url' => '/cp/shop/finance/erp/uae-tax-compliance?epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Worldwide Tax Toolkit', 'does' => 'Complete business taxation for 195+ countries — VAT/GST, corporate income tax (CIT), import/export customs duty, withholding,…', 'url' => '/cp/control/portal/epc_tax_toolkit_manage', 'scope' => 'client'),
	),
	'ERP / Modules' => array(
		array('name' => 'Accounts payable: Payables', 'does' => 'Vendor invoices, payments and AP setup', 'url' => '/cp/shop/finance/erp?area=ap&tab=payables&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Accounts payable: Vendor setup', 'does' => 'Vendor invoices, payments and AP setup', 'url' => '/cp/shop/finance/erp?area=ap&tab=ap_setup&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Accounts receivable: Customer setup', 'does' => 'Customer invoices, settlements and AR setup', 'url' => '/cp/shop/finance/erp?area=ar&tab=ar_setup&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Accounts receivable: Receivables', 'does' => 'Customer invoices, settlements and AR setup', 'url' => '/cp/shop/finance/erp?area=ar&tab=receivables&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Asset management: Fixed assets', 'does' => 'Asset register, maintenance and lifecycle', 'url' => '/cp/shop/finance/erp?area=asset_mgmt&tab=fixed_assets&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Audit workbench: Audit trail', 'does' => 'Audit policies, cases and audit trail', 'url' => '/cp/shop/finance/erp?area=audit_wb&tab=audit&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Audit workbench: Blockchain proofs', 'does' => 'Audit policies, cases and audit trail', 'url' => '/cp/shop/finance/erp?area=audit_wb&tab=blockchain_proofs&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Budgeting: Budget planning', 'does' => 'Budget registers, control and budget vs actual', 'url' => '/cp/shop/finance/erp?area=budgeting&tab=budget_planning&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Budgeting: Budgeting', 'does' => 'Budget registers, control and budget vs actual', 'url' => '/cp/shop/finance/erp?area=budgeting&tab=budgeting&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash and bank management: Bank accounts', 'does' => 'Bank accounts, cash, payments and reconciliation', 'url' => '/cp/shop/finance/erp?area=banking&tab=bank_setup&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash and bank management: Bank instruments', 'does' => 'Bank accounts, cash, payments and reconciliation', 'url' => '/cp/shop/finance/erp?area=banking&tab=bank_instruments&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash and bank management: Bank recon', 'does' => 'Bank accounts, cash, payments and reconciliation', 'url' => '/cp/shop/finance/erp?area=banking&tab=bank_recon&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash and bank management: Cash & bank', 'does' => 'Bank accounts, cash, payments and reconciliation', 'url' => '/cp/shop/finance/erp?area=banking&tab=cash_bank&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash and bank management: Cash flow forecast', 'does' => 'Bank accounts, cash, payments and reconciliation', 'url' => '/cp/shop/finance/erp?area=banking&tab=cash_forecast&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash and bank management: Payment batches', 'does' => 'Bank accounts, cash, payments and reconciliation', 'url' => '/cp/shop/finance/erp?area=banking&tab=payment_batches&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cash and bank management: Petty cash', 'does' => 'Bank accounts, cash, payments and reconciliation', 'url' => '/cp/shop/finance/erp?area=banking&tab=petty_cash&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Common: Agenda', 'does' => 'Shared agenda, contacts, documents and knowledge', 'url' => '/cp/shop/finance/erp?area=common&tab=agenda&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Common: AI advisor', 'does' => 'Shared agenda, contacts, documents and knowledge', 'url' => '/cp/shop/finance/erp?area=common&tab=ai_advisor&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Common: Contacts', 'does' => 'Shared agenda, contacts, documents and knowledge', 'url' => '/cp/shop/finance/erp?area=common&tab=contacts&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Common: Documents', 'does' => 'Shared agenda, contacts, documents and knowledge', 'url' => '/cp/shop/finance/erp?area=common&tab=documents&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Common: Knowledge base', 'does' => 'Shared agenda, contacts, documents and knowledge', 'url' => '/cp/shop/finance/erp?area=common&tab=knowledge_base&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Compliance: Document expiry', 'does' => 'Insurance policies, claims and document expiry tracking', 'url' => '/cp/shop/finance/erp?area=risk&tab=doc_expiry&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Compliance: Insurance', 'does' => 'Insurance policies, claims and document expiry tracking', 'url' => '/cp/shop/finance/erp?area=risk&tab=insurance&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Consolidations: Consolidation', 'does' => 'Multi-entity consolidation and eliminations', 'url' => '/cp/shop/finance/erp?area=consolidations&tab=consolidation_bu&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Consolidations: Multi-entity', 'does' => 'Multi-entity consolidation and eliminations', 'url' => '/cp/shop/finance/erp?area=consolidations&tab=multi_entity&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cost accounting: Financial depth', 'does' => 'Cost allocations, accruals and cost analysis', 'url' => '/cp/shop/finance/erp?area=cost_acct&tab=fin_advanced&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Cost management: Costing value-models', 'does' => 'Inventory costing value models and analysis', 'url' => '/cp/shop/finance/erp?area=cost_mgmt&tab=cost_models&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Credit and collections: Collections', 'does' => 'Collection cases, dunning and credit holds', 'url' => '/cp/shop/finance/erp?area=credit_coll&tab=collections&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Expense management: Expense reports', 'does' => 'Employee expense reports and reimbursements', 'url' => '/cp/shop/finance/erp?area=expense&tab=expense_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Fixed assets: Fixed assets', 'does' => 'Asset register, depreciation and disposals', 'url' => '/cp/shop/finance/erp?area=fixed_assets&tab=fixed_assets&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Aging (AR/AP/Inv)', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=aging&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Balance sheet', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=balance_sheet&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Chart of accounts', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=coa&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Dual trial balance (wt+val) [JW]', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=jw_trial_balance&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Financial depth', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=fin_advanced&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: General ledger', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=gl&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Journal voucher (jewellery) [JW]', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=jw_journal_voucher&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Opening balances', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=opening_balances&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Petty cash (jewellery) [JW]', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=jw_petty_cash&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Profit & loss', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=pl&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Reports', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Trial balance / reports', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=enterprise_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'General ledger: Year-end closing', 'does' => 'Chart of accounts, journals, period close and financial statements', 'url' => '/cp/shop/finance/erp?area=finance&tab=year_end&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Home: Approvals', 'does' => 'Dashboards, workflow and approvals', 'url' => '/cp/shop/finance/erp?area=overview&tab=approvals&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Home: Dashboard', 'does' => 'Dashboards, workflow and approvals', 'url' => '/cp/shop/finance/erp?area=overview&tab=dashboard&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Home: Process flow', 'does' => 'Dashboards, workflow and approvals', 'url' => '/cp/shop/finance/erp?area=overview&tab=processflow&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Home: Workflow', 'does' => 'Dashboards, workflow and approvals', 'url' => '/cp/shop/finance/erp?area=overview&tab=workflow&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Human resources: HR', 'does' => 'Workers, organization and labour-law compliance', 'url' => '/cp/shop/finance/erp?area=people&tab=hr&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Human resources: HR operations', 'does' => 'Workers, organization and labour-law compliance', 'url' => '/cp/shop/finance/erp?area=people&tab=hr_ops&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Human resources: Labour law & compliance', 'does' => 'Workers, organization and labour-law compliance', 'url' => '/cp/shop/finance/erp?area=people&tab=hr_law&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Human resources: Performance management', 'does' => 'Workers, organization and labour-law compliance', 'url' => '/cp/shop/finance/erp?area=people&tab=performance&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Human resources: Recruitment', 'does' => 'Workers, organization and labour-law compliance', 'url' => '/cp/shop/finance/erp?area=people&tab=recruitment&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Human resources: Workers', 'does' => 'Workers, organization and labour-law compliance', 'url' => '/cp/shop/finance/erp?area=people&tab=staff&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Barcode (jewellery) [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_barcode&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Colour stone master [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_color_stone&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Design master [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_design&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Diamond master [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_diamond&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Inventory', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=inventory&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Inventory (stock/groups)', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=inv_groups&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Karat master [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_karat&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Metal stock master [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_metal_stock&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Order planning', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=order_planning&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Pearl master [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_pearl&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Rate type master [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_rate_type&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Retail barcode', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=retail_barcode&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Stock balance (weight) [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_stock_balance&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Inventory management: Stock verification [JW]', 'does' => 'Stock, item groups, order planning and barcodes', 'url' => '/cp/shop/finance/erp?area=inventory_mgmt&tab=jw_stock_verification&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Landed cost: Landed cost', 'does' => 'Voyages, landed cost allocation and apportionment', 'url' => '/cp/shop/finance/erp?area=landed_cost_area&tab=landed_cost&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Leave and absence: HR operations', 'does' => 'Leave plans, requests and absence tracking', 'url' => '/cp/shop/finance/erp?area=leave_abs&tab=hr_ops&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Logistics: Customs & shipping', 'does' => 'Customs, shipping and inbound/outbound logistics', 'url' => '/cp/shop/finance/erp?area=logistics&tab=custom_shipping&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Logistics: Procurement CP', 'does' => 'Customs, shipping and inbound/outbound logistics', 'url' => '/cp/shop/finance/erp?area=logistics&tab=procurement_link&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Master planning: Master planning', 'does' => 'Master scheduling and material requirements planning', 'url' => '/cp/shop/finance/erp?area=master_planning_area&tab=master_planning&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Material handling equipment interface: Warehouse management', 'does' => 'Material handling and warehouse equipment integration', 'url' => '/cp/shop/finance/erp?area=mhei&tab=wms&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Organization administration: Business unit', 'does' => 'Legal entities, business units, contracts and documents', 'url' => '/cp/shop/finance/erp?area=enterprise&tab=business_units&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Organization administration: Contracts & e-sign', 'does' => 'Legal entities, business units, contracts and documents', 'url' => '/cp/shop/finance/erp?area=enterprise&tab=contracts&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Organization administration: Document formats', 'does' => 'Legal entities, business units, contracts and documents', 'url' => '/cp/shop/finance/erp?area=enterprise&tab=doc_formats&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Organization administration: Listing', 'does' => 'Legal entities, business units, contracts and documents', 'url' => '/cp/shop/finance/erp?area=enterprise&tab=listing&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Organization administration: Organization administration', 'does' => 'Legal entities, business units, contracts and documents', 'url' => '/cp/shop/finance/erp?area=enterprise&tab=org_admin&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Payroll: Payroll', 'does' => 'Payroll runs, earnings and statutory deductions', 'url' => '/cp/shop/finance/erp?area=payroll_area&tab=payroll&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: 3-way match', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=three_way_match&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Categories & policies', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=procurement_categories&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Diamond purchase [JW]', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=jw_diamond_purchase&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Metal purchase [JW]', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=jw_metal_purchase&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Purchase fixing [JW]', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=jw_purchase_fixing&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Purchase orders', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=purchase_orders&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Purchase requisitions', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=purchase_requisitions&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Purchase window [JW]', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=jw_purchase_window&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Purchases', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=purchases&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: RFQ', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=rfq&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Procurement and sourcing: Supplier portal', 'does' => 'Suppliers, RFQ, purchase orders and matching', 'url' => '/cp/shop/finance/erp?area=purchasing&tab=supplier_portal&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Product information management: Product information', 'does' => 'Products, dimensions and variant structures', 'url' => '/cp/shop/finance/erp?area=pim&tab=product_info&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Production control: Production', 'does' => 'Production orders, routes, operations and quality', 'url' => '/cp/shop/finance/erp?area=production&tab=manufacturing&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Production control: Production planning', 'does' => 'Production orders, routes, operations and quality', 'url' => '/cp/shop/finance/erp?area=production&tab=mfg_planning&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Production control: Quality management', 'does' => 'Production orders, routes, operations and quality', 'url' => '/cp/shop/finance/erp?area=production&tab=quality&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Project management and accounting: Project accounting', 'does' => 'Projects, budgets, WIP and revenue recognition', 'url' => '/cp/shop/finance/erp?area=projects&tab=project_accounting&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Project management and accounting: Projects', 'does' => 'Projects, budgets, WIP and revenue recognition', 'url' => '/cp/shop/finance/erp?area=projects&tab=projects&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Retail and commerce: Retail & commerce', 'does' => 'Channels, assortments, retail pricing, POS and statements', 'url' => '/cp/shop/finance/erp?area=retail&tab=retail_commerce&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: CRM', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=crm&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Delivery notes', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=delivery_notes&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Fulfilment', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=fulfilment&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Invoices (e-invoice)', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=invoices&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Marketing', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=marketing&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Metal sales [JW]', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=jw_metal_sales&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Opportunities', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=opportunities&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: POS advance [JW]', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=jw_pos_advance&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Prospects & leads', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=leads&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Retail sales (POS) [JW]', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=jw_retail_sales&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Revenue', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=revenue&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Sales analysis (weight) [JW]', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=jw_sales_analysis&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Sales fixing [JW]', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=jw_sales_fixing&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Sales orders', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=sales_orders&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Sales quotations', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=proposals&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Sales return [JW]', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=jw_sales_return&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Sales and marketing: Subscriptions', 'does' => 'CRM, prospects, quotations, sales orders, delivery and invoicing', 'url' => '/cp/shop/finance/erp?area=sales&tab=subscriptions&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: After-sales RMA', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=aftersales&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Contracts & e-sign', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=contracts&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Repair delivery [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_repair_delivery&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Repair jobs [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_repairs&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Repair receipt [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_repair_receipt&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Repair register [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_repair_register&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Repair sale [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_repair_sale&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Repair search [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_repair_search&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Repair transfer [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_repair_transfer&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Service management: Workshop receive [JW]', 'does' => 'Service agreements, contracts and service delivery', 'url' => '/cp/shop/finance/erp?area=service_mgmt&tab=jw_workshop_receive&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Accounting setup', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=erp_setup&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Currency master (jewellery) [JW]', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=jw_currency&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Data & integration', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=integration&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Data import', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=data_import&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Devin AI assistant', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=ai_assistant&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Platform services', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=platform&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Print designer', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=print_designer&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Sample data (jewellery) [JW]', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=jw_seed_data&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Security roles', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=security_roles&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Tenant configuration', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=tenant_config&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'System administration: Workflow automation', 'does' => 'Company setup, security, batch/platform services, data and integration', 'url' => '/cp/shop/finance/erp?area=setup&tab=workflow_automation&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Blockchain proofs', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=blockchain_proofs&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Compliance center', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=compliance&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Document control', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=document_control&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: E-invoicing', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=einvoice&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Electronic reporting', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=elec_reporting&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: External reporting', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Tax compliance', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=tax_compliance&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Tourist VAT refund (jewellery) [JW]', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=jw_tourist_vat&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Tourist VAT refunds', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=vat_refund&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: VAT return', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=vat_return&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax: Withholding tax', 'does' => 'VAT/tax returns, e-invoicing, compliance and statutory reporting', 'url' => '/cp/shop/finance/erp?area=tax&tab=withholding&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Warehouse management: Warehouse management', 'does' => 'Locations, license plates, waves, work and mobile RF', 'url' => '/cp/shop/finance/erp?area=warehouse&tab=wms&epc_erp_shell=1', 'scope' => 'client'),
	),
	'ERP / Tax & VAT' => array(
		array('name' => 'Credit notes & adjustments', 'does' => 'Issue credit notes linked to original tax invoices for returns and billing corrections. Maintains audit trail required for VAT…', 'url' => '/cp/shop/finance/erp?area=ar&tab=receivables&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'FTA XML / JSON export', 'does' => 'Export e-invoice payloads in formats suitable for Peppol endpoints and FTA compliance workflows. Operators configure seller…', 'url' => '/cp/shop/finance/erp?area=tax&tab=einvoice&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Peppol / PINT-AE e-invoice', 'does' => 'Generate Peppol-ready e-invoices aligned with UAE PINT-AE requirements — validate, print, and export XML/JSON for FTA…', 'url' => '/cp/shop/finance/erp?area=tax&tab=einvoice&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Tax invoices with TRN', 'does' => 'Tax-inclusive pricing on storefront with seller TRN on invoices visible to clients. Create invoices from orders with legal…', 'url' => '/cp/shop/document_control/document_control', 'scope' => 'client'),
		array('name' => 'UAE VAT 201 return (full format)', 'does' => 'The complete FTA VAT 201 built from posted sales & purchases — Boxes 1a–1g standard-rated per Emirate, tourist refunds,…', 'url' => '/cp/shop/finance/erp?area=tax&tab=vat_return&epc_erp_shell=1', 'scope' => 'client'),
	),
	'ERP / External Reporting' => array(
		array('name' => 'Built-in compliance engine', 'does' => 'Each return is validated against the law with PASS / REVIEW / FAIL flags — VAT special schemes (24kt investment gold 0%, B2B…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Business valuation report', 'does' => 'Values the business by three methods on the same model — discounted cash flow (WACC + Gordon terminal value), market multiples…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Corporate Tax return (full computation)', 'does' => 'The complete UAE Corporate Tax return under Federal Decree-Law 47/2022 — taxpayer & period, elections/reliefs (Small Business…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Drill-down to transaction level', 'does' => 'Every figure on a return is clickable in place: a box or computation line expands to its breakdown, a line expands to its…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'External Audit Report (ISA 700 / IFRS)', 'does' => 'A complete IFRS assurance pack with a professional cover page and table of contents: the Independent Auditor\\', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Financial model & 5-year forecast', 'does' => 'A five-year financial model built from the live GL actuals — an explicit assumptions block (growth, margins, capex, working…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Flexible reporting periods', 'does' => 'Each report carries its own statutory period model — VAT monthly or quarterly, Corporate Tax by financial year (including…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'FTA-style audit-file schedules', 'does' => 'One-click Excel/CSV supporting schedules in the FTA layout — VAT invoice-wise, customer TRN-wise, supplier-wise and…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Off-system Excel import → return', 'does' => 'Check or file other clients without touching the ERP: download a multi-sheet Excel template (company & TRN, boxes/lines,…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Professional PDF + commentary', 'does' => 'A colour, MIS-style filing pack with cover page, section numbering, the summary schedules and a plain-language "report…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Statutory reporting centre', 'does' => 'A country-driven report centre that auto-builds filing-ready statutory returns from your ERP data, localized to your…', 'url' => '/cp/shop/finance/erp?area=tax&tab=ext_reports&epc_erp_shell=1', 'scope' => 'client'),
	),
	'Documents' => array(
		array('name' => 'Document Control', 'does' => 'Invoices, PDFs, templates.', 'url' => '/cp/shop/document_control/document_control', 'scope' => 'client'),
		array('name' => 'Document library & archive', 'does' => 'Store signed contracts, compliance files, and client deliverables per customer or order. Tax and consultancy verticals give…', 'url' => '/cp/shop/document_control/document_control', 'scope' => 'client'),
		array('name' => 'Document templates', 'does' => 'Branded invoice, delivery note, quote, and contract templates with merge fields from orders and customers. Tax advisory…', 'url' => '/cp/shop/document_control/document_control', 'scope' => 'client'),
		array('name' => 'Legal footers & TRN blocks', 'does' => 'Configurable legal text, bank details, and TRN footer on all customer-facing documents. Reduces manual edits when onboarding…', 'url' => '/cp/shop/document_control/document_control', 'scope' => 'client'),
		array('name' => 'Print documents & PDFs', 'does' => 'Print or PDF from CP for any operational document — orders, deliveries, statements. Consistent branding across storefront…', 'url' => '/cp/shop/document_control/document_control', 'scope' => 'client'),
	),
	'Customers / CRM' => array(
		array('name' => 'Activities & follow-ups', 'does' => 'Log calls, meetings, and tasks against leads and customers — nothing falls through after a showroom visit or advisory intake form.', 'url' => '/cp/shop/customer_mgmt/customer_mgmt', 'scope' => 'client'),
		array('name' => 'Add user', 'does' => 'Create a new storefront or staff user.', 'url' => '/cp/users/usermanager/user', 'scope' => 'client'),
		array('name' => 'CRM pipeline & kanban', 'does' => 'Native CRM kanban pipeline inside ERP — leads, opportunities, and won deals without a separate CRM subscription. Consultancies…', 'url' => '/cp/shop/finance/erp?area=sales&tab=crm&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Customer approval workflows', 'does' => 'Approve new B2B accounts, medical institutions, or advisory clients before they can order. Tax and regulated catalogue…', 'url' => '/cp/users/customer_approvals', 'scope' => 'client'),
		array('name' => 'Customer approvals', 'does' => 'Approve trade registrations.', 'url' => '/cp/users/customer_approvals', 'scope' => 'client'),
		array('name' => 'Customer groups & profiles', 'does' => 'Segment customers for pricing, catalog visibility, and marketing. Profiles drive margin rules and which brands or categories…', 'url' => '/cp/shop/price-management', 'scope' => 'client'),
		array('name' => 'Customer management', 'does' => 'Customer hub & CRM.', 'url' => '/cp/shop/customer_mgmt/customer_mgmt', 'scope' => 'client'),
		array('name' => 'Customer management hub', 'does' => '360° customer view: contacts, orders, balance, documents, and notes in one CP screen. Staff answer client calls without…', 'url' => '/cp/shop/customer_mgmt/customer_mgmt', 'scope' => 'client'),
		array('name' => 'Leads & opportunities', 'does' => 'Capture website enquiries as leads and convert to opportunities with value and stage tracking. Won opportunities hint order…', 'url' => '/cp/shop/finance/erp?area=sales&tab=leads&epc_erp_shell=1', 'scope' => 'client'),
		array('name' => 'Registration fields', 'does' => 'Custom fields on registration forms.', 'url' => '/cp/users/polya-registracii', 'scope' => 'client'),
		array('name' => 'Registration options', 'does' => 'Registration paths on storefront.', 'url' => '/cp/users/registracionnye-varianty', 'scope' => 'client'),
		array('name' => 'User groups & roles', 'does' => 'Backend groups and privilege templates.', 'url' => '/cp/users/usergroups', 'scope' => 'client'),
		array('name' => 'User manager', 'does' => 'Search/edit customers and staff; assign price profile.', 'url' => '/cp/users/usermanager', 'scope' => 'client'),
	),
	'AI' => array(
		array('name' => 'AI parts agent chat', 'does' => 'Conversational parts expert on the storefront — search by part number, decode VIN, and get guided recommendations. Reduces…', 'url' => '/cp/shop/parts_agent_chats', 'scope' => 'client'),
		array('name' => 'AI Parts Expert chats', 'does' => 'Review AI agent conversations.', 'url' => '/cp/shop/parts_agent_chats', 'scope' => 'client'),
		array('name' => 'AI VIN decode assistance', 'does' => 'AI-assisted VIN decode narrows vehicle context before catalogue browse — fewer wrong-fit orders and faster workshop self-service.', 'url' => '/cp/shop/parts_agent_chats', 'scope' => 'client'),
		array('name' => 'Auto Price AI', 'does' => 'Discover, compare, and import products across market sources — buy from retailers or wholesalers, sell on Noon, Amazon, and…', 'url' => '/cp/control/portal/epc_auto_price_engine', 'scope' => 'client'),
		array('name' => 'Automation & integration hooks', 'does' => 'Event hooks for order placed, stock low, and lead captured — wire email, WhatsApp, or external systems. Foundation for…', 'url' => '/cp/control/portal/epc_integrations_hub', 'scope' => 'client'),
		array('name' => 'Demand intelligence', 'does' => 'Signals from search, crosses, and order history highlight what to stock and promote. Professional services pack includes…', 'url' => '/cp/shop/demand_countries', 'scope' => 'client'),
	),
	'Marketing' => array(
		array('name' => 'Featured collections & banners', 'does' => 'Curate lookbooks and collection grids — Namshi-style fashion and jewellery gallery layouts ship with industry themes.…', 'url' => '/cp/shop/catalogue/tovary-na-glavnoj', 'scope' => 'client'),
		array('name' => 'Marketing & growth', 'does' => 'Growth strategies hub.', 'url' => '/cp/shop/marketing/marketing', 'scope' => 'client'),
		array('name' => 'Marketing campaigns hub', 'does' => 'Plan and track campaigns linked to storefront landing pages and promo codes. Merchandising teams launch seasonal pushes…', 'url' => '/cp/shop/marketing/marketing', 'scope' => 'client'),
		array('name' => 'Promo & merchandising', 'does' => 'Hero banners, featured collections, and campaign-driven catalogue highlights on the storefront. UTM-ready URLs for measuring…', 'url' => '/cp/content/slider', 'scope' => 'client'),
		array('name' => 'Ten growth strategies', 'does' => 'Built-in playbook of ten proven growth tactics — from basket recovery to B2B outreach — with CP guidance per strategy.…', 'url' => '/cp/shop/marketing/marketing', 'scope' => 'client'),
	),
	'Content / CMS' => array(
		array('name' => 'Additional texts', 'does' => 'Reusable text snippets / legal blocks.', 'url' => '/cp/content/dopolnitelnye-teksty', 'scope' => 'client'),
		array('name' => 'Content manager', 'does' => 'Edit CMS page bodies and metadata.', 'url' => '/cp/content/content_manager', 'scope' => 'client'),
		array('name' => 'Content tree', 'does' => 'CMS page tree for storefront pages.', 'url' => '/cp/content/content_tree', 'scope' => 'client'),
		array('name' => 'File manager', 'does' => 'Upload and organize media files.', 'url' => '/cp/filemanager', 'scope' => 'client'),
		array('name' => 'Menu manager', 'does' => 'Storefront navigation menus.', 'url' => '/cp/menu/menu_manager', 'scope' => 'client'),
		array('name' => 'Sitemap', 'does' => 'Generate and review XML sitemap.', 'url' => '/cp/content/sitemap', 'scope' => 'client'),
		array('name' => 'Slider / banners', 'does' => 'Homepage and campaign image sliders.', 'url' => '/cp/content/slider', 'scope' => 'client'),
		array('name' => 'Structure dumps', 'does' => 'Export/import content structure dumps.', 'url' => '/cp/content/structure_dumps', 'scope' => 'client'),
	),
	'System & Admin' => array(
		array('name' => 'API key settings', 'does' => 'External API keys.', 'url' => '/cp/control/config?need_config_group=13', 'scope' => 'client'),
		array('name' => 'Communications test', 'does' => 'Send test e-mail / SMS from CP.', 'url' => '/cp/control/communications', 'scope' => 'client'),
		array('name' => 'Configuration', 'does' => 'Shop, e-mail, SMS, payment, agent toggle, contacts.', 'url' => '/cp/control/config', 'scope' => 'client'),
		array('name' => 'CP guideline', 'does' => 'Complete CP map, daily workflows, menu hints.', 'url' => '/cp/control/cp-guideline', 'scope' => 'client'),
		array('name' => 'Debug console', 'does' => 'Developer debug tools.', 'url' => '/cp/system/debug', 'scope' => 'client'),
		array('name' => 'Languages', 'does' => 'UI language strings and locales.', 'url' => '/cp/lang', 'scope' => 'client'),
		array('name' => 'Modules manager', 'does' => 'Enable/configure site modules.', 'url' => '/cp/modules/modules_manager', 'scope' => 'client'),
		array('name' => 'Notification settings', 'does' => 'Order and system e-mail/SMS templates.', 'url' => '/cp/control/notifications_settings', 'scope' => 'client'),
		array('name' => 'Packs manager', 'does' => 'Feature packs and module bundles.', 'url' => '/cp/packs/packs_manager', 'scope' => 'client'),
		array('name' => 'Packs setup / upload', 'does' => 'Upload and install pack archives.', 'url' => '/cp/packs/setup', 'scope' => 'client'),
		array('name' => 'Plugins manager', 'does' => 'Install and configure plugins.', 'url' => '/cp/plugins/plugins_manager', 'scope' => 'client'),
		array('name' => 'Server IP', 'does' => 'Show server public IP (utility).', 'url' => '/content/usefull/ip.php', 'scope' => 'client'),
		array('name' => 'SMS operators', 'does' => 'SMS gateway operator credentials.', 'url' => '/cp/control/sms-operatory', 'scope' => 'client'),
		array('name' => 'Templates manager', 'does' => 'Storefront theme/template packages.', 'url' => '/cp/templates/templates_manager', 'scope' => 'client'),
		array('name' => 'CP module packs per industry', 'does' => 'Enable or hide entire module packs — commerce, ERP, auto parts, logistics — per tenant. Sidebar groups stay clean; clients…', 'url' => '/cp/control/portal/industry_settings', 'scope' => 'both'),
		array('name' => 'Storefront theme packages', 'does' => 'Five production retail and services layouts — automotive, electronics, fashion, jewellery, advisory — with industry-tuned CP…', 'url' => '/cp/templates/templates_manager', 'scope' => 'both'),
		array('name' => 'Users, groups & roles', 'does' => 'Role-based CP access for admin, warehouse, finance, and counter staff. Super CP operators stay on platform DB; client staff…', 'url' => '/cp/users/usergroups', 'scope' => 'both'),
		array('name' => 'Operator audit & platform settings', 'does' => 'Platform branding, contact JSON presets, and deploy audit for operators. Super CP settings never leak to client hostnames —…', 'url' => '/cp/control/portal/epc_boc_audit_log', 'scope' => 'super'),
		array('name' => 'SSL & DNS onboarding assist', 'does' => 'Let\\', 'url' => '/cp/shop/tenant_hub/tenant_hub', 'scope' => 'super'),
	),
	'Industry Templates' => array(
		array('name' => 'Auto spare parts template', 'does' => 'VIN-aware catalogue, supplier prices, crosses, procurement, and B2B balances — the full eParts-style stack pre-loaded for…', 'url' => '', 'scope' => 'client'),
		array('name' => 'Consultancy & services template', 'does' => 'Proposal-to-delivery: CRM, projects, billing, and client-facing hub for management consultancies and professional service firms.', 'url' => '', 'scope' => 'client'),
		array('name' => 'Electronics retail template', 'does' => 'Virgin-style mega navigation, spec-heavy homepage, and SKU pagination for IT and consumer electronics. RMA and warranty hooks…', 'url' => '', 'scope' => 'client'),
		array('name' => 'Fashion & beauty template', 'does' => 'Lookbook collections, variant catalogue, and campaign-ready Namshi-style storefront. Order fulfilment and returns modules…', 'url' => '', 'scope' => 'client'),
		array('name' => 'Jewellery & luxury template', 'does' => 'Kiyasha-style gold and diamond aesthetic, gallery product cards, certificate metadata, and premium enquiry flows for fine…', 'url' => '', 'scope' => 'client'),
		array('name' => 'Medical supplies template', 'does' => 'Regulated catalogue, institutional login, batch and expiry fields, and audit-friendly delivery documentation for clinic…', 'url' => '', 'scope' => 'client'),
		array('name' => 'Rental operations template', 'does' => 'Rental SKU with daily/monthly periods, deposits, contracts, and monthly billing hooks for fleet, equipment, and commercial…', 'url' => '', 'scope' => 'client'),
		array('name' => 'Tax & advisory template', 'does' => 'Client portal, VAT workflows, document control, and advisory CRM on one hosted domain — Prime Invest-style layout for tax…', 'url' => '', 'scope' => 'client'),
	),
);
