<?php
/**
 * Regenerates aspnet/src/EcomAE.Platform/Storefront/FreeToolsTables.g.cs from the PHP
 * free-tools engines, so the ASP.NET twin carries the same country, tax, labour-law and
 * insurance tables byte for byte.
 *
 *   php scripts/gen_free_tools_tables.php > aspnet/src/EcomAE.Platform/Storefront/FreeToolsTables.g.cs
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$_SERVER['DOCUMENT_ROOT'] = $root;
define('_ASTEXE_', 1);
require_once $root . '/content/general_pages/epc_ecomae_free_tools.php';

function cs_str(string $s): string
{
	$out = '"';
	foreach (preg_split('//u', $s, -1, PREG_SPLIT_NO_EMPTY) as $ch) {
		$cp = mb_ord($ch, 'UTF-8');
		if ($ch === '"') {
			$out .= '\\"';
		} elseif ($ch === '\\') {
			$out .= '\\\\';
		} elseif ($cp < 0x20 || $cp > 0x7E) {
			if ($cp > 0xFFFF) {
				$out .= sprintf('\\U%08x', $cp);
			} else {
				$out .= sprintf('\\u%04x', $cp);
			}
		} else {
			$out .= $ch;
		}
	}
	return $out . '"';
}

function cs_val($v): string
{
	if (is_string($v)) {
		return cs_str($v);
	}
	if (is_int($v)) {
		return $v . 'L';
	}
	if (is_float($v)) {
		$t = var_export($v, true);
		return (strpbrk($t, '.eE') === false ? $t . '.0' : $t) . 'd';
	}
	if (is_bool($v)) {
		return $v ? 'true' : 'false';
	}
	if ($v === null) {
		return 'null';
	}
	throw new RuntimeException('unsupported value');
}

function cs_map(array $a, string $indent): string
{
	$lines = array();
	foreach ($a as $k => $v) {
		$lines[] = $indent . '    { ' . cs_str((string) $k) . ', ' . cs_val($v) . ' },';
	}
	return "new PhpArray\n" . $indent . "{\n" . implode("\n", $lines) . "\n" . $indent . '}';
}

$loc = file_get_contents($root . '/content/shop/finance/epc_erp_localization.php');
preg_match_all("/^\\s*'([A-Z]{2})' => array\\('/m", $loc, $m);
$countryCodes = $m[1];

$ft = file_get_contents($root . '/content/general_pages/epc_ecomae_free_tools.php');
preg_match('/function epc_free_tools_cit_rate.*?\\$map = array\\((.*?)\\);\\s*(?:if|return)/s', $ft, $cm);
preg_match_all("/'([A-Z]{2})' =>/", $cm[1], $cc);
preg_match('/function epc_free_tools_authority.*?\\$map = array\\((.*?)\\);\\s*(?:if|return)/s', $ft, $am);
preg_match_all("/'([A-Z]{2})' =>/", $am[1], $ac);

$hr = file_get_contents($root . '/content/shop/finance/epc_erp_hr_law.php');
preg_match('/function epc_hr_law_authority_url.*?\\$map = array\\((.*?)\\);\\s*(?:if|return)/s', $hr, $um);
preg_match_all("/'([A-Z]{2})' =>/", $um[1], $uc);

echo "// <auto-generated>\n";
echo "// php scripts/gen_free_tools_tables.php — country, tax, labour-law and insurance tables of the PHP free tools.\n";
echo "// </auto-generated>\n";
echo "namespace EcomAE.Platform.Storefront;\n\n";
echo "public static partial class FreeToolsEngines\n{\n";

echo "    private static readonly Dictionary<string, PhpArray> CountryProfiles = new(StringComparer.Ordinal)\n    {\n";
foreach ($countryCodes as $c) {
	$p = epc_country_profile($c);
	unset($p['hr_country']);
	echo '        [' . cs_str($c) . '] = ' . cs_map($p, '        ') . ",\n";
}
echo "    };\n\n";

echo "    private static readonly Dictionary<string, (double Rate, double Threshold, string Note)> CitRates = new(StringComparer.Ordinal)\n    {\n";
foreach ($cc[1] as $c) {
	$r = epc_free_tools_cit_rate($c);
	echo '        [' . cs_str($c) . '] = (' . cs_val($r['rate']) . ', ' . cs_val($r['threshold']) . ', ' . cs_str($r['note']) . "),\n";
}
echo "    };\n\n";
$r = epc_free_tools_cit_rate('');
echo '    private static readonly (double Rate, double Threshold, string Note) CitFallback = (' . cs_val($r['rate']) . ', ' . cs_val($r['threshold']) . ', ' . cs_str($r['note']) . ");\n\n";

echo "    private static readonly Dictionary<string, (string Authority, string VatReturn, string CtReturn)> Authorities = new(StringComparer.Ordinal)\n    {\n";
foreach ($ac[1] as $c) {
	$a = epc_free_tools_authority($c);
	echo '        [' . cs_str($c) . '] = (' . cs_str($a['authority']) . ', ' . cs_str($a['vat_return']) . ', ' . cs_str($a['ct_return']) . "),\n";
}
echo "    };\n\n";
$a = epc_free_tools_authority('');
echo '    private static readonly (string Authority, string VatReturn, string CtReturn) AuthorityFallback = (' . cs_str($a['authority']) . ', ' . cs_str($a['vat_return']) . ', ' . cs_str($a['ct_return']) . ");\n\n";

echo "    private static readonly Dictionary<string, PhpArray> HrProfiles = new(StringComparer.Ordinal)\n    {\n";
foreach (epc_hr_law_profiles_all() as $code => $p) {
	echo '        [' . cs_str((string) $code) . '] = ' . cs_map($p, '        ') . ",\n";
}
echo "    };\n\n";

echo "    private static readonly Dictionary<string, string> HrAuthorityUrls = new(StringComparer.Ordinal)\n    {\n";
foreach ($uc[1] as $c) {
	echo '        [' . cs_str($c) . '] = ' . cs_str(epc_hr_law_authority_url($c)) . ",\n";
}
echo "    };\n\n";
echo '    private const string HrAuthorityFallback = ' . cs_str(epc_hr_law_authority_url('')) . ";\n\n";

echo "    private static readonly (string Key, PhpArray Version)[] AeVersionOverlays =\n    [\n";
foreach (epc_hr_law_ae_versions() as $v) {
	$from = gmdate('Y-m-d H:i:s', (int) $v['valid_from']);
	unset($v['valid_from'], $v['valid_to']);
	echo '        (' . cs_str($from) . ', ' . cs_map($v, '        ') . "),\n";
}
echo "    ];\n\n";

echo "    private static readonly Dictionary<string, string> InsuranceClasses = new(StringComparer.Ordinal)\n    {\n";
foreach (epc_ins_classes() as $k => $label) {
	echo '        [' . cs_str($k) . '] = ' . cs_str($label) . ",\n";
}
echo "    };\n\n";

echo "    private static readonly Dictionary<string, (string Class, string Basis)[]> InsuranceRecommended = new(StringComparer.Ordinal)\n    {\n";
foreach (array('AE', 'SA', 'GB', 'IN') as $c) {
	echo '        [' . cs_str($c) . '] =' . "\n        [\n";
	foreach (epc_ins_country_recommended($c) as $r) {
		echo '            (' . cs_str($r['class']) . ', ' . cs_str($r['basis']) . "),\n";
	}
	echo "        ],\n";
}
echo "    };\n\n";
echo "    private static readonly (string Class, string Basis)[] InsuranceRecommendedFallback =\n    [\n";
foreach (epc_ins_country_recommended('') as $r) {
	echo '        (' . cs_str($r['class']) . ', ' . cs_str($r['basis']) . "),\n";
}
echo "    ];\n";
echo "}\n";
