#!/usr/bin/env python3
"""Generate parity evidence templates for the 90% zero-PHP target batches.

Default mode is dry-run and writes only a summary. Use --write to create template files
under docs/migration/parity/batch-*/ for operators to fill after real validation.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "docs/migration/inventory/zero-php-90-percent-target-plan.json"
BATCHES = ROOT / "docs/migration/inventory/php-route-job-cutover-batches.json"
EVIDENCE_ROOT = ROOT / "docs/migration/parity"
SUMMARY_JSON = ROOT / "docs/migration/inventory/zero-php-90-evidence-template-summary.json"
SUMMARY_MD = ROOT / "docs/migration/inventory/ZERO_PHP_90_EVIDENCE_TEMPLATE_SUMMARY.md"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate zero-PHP 90% parity evidence templates.")
    parser.add_argument("--write", action="store_true", help="Create missing evidence template JSON files.")
    args = parser.parse_args()

    plan = json.loads(PLAN.read_text())
    batches = json.loads(BATCHES.read_text())
    selected = {batch["batch"] for batch in plan["batches"]}
    assignments = [
        assignment | {"batch": batch["batch"]}
        for batch in batches["batches"]
        if batch["batch"] in selected
        for assignment in batch["assignments"]
    ]

    created = 0
    existing = 0
    templates = []
    for assignment in assignments:
        path = evidence_file_for(assignment)
        templates.append(str(path.relative_to(ROOT)))
        if path.exists():
            existing += 1
            continue
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(template_for(assignment), indent=2) + "\n")
            created += 1

    summary = {
        "mode": "write" if args.write else "dry-run",
        "targetPercent": plan["targetPercent"],
        "selectedBatches": plan["selectedBatches"],
        "selectedItems": len(assignments),
        "existingTemplates": existing,
        "createdTemplates": created,
        "missingTemplates": len(assignments) - existing - created,
        "evidenceRoot": str(EVIDENCE_ROOT.relative_to(ROOT)),
        "writeCommand": "python3 scripts/generate_zero_php_90_evidence_templates.py --write",
        "verifyCommand": "python3 scripts/verify_zero_php_90_readiness.py",
        "templatePreview": templates[:25],
    }
    SUMMARY_JSON.write_text(json.dumps(summary, indent=2) + "\n")
    SUMMARY_MD.write_text(render_markdown(summary))
    print(f"90% evidence templates: {summary['mode']} created={created} existing={existing} missing={summary['missingTemplates']}")
    return 0


def template_for(assignment: dict) -> dict:
    return {
        "schema": "zero-php-parity-evidence-v1",
        "status": "pending",
        "batch": assignment["batch"],
        "path": assignment["path"],
        "surface": assignment["surface"],
        "targetOwner": assignment["targetOwner"],
        "targetSlice": assignment["targetSlice"],
        "risk": assignment["risk"],
        "aspNetCoreImplementation": {
            "pullRequest": "",
            "routeOrWorker": "",
            "tests": [],
        },
        "parity": {
            "phpSample": "",
            "aspNetCoreSample": "",
            "comparisonResult": "pending",
        },
        "rollbackApproved": False,
        "productionSmokePassed": False,
        "phpFallbackRemoved": False,
        "phpFallbackRetainedForApprovedReason": False,
        "operatorNotes": "Fill this file only after real implementation, parity, rollback, and smoke evidence exist.",
    }


def evidence_file_for(assignment: dict) -> Path:
    normalized = assignment["path"].replace("/", "-").replace("_", "-")
    if normalized.lower().endswith(".php"):
        normalized = normalized[:-4]
    return EVIDENCE_ROOT / f"batch-{assignment['batch']:03d}" / f"{normalized.lower()}.json"


def render_markdown(summary: dict) -> str:
    rows = [f"- `{item}`" for item in summary["templatePreview"]]
    return "\n".join([
        "# Zero-PHP 90% Evidence Template Summary",
        "",
        "Generated by `scripts/generate_zero_php_90_evidence_templates.py`. Default mode is dry-run; no parity claim is made by this file.",
        "",
        f"- Mode: `{summary['mode']}`.",
        f"- Target percent: {summary['targetPercent']:.1f}%.",
        f"- Selected batches: {summary['selectedBatches']}.",
        f"- Selected items: {summary['selectedItems']}.",
        f"- Existing templates: {summary['existingTemplates']}.",
        f"- Created templates: {summary['createdTemplates']}.",
        f"- Missing templates: {summary['missingTemplates']}.",
        "",
        "## Commands",
        "",
        f"- Generate templates: `{summary['writeCommand']}`",
        f"- Verify 90% readiness: `{summary['verifyCommand']}`",
        "",
        "## First template paths",
        "",
        *rows,
        "",
    ])


if __name__ == "__main__":
    raise SystemExit(main())
