#!/usr/bin/env python3
"""Verify whether the 90% zero-PHP target has real evidence.

The command is intentionally strict: it exits non-zero until every selected batch item has
a parity evidence file that declares live-or-removed status plus rollback and smoke proof.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "docs/migration/inventory/zero-php-90-percent-target-plan.json"
BATCHES = ROOT / "docs/migration/inventory/php-route-job-cutover-batches.json"
REPORT_JSON = ROOT / "docs/migration/inventory/zero-php-90-readiness-report.json"
REPORT_MD = ROOT / "docs/migration/inventory/ZERO_PHP_90_READINESS_REPORT.md"
EVIDENCE_ROOT = ROOT / "docs/migration/parity"
READY_STATUSES = {"live", "removed"}


def main() -> int:
    plan = json.loads(PLAN.read_text())
    batches = json.loads(BATCHES.read_text())
    selected_batch_numbers = {batch["batch"] for batch in plan["batches"]}
    selected_assignments = [
        assignment | {"batch": batch["batch"]}
        for batch in batches["batches"]
        if batch["batch"] in selected_batch_numbers
        for assignment in batch["assignments"]
    ]

    checked = [check_assignment(item) for item in selected_assignments]
    ready_items = sum(1 for item in checked if item["ready"])
    missing_items = len(checked) - ready_items
    report = {
        "status": "ready" if missing_items == 0 else "blocked-missing-evidence",
        "targetPercent": plan["targetPercent"],
        "selectedBatches": plan["selectedBatches"],
        "selectedItems": len(checked),
        "readyItems": ready_items,
        "missingItems": missing_items,
        "requiredEvidenceRoot": str(EVIDENCE_ROOT.relative_to(ROOT)),
        "rules": [
            "Evidence status must be live or removed.",
            "rollbackApproved must be true.",
            "productionSmokePassed must be true.",
            "phpFallbackRemoved or phpFallbackRetainedForApprovedReason must be true.",
        ],
        "items": checked,
    }
    REPORT_JSON.write_text(json.dumps(report, indent=2) + "\n")
    REPORT_MD.write_text(render_markdown(report))

    print(f"90% readiness: {report['status']} ({ready_items}/{len(checked)} ready)")
    return 0 if missing_items == 0 else 1


def check_assignment(assignment: dict) -> dict:
    evidence_path = evidence_file_for(assignment)
    result = {
        "batch": assignment["batch"],
        "path": assignment["path"],
        "surface": assignment["surface"],
        "targetSlice": assignment["targetSlice"],
        "evidencePath": str(evidence_path.relative_to(ROOT)),
        "ready": False,
        "reason": "evidence-file-missing",
    }

    if not evidence_path.exists():
        return result

    evidence = json.loads(evidence_path.read_text())
    status = str(evidence.get("status", "")).lower()
    rollback_approved = bool(evidence.get("rollbackApproved"))
    smoke_passed = bool(evidence.get("productionSmokePassed"))
    fallback_safe = bool(evidence.get("phpFallbackRemoved")) or bool(evidence.get("phpFallbackRetainedForApprovedReason"))

    result.update({
        "status": status,
        "rollbackApproved": rollback_approved,
        "productionSmokePassed": smoke_passed,
        "phpFallbackSafe": fallback_safe,
    })

    if status not in READY_STATUSES:
        result["reason"] = "status-not-live-or-removed"
    elif not rollback_approved:
        result["reason"] = "rollback-not-approved"
    elif not smoke_passed:
        result["reason"] = "production-smoke-not-passed"
    elif not fallback_safe:
        result["reason"] = "php-fallback-not-safe"
    else:
        result["ready"] = True
        result["reason"] = "ready"

    return result


def evidence_file_for(assignment: dict) -> Path:
    normalized = assignment["path"].replace("/", "-").replace("_", "-")
    if normalized.lower().endswith(".php"):
        normalized = normalized[:-4]
    return EVIDENCE_ROOT / f"batch-{assignment['batch']:03d}" / f"{normalized.lower()}.json"


def render_markdown(report: dict) -> str:
    missing_preview = [item for item in report["items"] if not item["ready"]][:25]
    rows = [
        f"| {item['batch']} | `{item['path']}` | {item['targetSlice']} | {item['reason']} |"
        for item in missing_preview
    ]
    return "\n".join([
        "# Zero-PHP 90% Readiness Report",
        "",
        "Generated by `scripts/verify_zero_php_90_readiness.py`. This report is allowed to block 90% completion claims until evidence exists.",
        "",
        f"- Status: `{report['status']}`.",
        f"- Target percent: {report['targetPercent']:.1f}%.",
        f"- Selected batches: {report['selectedBatches']}.",
        f"- Selected items: {report['selectedItems']}.",
        f"- Ready items: {report['readyItems']}.",
        f"- Missing or blocked items: {report['missingItems']}.",
        "",
        "## Required evidence rules",
        "",
        "- Evidence status must be `live` or `removed`.",
        "- `rollbackApproved` must be true.",
        "- `productionSmokePassed` must be true.",
        "- `phpFallbackRemoved` or `phpFallbackRetainedForApprovedReason` must be true.",
        "",
        "## First missing/blocked items",
        "",
        "| Batch | Path | Slice | Reason |",
        "| ---: | --- | --- | --- |",
        *rows,
        "",
    ])


if __name__ == "__main__":
    sys.exit(main())
