namespace EcomAE.Platform.Storefront;

public static partial class StorefrontEditForm
{
    /// <summary>The literal html of <c>content/users/editform.php</c>, in source order, as PHP prints it.</summary>
    private static readonly string[] Html =
    [
        "\t\t\t<script>\n\t\t\t\tlocation=\"",
        "/users/editform?error_message=",
        "\";\n\t\t\t</script>\n\t\t\t",
        "\t\t<script>\n\t\t\tlocation=\"",
        "/users/editform?success_message=",
        "\";\n\t\t</script>\n\t\t",
        "\t\t<script>\n\t\tvar reg_fields = new Array();//Массив с объектами всех полей\n\t\t",
        "\t\t\treg_fields[reg_fields.length] = new Object();//Создаем новый объект поля. И инициализируем его поля:\n\t\t\treg_fields[reg_fields.length - 1].main_flag = ",
        ";\n\t\t\treg_fields[reg_fields.length - 1].name = \"",
        "\";\n\t\t\treg_fields[reg_fields.length - 1].caption = \"",
        "\";\n\t\t\treg_fields[reg_fields.length - 1].show_for = ",
        ";\n\t\t\treg_fields[reg_fields.length - 1].required_for = ",
        ";\n\t\t\treg_fields[reg_fields.length - 1].maxlen = ",
        ";\n\t\t\treg_fields[reg_fields.length - 1].regexp = \"",
        "\";\n\t\t\treg_fields[reg_fields.length - 1].widget_type = \"",
        "\";\n\t\t\treg_fields[reg_fields.length - 1].widget_options = ",
        ";\n\t\t\treg_fields[reg_fields.length - 1].value_buffer = \"\";//Текущее значения - для сохранения при переключении регистрационных вариантов\n\t\t\t",
        "\t\t</script>\n\t\t\n\n\t\t<!-- САМА ФОРМА -->\n\t\t<form id=\"regform\" onsubmit=\"return onSubmitCheck();\" method=\"post\">\n\t\t\t<input type=\"hidden\" name=\"edit_user\" value=\"edit_user\" />\n\t\t\t\n\t\t\t",
        "\t\t\t<input type=\"hidden\" name=\"csrf_guard_key\" value=\"",
        "\" />\n\t\t\t\n\t\t\t<!--Блок для выбора Регистрационного Варианта-->\n\t\t\t<div id=\"RegVariantsSelector\">\n\t\t\t\t",
        "\t\t\t\t\t<select id=\"reg_variant_selector\" name=\"reg_variant\" style=\"display:none\" onchange=\"regenerateFields();\">\n\t\t\t\t\t\t<option value=\"",
        "\">",
        "</option>\n\t\t\t\t\t</select>\n\t\t\t\t\t",
        "\t\t\t\t\t<div class=\"panel panel-primary\">\n\t\t\t\t\t\t<div class=\"panel-heading\">",
        "</div>\n\t\t\t\t\t\t<div class=\"panel-body\">\n\t\t\t\t\t\t\t  <div class=\"form-group\">\n\t\t\t\t\t\t\t\t<select id=\"reg_variant_selector\" name=\"reg_variant\" onchange=\"regenerateFields();\" class=\"form-control\" />\n\t\t\t\t\t\t\t\t",
        "\t\t\t\t\t\t\t\t\t<option value=\"",
        "\">",
        "</option>\n\t\t\t\t\t\t\t\t\t",
        "\t\t\t\t\t\t\t\t</select>\n\t\t\t\t\t\t\t  </div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t\t",
        "\t\t\t</div>\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t<!-- БЛОК ДОПОЛНИТЕЛЬНЫХ ПОЛЕЙ -->\n\t\t\t<div id=\"additional_fields_div\">\n\t\t\t</div>\n\t\t\t\n\t\t\t\n\t\t\t<!-- Блок для пароля -->\n\t\t\t<div class=\"panel panel-primary\">\n\t\t\t\t<!--<div class=\"panel-heading\">Пароль</div>-->\n\t\t\t\t<div class=\"panel-body\">\n\n\t\t\t\t\t<div class=\"form-group col-md-6\">\n\t\t\t\t\t\t<label for=\"password\" class=\"col-sm-4 control-label\">",
        "</label>\n\t\t\t\t\t\t<div class=\"col-sm-8\" style=\"padding:5px;\">\n\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"form-control\" id=\"password\" placeholder=\"",
        "\" />\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t<div class=\"form-group col-md-6\">\n\t\t\t\t\t\t<label for=\"password_repeat\" class=\"col-sm-4 control-label\">",
        "</label>\n\t\t\t\t\t\t<div class=\"col-sm-8\" style=\"padding:5px;\">\n\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password_repeat\" id=\"password_repeat\" value=\"\" placeholder=\"",
        "\">\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t\t\n\t\t\t\t\t<div class=\"text-center\">",
        ".</div>\n\t\t\t\t\t\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t\n\t\t\t\n\t\t\t<script>\n\t\t\t//Перегенировать поля\n\t\t\tfunction regenerateFields()\n\t\t\t{\n\t\t\t\tvar current_reg_variant = document.getElementById(\"reg_variant_selector\").value;\n\t\t\t\t\n\t\t\t\tvar additional_html = \"\";//HTML для дополнительных полей регистрации\n\t\t\t\tfor(var i=0; i < reg_fields.length; i++)\n\t\t\t\t{\n\t\t\t\t\t//Обработка show_for:\n\t\t\t\t\tif(reg_fields[i].show_for.indexOf(parseInt(current_reg_variant)) < 0)\n\t\t\t\t\t{\n\t\t\t\t\t\tcontinue;//Это поле не показываем\n\t\t\t\t\t}\n\t\t\t\t\t\n\t\t\t\t\t//Обработка required_for\n\t\t\t\t\tvar required_for = \"\";//Для звездочки\n\t\t\t\t\tif(reg_fields[i].required_for.indexOf(parseInt(current_reg_variant)) >= 0)\n\t\t\t\t\t{\n\t\t\t\t\t\trequired_for = \"*\";//Это поле не показываем\n\t\t\t\t\t}\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\tadditional_html += \"<div class=\\\"form-group\\\"><label for=\\\"\"+reg_fields[i].name+\"\\\" class=\\\"col-sm-2 control-label\\\">\"+reg_fields[i].caption+required_for+\"</label><div class=\\\"col-sm-10\\\" style=\\\"padding:5px;\\\">\";\n\t\t\t\t\t\n\t\t\t\t\t//Виджет:\n\t\t\t\t\tswitch(reg_fields[i].widget_type)\n\t\t\t\t\t{\n\t\t\t\t\t\tcase \"text\":\n\t\t\t\t\t\t\tadditional_html += \"<input onKeyUp=\\\"dynamicApplying('\"+reg_fields[i].name+\"');\\\" type=\\\"text\\\" name=\\\"\"+reg_fields[i].name+\"\\\" id=\\\"\"+reg_fields[i].name+\"\\\" value='\"+reg_fields[i].value_buffer.replace('/([\"\\'\\])/g', \"\\\\$1\")+\"' class=\\\"form-control\\\" placeholder=\\\"\"+reg_fields[i].caption+\"\\\" />\";\n\t\t\t\t\t\t\tbreak;\n\t\t\t\t\t};\n\t\t\t\t\t\n\t\t\t\t\tadditional_html += \"</div></div>\";\n\t\t\t\t}\n\t\t\t\t\n\t\t\t\tadditional_html = \"<div class=\\\"panel panel-primary\\\"><div class=\\\"panel-heading\\\">",
        "</div><div class=\\\"panel-body\\\">\" + additional_html + \"</div></div>\";\n\t\t\t\t\n\t\t\t\tdocument.getElementById(\"additional_fields_div\").innerHTML = \"\";\n\t\t\t\tdocument.getElementById(\"additional_fields_div\").innerHTML = additional_html;\n\t\t\t}//~function regenerateFields()\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t// --------------------------------------------------------------------------\n\t\t\t//Функция динамическиго применния значений для текстовых строк\n\t\t\tfunction dynamicApplying(attribute)\n\t\t\t{\n\t\t\t\tvar str_value = document.getElementById(attribute).value;//Текущее значение\n\t\t\t\t//Ищем поле\n\t\t\t\tfor(var i=0; i < reg_fields.length; i++)\n\t\t\t\t{\n\t\t\t\t\tif(reg_fields[i].name == attribute)\n\t\t\t\t\t{\n\t\t\t\t\t\treg_fields[i].value_buffer = str_value;\n\t\t\t\t\t\tconsole.log(reg_fields[i].value_buffer);\n\t\t\t\t\t\tbreak;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t\tregenerateFields();//Генерируем после загрузки страницы\n\t\t\t</script>\n\t\t\t\n\t\t\t\n\t\t\t<button class=\"btn btn-ar btn-primary\" type=\"submit\">",
        "</button>\n\t\t</form>\n\t\t\n\t\t\n\n\n\n\n\n\t\t",
        "\t\t<script>\n\t\t",
        "\t\t\tfor(var i=0; i < reg_fields.length; i++)\n\t\t\t{\n\t\t\t\tif(reg_fields[i].name == '",
        "')\n\t\t\t\t{\n\t\t\t\t\treg_fields[i].value_buffer = '",
        "';\n\t\t\t\t}\n\t\t\t}\n\t\t\t",
        "\t\t</script>\n\t\t",
        "\t\t<script>\n\t\t//1. Текущий регистрационный вариант:\n\t\tdocument.getElementById(\"reg_variant_selector\").value = ",
        ";\n\t\tregenerateFields();//Генерируем после загрузки страницы\n\t\t</script>\n\t\t",
        "\n\n\t\t\n\t\t\n\t\t\n\t\t<script>\n\t\t// ---------------------------------------------------------------------------------------------\n\t\t//ПРОВЕРКА КОРРЕКСТНОСТИ ЗАПОЛНЕНИЯ ФОРМЫ:\n\t\t//Капча здесь больше не используется, т.к. при сохранении этой формы нет отправки ссылок и кодов подтверждения контактов\n\t\tfunction onSubmitCheck()\n\t\t{\n\t\t\t//Получаем текущий выбранный Регистрационный Вариант:\n\t\t\tvar currentRegVariant = document.getElementById(\"reg_variant_selector\").value;\n\t\t\t\n\t\t\t//Проверка факта заполнения полей какими-либо значениями\n\t\t\tfor(var i=0; i<reg_fields.length; i++)\n\t\t\t{\n\t\t\t\tif(reg_fields[i].required_for.indexOf(parseInt(currentRegVariant)) != -1)//Заполнение требуется для данного Регистрационного Варианта\n\t\t\t\t{\n\t\t\t\t\tif(document.getElementById(reg_fields[i].name).value == \"\")//Но поле не заполнено\n\t\t\t\t\t{\n\t\t\t\t\t\talert(\"Заполните поле \"+reg_fields[i].caption);\n\t\t\t\t\t\treturn false;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}//for(i)\n\t\t\t\n\t\t\t//Обработка заполнения пароля:\n\t\t\tif(document.getElementById(\"password\").value != document.getElementById(\"password_repeat\").value)//Пароли должны совпадать\n\t\t\t{\n\t\t\t\talert(\"",
        "\");\n\t\t\t\treturn false;\n\t\t\t}\n\t\t\telse if(document.getElementById(\"password\").value.length < ",
        " && document.getElementById(\"password\").value.length !=0)//Совпадает. Теперь проверям минимально допустимую длину\n\t\t\t{\n\t\t\t\talert(\"",
        " ",
        " ",
        "\");\n\t\t\t\treturn false;\n\t\t\t}\n\t\t\t\n\t\t\t\n\t\t\t//Проверка соответствия заполненных значений регулярным выражениям\n\t\t\t//Если поле пустое - значит его можно было не заполнять (проверка на факт заполнения следует раньше). Но есть там есть значение, то оно обязательно должно соответствовать RegExp, даже если оно не обязательно к заполнению\n\t\t\tfor(var i=0; i<reg_fields.length; i++)\n\t\t\t{\n\t\t\t\tif(reg_fields[i].show_for.indexOf(parseInt(currentRegVariant)) == -1)//У этого поля не указан текущий Регистрационный Вариант - его нет в форме\n\t\t\t\t{\n\t\t\t\t\tcontinue;\n\t\t\t\t}\n\t\t\t\t\n\t\t\t\t//Если регулярное выражение пустое - значит пропускаем, т.к. требований к содержимому нет\n\t\t\t\tif(reg_fields[i].regexp == \"\")\n\t\t\t\t{\n\t\t\t\t\tcontinue;\n\t\t\t\t}\n\t\t\t\t\n\t\t\t\tif(String(document.getElementById(reg_fields[i].name).value) != \"\")\n\t\t\t\t{\n\t\t\t\t\tvar current_value = String(document.getElementById(reg_fields[i].name).value);//Заполненное значение\n\t\t\t\t\tvar regex = new RegExp(reg_fields[i].regexp);//Регулярное выражение для поля\n\t\t\t\t\t//Далее ищем подстроку по регулярному выражению\n\t\t\t\t\tvar match = regex.exec(String(current_value));\n\t\t\t\t\tif(match == null)\n\t\t\t\t\t{\n\t\t\t\t\t\talert(\"",
        " \"+reg_fields[i].caption+\" ",
        "\");\n\t\t\t\t\t\treturn false;\n\t\t\t\t\t}\n\t\t\t\t\telse\n\t\t\t\t\t{\n\t\t\t\t\t\tvar match_value = String(match[0]);//Подходящая подстрока\n\t\t\t\t\t\tif(match_value != current_value)\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\talert(\"",
        " \"+reg_fields[i].caption+\" ",
        "\");\n\t\t\t\t\t\t\treturn false;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\t//Заполнено правильно, если: есть подстрока по регулярному выражению и она полностью равна самой строке\n\t\t\t\t}\n\t\t\t}\n\n\t\t\treturn true;\n\t\t}//~function onSubmitCheck()\n\t\t// ---------------------------------------------------------------------------------------------\n\t\t</script>\n\t\t",
    ];
}
