namespace EcomAE.Platform.Storefront;

/// <summary>
/// The static bytes of the PHP <c>content/shop/returns</c> pages (CRLF sources, as PHP echoes them). <c>{{name}}</c> is a value
/// <see cref="StorefrontReturnsPages"/> fills in; <c>{{t:KEY}}</c> is <c>translate_str_by_id(KEY)</c>.
/// </summary>
public static partial class StorefrontReturnsPages
{
    /// <summary>returns.php up to the first row: search box and table head.</summary>
    internal const string ListHead =
        "<input class=\"form-control\" type=\"text\"\r\n"
        + "       placeholder=\"{{t:4583}}\" id=\"search-text\"\r\n"
        + "       onkeyup=\"tableSearch()\">\r\n"
        + "<div class=\"hr-line-dashed col-lg-12\"></div>\r\n"
        + "<table cellpadding=\"1\" cellspacing=\"1\" id=\"orders_returns_table\" class=\"table table-condensed table-striped\"\r\n"
        + "       style=\"border-collapse: separate; border-spacing: 0 5px;\">\r\n"
        + "    <thead>\r\n"
        + "    <tr>\r\n"
        + "        <th>ID</th>\r\n"
        + "        <th>{{t:2081}}</th>\r\n"
        + "        <th>{{t:3244}}</th>\r\n"
        + "        <th>{{t:3811}}</th>\r\n"
        + "        <th class=\"hidden\"></th>\r\n"
        + "    </tr>\r\n"
        + "    </thead>\r\n"
        + "    <tbody>\r\n"
        + "    ";

    /// <summary>One returns.php row; <c>{{unread}}</c> is <see cref="ListUnread"/> or empty.</summary>
    internal const string ListRow =
        "        <tr style=\"background: {{color}};\">\r\n"
        + "            <td>\r\n"
        + "                <a href=\"{{dp}}shop/returns/return?return_id={{id}}\"> {{id}}</a>\r\n"
        + "\t\t\t\t{{unread}}            </td>\r\n"
        + "            <td>{{caption}}</td>\r\n"
        + "            <td><a href=\"{{dp}}shop/orders/order?order_id={{order}}\"\r\n"
        + "                   target=\"_blank\"> {{order}}</a></td>\r\n"
        + "\r\n"
        + "            <td>{{total}}</td>\r\n"
        + "            <td class=\"hidden\">{{filter}}></td>\r\n"
        + "\r\n"
        + "        </tr>\r\n"
        + "        ";

    /// <summary>returns.php unread-messages badge of a row.</summary>
    internal const string ListUnread =
        "\t\t\t\t<small>\r\n"
        + "\t\t\t\t\t<a style=\"white-space: nowrap;\" class=\"dropdown-toggle label-menu-corner\" href=\"/shop/returns/return?return_id={{id}}\">\r\n"
        + "\t\t\t\t\t\t<i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\r\n"
        + "\t\t\t\t\t\t<span style=\"font-size: 9px;\">{{count}}</span>\r\n"
        + "\t\t\t\t\t</a>\r\n"
        + "\t\t\t\t</small>\r\n"
        + "\t\t\t\t";

    /// <summary>returns.php after the rows: table close and the tableSearch() filter.</summary>
    internal const string ListTail =
        "    </tbody>\r\n"
        + "</table>\r\n"
        + "\r\n"
        + "<script>\r\n"
        + "    function tableSearch() {\r\n"
        + "        var phrase = document.getElementById('search-text');\r\n"
        + "        var table = document.getElementById('orders_returns_table');\r\n"
        + "        var regPhrase = new RegExp(phrase.value, 'i');\r\n"
        + "        var flag = false;\r\n"
        + "        for (var i = 1; i < table.rows.length; i++) {\r\n"
        + "            flag = false;\r\n"
        + "            for (var j = table.rows[i].cells.length - 1; j >= 0; j--) {\r\n"
        + "                flag = regPhrase.test(table.rows[i].cells[j].innerHTML);\r\n"
        + "                if (flag) break;\r\n"
        + "            }\r\n"
        + "            if (flag) {\r\n"
        + "                table.rows[i].style.display = \"\";\r\n"
        + "            } else {\r\n"
        + "                table.rows[i].style.display = \"none\";\r\n"
        + "            }\r\n"
        + "\r\n"
        + "        }\r\n"
        + "    }\r\n"
        + "</script>\r\n"
        + "\r\n";

    /// <summary>return.php for a guest: the redirect script before its exit().</summary>
    internal const string ReturnGuest =
        "\t<script>location = '{{dp}}'</script>\r\n"
        + "\t";

    /// <summary>return.php heading up to the status caption.</summary>
    internal const string ReturnHead =
        "    <h3><label for=\"\">{{t:3802}} {{id}}</label></h3>\r\n"
        + "    <label for=\"\">{{t:3803}}: </label>\r\n";

    /// <summary>return.php items table head, after the status caption.</summary>
    internal const string ReturnTableHead =
        "    <p class=\"lead\" style=\"border-bottom: 2px solid; padding-bottom: 10px;\"><strong>{{t:3498}}</strong></p>\r\n"
        + "    <div style=\"overflow: hidden; overflow-x: auto;\">\r\n"
        + "        <table class=\"table\">\r\n"
        + "            <tr>\r\n"
        + "                <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:2070}}</th>\r\n"
        + "                <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:2071}}</th>\r\n"
        + "                <th style=\"vertical-align: middle;\">{{t:2102}}</th>\r\n"
        + "                <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:2751}}</th>\r\n"
        + "                <th style=\"vertical-align: middle; white-space: nowrap; text-align:center;\">{{t:4526}}</th>\r\n"
        + "                <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:3251}}</th>\r\n"
        + "            </tr>\r\n"
        + "            ";

    /// <summary>One return.php item block (row, photos, reason, comment, decision).</summary>
    internal const string ReturnRow =
        "                <tr style=\"border-top: 1px solid; \">\r\n"
        + "                    <td style=\"vertical-align: middle; white-space: nowrap;\">{{manufacturer}}</td>\r\n"
        + "                    <td style=\"vertical-align: middle; white-space: nowrap;\">{{article}}</td>\r\n"
        + "                    <td style=\"vertical-align: middle; width: 100%; min-width: 200px; max-width: 800px; word-wrap: break-word;\">{{name}}</td>\r\n"
        + "                    <td style=\"vertical-align: middle; white-space: nowrap;\">{{price}}</td>\r\n"
        + "                    <td style=\"vertical-align: middle; white-space: nowrap; text-align:center;\">{{count}}</td>\r\n"
        + "                    <td style=\"vertical-align: middle; white-space: nowrap;\">{{sum}}</td>\r\n"
        + "                </tr>\r\n"
        + "                <tr style=\"border-bottom: 1px solid;\">\r\n"
        + "                    <td colspan=\"6\">\r\n"
        + "\r\n"
        + "                        <div class=\"col-lg-12 col-sm-12 col-md-12\" style=\"margin-top: 10px;\">\r\n"
        + "                            <label for=\"\">Фото товара: </label>\r\n"
        + "                            <div style=\"display: flex;\">\r\n"
        + "\r\n"
        + "                                {{images}}                            </div>\r\n"
        + "                        </div>\r\n"
        + "                        <div class=\"col-lg-12 col-sm-12 col-md-12\" style=\"margin-top: 10px;\">\r\n"
        + "                            <label for=\"\">{{t:3807}}: </label>{{reason}}                        </div>\r\n"
        + "                        <div class=\"col-lg-12 col-sm-12 col-md-12\" style=\"margin-top: 10px;\">\r\n"
        + "                            <label for=\"\">{{t:4581}}: </label> <br>\r\n"
        + "                            <div>\r\n"
        + "                                {{comment}}                            </div>\r\n"
        + "                        </div>\r\n"
        + "                        <div class=\"col-lg-12 col-sm-12 col-md-12\" style=\"margin-top: 10px;\">\r\n"
        + "                            <label for=\"\">{{t:2081}}: </label> <br>\r\n"
        + "                            <div>\r\n"
        + "                                {{status}}                            </div>\r\n"
        + "                        </div>\r\n"
        + "                    </td>\r\n"
        + "                </tr>\r\n"
        + "                <tr>\r\n"
        + "                    <td colspan=\"6\" style=\"padding-top: 10px; border-top: 2px solid;\">\r\n"
        + "\r\n"
        + "                    </td>\r\n"
        + "                </tr>\r\n"
        + "                ";

    /// <summary>One return line photo, inlined as base64 like return.php.</summary>
    internal const string ReturnImage =
        "<div class=\"place_return_item_img\"><img onclick=\"openImage(this)\" class=\"return_item_img\" src = \"data:image/png;base64,{{base64}}\"></div>";

    /// <summary>return.php after the items: total, openImage() and return.css.</summary>
    internal const string ReturnTail =
        "        </table>\r\n"
        + "        <p class=\"lead\">{{t:3811}}: {{total}} руб.</p>\r\n"
        + "    </div>\r\n"
        + "    </div>\r\n"
        + "    </div>\r\n"
        + "    </div>\r\n"
        + "\r\n"
        + "\t<script>\r\n"
        + "\t\tfunction openImage(image)\r\n"
        + "\t\t{\r\n"
        + "\t\t\tlet w = window.open(\"\");\r\n"
        + "\t\t\tw.document.write(image.outerHTML);\r\n"
        + "\t\t}\r\n"
        + "\t</script>\r\n"
        + "\r\n"
        + "\t<link rel=\"stylesheet\" href=\"{{dp}}content/shop/returns/assets/return.css\">\r\n"
        + "\r\n";

    /// <summary>return_messages.php: the return chat polling ajax_get_order_messages.php.</summary>
    internal const string ReturnMessages =
        "<!-- Переписка с покупателем -->\r\n"
        + "<p class=\"lead\">{{t:4548}}</p>\r\n"
        + "<div>\r\n"
        + "    <div class=\"chat_block\" id=\"chat_block\">\r\n"
        + "    </div>\r\n"
        + "\r\n"
        + "    <br>\r\n"
        + "    {{t:4549}}:\r\n"
        + "    <textarea id=\"new_message_area\"></textarea>\r\n"
        + "    <button class=\"btn btn-ar btn-primary\" onclick=\"sendMessage();\">{{t:3211}}</button>\r\n"
        + "</div>\r\n"
        + "<script>\r\n"
        + "    // --------------------------------------------------------------------------\r\n"
        + "    //Получить сообщения по заказу\r\n"
        + "    function getOrderMessages() {\r\n"
        + "        jQuery.ajax({\r\n"
        + "            type: \"GET\",\r\n"
        + "            async: true,\r\n"
        + "            url: \"/content/shop/messager/ajax_get_order_messages.php\",\r\n"
        + "            dataType: \"json\",//Тип возвращаемого значения\r\n"
        + "            data: \"return_id={{id}}\" + \"&csrf_guard_key={{csrf}}\",\r\n"
        + "            success: function (answer) {\r\n"
        + "                var html = \"\";\r\n"
        + "                for (var i = 0; i < answer.length; i++) {\r\n"
        + "                    var class_str = \"bubble\";\r\n"
        + "                    var sender = \"{{t:4550}}\";\r\n"
        + "                    if (answer[i].is_customer == false) {\r\n"
        + "                        class_str += \"2\";\r\n"
        + "                        sender = \"{{t:3565}}\";\r\n"
        + "                    }\r\n"
        + "                    html += \"<div class=\\\"\" + class_str + \"\\\">\" + sender + \" \" + answer[i].time + \"<br>\" + answer[i].text + \"</div>\";\r\n"
        + "                }\r\n"
        + "                if (html == \"\") html = \"<div align=\\\"center\\\">{{t:3566}}</div>\";\r\n"
        + "                document.getElementById(\"chat_block\").innerHTML = html;\r\n"
        + "\r\n"
        + "                document.getElementById(\"chat_block\").scrollTop = document.getElementById(\"chat_block\").scrollHeight;\r\n"
        + "            }\r\n"
        + "        });\r\n"
        + "    }\r\n"
        + "\r\n"
        + "    // --------------------------------------------------------------------------\r\n"
        + "    //Отправить сообщение\r\n"
        + "    function sendMessage() {\r\n"
        + "        var text = document.getElementById(\"new_message_area\").value;\r\n"
        + "        if (text == \"\") {\r\n"
        + "            alert(\"{{t:3567}}\");\r\n"
        + "            return;\r\n"
        + "        }\r\n"
        + "\r\n"
        + "        jQuery.ajax({\r\n"
        + "            type: \"GET\",\r\n"
        + "            async: true,\r\n"
        + "            url: \"/content/shop/messager/ajax_send_message.php\",\r\n"
        + "            dataType: \"json\",//Тип возвращаемого значения\r\n"
        + "            data: \"return_id={{id}}&text=\" + encodeURI(text) + \"&csrf_guard_key={{csrf}}\",\r\n"
        + "            success: function (answer) {\r\n"
        + "                if (answer == true) {\r\n"
        + "                    document.getElementById(\"new_message_area\").value = \"\";\r\n"
        + "                    getOrderMessages();\r\n"
        + "                } else {\r\n"
        + "                    alert(\"{{t:3568}}\");\r\n"
        + "                }\r\n"
        + "            }\r\n"
        + "        });\r\n"
        + "    }\r\n"
        + "\r\n"
        + "    // --------------------------------------------------------------------------\r\n"
        + "    getOrderMessages();//Запрашиваем переписку по заказу\r\n"
        + "\r\n"
        + "    setInterval(function () {\r\n"
        + "        getOrderMessages();\r\n"
        + "    }, 300000);\r\n"
        + "</script>";

    /// <summary>add_return.php up to the first line; <c>{{note}}</c> is <see cref="AddNote"/> or empty.</summary>
    internal const string AddHead =
        "<link rel=\"stylesheet\" href=\"../../content/shop/returns/assets/return.css\">\r\n"
        + "<p class=\"lead\">{{t:3498}}</p>\r\n"
        + "{{note}}<div style=\"overflow: hidden; overflow-x: auto;\">\r\n"
        + "    <table class=\"table\">\r\n"
        + "        <tr>\r\n"
        + "            <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:2070}}</th>\r\n"
        + "            <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:2071}}</th>\r\n"
        + "            <th style=\"vertical-align: middle;\">{{t:2102}}</th>\r\n"
        + "            <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:2751}}</th>\r\n"
        + "            <th style=\"vertical-align: middle; white-space: nowrap; text-align:center;\">{{t:4526}}</th>\r\n"
        + "            <th style=\"vertical-align: middle; white-space: nowrap;\">{{t:3251}}</th>\r\n"
        + "        </tr>\r\n"
        + "        ";

    /// <summary>add_return.php retention notice.</summary>
    internal const string AddNote =
        "<div class=\"notification\">\r\n"
        + "    {{note}}</div>\r\n";

    /// <summary>One add_return.php line with its reason, photos and comment form.</summary>
    internal const string AddRow =
        "            <style>\r\n"
        + "                textarea {\r\n"
        + "                    width: 100%; /* Ширина поля в процентах */\r\n"
        + "                    height: 200px; /* Высота поля в пикселах */\r\n"
        + "                    resize: none; /* Запрещаем изменять размер */\r\n"
        + "                }\r\n"
        + "            </style>\r\n"
        + "            <tr style=\"\">\r\n"
        + "                <td style=\"vertical-align: middle; white-space: nowrap;\">{{manufacturer}}</td>\r\n"
        + "                <td style=\"vertical-align: middle; white-space: nowrap;\">{{article}}</td>\r\n"
        + "                <td style=\"vertical-align: middle; width: 100%; min-width: 200px; max-width: 800px; word-wrap: break-word;\">{{name}}</td>\r\n"
        + "\t\t\t\t\t\t\t\t<td style=\"vertical-align: middle; white-space: nowrap;\">\r\n"
        + "                    <input type=\"hidden\" id=\"item_price_{{id}}\" value=\"{{price_raw}}\">\r\n"
        + "                    {{price}}                </td>\r\n"
        + "                <td style=\"vertical-align: middle; white-space: nowrap; text-align:center;\">\r\n"
        + "                    <input type=\"number\" style=\"width: 70px;\" onblur=\"check_val();\" data-count=\"{{count}}\" id=\"item_count_{{id}}\" value=\"{{count}}\">\r\n"
        + "                </td>\r\n"
        + "\t\t\t\t\t\t\t\t<td style=\"vertical-align: middle; white-space: nowrap;\">{{sum}}</td>\r\n"
        + "            </tr>\r\n"
        + "            <tr>\r\n"
        + "                <td colspan=\"6\">\r\n"
        + "                    <div class=\"return_options\">\r\n"
        + "                        <form class=\"return_options_data\" enctype=\"multipart/form-data\" method=\"post\">\r\n"
        + "                            <input type=\"hidden\" name=\"item_id\" value=\"{{id}}\">\r\n"
        + "                            <input type=\"hidden\" name=\"csrf_guard_key\" value=\"{{csrf}}\">\r\n"
        + "                            <input type=\"hidden\" name=\"tech_key\" value=\"{{tech}}\";>\r\n"
        + "\r\n"
        + "                            <div class=\"col-lg-6 col-sm-6 col-md-12\" style=\"margin-top: 10px;\">\r\n"
        + "                                <label for=\"\">{{t:3807}}</label>\r\n"
        + "                                <select name=\"reason_id\" id=\"\" class=\"form-control\">\r\n"
        + "                                    <option value=\"-1\">{{t:4579}}</option>\r\n"
        + "                                    {{reasons}}                                </select>\r\n"
        + "                            </div>\r\n"
        + "                            <div class=\"col-lg-6 col-sm-6 col-md-12\" style=\"margin-top: 10px;\">\r\n"
        + "                                <label for=\"\">{{t:4580}}</label> <input name=\"images[]\" type=\"file\" multiple\r\n"
        + "                                                                         id=\"file_form_db\" class=\"form-control\"/>\r\n"
        + "                            </div>\r\n"
        + "                            <div class=\"col-lg-12 col-sm-6 col-md-12\" style=\"margin-top: 10px;\">\r\n"
        + "                                <label for=\"\">{{t:3571}}</label> <br><textarea name=\"comment\" id=\"\" cols=\"30\" rows=\"10\"\r\n"
        + "                                                                                placeholder=\"{{t:3571}}\"></textarea>\r\n"
        + "                            </div>\r\n"
        + "                        </form>\r\n"
        + "                    </div>\r\n"
        + "                </td>\r\n"
        + "            </tr>\r\n"
        + "            ";

    /// <summary>One shop_orders_returns_reasons option.</summary>
    internal const string AddReason =
        "<option value=\"{{id}}\">{{caption}}</option>";

    /// <summary>add_return.php table close.</summary>
    internal const string AddTableTail =
        "    </table>\r\n"
        + "\r\n"
        + "</div>\r\n";

    /// <summary>add_return.php total, the return_info form and the add_return.js.php include.</summary>
    internal const string AddFoot =
        "<p class=\"lead\">{{t:3811}}: <span id=\"total_price_span\">{{total}}</span></p>\r\n"
        + "\r\n"
        + "<form id=\"return_info\" enctype=\"multipart/form-data\" method=\"post\">\r\n"
        + "    <input type=\"hidden\" name=\"user_id\" value=\"{{user}}\">\r\n"
        + "    <input type=\"hidden\" name=\"return_id\" id=\"return_id\" value=\"\">\r\n"
        + "    <input type=\"hidden\" name=\"csrf_guard_key\" value=\"{{csrf}}\">\r\n"
        + "    <input type=\"hidden\" name=\"tech_key\" value=\"{{tech}}\";>\r\n"
        + "    <input type=\"hidden\" name=\"office_id\" value=\"{{office}}\";>\r\n"
        + "</form>\r\n"
        + "\r\n"
        + "<p>\r\n"
        + "\t<input type=\"button\" id=\"btn_confirm_return\" class=\"btn btn-ar btn-primary\" value=\"{{t:4527}}\" onclick=\"confirm_return()\">\r\n"
        + "</p>\r\n"
        + "\r\n"
        + "<script>\r\n"
        + "    let main_url = \"{{dp}}\";\r\n"
        + "\t\t                var retention_percentage = {{retention}};\r\n"
        + "                var main_total_price = \"{{total}}\";\r\n"
        + "</script>\r\n"
        + "<script src=\"{{dp}}content/shop/returns/assets/add_return.js.php\"></script>\r\n";

    /// <summary>content/shop/returns/assets/add_return.js.php after its config/DB/lang header.</summary>
    internal const string AddScript =
        "let total_file_size = 0;\r\n"
        + "function check_return_data(formElem) {\r\n"
        + "    let form = new FormData(formElem);\r\n"
        + "    let flag = {\r\n"
        + "        status:true,\r\n"
        + "        message:\"\"\r\n"
        + "    };\r\n"
        + "    let available_format = ['image/png', 'image/jpeg', 'image/jpg','image/bmp'];\r\n"
        + "    form.getAll('images[]').forEach(el => {\r\n"
        + "        if (!available_format.includes(el.type))\r\n"
        + "        {\r\n"
        + "            flag.message = \"{{t:4924}}\"\r\n"
        + "            flag.status = false;\r\n"
        + "            return flag;\r\n"
        + "        }\r\n"
        + "\r\n"
        + "        if (el.size > 5242880)\r\n"
        + "        {\r\n"
        + "            flag.message = \"{{t:4925}}\"\r\n"
        + "            flag.status = false;\r\n"
        + "            return flag;\r\n"
        + "        }\r\n"
        + "        total_file_size = total_file_size + el.size;\r\n"
        + "    });\r\n"
        + "\r\n"
        + "\r\n"
        + "    if (total_file_size > 15728640)\r\n"
        + "    {\r\n"
        + "        flag.message = \"{{t:4926}}\"\r\n"
        + "        flag.status = false;\r\n"
        + "        return flag;\r\n"
        + "    }\r\n"
        + "\r\n"
        + "    if (form.get('reason_id') == -1 || form.getAll('images[]')[0].name == '' || form.get('comment') == \"\")\r\n"
        + "    {\r\n"
        + "        flag.message = \"{{t:3127}}.\";\r\n"
        + "        flag.status = false;\r\n"
        + "        return flag;\r\n"
        + "    }\r\n"
        + "    return flag;\r\n"
        + "}\r\n"
        + "async function fetchDataReturn(forms, count_arr, total_sum) {\r\n"
        + "\tlet formElem = document.querySelector(\"#return_info\");\r\n"
        + "    let request_body = new FormData(formElem);\r\n"
        + "\r\n"
        + "    forms.forEach((el,key) => {\r\n"
        + "        let sub_data = new FormData(el);\r\n"
        + "        request_body.append(\"items[\"+key+\"][item_id]\", sub_data.get(\"item_id\"));\r\n"
        + "        request_body.append(\"items[\"+key+\"][reason_id]\", sub_data.get(\"reason_id\"));\r\n"
        + "        request_body.append(\"items[\"+key+\"][comment]\", sub_data.get(\"comment\"));\r\n"
        + "\t\t\t\trequest_body.append(\"items[\"+key+\"][count]\", count_arr[sub_data.get(\"item_id\")]);\r\n"
        + "        sub_data.getAll('images[]').forEach((image, index) => {\r\n"
        + "            request_body.append(\"images[\"+sub_data.get('item_id')+\"][\"+index+\"]\", image);\r\n"
        + "        });\r\n"
        + "    });\r\n"
        + "\r\n"
        + "\t\trequest_body.append(\"total_sum\", total_sum);\r\n"
        + "\r\n"
        + "    let response = await fetch(main_url + 'content/shop/returns/ajax/ajax_load_returns_data.php', {\r\n"
        + "        method: 'POST',\r\n"
        + "        body: request_body\r\n"
        + "    });\r\n"
        + "    let json = await response.json();\r\n"
        + "\r\n"
        + "    if (json.status != false)\r\n"
        + "        location = main_url + \"{{lang}}shop/returns/returns_list\";\r\n"
        + "    else\r\n"
        + "    {\r\n"
        + "        alert(json.error_message);\r\n"
        + "\t\t\t\tjQuery(\"#btn_confirm_return\").prop('disabled', false);\r\n"
        + "    }\r\n"
        + "\r\n"
        + "}\r\n"
        + "\r\n"
        + "function getItemsIdsFromUrl() {\r\n"
        + "\tlet params = window\r\n"
        + "\t\t\t.location\r\n"
        + "\t\t\t.search\r\n"
        + "\t\t\t.replace('?','')\r\n"
        + "\t\t\t.split('&')\r\n"
        + "\t\t\t.reduce(\r\n"
        + "\t\t\t\t\tfunction(p,e){\r\n"
        + "\t\t\t\t\t\t\tvar a = e.split('=');\r\n"
        + "\t\t\t\t\t\t\tp[ decodeURIComponent(a[0])] = decodeURIComponent(a[1]);\r\n"
        + "\t\t\t\t\t\t\treturn p;\r\n"
        + "\t\t\t\t\t},\r\n"
        + "\t\t\t\t\t{}\r\n"
        + "\t\t\t);\r\n"
        + "\r\n"
        + "\treturn JSON.parse(params['items']);\r\n"
        + "}\r\n"
        + "\r\n"
        + "function check_val() {\r\n"
        + "\tlet total_price = 0;\r\n"
        + "\tlet ids = getItemsIdsFromUrl();\r\n"
        + "\r\n"
        + "\tids.forEach((id) => {\r\n"
        + "\t\t\tlet max_count = Number(document.querySelector('#item_count_' + id).dataset.count);\r\n"
        + "\t\t\tlet price = Number(document.querySelector('#item_price_' + id).value);\r\n"
        + "\t\t\tlet count = Number(document.querySelector('#item_count_' + id).value);\r\n"
        + "\t\t\tif (max_count < count || count <= 0)\r\n"
        + "\t\t\t{\r\n"
        + "\t\t\t\t\tdocument.querySelector('#item_count_' + id).value = max_count;\r\n"
        + "\t\t\t\t\tdocument.getElementById(\"total_price_span\").textContent = main_total_price;\r\n"
        + "\t\t\t\t\ttotal_price += price * max_count;\r\n"
        + "\t\t\t}\r\n"
        + "\t\t\telse\r\n"
        + "\t\t\t\t\ttotal_price += price * count;\r\n"
        + "\t});\r\n"
        + "\r\n"
        + "\tdocument.getElementById(\"total_price_span\").textContent = total_price - (total_price / 100) * retention_percentage;\r\n"
        + "}\r\n"
        + "\r\n"
        + "function confirm_return() {\r\n"
        + "\t\tjQuery(\"#btn_confirm_return\").prop('disabled', true);\r\n"
        + "    let ids = getItemsIdsFromUrl();\r\n"
        + "    let count_need_arr = {};\r\n"
        + "    ids.forEach((item_id) => {\r\n"
        + "        count_need_arr[item_id] = document.querySelector('#item_count_' + item_id).value;\r\n"
        + "    });\r\n"
        + "\r\n"
        + "    let total_sum = document.querySelector('#total_price_span').textContent;\r\n"
        + "\r\n"
        + "    total_file_size = 0;\r\n"
        + "    let flag = true;\r\n"
        + "    let message = \"\";\r\n"
        + "    let forms = document.querySelectorAll('.return_options_data');\r\n"
        + "    forms.forEach(el => {\r\n"
        + "        let check_obj = check_return_data(el);\r\n"
        + "        if (check_obj.status === false)\r\n"
        + "        {\r\n"
        + "            flag = false;\r\n"
        + "            message = check_obj.message;\r\n"
        + "        }\r\n"
        + "    });\r\n"
        + "\r\n"
        + "\t\tif (flag) {\r\n"
        + "\t\t\tfetchDataReturn(forms, count_need_arr, total_sum);\r\n"
        + "\t\t}\r\n"
        + "\telse\r\n"
        + "\t{\r\n"
        + "\t\t\t alert(message);\r\n"
        + "\t\t\tjQuery(\"#btn_confirm_return\").prop('disabled', false);\r\n"
        + "\t}\r\n"
        + "}";
}
