using EcomAE.Platform.Data;
using EcomAE.Platform.Migration;
using Xunit;

namespace EcomAE.Platform.Tests;

public sealed class SurfaceDashboardSummaryReporterTests
{
    [Fact]
    public async Task BuildReturnsMigrationPlaceholderWhenDbUnavailable()
    {
        var reporter = new SurfaceDashboardSummaryReporter(new UnconfiguredFactory());
        var cp = await reporter.BuildControlPanelAsync();
        var erp = await reporter.BuildErpAsync();
        var bos = await reporter.BuildBosAsync();
        var tenants = await reporter.ListPortalTenantsAsync(10);
        var health = await reporter.BuildBosFleetHealthAsync(5);
        var accounts = await reporter.BuildErpAccountsAsync();
        var orders = await reporter.ListStorefrontOrdersAsync(9, 10);
        var cpOrders = await reporter.ListCpOrdersAsync(10);
        var users = await reporter.ListCpUsersAsync(10);
        var groups = await reporter.ListCpGroupsAsync(10);
        var suppliers = await reporter.ListErpSuppliersAsync(10);
        var purchases = await reporter.ListErpPurchasesAsync(10);
        var garage = await reporter.ListStorefrontGarageAsync(9, 10);
        var cashAccounts = await reporter.ListErpCashAccountsAsync(10);
        var profile = await reporter.BuildStorefrontProfileAsync(9);
        var cashEntries = await reporter.ListErpCashEntriesAsync(null, 10);
        var invoices = await reporter.ListErpInvoicesAsync(10);
        var journals = await reporter.ListErpGlJournalsAsync(10);
        var modules = await reporter.ListCpModulesAsync(10);
        var configItems = await reporter.ListCpConfigItemsMetaAsync(10);
        var readiness = await reporter.BuildBosFleetReadinessAsync();
        var coa = await reporter.ListErpCoaAccountsAsync(10);
        var warehouses = await reporter.ListErpWarehousesAsync(10);
        var salesOrders = await reporter.ListErpSalesOrdersAsync(10);
        var menus = await reporter.ListCpMenusAsync(10);
        var pages = await reporter.ListCpPagesAsync(10);
        var adminSessions = await reporter.ListCpAdminSessionsAsync(10);
        var storages = await reporter.ListCpStoragesAsync(10);
        var audit = await reporter.ListBosAuditLogAsync(null, 10);
        var purchaseOrders = await reporter.ListErpPurchaseOrdersAsync(10);
        var inventoryStock = await reporter.BuildErpInventoryStockSummaryAsync();
        var currencies = await reporter.ListCpCurrenciesAsync(10);
        var apiClients = await reporter.ListCpApiClientsMetaAsync(10);
        var powerBi = await reporter.BuildCpPowerBiDigestAsync(10);
        var mobileApps = await reporter.BuildCpMobileAppsDigestAsync();
        var metabase = await reporter.BuildCpMetabaseDigestAsync(10);
        var nlReporting = await reporter.ListCpNlReportDefinitionsAsync(10);
        var marketing = await reporter.BuildCpMarketingBroadcastDigestAsync(10);
        var demoTenants = await reporter.ListCpDemoTenantsAsync(10);
        var partsAgent = await reporter.BuildCpPartsAgentDigestAsync(10);
        var posOverview = await reporter.BuildCpPosOverviewDigestAsync(10);
        var taxToolkits = await reporter.BuildCpTaxToolkitsDigestAsync(10);
        var smsWhatsapp = await reporter.BuildCpSmsWhatsappDigestAsync(10);
        var crmBoard = await reporter.BuildCpCrmBoardDigestAsync(10);
        var documentControl = await reporter.BuildCpDocumentControlDigestAsync(10);
        var deliveryMethods = await reporter.BuildCpDeliveryMethodsDigestAsync(10);
        var crosses = await reporter.BuildCpCrossesDigestAsync(10);
        var hrOverview = await reporter.BuildCpHrOverviewDigestAsync(10);
        var productionOverview = await reporter.BuildCpProductionOverviewDigestAsync(10);
        var projectsOverview = await reporter.BuildCpProjectsOverviewDigestAsync(10);
        var industryPacks = await reporter.BuildCpIndustryPacksDigestAsync(10);
        var jewelleryRetail = await reporter.BuildCpJewelleryRetailDigestAsync(10);
        var priceLists = await reporter.BuildCpPriceListsDigestAsync(10);
        var autoPrice = await reporter.BuildCpAutoPriceDigestAsync(10);
        var uaeTax = await reporter.BuildCpUaeTaxComplianceDigestAsync(10);
        var budgets = await reporter.BuildCpBudgetsDigestAsync(10);
        var carriers = await reporter.BuildCpCarriersDigestAsync(10);
        var paymentGateways = await reporter.BuildCpPaymentGatewaysDigestAsync(10);
        var workflows = await reporter.BuildCpWorkflowsDigestAsync(10);
        var purchaseRequests = await reporter.BuildCpPurchaseRequestsDigestAsync(10);
        var promotions = await reporter.BuildCpPromotionsDigestAsync(10);
        var crmOpportunities = await reporter.BuildCpCrmOpportunitiesDigestAsync(10);
        var integrations = await reporter.BuildCpIntegrationsDigestAsync(10);
        var partSearchEmpty = await reporter.SearchStorefrontPartsAsync("", 10);
        var partSearch = await reporter.SearchStorefrontPartsAsync("0986424590", 10);
        var cartRejected = await reporter.ListStorefrontCartAsync(0, 10);
        var cart = await reporter.ListStorefrontCartAsync(9, 10);

        Assert.Equal("empty", partSearchEmpty.Source);
        Assert.Equal("migration", partSearch.Source);
        Assert.Equal("rejected", cartRejected.Source);
        Assert.Equal("migration", cart.Source);
        Assert.Equal("migration", cp.Source);
        Assert.Equal("migration", erp.Source);
        Assert.Equal("migration", bos.Source);
        Assert.Equal("migration", tenants.Source);
        Assert.Equal("migration", health.Source);
        Assert.Equal("migration", accounts.Source);
        Assert.Equal("migration", orders.Source);
        Assert.Equal("migration", cpOrders.Source);
        Assert.Equal(0, cpOrders.Summary.Open);
        Assert.Empty(cpOrders.Orders);
        Assert.Equal("migration", users.Source);
        Assert.Equal("migration", groups.Source);
        Assert.Equal("migration", suppliers.Source);
        Assert.Equal("migration", purchases.Source);
        Assert.Equal("migration", garage.Source);
        Assert.Equal("migration", cashAccounts.Source);
        Assert.Equal("migration", profile.Source);
        Assert.Equal("migration", cashEntries.Source);
        Assert.Equal("migration", invoices.Source);
        Assert.Equal("migration", journals.Source);
        Assert.Equal("migration", modules.Source);
        Assert.Equal("migration", configItems.Source);
        Assert.Equal("migration", readiness.Source);
        Assert.Equal("migration", coa.Source);
        Assert.Equal("migration", warehouses.Source);
        Assert.Equal("migration", salesOrders.Source);
        Assert.Equal("migration", menus.Source);
        Assert.Equal("migration", pages.Source);
        Assert.Equal("migration", adminSessions.Source);
        Assert.Equal("migration", storages.Source);
        Assert.Equal("migration", audit.Source);
        Assert.Equal("migration", purchaseOrders.Source);
        Assert.Equal("migration", inventoryStock.Source);
        Assert.Equal("migration", currencies.Source);
        Assert.Equal("migration", apiClients.Source);
        Assert.Equal("migration", powerBi.Source);
        Assert.Equal("migration", mobileApps.Source);
        Assert.Equal("migration", metabase.Source);
        Assert.Equal("migration", nlReporting.Source);
        Assert.Equal("migration", marketing.Source);
        Assert.Equal("migration", demoTenants.Source);
        Assert.Equal("migration", partsAgent.Source);
        Assert.Equal("migration", posOverview.Source);
        Assert.Equal("migration", taxToolkits.Source);
        Assert.Equal("migration", smsWhatsapp.Source);
        Assert.Equal("migration", crmBoard.Source);
        Assert.Equal("migration", documentControl.Source);
        Assert.Equal("migration", deliveryMethods.Source);
        Assert.Equal("migration", crosses.Source);
        Assert.Equal("migration", hrOverview.Source);
        Assert.Equal("migration", productionOverview.Source);
        Assert.Equal("migration", projectsOverview.Source);
        Assert.Equal("migration", industryPacks.Source);
        Assert.Equal("migration", jewelleryRetail.Source);
        Assert.Equal("migration", priceLists.Source);
        Assert.Equal("migration", autoPrice.Source);
        Assert.Equal("migration", uaeTax.Source);
        Assert.Equal("migration", budgets.Source);
        Assert.Equal("migration", carriers.Source);
        Assert.Equal("migration", paymentGateways.Source);
        Assert.Equal("migration", workflows.Source);
        Assert.Equal("migration", purchaseRequests.Source);
        Assert.Equal("migration", promotions.Source);
        Assert.Equal("migration", crmOpportunities.Source);
        Assert.Equal("migration", integrations.Source);
        Assert.Equal(0, cp.Users);
        Assert.Equal(0m, erp.CashPosition);
        Assert.Empty(tenants.Tenants);
        Assert.Empty(orders.Orders);
        Assert.Empty(users.Users);
        Assert.Empty(garage.Vehicles);
        Assert.Empty(cashAccounts.Accounts);
        Assert.Empty(cashEntries.Entries);
        Assert.Empty(journals.Journals);

        var account = await reporter.BuildStorefrontAccountAsync(9);
        Assert.Equal("migration", account.Source);
        Assert.Equal(9, account.UserId);
        Assert.Equal(0, account.GarageVehicles);
    }

    [Fact]
    public void LegacySqlIsSelectOnlyAndUsesErpTables()
    {
        Assert.StartsWith("SELECT", LegacySurfaceDashboardSql.CountUsers.Trim(), StringComparison.OrdinalIgnoreCase);
        Assert.Contains("epc_erp_cash_bank_accounts", LegacySurfaceDashboardSql.SumCashBankTotal, StringComparison.Ordinal);
        Assert.Contains("epc_portal_tenants", LegacySurfaceDashboardSql.SelectPortalTenants, StringComparison.Ordinal);
        Assert.Contains("shop_orders", LegacySurfaceDashboardSql.SelectCustomerOrders, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_garage", LegacySurfaceDashboardSql.SelectCustomerGarage, StringComparison.Ordinal);
        Assert.Contains("epc_erp_purchases", LegacySurfaceDashboardSql.SelectErpPurchases, StringComparison.Ordinal);
        Assert.Contains("epc_erp_cash_bank_accounts", LegacySurfaceDashboardSql.SelectErpCashAccounts, StringComparison.Ordinal);
        Assert.Contains("users_profiles", LegacySurfaceDashboardSql.SelectStorefrontUserProfiles, StringComparison.Ordinal);
        Assert.Contains("epc_erp_gl_journals", LegacySurfaceDashboardSql.SelectErpGlJournals, StringComparison.Ordinal);
        Assert.Contains("epc_einvoice_documents", LegacySurfaceDashboardSql.SelectErpInvoices, StringComparison.Ordinal);
        Assert.Contains("config_items", LegacySurfaceDashboardSql.SelectCpConfigItemsMeta, StringComparison.Ordinal);
        Assert.Contains("epc_erp_coa_accounts", LegacySurfaceDashboardSql.SelectErpCoaAccounts, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_warehouses", LegacySurfaceDashboardSql.SelectErpWarehouses, StringComparison.Ordinal);
        Assert.Contains("epc_erp_sales_orders", LegacySurfaceDashboardSql.SelectErpSalesOrders, StringComparison.Ordinal);
        Assert.Contains("epc_boc_audit", LegacySurfaceDashboardSql.SelectBosAuditLog, StringComparison.Ordinal);
        Assert.Contains("shop_storages", LegacySurfaceDashboardSql.SelectCpStorages, StringComparison.Ordinal);
        Assert.Contains("epc_erp_purchase_orders", LegacySurfaceDashboardSql.SelectErpPurchaseOrders, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_stock", LegacySurfaceDashboardSql.SelectErpInventoryStockSummary, StringComparison.Ordinal);
        Assert.Contains("shop_currencies", LegacySurfaceDashboardSql.SelectCpCurrencies, StringComparison.Ordinal);
        Assert.Contains("epc_api_clients", LegacySurfaceDashboardSql.SelectCpApiClientsMeta, StringComparison.Ordinal);
        Assert.Contains("epc_power_bi_config", LegacySurfaceDashboardSql.SelectCpPowerBiConfig, StringComparison.Ordinal);
        Assert.Contains("epc_power_bi_reports", LegacySurfaceDashboardSql.SelectCpPowerBiReports, StringComparison.Ordinal);
        Assert.Contains("integrations_json", LegacySurfaceDashboardSql.SelectCpMobileAppsIntegrationsJson, StringComparison.Ordinal);
        Assert.Contains("epc_metabase_config", LegacySurfaceDashboardSql.SelectCpMetabaseConfig, StringComparison.Ordinal);
        Assert.Contains("epc_metabase_dashboards", LegacySurfaceDashboardSql.SelectCpMetabaseDashboards, StringComparison.Ordinal);
        Assert.DoesNotContain("secret_key", LegacySurfaceDashboardSql.SelectCpMetabaseConfig, StringComparison.Ordinal);
        Assert.Contains("epc_report_definitions", LegacySurfaceDashboardSql.SelectCpNlReportDefinitions, StringComparison.Ordinal);
        Assert.DoesNotContain("query_template", LegacySurfaceDashboardSql.SelectCpNlReportDefinitions, StringComparison.Ordinal);
        Assert.Contains("epc_marketing_broadcast_campaigns", LegacySurfaceDashboardSql.SelectCpMarketingBroadcastCampaigns, StringComparison.Ordinal);
        Assert.DoesNotContain("body_html", LegacySurfaceDashboardSql.SelectCpMarketingBroadcastCampaigns, StringComparison.Ordinal);
        Assert.Contains("is_demo", LegacySurfaceDashboardSql.SelectCpDemoTenants, StringComparison.Ordinal);
        Assert.DoesNotContain("password", LegacySurfaceDashboardSql.SelectCpDemoTenants, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("epc_parts_agent_session", LegacySurfaceDashboardSql.SelectCpPartsAgentSessions, StringComparison.Ordinal);
        Assert.DoesNotContain("system_prompt", LegacySurfaceDashboardSql.SelectCpPartsAgentConfig, StringComparison.Ordinal);
        Assert.DoesNotContain("client_ip", LegacySurfaceDashboardSql.SelectCpPartsAgentSessions, StringComparison.Ordinal);
        Assert.Contains("epc_pos_sales", LegacySurfaceDashboardSql.SelectCpPosSales, StringComparison.Ordinal);
        Assert.Contains("epc_tax_toolkits", LegacySurfaceDashboardSql.SelectCpTaxToolkits, StringComparison.Ordinal);
        Assert.DoesNotContain("rules_json", LegacySurfaceDashboardSql.SelectCpTaxToolkits, StringComparison.Ordinal);
        Assert.DoesNotContain("reg_number", LegacySurfaceDashboardSql.SelectCpTaxTenantProfile, StringComparison.Ordinal);
        Assert.Contains("sms_api", LegacySurfaceDashboardSql.SelectCpSmsOperators, StringComparison.Ordinal);
        Assert.DoesNotContain("parameters_values", LegacySurfaceDashboardSql.SelectCpSmsOperators, StringComparison.Ordinal);
        Assert.Contains("phone_masked", LegacySurfaceDashboardSql.SelectCpWhatsappNotifyLog, StringComparison.Ordinal);
        Assert.DoesNotContain("`response`", LegacySurfaceDashboardSql.SelectCpWhatsappNotifyLog, StringComparison.Ordinal);
        Assert.Contains("epc_crm_leads", LegacySurfaceDashboardSql.SelectCpCrmLeads, StringComparison.Ordinal);
        Assert.DoesNotContain("email", LegacySurfaceDashboardSql.SelectCpCrmLeads, StringComparison.Ordinal);
        Assert.Contains("epc_jewel_voucher", LegacySurfaceDashboardSql.SelectCpJewelleryVouchers, StringComparison.Ordinal);
        Assert.DoesNotContain("passport", LegacySurfaceDashboardSql.SelectCpJewelleryVouchers, StringComparison.Ordinal);
        Assert.DoesNotContain("mobile", LegacySurfaceDashboardSql.SelectCpJewelleryVouchers, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("epc_pl_lists", LegacySurfaceDashboardSql.SelectCpPriceLists, StringComparison.Ordinal);
        Assert.DoesNotContain("stats_json", LegacySurfaceDashboardSql.SelectCpPriceLists, StringComparison.Ordinal);
        Assert.Contains("epc_auto_price_rules", LegacySurfaceDashboardSql.SelectCpAutoPriceRules, StringComparison.Ordinal);
        Assert.DoesNotContain("config_json", LegacySurfaceDashboardSql.SelectCpAutoPriceRules, StringComparison.Ordinal);
        Assert.DoesNotContain("notes", LegacySurfaceDashboardSql.SelectCpAutoPriceRules, StringComparison.Ordinal);
        Assert.Contains("epc_uae_tax_legislation_items", LegacySurfaceDashboardSql.SelectCpUaeTaxItems, StringComparison.Ordinal);
        Assert.DoesNotContain("erp_summary", LegacySurfaceDashboardSql.SelectCpUaeTaxItems, StringComparison.Ordinal);
        Assert.DoesNotContain("pdf_url", LegacySurfaceDashboardSql.SelectCpUaeTaxItems, StringComparison.Ordinal);
        Assert.Contains("epc_erp_pm_budgets", LegacySurfaceDashboardSql.SelectCpBudgets, StringComparison.Ordinal);
        Assert.DoesNotContain("`note`", LegacySurfaceDashboardSql.SelectCpBudgets, StringComparison.Ordinal);
        Assert.Contains("epc_erp_carriers", LegacySurfaceDashboardSql.SelectCpCarriers, StringComparison.Ordinal);
        Assert.DoesNotContain("contact_phone", LegacySurfaceDashboardSql.SelectCpCarriers, StringComparison.Ordinal);
        Assert.DoesNotContain("contact_email", LegacySurfaceDashboardSql.SelectCpCarriers, StringComparison.Ordinal);
        Assert.Contains("shop_payment_systems", LegacySurfaceDashboardSql.SelectCpPaymentGateways, StringComparison.Ordinal);
        Assert.DoesNotContain("parameters_values", LegacySurfaceDashboardSql.SelectCpPaymentGateways, StringComparison.Ordinal);
        Assert.Contains("epc_workflows", LegacySurfaceDashboardSql.SelectCpWorkflows, StringComparison.Ordinal);
        Assert.DoesNotContain("trigger_config", LegacySurfaceDashboardSql.SelectCpWorkflows, StringComparison.Ordinal);
        Assert.Contains("epc_proc_req", LegacySurfaceDashboardSql.SelectCpPurchaseRequests, StringComparison.Ordinal);
        Assert.DoesNotContain("justification", LegacySurfaceDashboardSql.SelectCpPurchaseRequests, StringComparison.Ordinal);
        Assert.DoesNotContain("decision_note", LegacySurfaceDashboardSql.SelectCpPurchaseRequests, StringComparison.Ordinal);
        Assert.Contains("epc_promo_promotions", LegacySurfaceDashboardSql.SelectCpPromotions, StringComparison.Ordinal);
        Assert.Contains("epc_crm_opportunities", LegacySurfaceDashboardSql.SelectCpCrmOpportunities, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectCpCrmOpportunities, StringComparison.Ordinal);
        Assert.Contains("epc_webhooks", LegacySurfaceDashboardSql.SelectCpIntegrations, StringComparison.Ordinal);
        Assert.DoesNotContain("secret_hash", LegacySurfaceDashboardSql.SelectCpIntegrations, StringComparison.Ordinal);
        Assert.DoesNotContain("secret_encrypted", LegacySurfaceDashboardSql.SelectCpIntegrations, StringComparison.Ordinal);
        Assert.DoesNotContain("`events`", LegacySurfaceDashboardSql.SelectCpIntegrations, StringComparison.Ordinal);
        Assert.Contains("epc_document_templates", LegacySurfaceDashboardSql.SelectCpDocumentTemplates, StringComparison.Ordinal);
        Assert.DoesNotContain("header_html", LegacySurfaceDashboardSql.SelectCpDocumentTemplates, StringComparison.Ordinal);
        Assert.Contains("shop_obtaining_modes", LegacySurfaceDashboardSql.SelectCpDeliveryModes, StringComparison.Ordinal);
        Assert.DoesNotContain("parameters_values", LegacySurfaceDashboardSql.SelectCpDeliveryModes, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_articles_analogs_list", LegacySurfaceDashboardSql.SelectCpCrossPairs, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_prices_data", LegacySurfaceDashboardSql.SelectStorefrontPartSearch, StringComparison.Ordinal);
        Assert.Contains("article_search", LegacySurfaceDashboardSql.SelectStorefrontPartSearch, StringComparison.Ordinal);
        Assert.Contains("shop_carts", LegacySurfaceDashboardSql.SelectStorefrontCartSummary, StringComparison.Ordinal);
        Assert.Contains("shop_carts", LegacySurfaceDashboardSql.SelectStorefrontCartLines, StringComparison.Ordinal);
        Assert.DoesNotContain("DELETE", LegacySurfaceDashboardSql.SelectStorefrontCartLines, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("client_key_hash", LegacySurfaceDashboardSql.SelectCpApiClientsMeta, StringComparison.Ordinal);
        Assert.DoesNotContain("`session`", LegacySurfaceDashboardSql.SelectCpAdminSessions, StringComparison.Ordinal);
        Assert.DoesNotContain("INSERT", LegacySurfaceDashboardSql.SumSupplierCredit, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("UPDATE", LegacySurfaceDashboardSql.SelectPortalTenants, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("DELETE", LegacySurfaceDashboardSql.SelectCustomerOrders, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("DELETE", LegacySurfaceDashboardSql.SelectCpUsers, StringComparison.OrdinalIgnoreCase);
    }

    private sealed class UnconfiguredFactory : ITenantDbConnectionFactory
    {
        public bool IsConfigured => false;

        public Task<System.Data.Common.DbConnection> OpenAsync(string? databaseName, CancellationToken cancellationToken = default)
            => throw new InvalidOperationException("not configured");
    }
}
