using EcomAE.Platform.Data;
using EcomAE.Platform.Migration;
using Xunit;

namespace EcomAE.Platform.Tests;

public sealed class SurfaceDashboardSummaryReporterTests
{
    [Fact]
    public async Task BuildReturnsMigrationPlaceholderWhenDbUnavailable()
    {
        var reporter = new SurfaceDashboardSummaryReporter(new UnconfiguredFactory());
        var cp = await reporter.BuildControlPanelAsync();
        var erpDigest = await reporter.BuildErpAsync();
        var erp = erpDigest.Summary;
        var bos = await reporter.BuildBosAsync();
        var tenants = await reporter.ListPortalTenantsAsync(10);
        var health = await reporter.BuildBosFleetHealthAsync(5);
        var accounts = await reporter.BuildErpAccountsAsync();
        var orders = await reporter.ListStorefrontOrdersAsync(9, 10);
        var cpOrders = await reporter.ListCpOrdersAsync(10);
        var users = await reporter.ListCpUsersAsync(10);
        var groups = await reporter.ListCpGroupsAsync(10);
        var suppliers = await reporter.ListErpSuppliersAsync(10);
        var purchases = await reporter.ListErpPurchasesAsync(10);
        var garage = await reporter.ListStorefrontGarageAsync(9, 10);
        var cashAccounts = await reporter.ListErpCashAccountsAsync(10);
        var profile = await reporter.BuildStorefrontProfileAsync(9);
        var cashEntries = await reporter.ListErpCashEntriesAsync(null, 10);
        var invoices = await reporter.ListErpInvoicesAsync(10);
        var journals = await reporter.ListErpGlJournalsAsync(10);
        var modules = await reporter.ListCpModulesAsync(10);
        var configItems = await reporter.ListCpConfigItemsMetaAsync(10);
        var readiness = await reporter.BuildBosFleetReadinessAsync();
        var coa = await reporter.ListErpCoaAccountsAsync(10);
        var warehouses = await reporter.ListErpWarehousesAsync(10);
        var salesOrders = await reporter.ListErpSalesOrdersAsync(10);
        var deliveryNotes = await reporter.ListErpDeliveryNotesAsync(10);
        var rfqs = await reporter.ListErpRfqsAsync(10);
        var threeWay = await reporter.ListErpThreeWayMatchAsync(10);
        var contacts = await reporter.ListErpContactsAsync(10);
        var paymentBatches = await reporter.ListErpPaymentBatchesAsync(10);
        var fiscalPeriods = await reporter.ListErpFiscalPeriodsAsync(10);
        var agenda = await reporter.ListErpAgendaEventsAsync(10);
        var documents = await reporter.ListErpDocumentsAsync(10);
        var expenseReports = await reporter.ListErpExpenseReportsAsync(10);
        var menus = await reporter.ListCpMenusAsync(10);
        var pages = await reporter.ListCpPagesAsync(10);
        var adminSessions = await reporter.ListCpAdminSessionsAsync(10);
        var storages = await reporter.ListCpStoragesAsync(10);
        var audit = await reporter.ListBosAuditLogAsync(null, 10);
        var purchaseOrders = await reporter.ListErpPurchaseOrdersAsync(10);
        var inventoryStock = await reporter.BuildErpInventoryStockDigestAsync(10);
        var currencies = await reporter.ListCpCurrenciesAsync(10);
        var apiClients = await reporter.ListCpApiClientsMetaAsync(10);
        var powerBi = await reporter.BuildCpPowerBiDigestAsync(10);
        var mobileApps = await reporter.BuildCpMobileAppsDigestAsync();
        var metabase = await reporter.BuildCpMetabaseDigestAsync(10);
        var nlReporting = await reporter.ListCpNlReportDefinitionsAsync(10);
        var marketing = await reporter.BuildCpMarketingBroadcastDigestAsync(10);
        var demoTenants = await reporter.ListCpDemoTenantsAsync(10);
        var partsAgent = await reporter.BuildCpPartsAgentDigestAsync(10);
        var posOverview = await reporter.BuildCpPosOverviewDigestAsync(10);
        var taxToolkits = await reporter.BuildCpTaxToolkitsDigestAsync(10);
        var smsWhatsapp = await reporter.BuildCpSmsWhatsappDigestAsync(10);
        var crmBoard = await reporter.BuildCpCrmBoardDigestAsync(10);
        var documentControl = await reporter.BuildCpDocumentControlDigestAsync(10);
        var deliveryMethods = await reporter.BuildCpDeliveryMethodsDigestAsync(10);
        var crosses = await reporter.BuildCpCrossesDigestAsync(10);
        var hrOverview = await reporter.BuildCpHrOverviewDigestAsync(10);
        var productionOverview = await reporter.BuildCpProductionOverviewDigestAsync(10);
        var projectsOverview = await reporter.BuildCpProjectsOverviewDigestAsync(10);
        var industryPacks = await reporter.BuildCpIndustryPacksDigestAsync(10);
        var jewelleryRetail = await reporter.BuildCpJewelleryRetailDigestAsync(10);
        var priceLists = await reporter.BuildCpPriceListsDigestAsync(10);
        var docpartPrices = await reporter.BuildCpDocpartPriceListsDigestAsync(10);
        var docpartDetail = await reporter.BuildCpDocpartPriceListDetailAsync(1);
        var autoPrice = await reporter.BuildCpAutoPriceDigestAsync(10);
        var uaeTax = await reporter.BuildCpUaeTaxComplianceDigestAsync(10);
        var budgets = await reporter.BuildCpBudgetsDigestAsync(10);
        var carriers = await reporter.BuildCpCarriersDigestAsync(10);
        var paymentGateways = await reporter.BuildCpPaymentGatewaysDigestAsync(10);
        var workflows = await reporter.BuildCpWorkflowsDigestAsync(10);
        var purchaseRequests = await reporter.BuildCpPurchaseRequestsDigestAsync(10);
        var promotions = await reporter.BuildCpPromotionsDigestAsync(10);
        var crmOpportunities = await reporter.BuildCpCrmOpportunitiesDigestAsync(10);
        var integrations = await reporter.BuildCpIntegrationsDigestAsync(10);
        var bankRecon = await reporter.BuildErpBankReconciliationDigestAsync(10);
        var stockTransfers = await reporter.BuildErpStockTransfersDigestAsync(10);
        var salesQuotations = await reporter.BuildErpSalesQuotationsDigestAsync(10);
        var workspaceFavorites = await reporter.BuildErpWorkspaceFavoritesDigestAsync(10);
        var fixedAssets = await reporter.BuildErpFixedAssetsDigestAsync(10);
        var processFlowTasks = await reporter.BuildErpProcessFlowTasksDigestAsync(10);
        var workflowTasks = await reporter.BuildErpWorkflowTasksDigestAsync(10);
        var vatReturn = await reporter.BuildErpVatReturnDigestAsync();
        var withholding = await reporter.BuildErpWithholdingDigestAsync(10);
        var pettyCash = await reporter.ListErpPettyCashAsync(10);
        var cashForecast = await reporter.BuildErpCashForecastDigestAsync(10);
        var bankInstruments = await reporter.BuildErpBankInstrumentsDigestAsync(10);
        var subscriptions = await reporter.BuildErpSubscriptionsDigestAsync(10);
        var supplierPortal = await reporter.BuildErpSupplierPortalDigestAsync(10);
        var virtualWarehouse = await reporter.BuildErpVirtualWarehouseDigestAsync(10);
        var staff = await reporter.ListErpStaffAsync(10);
        var hrRecords = await reporter.ListErpHrRecordsAsync(10);
        var contracts = await reporter.ListErpContractsAsync(10);
        var opening = await reporter.ListErpOpeningBatchesAsync(10);
        var erpMarketing = await reporter.ListErpMarketingCampaignsAsync(10);
        var payroll = await reporter.ListErpPayrollRunsAsync(10);
        var printTemplates = await reporter.ListErpPrintTemplatesAsync(10);
        var orderPlanning = await reporter.BuildErpOrderPlanningDigestAsync(10);
        var procCategories = await reporter.BuildErpProcurementCategoriesDigestAsync(10);
        var erpQuality = await reporter.BuildErpQualityDigestAsync(10);
        var erpRfid = await reporter.BuildErpRfidDigestAsync(10);
        var recruitment = await reporter.BuildErpRecruitmentDigestAsync(10);
        var customerGroups = await reporter.ListErpCustomerGroupsAsync(10);
        var performance = await reporter.BuildErpPerformanceDigestAsync(10);
        var productInfo = await reporter.BuildErpProductInfoDigestAsync(10);
        var reportScheduler = await reporter.BuildErpReportSchedulerDigestAsync(10);
        var projectAccounting = await reporter.BuildErpProjectAccountingDigestAsync(10);
        var docAttachments = await reporter.ListErpDocAttachmentsAsync(10);
        var inventoryReport = await reporter.BuildErpInventoryReportDigestAsync(10);
        var reportCenter = await reporter.BuildErpReportCenterDigestAsync(null, 10);
        var aging = await reporter.BuildErpAgingDigestAsync(10);
        var receivables = await reporter.BuildErpReceivablesDigestAsync(10);
        var stockMovements = await reporter.BuildErpInventoryMovementsDigestAsync(10);
        var pageBuilder = await reporter.BuildCpPageBuilderDigestAsync(10);
        var productCatalogue = await reporter.BuildCpProductCatalogueDigestAsync(10);
        var platformGovernance = await reporter.BuildCpPlatformGovernanceDigestAsync(10);
        var einvoiceDocuments = await reporter.BuildCpEinvoiceDocumentsDigestAsync(10);
        var jewelleryRepairs = await reporter.BuildCpJewelleryRepairsDigestAsync(10);
        var crmTickets = await reporter.BuildCpCrmTicketsDigestAsync(10);
        var marketingGrowth = await reporter.BuildCpMarketingGrowthDigestAsync(10);
        var soc2Compliance = await reporter.BuildCpSoc2ComplianceDigestAsync(10);
        var costModels = await reporter.BuildCpCostModelsDigestAsync(10);
        var finAdvanced = await reporter.BuildCpFinAdvancedDigestAsync(10);
        var blockchainProofs = await reporter.BuildCpBlockchainProofsDigestAsync(10);
        var landedCost = await reporter.BuildCpLandedCostDigestAsync(10);
        var warehouseWms = await reporter.BuildCpWarehouseWmsDigestAsync(10);
        var aiService = await reporter.BuildCpAiServiceDigestAsync(10);
        var returnsRma = await reporter.BuildCpReturnsRmaDigestAsync(10);
        var isolationAudit = await reporter.BuildCpIsolationAuditDigestAsync(10);
        var amlCompliance = await reporter.BuildCpAmlComplianceDigestAsync(10);
        var jewelleryMasters = await reporter.BuildCpJewelleryMastersDigestAsync(10);
        var consolidations = await reporter.BuildCpConsolidationsDigestAsync(10);
        var crmActivities = await reporter.BuildCpCrmActivitiesDigestAsync(10);
        var authMfa = await reporter.BuildCpAuthMfaDigestAsync(10);
        var electronicReporting = await reporter.BuildCpElectronicReportingDigestAsync(10);
        var collectionsDunning = await reporter.BuildCpCollectionsDunningDigestAsync(10);
        var marketplaceChannels = await reporter.BuildCpMarketplaceChannelsDigestAsync(10);
        var demandIntelligence = await reporter.BuildCpDemandIntelligenceDigestAsync(10);
        var creditLimits = await reporter.BuildCpCreditLimitsDigestAsync(10);
        var insuranceCompliance = await reporter.BuildCpInsuranceComplianceDigestAsync(10);
        var auditTrail = await reporter.BuildCpAuditTrailDigestAsync(10);
        var docExpiry = await reporter.BuildCpDocExpiryDigestAsync(10);
        var tenantConfig = await reporter.BuildCpTenantConfigDigestAsync(10);
        var jewelStockVerification = await reporter.BuildCpJewelleryStockVerificationDigestAsync(10);
        var taxExternalReporting = await reporter.BuildCpTaxExternalReportingDigestAsync(10);
        var poApprovals = await reporter.BuildCpPoApprovalsDigestAsync(10);
        var financeClose = await reporter.BuildCpFinanceCloseDigestAsync(10);
        var jewelleryFixing = await reporter.BuildCpJewelleryFixingDigestAsync(10);
        var webTracker = await reporter.BuildCpWebTrackerDigestAsync(10);
        var statistics = await reporter.BuildCpStatisticsDigestAsync(10);
        var accessories = await reporter.BuildCpAccessoriesDigestAsync(10);
        var synonyms = await reporter.BuildCpSynonymsDigestAsync(10);
        var seo = await reporter.BuildCpSeoDigestAsync(10);
        var socialHub = await reporter.BuildCpSocialHubDigestAsync(10);
        var tenantFeatures = await reporter.BuildCpTenantFeaturesDigestAsync(10);
        var customerBoard = await reporter.BuildCpCustomerBoardDigestAsync(10);
        var fulfillmentQueue = await reporter.BuildCpFulfillmentQueueDigestAsync(10);
        var fulfillmentDetail = await reporter.GetCpFulfillmentDetailAsync(1);
        var ssoSaml = await reporter.BuildCpSsoSamlDigestAsync(10);
        var eventBus = await reporter.BuildCpEventBusDigestAsync(10);
        var abandonedCarts = await reporter.BuildCpAbandonedCartsDigestAsync(10);
        var quoteRequests = await reporter.BuildCpQuoteRequestsDigestAsync(10);
        var platformCommunication = await reporter.BuildCpPlatformCommunicationDigestAsync(10);
        var infoBlocks = await reporter.BuildCpInfoBlocksDigestAsync(10);
        var freeTools = await reporter.BuildCpFreeToolsDigestAsync(10);
        var configSandbox = await reporter.BuildCpConfigSandboxDigestAsync(10);
        var marketplaceApps = await reporter.BuildCpMarketplaceAppsDigestAsync(10);
        var notifications = await reporter.BuildCpNotificationsDigestAsync(10);
        var portalSettings = await reporter.BuildCpPortalSettingsDigestAsync(10);
        var dataMigrations = await reporter.BuildCpDataMigrationsDigestAsync(10);
        var partSearchEmpty = await reporter.SearchStorefrontPartsAsync("", 10);
        var partSearch = await reporter.SearchStorefrontPartsAsync("0986424590", 10);
        var cartRejected = await reporter.ListStorefrontCartAsync(0, 10);
        var cart = await reporter.ListStorefrontCartAsync(9, 10);
        var workspace = await reporter.BuildErpWorkspaceHomeAsync();

        Assert.Equal("empty", partSearchEmpty.Source);
        Assert.Equal("migration", partSearch.Source);
        Assert.Equal("rejected", cartRejected.Source);
        Assert.Equal("migration", cart.Source);
        Assert.Equal("migration", cp.Source);
        Assert.Equal("migration", erp.Source);
        Assert.Equal("migration", workspace.Source);
        Assert.Equal(6, workspace.Trend.Count);
        Assert.Equal(5, workspace.ArAgingLabels.Count);
        Assert.Equal(0, workspace.Alerts.Total);
        Assert.Empty(workspace.TopSuppliers);
        Assert.Equal("migration", bos.Source);
        Assert.Equal("migration", tenants.Source);
        Assert.Equal("migration", health.Source);
        Assert.Equal("migration", accounts.Source);
        Assert.Equal("migration", orders.Source);
        Assert.Equal("migration", cpOrders.Source);
        Assert.Equal(0, cpOrders.Summary.Open);
        Assert.Empty(cpOrders.Orders);
        Assert.Equal("migration", users.Source);
        Assert.Equal("migration", groups.Source);
        Assert.Equal("migration", suppliers.Source);
        Assert.Equal("migration", purchases.Source);
        Assert.Equal("migration", garage.Source);
        Assert.Equal("migration", cashAccounts.Source);
        Assert.Equal("migration", profile.Source);
        Assert.Equal("migration", cashEntries.Source);
        Assert.Equal("migration", invoices.Source);
        Assert.Equal("migration", journals.Source);
        Assert.Equal("migration", modules.Source);
        Assert.Equal("migration", configItems.Source);
        Assert.Equal("migration", readiness.Source);
        Assert.Equal("migration", coa.Source);
        Assert.Equal("migration", warehouses.Source);
        Assert.Equal("migration", salesOrders.Source);
        Assert.Equal("migration", deliveryNotes.Source);
        Assert.Equal("migration", rfqs.Source);
        Assert.Equal("migration", threeWay.Source);
        Assert.Equal("migration", contacts.Source);
        Assert.Equal("migration", paymentBatches.Source);
        Assert.Equal("migration", fiscalPeriods.Source);
        Assert.Equal(0, deliveryNotes.Count);
        Assert.Equal(0, rfqs.Count);
        Assert.Equal(0, threeWay.Count);
        Assert.Equal(0, contacts.Count);
        Assert.Equal(0, paymentBatches.Count);
        Assert.Equal(0, fiscalPeriods.Count);
        Assert.Equal("migration", agenda.Source);
        Assert.Equal("migration", documents.Source);
        Assert.Equal("migration", expenseReports.Source);
        Assert.Equal(0, agenda.Count);
        Assert.Equal(0, documents.Count);
        Assert.Equal(0, expenseReports.Count);
        Assert.Equal("migration", menus.Source);
        Assert.Equal("migration", pages.Source);
        Assert.Equal("migration", adminSessions.Source);
        Assert.Equal("migration", storages.Source);
        Assert.Equal("migration", audit.Source);
        Assert.Equal("migration", purchaseOrders.Source);
        Assert.Equal("migration", inventoryStock.Source);
        Assert.Equal("migration", currencies.Source);
        Assert.Equal("migration", apiClients.Source);
        Assert.Equal("migration", powerBi.Source);
        Assert.Equal("migration", mobileApps.Source);
        Assert.Equal("migration", metabase.Source);
        Assert.Equal("migration", nlReporting.Source);
        Assert.Equal("migration", marketing.Source);
        Assert.Equal("migration", demoTenants.Source);
        Assert.Equal("migration", partsAgent.Source);
        Assert.Equal("migration", posOverview.Source);
        Assert.Equal("migration", taxToolkits.Source);
        Assert.Equal("migration", smsWhatsapp.Source);
        Assert.Equal("migration", crmBoard.Source);
        Assert.Equal("migration", documentControl.Source);
        Assert.Equal("migration", deliveryMethods.Source);
        Assert.Equal("migration", crosses.Source);
        Assert.Equal("migration", hrOverview.Source);
        Assert.Equal("migration", productionOverview.Source);
        Assert.Equal("migration", projectsOverview.Source);
        Assert.Equal("migration", industryPacks.Source);
        Assert.Equal("migration", jewelleryRetail.Source);
        Assert.Equal("migration", priceLists.Source);
        Assert.Equal("migration", docpartPrices.Source);
        Assert.Null(docpartDetail);
        Assert.Equal("migration", autoPrice.Source);
        Assert.Equal("migration", uaeTax.Source);
        Assert.Equal("migration", budgets.Source);
        Assert.Equal("migration", carriers.Source);
        Assert.Equal("migration", paymentGateways.Source);
        Assert.Equal("migration", workflows.Source);
        Assert.Equal("migration", purchaseRequests.Source);
        Assert.Equal("migration", promotions.Source);
        Assert.Equal("migration", crmOpportunities.Source);
        Assert.Equal("migration", integrations.Source);
        Assert.Equal("migration", bankRecon.Source);
        Assert.Equal("migration", stockTransfers.Source);
        Assert.Equal("migration", salesQuotations.Source);
        Assert.Equal("migration", workspaceFavorites.Source);
        Assert.Equal("migration", fixedAssets.Source);
        Assert.Equal("migration", processFlowTasks.Source);
        Assert.Equal("migration", workflowTasks.Source);
        Assert.Equal("migration", vatReturn.Source);
        Assert.Equal("migration", withholding.Source);
        Assert.Equal("migration", pettyCash.Source);
        Assert.Equal("migration", cashForecast.Source);
        Assert.Equal("migration", bankInstruments.Source);
        Assert.Equal("migration", subscriptions.Source);
        Assert.Equal("migration", supplierPortal.Source);
        Assert.Equal("migration", virtualWarehouse.Source);
        Assert.Equal("migration", staff.Source);
        Assert.Equal("migration", hrRecords.Source);
        Assert.Empty(hrRecords.Records);
        Assert.Equal("migration", contracts.Source);
        Assert.Equal("migration", opening.Source);
        Assert.Equal("migration", erpMarketing.Source);
        Assert.Equal("migration", payroll.Source);
        Assert.Equal("migration", printTemplates.Source);
        Assert.Equal(0, staff.Count);
        Assert.Equal(0, contracts.Count);
        Assert.Equal(0, opening.Count);
        Assert.Equal(0, erpMarketing.Count);
        Assert.Equal(0, payroll.Count);
        Assert.Equal(0, printTemplates.Count);
        Assert.Equal("migration", orderPlanning.Source);
        Assert.Equal("migration", procCategories.Source);
        Assert.Equal("migration", erpQuality.Source);
        Assert.Equal("migration", erpRfid.Source);
        Assert.Equal("migration", recruitment.Source);
        Assert.Equal("migration", customerGroups.Source);
        Assert.Equal(0, orderPlanning.Count);
        Assert.Equal(0, procCategories.Count);
        Assert.Equal(0, erpQuality.Count);
        Assert.Equal(0, erpRfid.Count);
        Assert.Equal(0, recruitment.Count);
        Assert.Equal(0, customerGroups.Count);
        Assert.Equal("migration", performance.Source);
        Assert.Equal("migration", productInfo.Source);
        Assert.Equal("migration", reportScheduler.Source);
        Assert.Equal("migration", projectAccounting.Source);
        Assert.Equal("migration", docAttachments.Source);
        Assert.Equal("migration", inventoryReport.Source);
        Assert.Equal(0, performance.Count);
        Assert.Equal(0, productInfo.Count);
        Assert.Equal(0, reportScheduler.Count);
        Assert.Equal(0, projectAccounting.Count);
        Assert.Equal(0, docAttachments.Count);
        Assert.Equal(0, inventoryReport.Count);
        Assert.Equal(0, workflowTasks.Count);
        Assert.Equal(0, withholding.Count);
        Assert.Equal(0, pettyCash.Count);
        Assert.Equal(0, subscriptions.Count);
        Assert.Equal("payable_to_fta", vatReturn.Summary.NetStatus);
        Assert.Equal("migration", reportCenter.Source);
        Assert.Equal(33, reportCenter.Summary.ReportCount);
        Assert.Equal(19, reportCenter.Summary.AreaCount);
        Assert.Equal(33, reportCenter.Reports.Count);
        Assert.Equal("migration", aging.Source);
        Assert.Equal("migration", receivables.Source);
        Assert.Equal(0, receivables.Count);
        Assert.Equal("migration", stockMovements.Source);
        Assert.Empty(inventoryStock.LowStock);
        Assert.Equal("migration", pageBuilder.Source);
        Assert.Equal("migration", productCatalogue.Source);
        Assert.Equal("migration", platformGovernance.Source);
        Assert.Equal("migration", einvoiceDocuments.Source);
        Assert.Equal("migration", jewelleryRepairs.Source);
        Assert.Equal("migration", crmTickets.Source);
        Assert.Equal("migration", marketingGrowth.Source);
        Assert.Equal("migration", soc2Compliance.Source);
        Assert.Equal("migration", costModels.Source);
        Assert.Equal("migration", finAdvanced.Source);
        Assert.Equal("migration", blockchainProofs.Source);
        Assert.Equal("migration", landedCost.Source);
        Assert.Equal("migration", isolationAudit.Source);
        Assert.Equal("migration", amlCompliance.Source);
        Assert.Equal("migration", jewelleryMasters.Source);
        Assert.Equal("migration", consolidations.Source);
        Assert.Equal("migration", crmActivities.Source);
        Assert.Equal("migration", authMfa.Source);
        Assert.Equal("migration", electronicReporting.Source);
        Assert.Equal("migration", collectionsDunning.Source);
        Assert.Equal("migration", marketplaceChannels.Source);
        Assert.Equal("migration", demandIntelligence.Source);
        Assert.Equal("migration", creditLimits.Source);
        Assert.Equal("migration", insuranceCompliance.Source);
        Assert.Equal("migration", warehouseWms.Source);
        Assert.Equal("migration", aiService.Source);
        Assert.Equal("migration", returnsRma.Source);
        Assert.Equal("migration", taxExternalReporting.Source);
        Assert.Equal("migration", poApprovals.Source);
        Assert.Equal("migration", financeClose.Source);
        Assert.Equal("migration", jewelleryFixing.Source);
        Assert.Equal("migration", webTracker.Source);
        Assert.Equal("migration", statistics.Source);
        Assert.Equal("migration", accessories.Source);
        Assert.Equal("migration", synonyms.Source);
        Assert.Equal("migration", seo.Source);
        Assert.Equal("migration", socialHub.Source);
        Assert.Equal("migration", tenantFeatures.Source);
        Assert.Equal("migration", customerBoard.Source);
        Assert.Equal("migration", fulfillmentQueue.Source);
        Assert.Null(fulfillmentDetail);
        Assert.Equal("migration", ssoSaml.Source);
        Assert.Equal("migration", eventBus.Source);
        Assert.Equal("migration", abandonedCarts.Source);
        Assert.Equal("migration", quoteRequests.Source);
        Assert.Equal("migration", platformCommunication.Source);
        Assert.Equal("migration", infoBlocks.Source);
        Assert.Equal("migration", freeTools.Source);
        Assert.Equal("migration", configSandbox.Source);
        Assert.Equal("migration", marketplaceApps.Source);
        Assert.Equal("migration", notifications.Source);
        Assert.Equal("migration", portalSettings.Source);
        Assert.Equal("migration", dataMigrations.Source);
        Assert.Equal(0, cp.Users);
        Assert.Equal(0m, erp.CashPosition);
        Assert.Empty(erpDigest.ApprovalQueue);
        Assert.Equal(0, erpDigest.Count);
        Assert.Empty(tenants.Tenants);
        Assert.Empty(orders.Orders);
        Assert.Empty(users.Users);
        Assert.Empty(garage.Vehicles);
        Assert.Empty(cashAccounts.Accounts);
        Assert.Empty(cashEntries.Entries);
        Assert.Empty(journals.Journals);

        var account = await reporter.BuildStorefrontAccountAsync(9);
        Assert.Equal("migration", account.Source);
        Assert.Equal(9, account.Summary.UserId);
        Assert.Equal(0, account.Summary.GarageVehicles);
        Assert.Empty(account.RecentOrders);
        Assert.Equal(0, account.Count);
    }

    [Fact]
    public void LegacySqlIsSelectOnlyAndUsesErpTables()
    {
        Assert.StartsWith("SELECT", LegacySurfaceDashboardSql.CountUsers.Trim(), StringComparison.OrdinalIgnoreCase);
        Assert.Contains("epc_erp_cash_bank_accounts", LegacySurfaceDashboardSql.SumCashBankTotal, StringComparison.Ordinal);
        Assert.Contains("epc_portal_tenants", LegacySurfaceDashboardSql.SelectPortalTenants, StringComparison.Ordinal);
        Assert.Contains("shop_orders", LegacySurfaceDashboardSql.SelectCustomerOrders, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_garage", LegacySurfaceDashboardSql.SelectCustomerGarage, StringComparison.Ordinal);
        Assert.Contains("epc_erp_purchases", LegacySurfaceDashboardSql.SelectErpPurchases, StringComparison.Ordinal);
        Assert.Contains("epc_erp_cash_bank_accounts", LegacySurfaceDashboardSql.SelectErpCashAccounts, StringComparison.Ordinal);
        Assert.Contains("users_profiles", LegacySurfaceDashboardSql.SelectStorefrontUserProfiles, StringComparison.Ordinal);
        Assert.Contains("epc_erp_gl_journals", LegacySurfaceDashboardSql.SelectErpGlJournals, StringComparison.Ordinal);
        Assert.Contains("epc_einvoice_documents", LegacySurfaceDashboardSql.SelectErpInvoices, StringComparison.Ordinal);
        Assert.Contains("config_items", LegacySurfaceDashboardSql.SelectCpConfigItemsMeta, StringComparison.Ordinal);
        Assert.Contains("epc_erp_coa_accounts", LegacySurfaceDashboardSql.SelectErpCoaAccounts, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_warehouses", LegacySurfaceDashboardSql.SelectErpWarehouses, StringComparison.Ordinal);
        Assert.Contains("epc_erp_sales_orders", LegacySurfaceDashboardSql.SelectErpSalesOrders, StringComparison.Ordinal);
        Assert.Contains("epc_boc_audit", LegacySurfaceDashboardSql.SelectBosAuditLog, StringComparison.Ordinal);
        Assert.Contains("shop_storages", LegacySurfaceDashboardSql.SelectCpStorages, StringComparison.Ordinal);
        Assert.Contains("epc_erp_purchase_orders", LegacySurfaceDashboardSql.SelectErpPurchaseOrders, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_stock", LegacySurfaceDashboardSql.SelectErpInventoryStockSummary, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_items", LegacySurfaceDashboardSql.SelectErpInventoryStockRows, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_warehouses", LegacySurfaceDashboardSql.SelectErpInventoryStockRows, StringComparison.Ordinal);
        Assert.Contains("reorder_level", LegacySurfaceDashboardSql.SelectErpInventoryLowStockRows, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_items", LegacySurfaceDashboardSql.CountErpCcInventoryItems, StringComparison.Ordinal);
        Assert.DoesNotContain("epc_erp_items", LegacySurfaceDashboardSql.CountErpCcInventoryItems, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_stock", LegacySurfaceDashboardSql.CountErpCcLowStockItems, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_items", LegacySurfaceDashboardSql.CountErpCcLowStockItems, StringComparison.Ordinal);
        Assert.DoesNotContain("`epc_erp_items`", LegacySurfaceDashboardSql.CountErpCcLowStockItems, StringComparison.Ordinal);
        Assert.Contains("company_id", LegacySurfaceDashboardSql.SelectErpReportCenterTableRowsByCompanyTemplate, StringComparison.Ordinal);
        Assert.Contains("information_schema.COLUMNS", LegacySurfaceDashboardSql.SelectErpReportCenterHasCompanyIdTemplate, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_movements", LegacySurfaceDashboardSql.SelectErpInventoryMovements, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_stock", LegacySurfaceDashboardSql.SumErpDashboardStockValue, StringComparison.Ordinal);
        Assert.Contains("epc_erp_gl_lines", LegacySurfaceDashboardSql.SelectErpCoaAccounts, StringComparison.Ordinal);
        Assert.Contains("shop_currencies", LegacySurfaceDashboardSql.SelectCpCurrencies, StringComparison.Ordinal);
        Assert.Contains("epc_api_clients", LegacySurfaceDashboardSql.SelectCpApiClientsMeta, StringComparison.Ordinal);
        Assert.Contains("epc_power_bi_config", LegacySurfaceDashboardSql.SelectCpPowerBiConfig, StringComparison.Ordinal);
        Assert.Contains("epc_power_bi_reports", LegacySurfaceDashboardSql.SelectCpPowerBiReports, StringComparison.Ordinal);
        Assert.Contains("integrations_json", LegacySurfaceDashboardSql.SelectCpMobileAppsIntegrationsJson, StringComparison.Ordinal);
        Assert.Contains("epc_metabase_config", LegacySurfaceDashboardSql.SelectCpMetabaseConfig, StringComparison.Ordinal);
        Assert.Contains("epc_metabase_dashboards", LegacySurfaceDashboardSql.SelectCpMetabaseDashboards, StringComparison.Ordinal);
        Assert.DoesNotContain("secret_key", LegacySurfaceDashboardSql.SelectCpMetabaseConfig, StringComparison.Ordinal);
        Assert.Contains("epc_report_definitions", LegacySurfaceDashboardSql.SelectCpNlReportDefinitions, StringComparison.Ordinal);
        Assert.DoesNotContain("query_template", LegacySurfaceDashboardSql.SelectCpNlReportDefinitions, StringComparison.Ordinal);
        Assert.Contains("epc_marketing_broadcast_campaigns", LegacySurfaceDashboardSql.SelectCpMarketingBroadcastCampaigns, StringComparison.Ordinal);
        Assert.DoesNotContain("body_html", LegacySurfaceDashboardSql.SelectCpMarketingBroadcastCampaigns, StringComparison.Ordinal);
        Assert.Contains("is_demo", LegacySurfaceDashboardSql.SelectCpDemoTenants, StringComparison.Ordinal);
        Assert.DoesNotContain("password", LegacySurfaceDashboardSql.SelectCpDemoTenants, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("epc_parts_agent_session", LegacySurfaceDashboardSql.SelectCpPartsAgentSessions, StringComparison.Ordinal);
        Assert.DoesNotContain("system_prompt", LegacySurfaceDashboardSql.SelectCpPartsAgentConfig, StringComparison.Ordinal);
        Assert.DoesNotContain("client_ip", LegacySurfaceDashboardSql.SelectCpPartsAgentSessions, StringComparison.Ordinal);
        Assert.Contains("epc_pos_sales", LegacySurfaceDashboardSql.SelectCpPosSales, StringComparison.Ordinal);
        Assert.Contains("epc_tax_toolkits", LegacySurfaceDashboardSql.SelectCpTaxToolkits, StringComparison.Ordinal);
        Assert.DoesNotContain("rules_json", LegacySurfaceDashboardSql.SelectCpTaxToolkits, StringComparison.Ordinal);
        Assert.DoesNotContain("reg_number", LegacySurfaceDashboardSql.SelectCpTaxTenantProfile, StringComparison.Ordinal);
        Assert.Contains("sms_api", LegacySurfaceDashboardSql.SelectCpSmsOperators, StringComparison.Ordinal);
        Assert.DoesNotContain("parameters_values", LegacySurfaceDashboardSql.SelectCpSmsOperators, StringComparison.Ordinal);
        Assert.Contains("phone_masked", LegacySurfaceDashboardSql.SelectCpWhatsappNotifyLog, StringComparison.Ordinal);
        Assert.DoesNotContain("`response`", LegacySurfaceDashboardSql.SelectCpWhatsappNotifyLog, StringComparison.Ordinal);
        Assert.Contains("epc_crm_leads", LegacySurfaceDashboardSql.SelectCpCrmLeads, StringComparison.Ordinal);
        Assert.DoesNotContain("email", LegacySurfaceDashboardSql.SelectCpCrmLeads, StringComparison.Ordinal);
        Assert.Contains("epc_jewel_voucher", LegacySurfaceDashboardSql.SelectCpJewelleryVouchers, StringComparison.Ordinal);
        Assert.DoesNotContain("passport", LegacySurfaceDashboardSql.SelectCpJewelleryVouchers, StringComparison.Ordinal);
        Assert.DoesNotContain("mobile", LegacySurfaceDashboardSql.SelectCpJewelleryVouchers, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("epc_pl_lists", LegacySurfaceDashboardSql.SelectCpPriceLists, StringComparison.Ordinal);
        Assert.DoesNotContain("stats_json", LegacySurfaceDashboardSql.SelectCpPriceLists, StringComparison.Ordinal);
        Assert.Contains("epc_auto_price_rules", LegacySurfaceDashboardSql.SelectCpAutoPriceRules, StringComparison.Ordinal);
        Assert.DoesNotContain("config_json", LegacySurfaceDashboardSql.SelectCpAutoPriceRules, StringComparison.Ordinal);
        Assert.DoesNotContain("notes", LegacySurfaceDashboardSql.SelectCpAutoPriceRules, StringComparison.Ordinal);
        Assert.Contains("epc_uae_tax_legislation_items", LegacySurfaceDashboardSql.SelectCpUaeTaxItems, StringComparison.Ordinal);
        Assert.DoesNotContain("erp_summary", LegacySurfaceDashboardSql.SelectCpUaeTaxItems, StringComparison.Ordinal);
        Assert.DoesNotContain("pdf_url", LegacySurfaceDashboardSql.SelectCpUaeTaxItems, StringComparison.Ordinal);
        Assert.Contains("epc_erp_pm_budgets", LegacySurfaceDashboardSql.SelectCpBudgets, StringComparison.Ordinal);
        Assert.DoesNotContain("`note`", LegacySurfaceDashboardSql.SelectCpBudgets, StringComparison.Ordinal);
        Assert.Contains("epc_carrier_accounts", LegacySurfaceDashboardSql.SelectCpCarriers, StringComparison.Ordinal);
        Assert.Contains("epc_carrier_shipments", LegacySurfaceDashboardSql.SelectCpCarrierStats, StringComparison.Ordinal);
        Assert.DoesNotContain("epc_erp_carriers", LegacySurfaceDashboardSql.SelectCpCarriers, StringComparison.Ordinal);
        Assert.DoesNotContain("config_json", LegacySurfaceDashboardSql.SelectCpCarriers, StringComparison.Ordinal);
        Assert.Contains("shop_payment_systems", LegacySurfaceDashboardSql.SelectCpPaymentGateways, StringComparison.Ordinal);
        Assert.Contains("anable", LegacySurfaceDashboardSql.SelectCpPaymentGateways, StringComparison.Ordinal);
        Assert.DoesNotContain("parameters_values", LegacySurfaceDashboardSql.SelectCpPaymentGateways, StringComparison.Ordinal);
        Assert.Contains("epc_workflows", LegacySurfaceDashboardSql.SelectCpWorkflows, StringComparison.Ordinal);
        Assert.DoesNotContain("trigger_config", LegacySurfaceDashboardSql.SelectCpWorkflows, StringComparison.Ordinal);
        Assert.Contains("epc_proc_req", LegacySurfaceDashboardSql.SelectCpPurchaseRequests, StringComparison.Ordinal);
        Assert.DoesNotContain("justification", LegacySurfaceDashboardSql.SelectCpPurchaseRequests, StringComparison.Ordinal);
        Assert.DoesNotContain("decision_note", LegacySurfaceDashboardSql.SelectCpPurchaseRequests, StringComparison.Ordinal);
        Assert.Contains("epc_promo_promotions", LegacySurfaceDashboardSql.SelectCpPromotions, StringComparison.Ordinal);
        Assert.Contains("epc_crm_opportunities", LegacySurfaceDashboardSql.SelectCpCrmOpportunities, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectCpCrmOpportunities, StringComparison.Ordinal);
        Assert.Contains("epc_tenant_feature_flags", LegacySurfaceDashboardSql.SelectCpIntegrationFeatureFlags, StringComparison.Ordinal);
        Assert.DoesNotContain("config_json", LegacySurfaceDashboardSql.SelectCpIntegrationFeatureFlags, StringComparison.Ordinal);
        Assert.Contains("payment_gateways", string.Join(",", CpIntegrationsHubCatalog.All.Select(x => x.Key)), StringComparison.Ordinal);

        Assert.Contains("epc_erp_bank_statement_lines", LegacySurfaceDashboardSql.SelectErpBankReconciliationLines, StringComparison.Ordinal);
        Assert.Contains("epc_warehouse_transfers", LegacySurfaceDashboardSql.SelectErpStockTransfers, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectErpStockTransfers, StringComparison.Ordinal);
        Assert.Contains("epc_crm_quotes", LegacySurfaceDashboardSql.SelectErpSalesQuotations, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectErpSalesQuotations, StringComparison.Ordinal);
        Assert.Contains("epc_user_shortcuts", LegacySurfaceDashboardSql.SelectErpWorkspaceFavorites, StringComparison.Ordinal);
        Assert.Contains("epc_erp_staff_profiles", LegacySurfaceDashboardSql.SelectErpStaffProfiles, StringComparison.Ordinal);
        Assert.Contains("epc_erp_contracts", LegacySurfaceDashboardSql.SelectErpContracts, StringComparison.Ordinal);
        Assert.DoesNotContain("body_text", LegacySurfaceDashboardSql.SelectErpContracts, StringComparison.Ordinal);
        Assert.DoesNotContain("ocr_text", LegacySurfaceDashboardSql.SelectErpContracts, StringComparison.Ordinal);
        Assert.Contains("epc_erp_opening_batches", LegacySurfaceDashboardSql.SelectErpOpeningBatches, StringComparison.Ordinal);
        Assert.Contains("epc_erp_marketing_campaigns", LegacySurfaceDashboardSql.SelectErpMarketingCampaigns, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectErpMarketingCampaigns, StringComparison.Ordinal);
        Assert.Contains("epc_erp_payroll_runs", LegacySurfaceDashboardSql.SelectErpPayrollRuns, StringComparison.Ordinal);
        Assert.Contains("epc_erp_print_templates", LegacySurfaceDashboardSql.SelectErpPrintTemplates, StringComparison.Ordinal);
        Assert.Contains("epc_erp_order_recommendations", LegacySurfaceDashboardSql.SelectErpOrderRecommendations, StringComparison.Ordinal);
        Assert.Contains("epc_proc_category", LegacySurfaceDashboardSql.SelectErpProcCategories, StringComparison.Ordinal);
        Assert.Contains("epc_qm_plan", LegacySurfaceDashboardSql.SelectErpQmPlans, StringComparison.Ordinal);
        Assert.DoesNotContain("corrective_action", LegacySurfaceDashboardSql.SelectErpQmNcrs, StringComparison.Ordinal);
        Assert.Contains("epc_rfid_tags", LegacySurfaceDashboardSql.SelectErpRfidTags, StringComparison.Ordinal);
        Assert.Contains("epc_hrt_job", LegacySurfaceDashboardSql.SelectErpRecruitmentJobs, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectErpRecruitmentJobs, StringComparison.Ordinal);
        Assert.Contains("epc_customer_groups", LegacySurfaceDashboardSql.SelectErpCustomerGroups, StringComparison.Ordinal);
        Assert.DoesNotContain("description", LegacySurfaceDashboardSql.SelectErpCustomerGroups, StringComparison.Ordinal);
        Assert.Contains("epc_hrt_review", LegacySurfaceDashboardSql.SelectErpPerformanceReviews, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectErpPerformanceReviews, StringComparison.Ordinal);
        Assert.Contains("epc_erp_inv_items", LegacySurfaceDashboardSql.SelectErpProductInfoItems, StringComparison.Ordinal);
        Assert.DoesNotContain("options_json", LegacySurfaceDashboardSql.SelectErpProductInfoFieldDefs, StringComparison.Ordinal);
        Assert.DoesNotContain("combo_json", LegacySurfaceDashboardSql.SelectErpProductInfoVariants, StringComparison.Ordinal);
        Assert.Contains("epc_report_schedules", LegacySurfaceDashboardSql.SelectErpReportSchedules, StringComparison.Ordinal);
        Assert.DoesNotContain("recipients", LegacySurfaceDashboardSql.SelectErpReportSchedules, StringComparison.Ordinal);
        Assert.DoesNotContain("body_template", LegacySurfaceDashboardSql.SelectErpReportSchedules, StringComparison.Ordinal);
        Assert.Contains("epc_prja_budget", LegacySurfaceDashboardSql.SelectErpPrjaBudgets, StringComparison.Ordinal);
        Assert.DoesNotContain("detail_json", LegacySurfaceDashboardSql.SelectErpPrjaRecognitions, StringComparison.Ordinal);
        Assert.Contains("epc_doc_attachments", LegacySurfaceDashboardSql.SelectErpDocAttachments, StringComparison.Ordinal);
        Assert.DoesNotContain("file_path", LegacySurfaceDashboardSql.SelectErpDocAttachments, StringComparison.Ordinal);
        Assert.Contains("epc_inventory_categories", LegacySurfaceDashboardSql.SelectErpInventoryReportCategories, StringComparison.Ordinal);
        Assert.DoesNotContain("header_html", LegacySurfaceDashboardSql.SelectErpPrintTemplates, StringComparison.Ordinal);
        Assert.DoesNotContain("custom_css", LegacySurfaceDashboardSql.SelectErpPrintTemplates, StringComparison.Ordinal);
        Assert.Contains("epc_erp_fa_assets", LegacySurfaceDashboardSql.SelectErpFixedAssets, StringComparison.Ordinal);
        Assert.DoesNotContain("`note`", LegacySurfaceDashboardSql.SelectErpFixedAssets, StringComparison.Ordinal);
        Assert.Contains("epc_page_builder_layouts", LegacySurfaceDashboardSql.SelectCpPageBuilderLayouts, StringComparison.Ordinal);
        Assert.DoesNotContain("layout_json", LegacySurfaceDashboardSql.SelectCpPageBuilderLayouts, StringComparison.Ordinal);
        Assert.DoesNotContain("brand_json", LegacySurfaceDashboardSql.SelectCpPageBuilderLayouts, StringComparison.Ordinal);
        Assert.Contains("shop_catalogue_products", LegacySurfaceDashboardSql.SelectCpProductCatalogue, StringComparison.Ordinal);
        Assert.Contains("epc_platform_governance_rules", LegacySurfaceDashboardSql.SelectCpPlatformGovernanceRules, StringComparison.Ordinal);
        Assert.DoesNotContain("config_json", LegacySurfaceDashboardSql.SelectCpPlatformGovernanceRules, StringComparison.Ordinal);
        Assert.DoesNotContain("`description`", LegacySurfaceDashboardSql.SelectCpPlatformGovernanceRules, StringComparison.Ordinal);
        Assert.Contains("epc_document_templates", LegacySurfaceDashboardSql.SelectCpDocumentTemplates, StringComparison.Ordinal);
        Assert.DoesNotContain("header_html", LegacySurfaceDashboardSql.SelectCpDocumentTemplates, StringComparison.Ordinal);
        Assert.Contains("shop_obtaining_modes", LegacySurfaceDashboardSql.SelectCpDeliveryModes, StringComparison.Ordinal);
        Assert.DoesNotContain("parameters_values", LegacySurfaceDashboardSql.SelectCpDeliveryModes, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_articles_analogs_list", LegacySurfaceDashboardSql.SelectCpCrossPairs, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_prices_data", LegacySurfaceDashboardSql.SelectStorefrontPartSearch, StringComparison.Ordinal);
        Assert.Contains("{ARTICLE_MATCH}", LegacySurfaceDashboardSql.SelectStorefrontPartSearch, StringComparison.Ordinal);
        Assert.Contains("@brand", LegacySurfaceDashboardSql.SelectStorefrontPartSearch, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_prices_data", LegacySurfaceDashboardSql.SelectStorefrontArticleWarehouseBrands, StringComparison.Ordinal);
        Assert.Contains("{ARTICLE_MATCH}", LegacySurfaceDashboardSql.SelectStorefrontArticleWarehouseBrands, StringComparison.Ordinal);
        Assert.Contains("shop_docpart_articles_analogs_list", LegacySurfaceDashboardSql.SelectStorefrontArticleCrossPairs, StringComparison.Ordinal);
        Assert.Contains("{CROSS_MATCH}", LegacySurfaceDashboardSql.SelectStorefrontArticleCrossPairs, StringComparison.Ordinal);
        Assert.Equal(15, CountOccurrences(LegacySurfaceDashboardSql.DocpartNormalizeArticleExpr("`article`"), "REPLACE("));
        Assert.Contains("shop_carts", LegacySurfaceDashboardSql.SelectStorefrontCartSummary, StringComparison.Ordinal);
        Assert.Contains("shop_carts", LegacySurfaceDashboardSql.SelectStorefrontCartLines, StringComparison.Ordinal);
        Assert.Contains("t2_exist", LegacySurfaceDashboardSql.SelectStorefrontCartLines, StringComparison.Ordinal);
        Assert.DoesNotContain("DELETE", LegacySurfaceDashboardSql.SelectStorefrontCartLines, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("UPDATE", LegacySurfaceDashboardSql.SelectStorefrontCartLines, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("client_key_hash", LegacySurfaceDashboardSql.SelectCpApiClientsMeta, StringComparison.Ordinal);
        Assert.DoesNotContain("`session`", LegacySurfaceDashboardSql.SelectCpAdminSessions, StringComparison.Ordinal);
        Assert.DoesNotContain("INSERT", LegacySurfaceDashboardSql.SumSupplierCredit, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("UPDATE", LegacySurfaceDashboardSql.SelectPortalTenants, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("DELETE", LegacySurfaceDashboardSql.SelectCustomerOrders, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("DELETE", LegacySurfaceDashboardSql.SelectCpUsers, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("epc_soc2_controls", LegacySurfaceDashboardSql.SelectCpSoc2Controls, StringComparison.Ordinal);
        Assert.DoesNotContain("`description`", LegacySurfaceDashboardSql.SelectCpSoc2Controls, StringComparison.Ordinal);
        Assert.DoesNotContain("`implementation`", LegacySurfaceDashboardSql.SelectCpSoc2Controls, StringComparison.Ordinal);
        Assert.Contains("epc_costm_item", LegacySurfaceDashboardSql.SelectCpCostModelItems, StringComparison.Ordinal);
        Assert.Contains("epc_fin_periods", LegacySurfaceDashboardSql.SelectCpFinPeriods, StringComparison.Ordinal);
        Assert.Contains("epc_bc_proofs", LegacySurfaceDashboardSql.SelectCpBlockchainProofs, StringComparison.Ordinal);
        Assert.DoesNotContain("payload_json", LegacySurfaceDashboardSql.SelectCpBlockchainProofs, StringComparison.Ordinal);
        Assert.DoesNotContain("merkle_proof_json", LegacySurfaceDashboardSql.SelectCpBlockchainProofs, StringComparison.Ordinal);
        Assert.Contains("epc_landed_cost_sheets", LegacySurfaceDashboardSql.SelectCpLandedCostSheets, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectCpLandedCostSheets, StringComparison.Ordinal);
        Assert.Contains("epc_erp_wms_work", LegacySurfaceDashboardSql.SelectCpWarehouseWmsWork, StringComparison.Ordinal);
        Assert.Contains("epc_ai_queries", LegacySurfaceDashboardSql.SelectCpAiServiceQueries, StringComparison.Ordinal);
        Assert.DoesNotContain("input_text", LegacySurfaceDashboardSql.SelectCpAiServiceQueries, StringComparison.Ordinal);
        Assert.DoesNotContain("output_text", LegacySurfaceDashboardSql.SelectCpAiServiceQueries, StringComparison.Ordinal);
        Assert.Contains("epc_rma_requests", LegacySurfaceDashboardSql.SelectCpReturnsRmaRequests, StringComparison.Ordinal);
        Assert.DoesNotContain("`description`", LegacySurfaceDashboardSql.SelectCpReturnsRmaRequests, StringComparison.Ordinal);
        Assert.DoesNotContain("resolution_notes", LegacySurfaceDashboardSql.SelectCpReturnsRmaRequests, StringComparison.Ordinal);
        Assert.Contains("epc_ci_audit_runs", LegacySurfaceDashboardSql.SelectCpIsolationAuditRuns, StringComparison.Ordinal);
        Assert.DoesNotContain("report_json", LegacySurfaceDashboardSql.SelectCpIsolationAuditRuns, StringComparison.Ordinal);
        Assert.Contains("epc_aml_kyc", LegacySurfaceDashboardSql.SelectCpAmlComplianceKyc, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectCpAmlComplianceKyc, StringComparison.Ordinal);
        Assert.DoesNotContain("id_document_path", LegacySurfaceDashboardSql.SelectCpAmlComplianceKyc, StringComparison.Ordinal);
        Assert.Contains("epc_jewel_karat_master", LegacySurfaceDashboardSql.SelectCpJewelleryMastersKarats, StringComparison.Ordinal);
        Assert.DoesNotContain("`description`", LegacySurfaceDashboardSql.SelectCpJewelleryMastersKarats, StringComparison.Ordinal);
        Assert.Contains("epc_cons_entities", LegacySurfaceDashboardSql.SelectCpConsolidationsEntities, StringComparison.Ordinal);
        Assert.Contains("epc_cmp_rules", LegacySurfaceDashboardSql.SelectCpTaxExternalReportingStats, StringComparison.Ordinal);
        Assert.DoesNotContain("value_json", LegacySurfaceDashboardSql.SelectCpTaxExternalReportingRows, StringComparison.Ordinal);
        Assert.Contains("epc_po_requests", LegacySurfaceDashboardSql.SelectCpPoApprovalsStats, StringComparison.Ordinal);
        Assert.DoesNotContain("`description`", LegacySurfaceDashboardSql.SelectCpPoApprovalsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("`notes`", LegacySurfaceDashboardSql.SelectCpPoApprovalsRows, StringComparison.Ordinal);
        Assert.Contains("epc_erp_opening_batches", LegacySurfaceDashboardSql.SelectCpFinanceCloseStats, StringComparison.Ordinal);
        Assert.Contains("epc_erp_periods", LegacySurfaceDashboardSql.SelectCpFinanceCloseStats, StringComparison.Ordinal);
        Assert.DoesNotContain("`note`", LegacySurfaceDashboardSql.SelectCpFinanceCloseRows, StringComparison.Ordinal);
        Assert.Contains("epc_jewel_fixing", LegacySurfaceDashboardSql.SelectCpJewelleryFixingStats, StringComparison.Ordinal);
        Assert.Contains("epc_fix_unfix_purchases", LegacySurfaceDashboardSql.SelectCpJewelleryFixingStats, StringComparison.Ordinal);
        Assert.DoesNotContain("`remarks`", LegacySurfaceDashboardSql.SelectCpJewelleryFixingRows, StringComparison.Ordinal);
        Assert.Contains("epc_web_tracker_sessions", LegacySurfaceDashboardSql.SelectCpWebTrackerStats, StringComparison.Ordinal);
        Assert.DoesNotContain("`ip`", LegacySurfaceDashboardSql.SelectCpWebTrackerRows, StringComparison.Ordinal);
        Assert.DoesNotContain("`ua`", LegacySurfaceDashboardSql.SelectCpWebTrackerRows, StringComparison.Ordinal);
        Assert.Contains("shop_carts", LegacySurfaceDashboardSql.SelectCpAbandonedCartsStats, StringComparison.Ordinal);
        Assert.Contains("session_id", LegacySurfaceDashboardSql.SelectCpAbandonedCartsStats, StringComparison.Ordinal);
        Assert.Contains("shop_carts", LegacySurfaceDashboardSql.SelectCpAbandonedCartsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("DELETE", LegacySurfaceDashboardSql.SelectCpAbandonedCartsRows, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("shop_quote_requests", LegacySurfaceDashboardSql.SelectCpQuoteRequestsStats, StringComparison.Ordinal);
        Assert.DoesNotContain("admin_note", LegacySurfaceDashboardSql.SelectCpQuoteRequestsRows, StringComparison.Ordinal);
        Assert.Contains("epc_platform_comm_settings", LegacySurfaceDashboardSql.SelectCpPlatformCommunicationStats, StringComparison.Ordinal);
        Assert.DoesNotContain("`description`", LegacySurfaceDashboardSql.SelectCpPlatformCommunicationRows, StringComparison.Ordinal);
        Assert.Contains("epc_platform_info_blocks", LegacySurfaceDashboardSql.SelectCpInfoBlocksStats, StringComparison.Ordinal);
        Assert.DoesNotContain("content_html", LegacySurfaceDashboardSql.SelectCpInfoBlocksRows, StringComparison.Ordinal);
        Assert.Contains("epc_free_tool_accounts", LegacySurfaceDashboardSql.SelectCpFreeToolsStats, StringComparison.Ordinal);
        Assert.DoesNotContain("`token`", LegacySurfaceDashboardSql.SelectCpFreeToolsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("pass_hash", LegacySurfaceDashboardSql.SelectCpFreeToolsRows, StringComparison.Ordinal);
        Assert.Contains("epc_config_snapshots", LegacySurfaceDashboardSql.SelectCpConfigSandboxStats, StringComparison.Ordinal);
        Assert.DoesNotContain("config_data", LegacySurfaceDashboardSql.SelectCpConfigSandboxRows, StringComparison.Ordinal);
        Assert.Contains("epc_marketplace_apps", LegacySurfaceDashboardSql.SelectCpMarketplaceAppsStats, StringComparison.Ordinal);
        Assert.DoesNotContain("review_text", LegacySurfaceDashboardSql.SelectCpMarketplaceAppsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("`description`", LegacySurfaceDashboardSql.SelectCpMarketplaceAppsRows, StringComparison.Ordinal);
        Assert.Contains("epc_notifications", LegacySurfaceDashboardSql.SelectCpNotificationsStats, StringComparison.Ordinal);
        Assert.DoesNotContain("`body`", LegacySurfaceDashboardSql.SelectCpNotificationsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("metadata", LegacySurfaceDashboardSql.SelectCpNotificationsRows, StringComparison.Ordinal);
        Assert.Contains("epc_portal_site_settings", LegacySurfaceDashboardSql.SelectCpPortalSettingsStats, StringComparison.Ordinal);
        Assert.Contains("epc_portal_deploy_targets", LegacySurfaceDashboardSql.SelectCpPortalSettingsStats, StringComparison.Ordinal);
        Assert.DoesNotContain("contact_json", LegacySurfaceDashboardSql.SelectCpPortalSettingsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("theme_json", LegacySurfaceDashboardSql.SelectCpPortalSettingsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("cp_menu_json", LegacySurfaceDashboardSql.SelectCpPortalSettingsRows, StringComparison.Ordinal);
        Assert.Contains("epc_data_migrations", LegacySurfaceDashboardSql.SelectCpDataMigrationsStats, StringComparison.Ordinal);
        Assert.Contains("epc_data_migration_rows", LegacySurfaceDashboardSql.SelectCpDataMigrationsStats, StringComparison.Ordinal);
        Assert.DoesNotContain("file_path", LegacySurfaceDashboardSql.SelectCpDataMigrationsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("column_mapping", LegacySurfaceDashboardSql.SelectCpDataMigrationsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("validation_errors", LegacySurfaceDashboardSql.SelectCpDataMigrationsRows, StringComparison.Ordinal);
        Assert.DoesNotContain("raw_data", LegacySurfaceDashboardSql.SelectCpDataMigrationsRows, StringComparison.Ordinal);
    }

    [Fact]
    public void ErpReportCenterTableEntriesHaveAllowlistedTables()
    {
        Assert.Equal(33, ErpReportCenterRegistry.All.Count);
        foreach (var entry in ErpReportCenterRegistry.All.Where(e => e.Kind == ErpReportCenterRegistry.SourceKind.Table))
        {
            Assert.False(string.IsNullOrWhiteSpace(entry.Table), entry.Key + " missing Table");
            Assert.Matches("^[A-Za-z0-9_]+$", entry.Table!);
            if (!string.IsNullOrWhiteSpace(entry.FallbackTable))
            {
                Assert.Matches("^[A-Za-z0-9_]+$", entry.FallbackTable!);
            }
        }

        Assert.Contains(ErpReportCenterRegistry.All, e => e.Key == "ap_withholding" && e.Table == "epc_wht_txn");
        Assert.Contains(ErpReportCenterRegistry.All, e => e.Key == "proc_requisitions" && e.Table == "epc_proc_req");
        Assert.Contains(ErpReportCenterRegistry.All, e => e.Key == "tax_er_runs" && e.Table == "epc_er_run");
    }

    [Fact]
    public void BuildErpApprovalQueueMirrorsPhpCommandCenterShape()
    {
        var summary = new ErpDashboardSummary(
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0,
            0, 0, 0, 0, 0, "open", 0,
            2, 1, 0, 3, 0, 1,
            0, 0, 0,
            "database", "");
        var queue = SurfaceDashboardSummaryReporter.BuildErpApprovalQueue(summary);
        Assert.Equal(4, queue.Count);
        Assert.Contains(queue, q => q.Id == "draft_so" && q.Count == 2 && q.Category == "Sales");
        Assert.Contains(queue, q => q.Id == "pending_po" && q.Count == 1);
        Assert.Contains(queue, q => q.Id == "overdue_invoices" && q.Count == 3 && q.Severity == "danger");
        Assert.Contains(queue, q => q.Id == "pending_einvoice" && q.Count == 1);
        Assert.DoesNotContain(queue, q => q.Id == "unposted_gl");
        Assert.DoesNotContain(queue, q => q.Id == "low_stock");
    }

    private static int CountOccurrences(string haystack, string needle)
    {
        var count = 0;
        var idx = 0;
        while ((idx = haystack.IndexOf(needle, idx, StringComparison.Ordinal)) >= 0)
        {
            count++;
            idx += needle.Length;
        }

        return count;
    }

    private sealed class UnconfiguredFactory : ITenantDbConnectionFactory
    {
        public bool IsConfigured => false;

        public Task<System.Data.Common.DbConnection> OpenAsync(string? databaseName, CancellationToken cancellationToken = default)
            => throw new InvalidOperationException("not configured");

        public Task<System.Data.Common.DbConnection> OpenAsync(string? databaseName, string? userName, string? password, CancellationToken cancellationToken = default)
            => throw new InvalidOperationException("not configured");

        public Task<System.Data.Common.DbConnection> OpenForTenantAsync(EcomAE.Platform.Services.TenantContext? tenant, CancellationToken cancellationToken = default)
            => throw new InvalidOperationException("not configured");

        public Task<System.Data.Common.DbConnection> OpenRegistryAsync(CancellationToken cancellationToken = default)
            => throw new InvalidOperationException("not configured");
    }
}