namespace EcomAE.Platform.Presentation;

/// <summary>
/// PHP erp_tabs_* → ASP.NET primary app map (PHP remains write-authoritative).
/// Generated for full tab coverage; unmapped tabs fall through to area hubs or /erp/module-app.
/// </summary>
public static class ErpPhpTabRouteMap
{
    public const string ModuleAppPath = "/erp/module-app";

    private static readonly Dictionary<string, string> TabRoutes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["accounting"] = "/erp/gl-journals-app",
        ["accounting_automation"] = "/cp/fin-advanced-app?tab=accounting_automation",
        ["accounts"] = "/erp/accounts-summary-app",
        ["aftersales"] = "/cp/returns-rma-app",
        ["agenda"] = "/erp/agenda-app",
        ["aging"] = "/erp/aging-app",
        ["ai_advisor"] = "/erp/guide-app?tab=ai_advisor",
        ["ai_assistant"] = "/erp/guide-app?tab=ai_assistant",
        ["aml_compliance"] = "/cp/aml-compliance-app",
        ["ap_aging"] = "/erp/aging-app",
        ["ap_setup"] = "/erp/suppliers-app?tab=ap_setup",
        ["approval"] = "/erp/approvals-app",
        ["approvals"] = "/erp/approvals-app",
        ["ar_aging"] = "/erp/aging-app",
        ["ar_setup"] = "/erp/contacts-app?tab=ar_setup",
        ["assets"] = "/erp/fixed-assets-app",
        ["audit"] = "/cp/audit-trail-app",
        ["balance_sheet"] = "/erp/report-center-app",
        ["bank_entries"] = "/erp/cash-entries-app",
        ["bank_instruments"] = "/erp/bank-reconciliation-app?tab=bank_instruments",
        ["bank_setup"] = "/erp/cash-accounts-app?tab=bank_setup",
        ["bank_recon"] = "/erp/bank-reconciliation-app",
        ["banking"] = "/erp/cash-accounts-app",
        ["barcode_purchase"] = "/erp/purchase-orders-app?tab=barcode_purchase",
        ["blockchain_proofs"] = "/cp/blockchain-proofs-app",
        ["budget_planning"] = "/cp/budgets-app",
        ["budgeting"] = "/cp/budgets-app",
        ["business_units"] = "/cp/consolidations-app?tab=business_units",
        ["card_reader"] = "/cp/pos-overview-app",
        ["cash"] = "/erp/cash-accounts-app",
        ["cash_bank"] = "/erp/cash-accounts-app",
        ["cash_forecast"] = "/erp/cash-accounts-app?tab=cash_forecast",
        ["chart_of_accounts"] = "/erp/coa-accounts-app",
        ["coa"] = "/erp/coa-accounts-app",
        ["collections"] = "/cp/collections-dunning-app",
        ["compliance"] = "/cp/soc2-compliance-app",
        ["consolidation_bu"] = "/cp/consolidations-app",
        ["consolidation_group"] = "/cp/consolidations-app",
        ["consolidation_ic"] = "/cp/consolidations-app",
        ["contacts"] = "/erp/contacts-app",
        ["contracts"] = "/erp/contracts-app",
        ["cost_models"] = "/cp/cost-models-app",
        ["crm"] = "/cp/crm-tickets-app",
        ["crm_integration"] = "/cp/crm-board-app?tab=crm_integration",
        ["custom_shipping"] = "/cp/fulfillment-queue-app?tab=custom_shipping",
        ["customer_groups"] = "/erp/customer-groups-app",
        ["dashboard"] = "/erp",
        ["data_import"] = "/cp/data-migrations-app",
        ["data_migration"] = "/cp/data-migrations-app",
        ["delivery_notes"] = "/erp/delivery-notes-app",
        ["doc_attachment"] = "/erp/doc-attachments-app",
        ["doc_expiry"] = "/cp/doc-expiry-app",
        ["doc_formats"] = "/erp/documents-app?tab=doc_formats",
        ["document_control"] = "/cp/doc-expiry-app",
        ["documents"] = "/erp/documents-app",
        ["drilldown"] = "/erp/report-center-app?tab=drilldown",
        ["ecommerce_integration"] = "/cp/integrations-app",
        ["einvoice"] = "/cp/einvoice-documents-app",
        ["elec_reporting"] = "/cp/electronic-reporting-app",
        ["enterprise_reports"] = "/erp/report-center-app?tab=enterprise_reports",
        ["erp_setup"] = "/cp/tenant-config-app?tab=erp_setup",
        ["exec_dashboard"] = "/erp",
        ["expense_reports"] = "/erp/expense-reports-app",
        ["ext_reports"] = "/cp/tax-external-reporting-app",
        ["external_reports"] = "/cp/tax-external-reporting-app",
        ["favorites"] = "/erp/workspace-favorites-app",
        ["fin_advanced"] = "/cp/fin-advanced-app",
        ["fix_unfix"] = "/cp/jewellery-fixing-app?tab=fix_unfix",
        ["fixed_assets"] = "/erp/fixed-assets-app",
        ["fulfilment"] = "/cp/fulfillment-queue-app",
        ["general_journal"] = "/erp/gl-journals-app",
        ["gl"] = "/erp/gl-journals-app",
        ["gold_rate"] = "/cp/jewellery-masters-app?tab=gold_rate",
        ["gold_scheme"] = "/cp/jewellery-masters-app?tab=gold_scheme",
        ["guide"] = "/erp/guide-app",
        ["hr"] = "/cp/hr-overview-app",
        ["hr_law"] = "/cp/hr-overview-app?tab=hr_law",
        ["hr_ops"] = "/cp/hr-overview-app?tab=hr_ops",
        ["industry_intel"] = "/cp/industry-packs-app",
        ["insurance"] = "/cp/insurance-compliance-app",
        ["integration"] = "/cp/integrations-app",
        ["inv_groups"] = "/erp/stock-transfers-app",
        ["inventory"] = "/erp/inventory-stock-app",
        ["inventory_report"] = "/erp/inventory-report-app",
        ["inventory_stock"] = "/erp/inventory-stock-app",
        ["invoices"] = "/erp/invoices-app",
        ["jewellery"] = "/cp/jewellery-retail-app?tab=jewellery",
        ["jewellery_tag"] = "/cp/jewellery-masters-app?tab=jewellery_tag",
        ["journals"] = "/erp/gl-journals-app",
        ["jw_barcode"] = "/cp/jewellery-masters-app?tab=jw_barcode",
        ["jw_color_stone"] = "/cp/jewellery-masters-app?tab=jw_color_stone",
        ["jw_currency"] = "/cp/jewellery-masters-app?tab=jw_currency",
        ["jw_design"] = "/cp/jewellery-masters-app?tab=jw_design",
        ["jw_diamond"] = "/cp/jewellery-masters-app?tab=jw_diamond",
        ["jw_diamond_purchase"] = "/cp/jewellery-fixing-app?tab=jw_diamond_purchase",
        ["jw_journal_voucher"] = "/erp/gl-journals-app?tab=jw_journal_voucher",
        ["jw_karat"] = "/cp/jewellery-masters-app",
        ["jw_metal_purchase"] = "/cp/jewellery-fixing-app?tab=jw_metal_purchase",
        ["jw_metal_sales"] = "/cp/jewellery-retail-app?tab=jw_metal_sales",
        ["jw_metal_stock"] = "/cp/jewellery-stock-verification-app?tab=jw_metal_stock",
        ["jw_pearl"] = "/cp/jewellery-masters-app?tab=jw_pearl",
        ["jw_petty_cash"] = "/erp/cash-accounts-app?tab=jw_petty_cash",
        ["jw_pos_advance"] = "/cp/pos-overview-app",
        ["jw_purchase_fixing"] = "/cp/jewellery-fixing-app",
        ["jw_purchase_window"] = "/cp/jewellery-fixing-app?tab=jw_purchase_window",
        ["jw_rate_type"] = "/cp/jewellery-masters-app?tab=jw_rate_type",
        ["jw_repair_delivery"] = "/cp/jewellery-repairs-app?tab=jw_repair_delivery",
        ["jw_repair_receipt"] = "/cp/jewellery-repairs-app?tab=jw_repair_receipt",
        ["jw_repair_register"] = "/cp/jewellery-repairs-app?tab=jw_repair_register",
        ["jw_repair_sale"] = "/cp/jewellery-repairs-app?tab=jw_repair_sale",
        ["jw_repair_search"] = "/cp/jewellery-repairs-app?tab=jw_repair_search",
        ["jw_repair_transfer"] = "/cp/jewellery-repairs-app?tab=jw_repair_transfer",
        ["jw_repairs"] = "/cp/jewellery-repairs-app",
        ["jw_retail_sales"] = "/cp/jewellery-retail-app?tab=jw_retail_sales",
        ["jw_sales_analysis"] = "/cp/jewellery-retail-app?tab=jw_sales_analysis",
        ["jw_sales_fixing"] = "/cp/jewellery-fixing-app?tab=jw_sales_fixing",
        ["jw_sales_return"] = "/cp/jewellery-retail-app?tab=jw_sales_return",
        ["jw_seed_data"] = "/cp/jewellery-masters-app?tab=jw_seed_data",
        ["jw_stock_balance"] = "/cp/jewellery-stock-verification-app?tab=jw_stock_balance",
        ["jw_stock_verification"] = "/cp/jewellery-stock-verification-app",
        ["jw_tourist_vat"] = "/cp/uae-tax-compliance-app?tab=jw_tourist_vat",
        ["jw_trial_balance"] = "/erp/report-center-app?tab=jw_trial_balance",
        ["jw_workshop_receive"] = "/cp/jewellery-repairs-app?tab=jw_workshop_receive",
        ["knowledge"] = "/erp/guide-app",
        ["knowledge_base"] = "/erp/guide-app",
        ["landed_cost"] = "/cp/landed-cost-app",
        ["landed_cost_v2"] = "/cp/landed-cost-app",
        ["leads"] = "/cp/crm-board-app",
        ["ledger"] = "/erp/stock-movements-app",
        ["listing"] = "/cp/projects-overview-app?tab=listing",
        ["manufacturing"] = "/cp/production-overview-app",
        ["marketing"] = "/erp/marketing-app",
        ["master_planning"] = "/erp/order-planning-app?tab=master_planning",
        ["mfg_planning"] = "/cp/production-overview-app?tab=mfg_planning",
        ["movements"] = "/erp/stock-movements-app",
        ["multi_entity"] = "/cp/consolidations-app?tab=multi_entity",
        ["on_premises"] = "/erp/on-premises-app",
        ["onpremises"] = "/erp/on-premises-app",
        ["opening"] = "/erp/opening-app",
        ["opening_balances"] = "/erp/opening-app",
        ["opportunities"] = "/cp/crm-opportunities-app",
        ["order_planning"] = "/erp/order-planning-app",
        ["org_admin"] = "/cp/tenant-config-app?tab=org_admin",
        ["overview"] = "/erp",
        ["payables"] = "/erp/payables-app",
        ["payment_batches"] = "/erp/payment-batches-app",
        ["payroll"] = "/erp/payroll-app",
        ["performance"] = "/erp/performance-app",
        ["petty_cash"] = "/erp/cash-accounts-app?tab=petty_cash",
        ["pl"] = "/erp/report-center-app",
        ["platform"] = "/cp/tenant-config-app?tab=platform",
        ["print_designer"] = "/erp/print-designer-app",
        ["process_flow"] = "/erp/process-flow-tasks-app",
        ["processflow"] = "/erp/process-flow-tasks-app",
        ["procurement_categories"] = "/erp/procurement-categories-app",
        ["procurement_link"] = "/cp/purchase-requests-app",
        ["product_info"] = "/erp/product-info-app",
        ["project_accounting"] = "/erp/project-accounting-app",
        ["projects"] = "/cp/projects-overview-app",
        ["proposals"] = "/erp/sales-quotations-app",
        ["purchase_orders"] = "/erp/purchase-orders-app",
        ["purchase_requisitions"] = "/cp/purchase-requests-app",
        ["purchaseorders"] = "/erp/purchase-orders-app",
        ["purchases"] = "/erp/purchases-app",
        ["quality"] = "/erp/quality-app",
        ["quotations"] = "/erp/sales-quotations-app",
        ["revenue"] = "/erp/report-center-app?tab=revenue",
        ["rc_finance"] = "/erp/report-center-app",
        ["receivables"] = "/erp/receivables-app",
        ["reconciliation"] = "/erp/bank-reconciliation-app",
        ["recruitment"] = "/erp/recruitment-app",
        ["report_center"] = "/erp/report-center-app",
        ["report_scheduler"] = "/erp/report-scheduler-app",
        ["reportcenter"] = "/erp/report-center-app",
        ["reports"] = "/erp/report-center-app",
        ["retail_barcode"] = "/cp/jewellery-retail-app?tab=retail_barcode",
        ["retail_commerce"] = "/cp/jewellery-retail-app",
        ["rfid"] = "/erp/rfid-app",
        ["rfq"] = "/erp/rfq-app",
        ["sales_orders"] = "/erp/sales-orders-app",
        ["sales_quotations"] = "/erp/sales-quotations-app",
        ["salesorders"] = "/erp/sales-orders-app",
        ["security_roles"] = "/cp/tenant-config-app?tab=security_roles",
        ["setup"] = "/cp/tenant-config-app?tab=setup",
        ["shortcut_icons"] = "/erp/workspace-favorites-app",
        ["sla"] = "/cp/crm-tickets-app?tab=sla",
        ["staff"] = "/erp/staff-app",
        ["stock"] = "/erp/inventory-stock-app",
        ["subscriptions"] = "/erp/sales-orders-app?tab=subscriptions",
        ["supplier_portal"] = "/erp/suppliers-app?tab=supplier_portal",
        ["tax_compliance"] = "/cp/uae-tax-compliance-app",
        ["tenant_config"] = "/cp/tenant-config-app",
        ["three_way_match"] = "/erp/three-way-match-app",
        ["tickets"] = "/cp/crm-tickets-app",
        ["tourist_refund"] = "/erp/vat-app?tab=tourist_refund",
        ["transfers"] = "/erp/stock-transfers-app",
        ["vat"] = "/erp/vat-app",
        ["vat_refund"] = "/erp/vat-app?tab=vat_refund",
        ["vat_return"] = "/erp/vat-app?tab=vat_return",
        ["vendors"] = "/erp/suppliers-app",
        ["virtual_warehouse"] = "/erp/warehouses-app?tab=virtual_warehouse",
        ["warehouse"] = "/erp/warehouses-app",
        ["withholding"] = "/erp/withholding-app",
        ["wms"] = "/cp/warehouse-wms-app",
        ["workflow"] = "/erp/workflow-app",
        ["workflow_automation"] = "/cp/workflows-app",
        ["workspace"] = "/erp/workspace-favorites-app",
        ["year_end"] = "/erp/period-close-app",
    };

    public static IReadOnlyDictionary<string, string> All => TabRoutes;

    public static bool TryMapTab(string? tab, out string href)
    {
        href = string.Empty;
        if (string.IsNullOrWhiteSpace(tab)) return false;
        var key = tab.Trim();
        if (!TabRoutes.TryGetValue(key, out var mapped) || string.IsNullOrWhiteSpace(mapped))
        {
            return false;
        }
        href = mapped;
        return true;
    }

    public static string MapTabOrModuleApp(string? tab)
    {
        if (TryMapTab(tab, out var href)) return href;
        var key = (tab ?? string.Empty).Trim();
        if (key.Length == 0) return "/erp";
        return ModuleAppPath + "?tab=" + Uri.EscapeDataString(key);
    }
}
