using System.Linq;

namespace EcomAE.Platform.Presentation;

/// <summary>
/// PHP-aligned chrome navigation for ASP.NET presentation shells.
/// Links point at live PHP routes for unported modules (hybrid preserve-functionality).
/// Source maps: epc_cp_nav_tree.php, erp_nav_areas.php, epc_bos_unified.php.
/// </summary>
public static class LegacyChromeNavCatalog
{
    public sealed record NavItem(string Label, string Href, string? Hint = null);

    /// <summary>CP top bar short labels → PHP Control Panel entry points.</summary>
    public static readonly IReadOnlyList<NavItem> ControlPanel =
    [
        new("CONTROL", "/CP/", "Command centre home"),
        new("Commerce", "/CP/shop/orders/orders", "OMS / orders (PHP console)"),
        new("Customers", "/CP/control/users", "Users & customers"),
        new("Documents", "/CP/control/shop/docpart", "Documents"),
        new("ERP", "/ERP/", "ERP shell"),
        new("Purchase", "/CP/control/shop/procurement", "Procurement"),
        new("Channels", "/CP/control/shop/channels", "Sales channels"),
        new("Logistics", "/CP/control/shop/logistics", "Logistics"),
        new("AI", "/CP/control/shop/ai", "AI tools"),
        new("Marketing", "/CP/control/shop/marketing", "Marketing"),
        new("Payments", "/CP/control/shop/payments", "Payments"),
        new("Integrations", "/CP/control/shop/integrations", "Integrations"),
        new("Portal", "/CP/control/portal", "Portal / tenants"),
        new("Platform", "/CP/control/portal/epc_super_cp_fleet_dashboard", "Platform fleet"),
        new("Operator", "/CP/control", "Operator tools")
    ];

    public static readonly IReadOnlyList<NavItem> ControlPanelQuickActions =
    [
        new("Dashboard summary KPIs", "/cp/dashboard-summary-app"),
        new("Orders (OMS)", "/cp/orders"),
        new("Orders PHP OMS", "/CP/shop/orders/orders"),
        new("Users list", "/cp/users-app"),
        new("Groups list", "/cp/groups-app"),
        new("Modules list", "/cp/modules-app"),
        new("Modules PHP", "/CP/modules/modules_manager"),
        new("Pages list", "/cp/pages-app"),
        new("Content manager PHP", "/CP/content/content_manager"),
        new("Menus list", "/cp/menus-app"),
        new("Menu manager PHP", "/CP/menu/menu_manager"),
        new("Tenants list", "/cp/tenants-app"),
        new("Tenant control PHP", "/CP/control/portal/epc_tenant_control_center"),
        new("Currencies list", "/cp/currencies-app"),
        new("Currency rates PHP", "/CP/shop/finance/nastrojka-kursov-valyut"),
        new("Storages list", "/cp/storages-app"),
        new("Storages PHP", "/CP/shop/logistics/storages"),
        new("Admin sessions list", "/cp/admin-sessions-app"),
        new("API clients list", "/cp/api-clients-app"),
        new("API clients PHP", "/CP/control/portal/epc_api_clients_manage"),
        new("Power BI list", "/cp/power-bi-app"),
        new("Power BI PHP", "/CP/control/portal/epc_power_bi"),
        new("Mobile apps summary", "/cp/mobile-apps-app"),
        new("Mobile apps PHP", "/CP/control/portal/epc_mobile_apps"),
        new("Metabase list", "/cp/metabase-app"),
        new("Metabase PHP", "/CP/general_pages/epc_metabase_embed"),
        new("NL reporting list", "/cp/nl-reporting-app"),
        new("NL reporting PHP", "/CP/control/portal/epc_nl_reporting"),
        new("Marketing broadcast list", "/cp/marketing-broadcast-app"),
        new("Marketing broadcast PHP", "/CP/control/portal/epc_marketing_broadcast"),
        new("Demo tenants list", "/cp/demo-tenants-app"),
        new("Demo tenants PHP", "/CP/control/portal/epc_demo_tenants_manage"),
        new("Parts Agent chats", "/cp/parts-agent-chats-app"),
        new("Parts Agent PHP", "/CP/shop/parts_agent/parts_agent_chats"),
        new("POS overview", "/cp/pos-overview-app"),
        new("POS terminal PHP", "/CP/control/shop/pos"),
        new("Tax toolkits", "/cp/tax-toolkits-app"),
        new("Tax toolkit PHP", "/CP/control/portal/epc_tax_toolkit_manage"),
        new("SMS / WhatsApp", "/cp/sms-whatsapp-app"),
        new("SMS operators PHP", "/CP/control/sms_turning"),
        new("CRM board", "/cp/crm-board-app"),
        new("CRM PHP", "/CP/shop/crm/crm_main"),
        new("Document control", "/cp/document-control-app"),
        new("Document control PHP", "/CP/shop/document_control/document_control"),
        new("Delivery methods", "/cp/delivery-methods-app"),
        new("Delivery methods PHP", "/CP/shop/logistics/sposoby-polucheniya"),
        new("Crosses list", "/cp/crosses-app"),
        new("Crosses PHP", "/CP/shop/crosses"),
        new("HR overview", "/cp/hr-overview-app"),
        new("HR PHP", "/CP/shop/finance/erp?area=people&tab=hr&epc_erp_shell=1"),
        new("Production overview", "/cp/production-overview-app"),
        new("Production PHP", "/CP/shop/finance/erp?area=production&tab=manufacturing&epc_erp_shell=1"),
        new("Projects overview", "/cp/projects-overview-app"),
        new("Projects PHP", "/CP/shop/finance/erp?area=projects&tab=projects&epc_erp_shell=1"),
        new("Industry packs", "/cp/industry-packs-app"),
        new("Industry packs PHP", "/CP/control/portal/industry_settings"),
        new("Jewellery retail", "/cp/jewellery-retail-app"),
        new("Jewellery retail PHP", "/CP/shop/finance/erp?area=retail&tab=retail_commerce&epc_erp_shell=1"),
        new("Price lists", "/cp/price-lists-app"),
        new("Price lists PHP", "/CP/shop/prices"),
        new("Auto price", "/cp/auto-price-app"),
        new("Auto price PHP", "/CP/control/portal/epc_auto_price_engine"),
        new("UAE tax compliance", "/cp/uae-tax-compliance-app"),
        new("UAE tax PHP", "/CP/shop/finance/erp/uae-tax-compliance?epc_erp_shell=1"),
        new("Budgets", "/cp/budgets-app"),
        new("Budgets PHP", "/CP/shop/finance/erp?area=budgeting&tab=budgeting&epc_erp_shell=1"),
        new("Carriers", "/cp/carriers-app"),
        new("Carriers PHP", "/CP/shop/logistics/carriers"),
        new("Payment gateways", "/cp/payment-gateways-app"),
        new("Payment gateways PHP", "/CP/shop/payments/payments"),
        new("Workflows", "/cp/workflows-app"),
        new("Workflows PHP", "/CP/shop/finance/erp?area=setup&tab=workflow_automation&epc_erp_shell=1"),
        new("Purchase requests", "/cp/purchase-requests-app"),
        new("Purchase requests PHP", "/CP/shop/finance/erp?area=purchasing&tab=purchase_requisitions&epc_erp_shell=1"),
        new("Promotions", "/cp/promotions-app"),
        new("Promotions PHP", "/CP/control/portal/epc_promotions_engine"),
        new("CRM opportunities", "/cp/crm-opportunities-app"),
        new("CRM opportunities PHP", "/CP/shop/finance/erp?area=sales&tab=opportunities&epc_erp_shell=1"),
        new("Integrations", "/cp/integrations-app"),
        new("Integrations PHP", "/CP/control/portal/epc_integrations_hub"),
        new("Page builder", "/cp/page-builder-app"),
        new("Page builder PHP", "/CP/control/portal/epc_visual_page_editor"),
        new("Product catalogue", "/cp/product-catalogue-app"),
        new("Product catalogue PHP", "/CP/shop/catalogue/catalogue_editor"),
        new("Platform governance", "/cp/platform-governance-app"),
        new("Platform governance PHP", "/CP/control/portal/epc_platform_governance"),
        new("E-invoice documents", "/cp/einvoice-documents-app"),
        new("E-invoice PHP", "/ERP/?epc_erp_shell=1&area=tax&tab=einvoice"),
        new("Jewellery repairs", "/cp/jewellery-repairs-app"),
        new("Jewellery repairs PHP", "/ERP/?epc_erp_shell=1&area=service_mgmt&tab=jw_repairs"),
        new("CRM tickets", "/cp/crm-tickets-app"),
        new("CRM tickets PHP", "/ERP/?epc_erp_shell=1&area=sales&tab=crm"),
        new("Marketing growth", "/cp/marketing-growth-app"),
        new("Marketing growth PHP", "/CP/shop/marketing/marketing"),
        new("SOC 2 compliance", "/cp/soc2-compliance-app"),
        new("SOC 2 PHP", "/CP/control/portal/epc_soc2_compliance"),
        new("Cost models", "/cp/cost-models-app"),
        new("Cost models PHP", "/ERP/?epc_erp_shell=1&area=cost_mgmt&tab=cost_models"),
        new("Fin advanced", "/cp/fin-advanced-app"),
        new("Fin advanced PHP", "/ERP/?epc_erp_shell=1&area=cost_acct&tab=fin_advanced"),
        new("Blockchain proofs", "/cp/blockchain-proofs-app"),
        new("Blockchain proofs PHP", "/ERP/?epc_erp_shell=1&area=tax&tab=blockchain_proofs"),
        new("Landed cost", "/cp/landed-cost-app"),
        new("Landed cost PHP", "/ERP/?epc_erp_shell=1&area=landed_cost_area&tab=landed_cost"),
        new("Warehouse WMS", "/cp/warehouse-wms-app"),
        new("Warehouse WMS PHP", "/ERP/?epc_erp_shell=1&area=warehouse&tab=wms"),
        new("AI service", "/cp/ai-service-app"),
        new("AI service PHP", "/CP/general_pages/epc_ai_service"),
        new("Returns RMA", "/cp/returns-rma-app"),
        new("Returns RMA PHP", "/CP/shop/returns-manager"),
        new("Isolation audit", "/cp/isolation-audit-app"),
        new("Isolation audit PHP", "/CP/control/portal/epc_commerce_isolation_audit"),
        new("AML compliance", "/cp/aml-compliance-app"),
        new("AML compliance PHP", "/ERP/?epc_erp_shell=1&area=tax&tab=aml_compliance"),
        new("Jewellery masters", "/cp/jewellery-masters-app"),
        new("Jewellery masters PHP", "/ERP/?epc_erp_shell=1&area=inventory_mgmt&tab=jw_karat"),
        new("Consolidations", "/cp/consolidations-app"),
        new("Consolidations PHP", "/ERP/?epc_erp_shell=1&area=consolidations&tab=consolidation_bu"),
        new("CRM activities", "/cp/crm-activities-app"),
        new("CRM activities PHP", "/CP/shop/crm/crm_main?tab=activities"),
        new("Auth MFA", "/cp/auth-mfa-app"),
        new("Auth MFA PHP", "/CP/control/portal/epc_cp_auth_settings"),
        new("Electronic reporting", "/cp/electronic-reporting-app"),
        new("Electronic reporting PHP", "/ERP/?epc_erp_shell=1&area=tax&tab=elec_reporting"),
        new("Collections dunning", "/cp/collections-dunning-app"),
        new("Marketplace channels", "/cp/marketplace-channels-app"),
        new("Demand intelligence", "/cp/demand-intelligence-app"),
        new("Credit limits", "/cp/credit-limits-app"),
        new("Insurance compliance", "/cp/insurance-compliance-app"),
        new("Collections dunning PHP", "/CP/shop/finance/epc_collections_dunning"),
        new("Config items list", "/cp/config-items-app"),
        new("Site config PHP", "/CP/control/config_edit"),
        new("Users PHP", "/CP/control/users"),
        new("Groups PHP", "/CP/users/usergroups"),
        new("Multivendor", "/CP/control/shop/multivendor"),
        new("Crosses", "/CP/control/shop/docpart/crosses"),
        new("Procurement", "/CP/control/shop/procurement"),
        new("POS terminal", "/CP/control/shop/pos"),
        new("ERP finance", "/ERP/?epc_erp_shell=1&area=overview"),
        new("Stock", "/CP/control/shop/catalogue/stock"),
        new("Prices", "/CP/control/shop/prices"),
        new("Web tracker", "/CP/control/shop/web_tracker")
    ];

    /// <summary>ERP category bar → PHP ERP shell areas (epc_erp_nav_categories_config via PhpModuleCatalog).</summary>
    public static IReadOnlyList<NavItem> Erp =>
        new NavItem[] { new("Ecom BOS", "/ERP/", "ERP home") }
            .Concat(PhpModuleCatalog.ErpCategories.Select(c => new NavItem(c.Label, c.Href, c.Id)))
            .ToArray();

    public static readonly IReadOnlyList<NavItem> ErpQuickActions =
    [
        new("Sales orders list", "/erp/sales-orders-app"),
        new("Sales orders PHP", "/ERP/?epc_erp_shell=1&area=sales&tab=sales_orders"),
        new("Purchase orders list", "/erp/purchase-orders-app"),
        new("Purchase orders PHP", "/ERP/?epc_erp_shell=1&area=purchasing&tab=purchase_orders"),
        new("Invoices list", "/erp/invoices-app"),
        new("Invoices PHP", "/ERP/?epc_erp_shell=1&area=sales&tab=invoices"),
        new("Dashboard summary KPIs", "/erp/dashboard-summary-app"),
        new("Accounts summary KPIs", "/erp/accounts-summary-app"),
        new("Cash & bank list", "/erp/cash-accounts-app"),
        new("Cash ledger entries", "/erp/cash-entries-app"),
        new("Cash & bank PHP", "/ERP/?epc_erp_shell=1&area=banking&tab=cash_bank"),
        new("Chart of accounts list", "/erp/coa-accounts-app"),
        new("Chart of accounts PHP", "/ERP/?epc_erp_shell=1&area=finance&tab=coa"),
        new("GL journals list", "/erp/gl-journals-app"),
        new("General ledger PHP", "/ERP/?epc_erp_shell=1&area=finance&tab=gl"),
        new("Warehouses list", "/erp/warehouses-app"),
        new("Inventory stock KPIs", "/erp/inventory-stock-app"),
        new("Inventory PHP", "/ERP/?epc_erp_shell=1&area=inventory_mgmt&tab=inventory"),
        new("Bank reconciliation", "/erp/bank-reconciliation-app"),
        new("Bank reconciliation PHP", "/ERP/?epc_erp_shell=1&area=banking&tab=bank_recon"),
        new("Stock transfers", "/erp/stock-transfers-app"),
        new("Stock transfers PHP", "/ERP/?epc_erp_shell=1&area=inventory_mgmt&tab=inv_groups"),
        new("Sales quotations", "/erp/sales-quotations-app"),
        new("Sales quotations PHP", "/ERP/?epc_erp_shell=1&area=sales&tab=proposals"),
        new("Workspace favorites", "/erp/workspace-favorites-app"),
        new("Workspace favorites PHP", "/ERP/?epc_erp_shell=1&area=overview&tab=dashboard"),
        new("Fixed assets", "/erp/fixed-assets-app"),
        new("Fixed assets PHP", "/ERP/?epc_erp_shell=1&area=fixed_assets&tab=fixed_assets"),
        new("Suppliers list", "/erp/suppliers-app"),
        new("Payables PHP", "/ERP/?epc_erp_shell=1&area=ap&tab=payables"),
        new("Purchases list", "/erp/purchases-app"),
        new("Purchases PHP", "/ERP/?epc_erp_shell=1&area=purchasing&tab=purchases"),
        new("Staff", "/ERP/?epc_erp_shell=1&area=people"),
        new("Income Statement", "/ERP/?epc_erp_shell=1&area=finance&tab=pl"),
        new("Balance Sheet", "/ERP/?epc_erp_shell=1&area=finance&tab=balance_sheet")
    ];

    /// <summary>BOS sidebar sections → PHP /BOS/ (and CP portal modules when applicable).</summary>
    public static readonly IReadOnlyList<NavItem> Bos =
    [
        new("Fleet Command", "/BOS/?m=command_center"),
        new("Tenant Operations", "/BOS/?m=fleet_cp"),
        new("Commerce", "/BOS/"),
        new("Catalogue", "/BOS/"),
        new("Logistics", "/BOS/"),
        new("Marketing", "/BOS/"),
        new("Professional", "/BOS/"),
        new("ERP Finance", "/ERP/?epc_erp_shell=1&area=overview"),
        new("Auto Parts", "/BOS/"),
        new("Tax & Advisory", "/BOS/"),
        new("Platform", "/CP/control/portal")
    ];

    public static readonly IReadOnlyList<NavItem> BosQuickActions =
    [
        new("Audit log list", "/bos/audit-log-app"),
        new("Audit log PHP", "/CP/control/portal/epc_boc_audit_log"),
        new("Fleet tenants list", "/bos/tenants-app"),
        new("Tenant control PHP", "/CP/control/portal/epc_tenant_control_center"),
        new("Fleet health KPIs", "/bos/fleet-health-app"),
        new("Fleet readiness KPIs", "/bos/fleet-readiness-app"),
        new("Fleet summary KPIs", "/bos/fleet-summary-app"),
        new("Platform health PHP", "/CP/control/portal/epc_platform_health_checkup"),
        new("Fleet command", "/bos/app"),
        new("Native BOS", "/BOS/")
    ];

    public static readonly IReadOnlyList<NavItem> Storefront =
    [
        new("Home", "https://epartscart.com/"),
        new("Search parts", "/storefront/search-app"),
        new("Search PHP", "https://epartscart.com/shop/part_search"),
        new("Catalog", "https://epartscart.com/"),
        new("Account summary", "/storefront/account-summary-app"),
        new("Account PHP", "https://epartscart.com/users/"),
        new("Cart", "/storefront/cart-app"),
        new("Cart PHP", "https://epartscart.com/shop/cart"),
        new("My orders", "/storefront/orders-app"),
        new("Orders PHP", "https://epartscart.com/shop/orders"),
        new("Garage", "/storefront/garage-app"),
        new("Garage PHP", "https://epartscart.com/shop/part_search"),
        new("Profile", "/storefront/profile-app"),
        new("Profile PHP", "https://epartscart.com/users/profile"),
        new("Checkout PHP", "https://epartscart.com/shop/checkout/how_get")
    ];
}
